project:
  type: book
  output-dir: docs

crossref:
  thm-title: "Application area"
  thm-prefix: "Application area"
  lst-title: "Active R chunk"
  lst-prefix: "Active R chunk"
  eq-title: "Math expression"
  eq-prefix: "Math expression"
  custom:
    - key: try
      kind: float
      reference-prefix: "Try it!"
    - key: enr
      kind: float
      reference-prefix: "Enrichment topic"
    - key: lck
      kind: float
      reference-prefix: "Learning check"
    - key: drl
      kind: float
      reference-prefix: "Drill"
    - key: vid 
      reference-prefix: Video
      kind: float 
    - key: rcd
      kind: float
      reference-prefix: "Active R chunk"


book:
  title: "MOSAIC Calculus"
  author: "Daniel Kaplan, webr version 02/11/2025"
  navbar: 
    search: true
    logo: www/Cover-1.png
  chapters:
    - index.qmd
    # - intro.qmd
    - part: preliminaries-part.qmd
      chapters:
        - Preliminaries/01-quant-fun-space.qmd
        - Preliminaries/02-notation.qmd
        - Preliminaries/03-computing.qmd
        - Preliminaries/04-graphs-and-graphics.qmd
        - Preliminaries/05-pattern-book-functions.Rmd
        - Preliminaries/06-describing-functions.Rmd
        - Preliminaries/07-data-functions-graphics.Rmd #Chap 7
    - part: modeling-part.qmd
      chapters:
        - Modeling/08-parameters.Rmd
        - Modeling/09-assembling-functions.Rmd
        - Modeling/10-functions-with-multiple-inputs.Rmd # Chap 10
        - Modeling/11-fitting-features.Rmd
        - Modeling/12-low-order-polynomials.Rmd
        - Modeling/13-operations.Rmd
        - Modeling/14-magnitudes.Rmd
        - Modeling/15-dimensions.Rmd  # Chap 15
        - Modeling/16-modeling-scientific-method.Rmd
    - part: differentiation-part.qmd
      chapters:
        - Differentiation/17-continuous-change.Rmd
        - Differentiation/18-rate-of-change.Rmd
        - Differentiation/19-evanescent-h.Rmd
        - Differentiation/20-computing.Rmd # Chap 20
        - Differentiation/21-concavity.Rmd
        - Differentiation/22-cont-and-smooth.Rmd
        - Differentiation/23-rules.Rmd
        - Differentiation/24-optim.Rmd
        - Differentiation/25-partial.Rmd # Chap 25
        - Differentiation/26-approximation.Rmd
        - Differentiation/27-taylor.Rmd
        - Differentiation/Differentiation-projects.Rmd
    - part: linear-combinations-part.qmd
      chapters:
        - Linear-combinations/28-Vectors.Rmd
        - Linear-combinations/29-linear-combinations.Rmd
        - Linear-combinations/30-projection.Rmd
        - Linear-combinations/31-target-problem.Rmd
        - Linear-combinations/32-stat-modeling.Rmd
        # - Linear-combinations/B5-Fourier.Rmd 
    - part: accumulation-part.qmd
      chapters:
        - Accumulation/33-intro.Rmd
        - Accumulation/34-visualizing.Rmd
        - Accumulation/35-integration.Rmd
        - Accumulation/36-functions.Rmd
        - Accumulation/37-euler.Rmd
        - Accumulation/38-symbolic.Rmd
    - part: dynamics-part.qmd
      chapters:
        - Dynamics/39-diff-eq.Rmd
        - Dynamics/40-solution.Rmd
        - Dynamics/41-flow-on-line.Rmd
        - Dynamics/42-flow-on-plane.Rmd
        - Dynamics/43-modeling.Rmd
        - Dynamics/44-equilibria.Rmd
        - Dynamics/45-eigen.Rmd
        - Dynamics/46-second-order.Rmd
        
    #DRAFT     # - Dynamics/B6-forcing.Rmd
    - part: manifestations-part.qmd
      chapters:
        - Manifestations/47-operations.Rmd
        - Manifestations/48-splines.Rmd
        - Manifestations/49-optimization.Rmd
        - Manifestations/50-probability.Rmd
        - Manifestations/51-future-value.Rmd
        - Manifestations/52-mechanics.Rmd
        - Manifestations/53-diffusion.Rmd
    - part: "Appendices"
      chapters:
          - Glossary.qmd
    #     - Symbolic-manipulation.qmd
    #     - R-mosaic-setup.Rmd
    #      - video-resources.Rmd

  site-url: https://dtkaplan.github.io/MC2/
  repo-url: https://github.com/dtkaplan/MC2/
  repo-branch: main
  repo-actions: [edit]
  
  

comments: 
  hypothesis: true

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: mosaic-calc-style.css
    include-in-header: 
      - mathjax-definitions.html
  pdf:
    documentclass: scrreport
    include-in-header: 
      - latex-definitions.tex
    always_allow_html: true
    keep-tex: true
    reference-location: margin
    citation-location: margin

# Enable webR
webr:
  channel-type: 'automatic'
  repos: ["https://dtkaplan.r-universe.dev"]
  packages: ['ggplot2', 'mosaicCalc', 'LSTbook']
filters:
  - webr
