# BLOCK II. Differentiation {#sec-differentiation-part .unnumbered}

A mathematical function is a relationship between inputs and an output. An important and useful way to work with functions is to examine change in output as the inputs are changed by a small amount. The process of calculating this change-in-output per change-in-input---a ***rate*** of change---is called ***differentation***. Often, the rate of change is itself a function. Such rate-of-change functions are given a special label: ***derivative*** functions.

This Block introduces the concept of a rate-of-change function, ways of computing them, and how the derivative of a function can be inferred from a graph of the function. We will explore the connection between the value of the rate-of-change function and the location of an input that ***optimizes*** the output of the original function. We will consider the idea of rate-of-change for a function that has multiple inputs. 

Sometimes, your knowledge of a real-world system takes the form of knowing the behavior of the rate-of-change function. This can be an important guide to constructing mathematical models. 
