# Glossary

**apply the function**,1,01
**applying**,1,01
**axis**,1,01
**convert**,1,01
**coordinate plane**,1,01
**degree of freedom**,1,01
**dimension**,2,01
**domain**,4,01
**functions**,3,01
**inputs**,1,01
**maps**,1,01
**mathematical models**,1,01
**model**,1,01
**name of an input**,1,01
**not a symbolic name**,1,01
**number line**,2,01
**output**,4,01
**quantity**,4,01
**range**,1,01
**scale**,1,01
**trajectory**,3,01
**application of a function to an input**,1,02
**apply a function**,1,02
**argument**,1,02
**constants**,1,02
**defining**,1,02
**evaluate a function on**,1,02
**formula**,3,02
**notation**,1,02
**parameters**,4,02
**period**,4,02
**special inputs**,2,02
**declarative**,1,03
**do some action**,1,03
**evaluating**,1,03
**format**,1,03
**imperative**,1,03
**only**,1,03
**storage arrow**,1,03
**storage**,1,03
**tilde expression**,2,03
**constant value**,1,04
**contour plot**,2,04
**function**,12,04
**graph**,3,04
**graphical domain**,1,04
**graphs**,1,04
**one**,1,04
**output space**,1,04
**slice**,3,04
**space**,1,04
**surface**,2,04
**base**,1,05
**bit**,1,05
**decade**,1,05
**doubling time**,1,05
**gaussian**,1,05
**inversely proportional**,1,05
**monomials**,2,05
**natural logarithm**,2,05
**negative powers**,1,05
**non-integer powers**,1,05
**normal function**,1,05
**not**,8,05
**pattern-book functions**,2,05
**power-law functions**,1,05
**sigmoidal**,1,05
**argmax**,8,06
**argmin**,5,06
**asymptotic**,1,06
**at**,1,06
**change in slope**,1,06
**change**,1,06
**concave down**,3,06
**concave up**,4,06
**concavity**,5,06
"**continuous on an interval (a,b)**",1,06
**continuous**,4,06
**cycle**,1,06
**decrease**,1,06
**divided by**,1,06
**extrema**,1,06
**horizontal asymptote**,1,06
**increase**,1,06
**inflection points**,1,06
**input**,5,06
**local maximum**,3,06
**local minimum**,3,06
**monotonic**,2,06
**negative concavity**,1,06
**not include 0**,1,06
**of**,1,06
**optimization**,2,06
**periodic**,1,06
**positive concavity**,1,06
**rate of change**,3,06
**vertical asymptote**,2,06
**continuous domain**,1,07
**data frame**,3,07
**discrete**,1,07
**evaluate**,2,07
**explanatory variables**,2,07
**interpolation**,4,07
**machine learning**,1,07
**point plot**,1,07
**response**,1,07
**statistics**,1,07
**variable**,1,07
**black**,4,08
**input scaling**,2,08
**output scaling**,2,08
**parameter**,2,08
**pure number**,1,08
**pure numbers**,1,08
**quantities**,2,08
**coefficients**,2,09
**constant of proportionality**,1,09
**discontinuity**,2,09
**exterior function**,2,09
**fitting the function**,1,09
**function composition**,1,09
**inner**,1,09
**interior function**,2,09
**linear combination**,4,09
**local behavior**,1,09
**outer**,1,09
**piecewise function**,1,09
**wave packet**,1,09
**without lifting the pencil from the paper**,1,09
**displacement**,3,10
**just the identity function**,1,10
**multiplication**,1,10
**10**,1,11
**amplitude**,1,11
**baseline**,1,11
**fitting**,1,11
**half**,1,11
**layers**,1,11
**modeling cycle**,4,11
**newton's law of cooling**,2,11
**polishing**,1,11
**regression**,1,11
**constant term**,2,12
**demand functions**,2,12
**eight simple shapes**,6,12
**interaction term**,3,12
**linear terms**,1,12
**order**,1,12
**polynomial**,1,12
**production functions**,2,12
**quadratic terms**,2,12
**information**,1,13
**inverting**,1,13
**iterate**,4,13
**iteration**,1,13
**maximization**,1,13
**minimization**,1,13
**zero finding**,2,13
**decades**,1,14
**difference**,1,14
**log-log**,1,14
**logarithm**,1,14
**lux**,1,14
**magnitude**,2,14
**negative values**,1,14
**order of magnitude**,1,14
**orders of magnitude**,1,14
**ratio**,1,14
**scientific notation**,1,14
**semi-log**,1,14
**units**,1,14
**[acceleration]**,1,15
**[area]**,1,15
**[energy]**,1,15
**[force]**,1,15
**[momentum]**,1,15
**[power]**,1,15
**[velocity]**,1,15
**[volume]**,1,15
**coefficients must themselves have dimension**,1,15
**compound dimensions**,1,15
**degrees**,1,15
**density**,2,15
**dimensionless**,1,15
**divide**,3,15
**flavors of one**,1,15
**fundamental dimensions**,1,15
**gravity**,2,15
**length**,4,15
**mass**,3,15
**multiply**,2,15
**never**,1,15
**radians**,2,15
**time**,3,15
**unit**,2,15
**work**,2,15
**data**,1,16
**empirical models**,1,16
**extrapolation**,1,16
**hypothetico-deductive model**,1,16
**mechanistic models**,1,16
**observation**,1,16
**residuals**,1,16
**scientific method**,1,16
**systematic**,1,16
**54**,1,17
**differentiation**,4,17
**elliptical**,1,17
**flow**,2,17
**water volume**,1,17
**with-respect-to**,1,17
**average rate of change**,1,18
**instantaneous slope function**,1,18
**instantaneous slope**,1,18
**model the model**,1,18
**objective function**,4,18
**rate**,1,18
**slope function**,1,18
**velocity**,2,18
**[non-standard analysis](https://en.wikipedia.org/wiki/hyperreal_number)**,1,19
**derivative**,2,19
**theory of limits**,1,19
**finite-difference**,1,20
**second derivative**,4,20
**static**,1,20
**symbolic differentiation**,1,20
**change in the slope**,1,21
**constant**,1,21
**curvature**,3,21
**first derivative**,1,21
**radius of curvature**,1,21
**smooth**,1,21
**smoothness**,3,21
**third derivative**,2,21
**transition**,2,21
**twice**,1,21
**you are not expected to memorize it**,1,21
**c-infinity**,1,22
**continuity**,1,22
**continuous sets**,1,22
**cubic splines**,1,22
**differencing operator**,1,22
**discrete sets**,1,22
**example of non-$c^2$ functions:**,1,22
**examples of $c^\infty$ functions**,1,22
**heaviside function**,1,22
**ramp function**,1,22
**real numbers**,2,22
**small change in input**,1,22
**small change in output**,1,22
**adding**,1,23
**chain rule**,1,23
**composition of two functions**,1,23
**composition**,1,23
**derive**,1,23
**h-theory**,1,23
**left graph**,1,23
**linear operator**,1,23
**per capita**,1,23
**per**,8,23
**percent**,1,23
**power-law rule**,1,23
**product of two functions**,1,23
**product rule**,2,23
**proportional increase**,1,23
**right graph**,1,23
**rules**,1,23
**scaling**,2,23
**step 1**,1,23
**step 2**,1,23
**step 3**,1,23
**arg**,1,24
**critical points**,1,24
**decision quantity**,1,24
**differential equations**,3,24
**max**,2,24
**maximize**,1,24
**maximum**,2,24
**micron**,1,24
**minimize**,1,24
**minimum**,1,24
**multiple objectives**,1,24
**negative**,2,24
**objectives**,1,24
**only part**,1,24
"**out of 55,000**",1,24
**parabola**,1,24
**positive**,1,24
**precision**,1,24
**revenue**,1,24
**slope**,4,24
**value of the second derivative**,1,24
**value**,1,24
**all other things being equal**,1,25
**all other things held constant**,1,25
**blue**,1,25
**facet**,1,25
**gradient field**,1,25
**gradient vector**,2,25
**gradient**,2,25
**green**,1,25
**held constant**,1,25
**orientation**,1,25
**partial derivative**,1,25
**partial derivatives**,1,25
**sum**,1,25
**tangent plane**,1,25
**linear regression**,1,26
**linear**,1,26
**local**,2,26
**mixed partial derivatives**,1,26
**quadratic**,1,26
**second-order polynomial**,1,26
**error**,2,27
**exact**,1,27
**far**,1,27
**indeterminant form**,1,27
**l'hopital's rule**,1,27
**least squares**,1,27
**n-th order**,1,27
**near**,3,27
**tail domains**,1,27
**taylor polynomial**,2,27
**well behaved**,1,27
**wriggly domain**,1,27
** componentwise **,1,28
**alignment**,1,28
**angle**,2,28
**column vector**,1,28
**column**,1,28
**correlation coefficient**,1,28
**cosine of the angle**,2,28
**degrees of freedom**,1,28
**direction**,2,28
**dot product**,3,28
**embedded**,1,28
**functional notation**,1,28
**functional**,1,28
**infix notation**,1,28
**linear algebra**,1,28
**matrix mechanics**,1,28
**mean**,3,28
**negative correlation**,1,28
**orthogonal**,2,28
**positively correlated**,1,28
**protractor**,1,28
**row vector**,1,28
**ruler**,1,28
**scalar**,2,28
**scale a vector**,1,28
**square length**,1,28
**step**,2,28
**subspace**,4,28
**tail**,1,28
**tip**,1,28
**variance**,6,28
**vector space**,1,28
**vectors**,3,28
**zero correlation**,1,28
**bold-faced**,1,29
**componentwise multiplication**,1,29
**matrix multiplication**,1,29
**matrix**,2,29
**projected onto**,1,29
**scaled**,1,29
**subspace spanned**,1,29
**subspaces**,1,29
**subtraction**,1,29
**table**,1,29
**tail to tail**,1,29
**vector**,1,29
**at the same time**,1,30
**decomposing**,1,30
**decomposition**,1,30
**model space**,1,30
**model vector**,1,30
**mutually orthogonal**,2,30
**not mutually orthogonal**,1,30
**projecting**,1,30
**projection**,1,30
**residual vector**,1,30
**target vector**,1,30
**unit length vector**,1,30
**both**,4,31
**columns of data**,1,31
**projection problem**,2,31
**target problem**,4,31
**accounted for**,1,32
**analysis of variance**,1,32
**artificial intelligence**,1,32
**body mass index**,1,32
**genetics**,1,32
**intercept**,1,32
**maximum likelihood estimation**,2,32
**r-squared**,1,32
**response variable**,1,32
**unaccounted for**,1,32
**unexplained**,1,32
**variation**,1,32
**anti-differentiation**,2,33
**brackets**,1,33
**with-respect-to input**,1,33
**age of the universe**,1,35
**anti-derivative**,1,35
**apply**,2,35
**bold-face**,3,35
**bounds of integration**,1,35
**constant of integration**,3,35
**definite integral**,3,35
**dummy variable**,1,35
**first fundamental theorem of calculus**,1,35
**flavor of one**,1,35
**force accumulated over time**,1,35
**force**,2,35
**indefinite integral**,1,35
**lower bound of integration**,1,35
**momentum**,2,35
**net change**,2,35
**second fundamental theorem of calculus**,1,35
**upper bound of integration**,1,35
**analyze**,1,36
**decompose**,1,36
**fourier transform**,2,36
**frequency domain**,1,36
**harmonics**,1,36
**knots**,2,36
**molecular vibrational spectroscopy**,1,36
**periodicity**,1,36
**time domain**,1,36
**waveforms**,1,36
**cumulative sum**,1,37
**cumulative**,1,37
**dynamics**,3,37
**euler steps**,1,37
**gauss-legendre quadrature**,1,37
**integrand**,1,37
**series of quantities**,1,37
**cataloged functions**,2,38
**elementary functions**,1,38
**helper function**,1,38
**no such rules**,1,38
**normal pdf**,1,38
**parts**,2,38
**slope function visualization**,1,38
**symbolic anti-derivatives**,1,38
**symbolic derivatives**,1,38
**techniques of integration**,1,38
**u-substitution**,1,38
**a trajectory can never cross itself**,1,39
**change in state**,1,39
**chaos**,2,39
"**continuous-time, continuous-space system**",1,39
**deterministic**,2,39
**differential equation**,1,39
**dimension of the state space**,1,39
"**discrete-time, discrete-state dynamical system**",1,39
**dynamical functions**,1,39
**dynamical state**,1,39
**dynamical system**,1,39
**dynamical systems**,1,39
**essential**,1,39
**first-order differential equations**,2,39
**fixed point**,3,39
**function of time**,1,39
**gradient ascent**,2,39
**initial condition**,3,39
**instantaneous state**,2,39
**oscillates**,1,39
**path**,1,39
**position**,2,39
**second-order differential equation**,3,39
**solution**,1,39
**speed**,2,39
**state space**,4,39
**state velocity**,3,39
**state**,1,39
**stochastic**,2,39
**system of differential equations**,1,39
**system**,1,39
**time series**,1,39
**accumulating**,1,40
**ansatz**,2,40
**continuous-time function**,1,40
**euler formula**,1,40
**euler method**,1,40
**graphical method**,1,40
**integrating**,1,40
**limit definition of the derivative**,1,40
**logistic equation**,1,40
**method of ansätze**,1,40
**solutions**,1,40
**substitution methods**,1,40
**[catastrophe theory](https://en.wikipedia.org/wiki/catastrophe_theory)**,1,41
**[tipping point](https://en.wikipedia.org/wiki/tipping_point)**,1,41
**evaluated**,1,41
**fixed points**,2,41
**flow field**,1,41
**linear approximation**,1,41
**linearization**,1,41
**net**,1,41
**stability**,1,41
**stable**,2,41
**sustainability**,1,41
**unstable**,1,41
**neutral stability**,1,42
**nullclines**,1,42
**saddle**,1,42
**saddles**,1,42
**sink**,1,42
**source**,1,42
**vector field**,1,42
**bounded stable model**,1,43
**bounded unstable model**,1,43
**carrying capacity**,1,43
**chain reaction**,1,43
**conserved**,2,43
**coupled**,1,43
**critical mass**,1,43
**explosion**,1,43
**fissile**,1,43
**framework**,1,43
**function shape**,1,43
**interaction**,1,43
**linear stable model**,1,43
**linear unstable model**,1,43
**love**,1,43
**near zero**,1,43
**phase plane**,1,43
**predator-prey model**,1,43
**radioactive decay**,1,43
**reactor**,1,43
**sir model**,1,43
**square of the army size**,1,43
**the same problem**,1,43
**twice as capable**,1,43
**two**,1,43
**warfare**,1,43
"** in the language of dynamical systems, the equilibrium state of a system is called a **",1,44
**equilibrium**,2,44
**steady state**,1,44
**transient**,2,44
**cruise control**,1,45
**eigenvalues**,2,45
**eigenvectors**,1,45
**angular frequency**,1,46
**ballistics**,1,46
**complex number**,1,46
**critically damped**,1,46
**damping**,1,46
**force-balance equations**,1,46
**fundamental theorem of calculus**,1,46
**law ii**,1,46
**must have**,1,46
**theory of general relativity**,1,46
**accumulate**,1,47
**anti-differentiate the function**,1,47
**argmax finding**,1,47
**computational mathematicians**,1,47
**differentiate the function**,1,47
**equations**,1,47
**evaluating a function**,1,47
**ideal result**,1,47
**integrate the function**,1,47
**logistic map**,1,47
**mathematical modeling**,1,47
**mathematical task**,1,47
**name**,1,47
**newton step**,1,47
**number**,1,47
**operations on functions**,1,47
**realistic result**,1,47
**solving**,1,47
**zero-finding**,1,47
**ad hoc**,1,48
**control point**,1,48
**cubic segments**,1,48
**cubic spline**,2,48
**five**,1,48
**function fitting**,1,48
**interpolating function**,1,48
**mandate**,1,48
**s**,2,48
**single valued**,1,48
**six**,1,48
**stiff**,1,48
**stiffness**,1,48
**aids to human decision making**,1,49
**budget constraint**,1,49
**cobb-douglas**,1,49
**constraint**,1,49
**dominated**,1,49
**dynamic programming**,1,49
**equality constraint**,1,49
**equality constraints**,1,49
**evaluation phase**,1,49
**gradient descent**,1,49
**incommensurate**,1,49
**inequality constraint**,1,49
**iterative**,1,49
**lagrange multiplier**,2,49
**linear programming**,1,49
**min**,1,49
**modeling phase**,1,49
**operations research**,1,49
**parallel**,1,49
**potential energy**,1,49
**quadratic programming**,1,49
**relaxed**,1,49
**shadow price**,1,49
**simplex**,1,49
**solution phase**,1,49
**spring-mass systems: an example context**,1,49
**sub-optimal**,1,49
**vector input**,1,49
**arithmetic mean**,1,50
**bayes' rule**,1,50
**bayesian inference**,1,50
**center of mass**,1,50
**event**,1,50
**expected value**,2,50
**exponential probability density**,1,50
**gaussian density function**,1,50
**hypothesis**,1,50
**hypothetical reasoning**,1,50
**likelihood function**,1,50
**likelihood functions**,1,50
**normal distribution**,1,50
**normalize**,1,50
**normalizing**,1,50
**not a probability**,1,50
**not definitive**,1,50
**outcome**,1,50
**posterior functions**,1,50
**posterior**,1,50
**prior functions**,1,50
**prior**,1,50
**priors**,1,50
**probability density function**,1,50
**probability density functions**,2,50
**probability density**,3,50
**probability**,1,50
**relative  density**,1,50
**relative density function**,1,50
**relative density functions**,1,50
**risk of disease transmission**,1,50
**sd**,1,50
**standard deviation**,2,50
**uncertainty**,1,50
**under construction**,1,50
**uniform density function**,1,50
**update**,1,50
**compound interest**,1,51
**constrained optimization**,1,51
**discount**,1,51
**discounting function**,1,51
**discounting**,1,51
**interest rate**,1,51
**interest rates**,1,51
**interest**,1,51
**mortgage**,1,51
**net present value**,1,51
**nominal income stream**,1,51
**present value**,3,51
**stream**,1,51
**term**,1,51
**transitive**,1,51
**votes**,1,51
** more precisely it can be called **,1,52
**angular acceleration**,1,52
**area**,1,52
**conservation of momentum**,1,52
**decomposed**,1,52
**decomposing a vector**,1,52
**energy**,1,52
**finite**,1,52
**forces**,1,52
**infinitesimal**,1,52
**instantaneous length**,1,52
**instantaneous rate of change**,1,52
**kinetic energy**,1,52
**latent**,1,52
**mechanics**,1,52
**rotation**,1,52
**statics**,1,52
**study of machines**,1,52
**torque**,1,52
**turbofan engines**,1,52
**turbojet engines**,1,52
**diffusion equation**,1,53
**essay**,1,53
**heat equation**,1,53
**optional background**,1,53
**quick review questions**,1,53
**random walk**,1,53
**three**,1,53
**wrongly**,1,53
