# BLOCK I. Modeling {#sec-modeling-part .unnumbered}

A ***model*** is a representation of something---for instance, a building---for a specific purpose. A model of a building might take several different forms, depending on the purpose. For example, a blueprint plan shows the layout of rooms, corridors, windows, etc. for the purpose of exploring the design and guiding the construction. A three-dimensional balsa-wood model of a building helps to examine how the building appears from different perspectives. A list of components in the building is a model whose purpose is to facilitate ordering those components and checking whether everything needed is at hand during construction.

A ***mathematical model*** is a model made up of mathematical stuff. Balsa-wood and blueprint paper are not mathematical stuff. This Block introduces some of the different kinds of mathematical stuff that we will use in constructing mathematical models. Of primary importance will be mathematical functions. The block describes various aspects of functions: parameters and the ways to set their values, ways to construct complicated functions out of simpler components, a particularly useful type of function---polynomials---that are a type of modeling "clay."

Using mathematical models often involves performing a mathematical operation on a model. One type of operation emphasized in high-school math is ***solving*** which takes information in one form (e.g., a function) and gives information in another form (e.g., the inputs that will cause the function output to take on a specific value). Other kinds of operations are ***optimization*** and ***iteration***, which will be introduced in this Block. 

Although functions are fundamental to mathematical modeling, there are other mathematical and scientific concepts that make it much easier to think about how a model relates to the real world. Two of these are the mathematics of ***magnitude*** and the ***units*** and ***dimension*** of quantities. 

Finally, the block considers the process of building models and techniques that help a human modeler to get started and then refine the model until it can serve its purpose.