# Preliminaries {#sec-preliminaries-part .nonumber}

Calculus is about change, and change is about relationships. Consider the complex and intricate network of relationships that determine climate: a changing climate implies that there is a relationship between, say, global average temperature and time. Scientists know temperature changes with levels of CO~2~ and methane which themselves change due to their production or elimination by atmospheric and geological processes. A change in one component of climate (e.g., ocean acidification or pH level) provokes change in others. 

to describe and use the relationships we find in the natural or designed world, we build mathematical representations of them. We call these ***mathematical models***. On its own, the word "model" signifies a representation of something in a format which serves a specific ***purpose***. A blueprint describing the design of a building is an everyday example of a model. The blueprint *represents* the building but in a way that is utterly different from the building itself. Blueprints are much easier to construct or modify than buildings, they can be carried and shared easily. Two of the purposes of a blueprint is to aid in the design of buildings and to communicate that design to the people securing the necessary materials and putting them together into the building itself. 

::: {.column-margin}
Models provide the link between the real world and the abstractions of mathematics.
:::

Atmospheric scientists build models of climate whose purpose is to explore scenarios for the future emission of greenhouse gasses. The model serves as a stand-in for the Earth, enabling predictions in a few hours of decades of future change in the climate. This is essential for the development of policies to stabilize the climate.


::: {.column-margin}
A concise definition of a "model" is *a representation for a purpose*. Defining the ***purpose*** for your model is a crucial first step in building a mathematical representation that will serve that purpose. Useful models of the same real-world setting can be very different, depending on the purpose. For instance, one routine use for a model is to make a prediction. But other models are intended for exploring the connections among the components of the system being modeled.
:::

Designing a building or modeling the climate requires expertise and skill in a number of areas. Nonetheless, constructing a model is *relatively easy* compared to the alternative. Models make it relatively easy to extract the information that's needed for the purpose at hand. For instance, a blueprint gives a comprehensive overview of a building in a way that's hard to duplicate just by walking around an actual building. 


Models are easy to manipulate compared to reality, easy to implement (think "draw a blueprint" versus "construct a building"), and easy to extract information from. We can build multiple models and compare and contrast them to gain insight into the real-world situation behind the models.

A ***mathematical model*** is a model made out of mathematical and computational stuff. Example: a bank's account books are a model made mostly out of numbers. But in technical areas---science and engineering are obvious examples, but there are many other fields, too---numbers don't get you very far.  By learning calculus, you gain access to important mathematical and computational concepts and tools for building models and extracting information from them.


A major use of mathematics is building models constructed out of mathematical concepts and objects. The chapters in this Preliminaries section of this book introduce some of the fundamental mathematical entities that are the heart of modeling. 


