---
id: "areas"
author: "Transcribed by Daniel Kaplan from MMAC"
---

```{r include=FALSE}
library(etude2)
```

In the following (drawn from MMAC 6.4.49-52) the function $t()$ gives the height of the top of a large net in meters above the ground. The function $b()$ gives the height of the bottom of the net. $x$ is in units of miles.

```{r areas1, echo=FALSE}
askMC(
  "Let $t(x) \\equiv 9$ meters and $b(x) \\equiv x$ meters. What is the *area* of the net in the span running from $0 \\leq x \\leq 3$?",
  "11 meter $\\times$ miles",
  "14.5 meter $\\times$ miles",
  "+22.5 meter $\\times$ miles+",
  "27 meter $\\times$ miles",
  random_answer_order = FALSE
)
```


```{r areas2, echo=FALSE}
askMC(
  "Let $t(x) \\equiv 1$ meter and $b(x) \\equiv -x$ meters. What is the *area* of the net in the span running from mile $-1 \\leq x \\leq 1$?",
  "-2 meter $\\times$ miles",
  "0 meter $\\times$ miles",
  "+2 meter $\\times$ miles+",
  "4 meter $\\times$ miles",
  random_answer_order = FALSE
)
```

```{r areas3, echo=FALSE}
askMC(
  "Let $t(x) \\equiv 2-x$ meter and $b(x) \\equiv x^2$ meters. What is the *area* of the net in the span running from mile $0 \\leq x \\leq 1$?",
   "about 1.16 square-meter" = "The number 1.16 would be right if the units were meters $\\times$ miles. But the units are meters-squared",
  "+about 1900 square meters+",
  "about 38,000 square meters",
  "about 76,000 square meters",
  random_answer_order = FALSE
)
```

```{r areas4, echo=FALSE}
askMC(
  "Let $t(x) \\equiv 4 - x^2$ meter and $b(x) \\equiv x^2 - 4$ meters. What is the *area* of the net in the span running from mile $-1 \\leq x \\leq 2$?",
   "about 24 square-meter" = "The number 24 would be right if the units were meters $\\times$ miles. But the units are meters-squared",
  "about 1900 square meters",
  "+about 38,000 square meters+",
  "about 76,000 square meters",
  random_answer_order = FALSE
)
```
