---
id: "calf-know-painting"
title: "Properties of Antiderivatives"
author: "Ray Hill"
global_id: "DkoUjX"
---

As you know, $$\int_a^c f(x) dx = \int_a^b f(x) dx + \int_b^c f(x) dx\\ \text{and}\\\int_a^c f(x) dx = - \int_c^a f(x) dx\ .$$


Here are some definite integrals for which, without stating anything more about the function, we give you the numerical result.


    |    
---------------------------|-------------------------------
$\int_{2}^{7} f(x) \,dx = -8$ | $\int_{-6}^{-2} g(x) \,dx = 3$
$\int_{2}^{12} f(x) \,dx = -14$ | $\int_{0}^{2} g(x) \,dx = 1$
$\int_{2}^{7} h(x) \,dx = 5$ | $\int_{0}^{2} h(x) \,dx = 6$

Consider these the facts you have to work with when answering the following questions:



```{r antid-1, echo=FALSE}
askMC(
  "$\\int_{2}^{7} 3f(x) \\,dx =$? ",
  "-8" = "Did you see the three?",
  "-42" = "Check the bounds",
  "+-24+",
  "13"
)
```

```{r antid-2, echo=FALSE}
askMC(
  "$\\int_{7}^{12} f(x) \\,dx =$? ",
  "6" = "Be careful with your signs",
  "22" = " Be careful with your signs ",
  "+-6+",
  "-22" = " Be careful with your signs "
)
```

```{r antid-3, echo=FALSE}
askMC(
  "$\\int_{2}^{7} f(x) + g(x) \\,dx =$?",
  "-3" = "Do you know $\\int_{2}^{7} g(x) \\,dx$?",
  "8" = "Do you know $\\int_{2}^{7} g(x) \\,dx$?",
  "-8" = "Do you know $\\int_{2}^{7} g(x) \\,dx$?",
  "+insufficient information to answer question+"
)
```


```{r antid-4, echo=FALSE}
askMC(
  "$\\int_{2}^{2} r(x) \\,dx =$?",
  "-3" = "Look at the bounds",
  "+0+" = "Even though you don’t know $r(x)$ this is always true when the bounds are the same",
  "-8" = "Look at the bounds",
  "insufficient information to answer question at t"= "Look at the bounds"
)
```


```{r antid-5, echo=FALSE}
askMC(
  "$\\int_{-6}^{-2} \\left[\\strut g(x)+3\\right] \\,dx =$?",
  "6" = "You need to integrate the 3",
  "+15+",
  "12" = "Don’t forget g(x)",
  "3"= "Break it up into two different integrals"
)
```



```{r antid-6, echo=FALSE}
askMC(
  "$\\int_{12}^{7} f(x) \\,dx =$ ",
  "-6" = "Be careful with your signs",
  "22" = " Be careful with your signs ",
  "+6+",
  "-22" = " Be careful with your signs "
)
```


