---
id: "fawn-spend-futon"
created: "Wed May 25 13:08:19 2022"
global_id: "eE0ah9"
---


Compute symbolically the following anti-derivatives.

```{r fsfv-1, echo=FALSE, results="markup"}
askMC(
  prompt = r"($\int \left(\sqrt x \cdot \ln(x) \right)\ dx=)",
  r"(\frac{3}{2} x^{\frac{3}{2}}\cdot \ln(x)-\frac{9}{4} x^{\frac{3}{2}}+C)",
  r"(\frac{3}{2} x^{\frac{3}{2}}\cdot \ln(x)-x^{\frac{3}{2}}+C)",
  r"(+\frac{2}{3} x^{\frac{3}{2}}\cdot \ln(x)-\frac{4}{9} x^{\frac{3}{2}}+C+)",
  r"(-2 x^{-\frac{1}{2}}\cdot \ln(x)-4 x^-{\frac{1}{2}}+C)",
  random_answer_order = FALSE
)
```


```{r fsfv-2, echo=FALSE, results="markup"}
askMC(
  prompt = r"($\int -3x\cdot \cos(2x)\ dx=)",

  r"(-\frac{3}{2} \cos(2x)-3x\cdot \sin(2x)+C)",
  r"(- \frac{3}{4} \cos(2x)-\frac{3}{2} \sin(2x)+C)",
  r"(+-\frac{3}{4} \cos(2x)-\frac{3}{2} x\cdot \sin(2x)+C+)",
  r"(- \frac{3}{4} \cos(2x)-\frac{3}{2} x \cdot \sin(2x)+C)",
  random_answer_order = FALSE
)
```

```{r fsfv-3, echo=FALSE, results="markup"}
askMC(
  prompt = r"($\int \left(y^3 \cdot e^y \right)\ dy=)",
  r"(\frac{1}{4} y^4e^y+C)",
  r"(y^3e^y-3e^yy^2+C)",
  r"(-y^3 e^y + 3y^2  e^y-6ye^y +6e^y+C+C)",
  r"(+y^3 e^y - 3y^2  e^y+6ye^y -6e^y+C+)",
  random_answer_order = FALSE
)
```
