---
id: "fir-chew-ship"
created: "Wed May 25 12:47:46 2022"
global_id: "tqtL4c"
skill: "Sc-Cal-403"
---

Calculate each of the following anti-derivatives.

```{r fcsq-1, echo=FALSE, results="markup"}
askMC(
  prompt = r"($\int \frac{x}{\sqrt {9-x^2}}dx=$)",
  r"($\frac 1 2 \ln\sqrt{9-x^2}+C$)",
  r"(+$\sqrt{9-x^2}+C$+)",
  r"($\frac 1 4 \sqrt{9-x^2}+C$)",
  r"($\sqrt{9-x^2}+C$)",
  random_answer_order=FALSE
)
```


```{r fcsq-2, echo=FALSE, results="markup"}
askMC(
  prompt = r"($\int \frac{\ln|x|}{x} dx=$+)",
  r"(+$+\frac {(ln|x|)^2} 2+C$+)",
  r"($\frac 1{2x^2}+C$)",
  r"($\frac{1-\ln|x|}{x^2}+C$)",
  r"($C$)",
  random_answer_order = FALSE
)
```



```{r fcsq-3, echo=FALSE, results="markup"}
askMC(
  prompt = r"($int_0^{\frac \pi 4}\sin(2x)dx=$)",
  -1.
  -0.5,
  "+0.5+",
  11,
  random_answer_order = FALSE
)
```



```{r fcsq-4, echo=FALSE, results="markup"}
askMC(
  prompt = r"($\int_0^{\frac \pi 2}\cos(x)\sqrt{\sin(x)}dx=$)",
  r"($-\frac{2}{3}$)",
  r"($-\frac{1}{2}$)",
  r"($\frac{1}{2}$)",
  r"(+$\frac{2}{3}$+)",
  random_answer_order = FALSE
)
```



```{r fcsq-5, echo=FALSE, results="markup"}
askMC(
  prompt = r"($\int \sin^3(5x)\cdot\cos(5x)dx=\int (\sin(5x))^3\cdot\cos(5x)dx=$)",
  r"($frac {\sin^2(5x)}{10}+C$)",
  r"(+$frac {\sin^4(5x)}{20}+C$+)",
  r"($frac {\sin^4(5x)}{4}+C$)",
  r"($frac {4\sin^4(5x)}{5}+C$)",
  random_answer_order = FALSE
)
```
