---
id: "fly-tell-drawer"
created: "Wed May 25 13:21:28 2022"
global_id: "mlrMfA"
skill: "Sc-Cal-403"
---

Compute symbolically the following anti-derivatives.

```{r ftdp-1, echo=FALSE, results="markup"}
askMC(
  prompt = r"($\int \frac{\ln(x)}{x^3}\ dx=$)",
  r"($\frac {4\cdot (x\ln(x)-x)}{x^4}+C$)",
  r"($\frac{x^3\cdot\frac 1 x-ln(x)\cdot 3x^2}{x^6}+C$)",
  r"($-\frac 1 2 x^{-2}\cdot \ln(x)+\frac 1 2 x^{-3}+C$)",
  r"(+$-\frac {\ln(x)}{2x^2}-\frac 1 {4x^2} +C$+)",
  random_answer_order = FALSE
)
```


```{r ftdp-2, echo=FALSE, results="markup"}
askMC(
  prompt = r"($\int x^3\cdot \cos(x^4+2)\  dx=$)",
  r"(+$\frac{\sin(x^4+2)}{4}+C$+)",
  r"($3x^2\cdot\cos(x^4+2)-4x^6\cdot \sin(x^4+2)+C$)",
  r"($\sin(x^4+2)+C$)",
  r"($4\sin(x^4+2)+C$)",
  random_answer_order = FALSE
)
```



```{r ftdp-3, echo=FALSE, results="markup"}
askMC(
  prompt = r"($\int e^t\cdot (2e^t-6)^3\ dt=$)",
  r"($e^t\cdot (2e^t-6)^3+3e^{2t}\cdot(2e^t-6)^2+C$)",
  r"($(2e^t-6)^4+C$)",
  r"(+$\frac{(2e^t-6)^4}8+C$+)",
  r"($\frac{(2e^t-6)^4}4+C$)",
  random_answer_order = FALSE
)
```


```{r ftdp-4, echo=FALSE, results="markup"}
askMC(
  prompt = r"($\int \frac{x} {e^{3x}}\ dx=$)",
  r"($\frac{e^{3x}-3x\cdot e^{3x}}{e^{6x}}+C$)",
  r"(+$-\frac x 3e^{-3x}-\frac 1 9 e^{-3x}+C$+)",
  r"($\frac{3x^2}{2e^{3x}}+C$)",
  r"($x\cdot e^{-3x}-e^{-3x}+C$)",
  random_answer_order = FALSE
)
```



```{r ftdp-5, echo=FALSE, results="markup"}
askMC(prompt = r"($\int_0^\pi \cos^4(x)\cdot \sin(x) dx=\int_0^\pi (\cos(x))^4\cdot \sin(x)\ dx=$)",
  r"($-\frac 2 5$)",
  r"($0$)",
  r"(+$\frac 2 5$+)",
  r"($2$)",
  random_answer_order = FALSE
)
```

```{r ftdp-6, echo=FALSE, results="markup"}
askMC(  
  prompt = r"($\int (x+3)(x^2-1)\ dx=$)",
  r"($(x^2-1)+2x\cdot (x+3)+C$)",
  r"($\left(\frac {x^2} 2+3x\right)\left(\frac {x^3} 3 -x\right)+C$)",
  r"($3x^2+6x-1+C$)",
  r"(+$\frac {x^4} 4+x^3 -\frac{x^2} 2-3x+C$+)",
  random_answer_order = FALSE
)
```
