---
id: "frog-pitch-clock"
created: "Tue Jul 20 14:26:52 2021"
global_id: "Y7ecmI"
---

```{r usub1, echo=FALSE}
askMC(
  "In $h(x) = 2x/(x^2 + 2)$ which of the following is a plausible candidate for an interior function $g(x)$?",
  "$\\sin(x)$",
  "$\\ln(x)$",
  "$2x$" = "In order for this to be an interior function $g(x)$ there has to be some other function embracing it. $2x$ is standing proudly on its own, so it's not a good choice for $g(x)$",
  "+$x^2 + 2$+"
)
```

```{r usub2, echo=FALSE}
askMC(
  "Continuing with the integral of $h(x) = 2x/(x^2 + 2)$ and the working guess that $g(x) = x^2 + 2$, do you see any part of $h()$ which is a match to $\\partial_x g()$?",
  "$1/x$" = "But that's not anything like $\\partial_x g(x)$.",
  "$\\ln(x)$",
  "+$2x$+"
)
```

```{r usub3, echo=FALSE}
askMC(
  "Taking seriously the progress we made in the previous two questions, we now need to write  $h(x)$ as $f(x^2 + 2) 2x$? What should $f()$ be to make this match $h(x)$?",
  "$f(x) = \\sin(x)$",
  "$f(x) = \\ln(x)$",
  "+$f(x) = 1/x$+",
  "$x^2 + 2$"
)
```

Now that you have found both $g()$ and $f()$, you simply need to find a function $F(x)$ such that $\partial_x F(x) = f(x)$.  Since $\partial_x \ln(x) = 1/x$, we know that $F(x) = \ln(x)$. Thus,  $\int h(x) dx = F(g(x)) = F(x^2 + 2) = \ln(x^2 + 2)$.

