---
id: "giraffe-wear-fork"
created: "Wed Aug  4 11:29:09 2021"
global_id: "ixU83c"
---


DRAFT DRAFT

Link this to Exercises/Fun/Boyd-1.Rmd.




If you multiply $P_s$ (specific power) times the duration of a flight segment, the result has dimension [Power]$\times M^{-1}$ which is power per mass: so-called "specific power." 

[I think this should be [Energy]$\times M^{-1}$, that is, energy per mass; so-called "specific power."]

In practice, all of the quantities in the E-M Theory formula change with time, often very quickly in a fighter aircraft. In order to know the aircraft specific energy at any instant, we need to accumulate the changing specific power over time. This amounts to finding the anti-derivative of specific power with respect to time: $$\text{specific energy} \equiv \int P_s(t) dt$$ You can think of the $dt$ as a short interval of time.  $P_s(t) dt$ is  multiplying specific power at instant $t$ by the duration of that short interval of time which produces a small amount of specific energy at instant $t$. The $\int$ means "accumulate" these small bits of specific energy from each instant in time over a longer time interval.

```{r boyd-3, echo=FALSE, results="markup"}
askMC(
  prompt = "What is the dimension of $dt$ within the context of this problem?",
  "+[dt] = T+" = "Correct",
  "[dt] = M" = "Think about what you are accumulating over.",
  "[dt] = L" = "Think about what you are accumulating over.",
  "[dt] = 1/T" = "Reconsider the units of specific energy."
)
```
