---
id: "lessons-from-euler"
author: "Daniel Kaplan"
---

Some things to learn from the Euler Method:

1. Anti-differentiation is no more than *accumulating* the $f(x)$, after multiplying it by an appropriate step size $h$.

2. Since $h$ has the same dimension as the input $x$, the dimension of the anti-derivative will be [$f(x)$][$h$].

In our description of the Euler method, we made the assumption that when integrating $f(x)$ over the domain $a \leq x \leq b$, we can set $F(a) = 0$.  There's nothing fatal about this assumption, but we should admit that we could have used any value we like for $F(a)$. Using a non-zero value of $F(a)$ would simply add the same number to every point in the output of the Euler Method.

3. Any chosen number for $F(a)$ generates an authentic, genuine anti-derivative of $f(x)$. Since $F(a)$ can be any number at all, there are infinitely many anti-derivatives of any function $f(x)$. They all have the same shape, but differ from one another by a constant.

This constant, which amounts to the choice of $F(a)$, is called the "constant of integration." In many modeling tasks involving anti-differentiation, we need to find a choice for the "constant of integration" (that is, $F(a)$) that fits with what else we know about the system being modeled.

**Essay**: Briefly restate these \"Lessons from Euler\" in your own words.


```{r C1, echo=FALSE}
askMC(
  "Suppose we want to give a formula for a function $F(x)$ which is to be the anti-derivative of the function $f(x) \\equiv x^2$. We don't need the Euler method for this simple problem, the answer is $F(x) \\equiv \\frac{1}{3} x^3 + C$. We want to give the correct numeric value for $C$ so that $F(3) = 12$. What should $C$ be?",
   "$C$ should be -3." = "This would give us $F(3) = \\frac{1}{3} 3^3 - 3$, which is 6, not the $F(3) = 12$ asked for.",
  "+$C$ should be 3.+",
  "$C$ should be 12." = "This would give us $F(3) = \\frac{1}{3} 3^3 + 12$, which is 21, not the $F(3) = 12$ asked for."
)
```
