---
id: "MMAC-1"
title: "MMAC Exercises"
author: "Transcribed by Daniel Kaplan"
---

```{r include=FALSE}

```



```{r MMAC1, echo=FALSE}
askMC(
  "$$\\text{Find}\\ \\ \\int_0^3 \\left[ 2x + 1\\right] dx$$",
  "$x^2 + x$" = "Note that the limits of integration are numbers.",
  "9",
  "+12+",
  "48",
  random_answer_order = FALSE)
```

```{r MMAC2, echo=FALSE}
askMC(
  "$$\\text{Find}\\ \\ \\int_0^4 \\left[ 4x^3 + 6x\\right] dx$$",
  "$x^4 + x^2$" = "Note that the limits of integration are numbers.",
  "128",
  "164",
  "176",
  "256",
  "+304+",
  random_answer_order = FALSE)
```

```{r MMAC3, echo=FALSE}
askMC(
  "$$\\text{Find}\\ \\ \\int_0^2 \\left[ x^3 - 3 x^2\\right] dx$$",
  "$x^4 / 4 + x^3$" = "Note that the limits of integration are numbers.",
  "+-4+",
  "0",
  "4",
  "8",
  random_answer_order = FALSE)
```

```{r MMAC4, echo=FALSE}
askMC(
  "$$\\text{Find}\\ \\ \\int_2^0 \\left[ x^3 - 3 x^2\\right] dx$$",
  "$x^4/4 + x^3$" = "Note that the limits of integration are numbers.",
  "-4",
  "0",
  "+4+",
  "8",
  random_answer_order = FALSE)
```

```{r MMAC5, eval=FALSE, echo=FALSE}
askMC(
  "$$\\text{Find}\\ \\ \\int_1^2 \\left[\\sqrt{x} + \\frac{1}{\\sqrt{x}}\\right] dx$$",
  "+$\\frac{1}{3}\\left[2\\sqrt{2} - 4\\right]$+",
  "0",
  "$\\frac{2}{3}\\left[\\sqrt{2} - 4\\right]$",
  "$\\frac{2}{3}\\left[2 - \\sqrt{2}\\right]$",
  random_answer_order = FALSE)
```

```{r MMAC6, echo=FALSE}
askMC(
  "$$\\text{Find}\\ \\ \\int_1^2 \\exp(2 x - 7) dx$$",
  "0.013",
  "+0.022+",
  "0.13",
  "0.22",
  "1.3",
  "2.2",
  random_answer_order = FALSE)
```

```{r MMAC7, echo=FALSE}
askMC(
  "$$\\text{Find}\\ \\ \\int_{-2}^{-1} \\left[\\frac{1}{x^2} + x^3\\right] dx$$",
  "-2.75",
  "+-3.25+",
  "-3.75",
  "-4.25",
  random_answer_order = FALSE)
```

```{r MMAC8, echo=FALSE}
askMC(
  "$$\\text{Find}\\ \\ \\int_0^{\\pi} \\left[\\sin(x) - \\cos(x)\\right] dx$$",
  "-2",
  "-1",
  "0",
  "1",
  "+2+",
  random_answer_order = FALSE)
```

```{r MMAC9, echo=FALSE}
askMC(
  "$$\\text{Find}\\ \\ \\int_{-\\pi}^{\\pi} \\left[\\sin(3x) - \\sin(2x)\\right] dx$$",
  "-5/6",
  "-1/2",
  "+0+",
  "1/2",
  "5/6",
  random_answer_order = FALSE)
```
