---
id: "owl-give-closet"
created: "Wed Sep 22 13:36:38 2021"
topic: "differentials"
global_id: "HoQaaq"
---


```{r diff1, echo=FALSE}
askMC(
  "What is the differential of $u = x + 5$?",
  "+$du = dx$+" = "Since $\\partial_x (x+5) = 1$.",
  "$du = (x+5)dx$" = "You should have used $\\partial_x (x+5)$ instead of $(x+5)$ on the right side.",
  "$du = 5 dx$" = "Is $\\partial_x (x+5) = 5$? No!",
  "$du = x dx$" = "You should have used $\\partial_x (x+5) = 1$ instead of $x$ on the right side."
)
```


```{r diff2, echo=FALSE}
askMC(
  "What is the differential of $u = \\sin(2x + 5)$?",
  "+$du = 2 \\cos(2x + 5) dx$+" = "Since $\\partial_x \\sin(2x + 5) = 2 \\cos(2x + 5)$.",
  "$du = (2x+5)dx$" = "You should have used $\\partial_x \\sin(2x+5)$ instead of $(2x+5)$ on the right side.",
  "$du = 5 dx$" = "Is $\\partial_x \\sin(2x+5) = 5$? No!",
  "$du = 2x dx$" = "You should have used $\\partial_x \\sin(2x+5) = 2 \\cos(2x + 5)$ instead of $2x$ on the right side."
)
```

```{r diff3, echo=FALSE}
askMC(
  "What is the differential of $v = e^x$?",
  "$du = e^x dx$" = "The name of the function here is $v()$, not $u$. So the differential should be written $dv$.",
  "+$dv = e^x dx$+" = "Since $\\partial_x e^x = 1$.",
  "$du = x dx$" = "The name of the function here is $v()$, not $u$. So the differential should be written $dv$.",
  "$dv = x dx$" = "But $\\partial e^x = e^x$, not $x$."
)
```

```{r diff4, echo=FALSE}
askMC(
  "What is the differential of $f = \\cos(\\ln(t))$?",
  "+$df = -\\frac{\\sin(\\ln(t))}{t} dt$+" = "Since the chain rule tells us $\\partial_t\\cos(\\ln(t)) = -\\sin(\\ln(t))/x$.",
    "$du = -\\frac{\\sin(\\ln(t))}{t} dt$" = "There is no $u$ in sight in this problem. It is $f$.",
    "$dv = -\\frac{\\sin(\\ln(t))}{t} dt$" = "There is no $v$ being used in this problem. It is $f$ that we are asking about.",
    "$df = -\frac{\\sin(\\ln(x))}{x} dx$" = "$f$ is a function of $t$, not $x$."
)
```

