---
id: "road-cone-metaphor"
author: "Daniel Kaplan"
---

A textbook might have a problem like this:
$$\text{Find}\ \ \int\! x^2 dx$$
This is a command to you, the student, to find a simpler algebraic form for the function $\int x^2 dx$. The answer the textbook seeks is, of course, $$\frac{1}{3} x^3 + C$$.

I would rather textbooks say: "Write an algebraic expression for the anti-derivative of the function $f(x) \equiv x^2$." We don't really need the $\int$ involved.

Now consider a textbook problem like this:
$$\text{Find}\ \ \int_{500}^{1000}\!\! \frac{x^2}{10000000}dx$$

The 0 and 10 here are the "limits of integration." The word "limit" here does not have any connection to the concept of "limits" we studied in defining the derivative of a function. Maybe it would be better to say, "0 to 10 are the bounds of integration." The idea is that we will *accumulate* the quantity $x^2 / 10000000$ over the interval $500 \leq x \leq 1000$.

To be more concrete, watch the first 30 seconds or so of the following video, which shows a truck laying out traffic cones along a road with a few moments showing the "anti" operation of collecting the cones.

<iframe width="560" height="315" src="https://www.youtube.com/embed/mwHhHh4dXJs" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

Put yourself on the scene when the construction site is being set up, a first step of which is to mark off the construction zone with traffic cones. That is what the truck is doing at the start of the video.

Suppose the truck is at position $x$ along the road. At that position, there are $f(x)$ cones on the truck. We will call this the "cone stock" on the truck. The function $\partial_x f(x)$ is the derivative of $f(x)$ with respect to $x$: As the truck drives along the road, that is, as $x$ increases, the truck is unloading its stock of cones. How fast is this unloading? In the video it looks like it is about 1 cone every 33 feet, or let's say 3 cones per hundred feet. That is, the quantity $f(x)$ is changing at a rate of 3 cones per hundred feet: $\partial_x f(x) = -0.03$. The derivative function is a constant: the cones are being placed evenly along the road.

Now imagine yourself on another day at another place, at the end of construction. The job of the truck is to pick up the cones. Imagine that the density of cones is described by the function $g(x)$. If we evaluate $g(x)$ at a specific point on the road, we get the density of cones at that point for example 6 cones per 100 feet (0.06 cones/foot). The truck has already picked up some cones and is continuing to do so. Suppose that the contractor or laid out the cones was not very good: they weren't put down at a regular spacing. Instead, in some spots the cones were put close together: so $g(x)$ is large. In other places the cones are far apart: $g(x)$ is small. The higher is $g(x)$, the more densely the cones are spaced.

As it drives along the road, the truck pick up the cones. Suppose the truck is at mile marker 1.3, equivalent to 6864 feet from marker 0. The truck picks up cones until reaching mile marker 2.4: equivalent to 12,672 feet from marker 0. How many cones did the truck pick up? Easy, it is:
$$\int_{6864}^{12,672} g(x) dx$$
The cone density along the road, $g(x)$, is a function of position. But the accumulation from mile marker 1.3 to marker 2.4 is not a function: it is a number of cones. Note the units: $g(x)$ is cones/foot while $\int g(x)dx$ is simply cones.

Now, we might prefer to keep track of the cone stock as the truck drives along the road. This would simply be a matter of counting the number of cones on the truck at each point $x$ along the road. Of course this number is changing with $x$: the stock is a *function* of $x$. This stock function is what we are trying to find when we anti-differentiate $g(x)$. If we know $g(x)$---the density of cones along the road---we can figure out $G(x)$.

It is not quite the case that $G(x)$ is the stock on the truck. to know that, we would have to know how many cones were on the truck when it started out. All we know for certain is that the flow of cones onto the truck (with respect to road position $x$) is the derivative of $G(x)$ w.r.t. $x$. That is, the flow onto the truck is $\partial_x G(x) = g(x)$.

When we know $G(x)$ we don't exactly know the stock on the truck. But from $G(x)$ we can exactly calculate how many cones the truck accumulated from mile marker 1.3 (6864 ft) to 2.4 (12,762 ft). That accumulated number will be $$G(12672) - G(6864)$$
Back to the textbook problem:
$$\text{Find}\ \ \int_{500}^{1000}\!\! \frac{x^2}{10000000}dx$$

In terms of road construction, think of this as the number of cones picked up when driving from position 500 ft to position 1000 ft. Evidently, at the start of the run---that is, at $x=500$, the density of cones is $500^2 / 10000000 =  0.025$ cones per foot: one cone every 40 feet. At the end of the run---position $x=1000$---the density is 0.1 cones per foot: one cone every 10 feet.

The answer to the textbook problem will be a number of cones. To find that number, we can follow this procedure:

1. Find an anti-derivative of the function $g(x) = \frac{x^2}{10000000}$ This will be $G(x) = \frac{x^3}{30000000}$.
2. Evaluate the anti-derivative at the starting and ending points of the run and subtract:
$$G(1000) - G(500) = \frac{1000^3}{30000000} - \frac{500^3}{30000000} = 33.333 - 4.166 = 29.166\ \text{cones}$$

Let's restate this in terms of some typical quantities involving anti-differentiation:

1. $\int g(x) dx$ is just the function $G(x)$, the anti-derivative of $g(x)$ with respect to $x$. We can find **an** anti-derivative using any of the techniques we are studying for doing so. But to remind us that we can add a constant to any anti-derivative of $g(x)$ and still have an anti-derivative, we write down $+ C$.
2. $\int_a^b g(x) dx$ is the total accumulation of $g(x)$ over the interval $a \leq x \leq b$. In terms of our road-cone example, this is the number of cones picked up between road position $x=a$ and position $x=b$. We will calculate this number using the anti-derivative evaluated at each endpoint: $$\int_a^b g(x) dx = G(b) - G(a)$$ We don't have to worry about the $+ C$ in problem (1) because we know the starting point for accumulation. At point $x=a$ we had accumulated no cones yet. There might have been some cones already on the truck (that is  the $+ C$) but it does not matter because we are looking at the *difference* in the number or cones on the truck at point $x=a$ and $x=b$, and the already-on-the-truck cones cancel out.
3. $\int_a^y g(x) dx$ can be confusing. We are used to seeing a constant for the upper bound of integration, but here we have a name. It is easier to see what's going on if we express $\int_a^y g(x)dx$ in terms of an anti-derivative function $G(x)$:
$$\int_a^y g(x) dx = G(y) - G(a)$$
This will be a function of $y$. There is no need to put in a $+ C$ because the $+ C$ for the first term will be canceled out when we subtract the $+ C$ in the second term.

Form (3) is asking us to keep track of how many cones have been added to the truck since we left point $x=a$ and reached some other point $x=y$. If we plug in $y=b$, Form (3) turns into Form (2), how many cones were collected between positions $a$ and $b$. Form (3) is something like the anti-derivative function. The only difference is that we do not need the $+ C$ because whatever it might be, it gets canceled out in the subtraction.

Suppose we are asked to calculate yet another quantity:

4. $\partial_y \int_a^y g(x) dx$, the derivative of form (3) with respect to $y$. Again, think of this in terms of the difference of anti-derivatives:
$$\partial_y \int_a^y g(x) dx = \partial_y \left[G(y) - G(a)\right] = \partial_y G(y) - \partial_y G(a) = \partial_y G(y) - 0 = g(y)$$

The next-to-last step reflects that $G(a)$ is a number of cones, not a function of $y$. The derivative with respect to $y$ of something that is not a function of $y$ is always 0.

$\partial_y \int_a^y g(x) dx$ tells us how fast the cones are accumulating on the truck as we drive along the road. In other words, $\partial_y \int_a^y g(x) dx$ has units cones/foot and it is exactly the density of cones (per foot of road) at position $y$, that is, $g(y)$, the density of cones at position $y$.
