---
id: "seaweed-bend-socks"
created: "Wed May 25 12:05:19 2022"
global_id: "aBNbzM"
skill: "Sc-Cal-403"
---


```{r sbsr-1, echo=FALSE, results="markup"}
askMC(
  prompt="Find the antiderivative $$\\int \\frac{x^2+x+1}{x}\\ dx\\ .$$",
  "+$\\frac{1}{2} x^2+x+\\ln(|x|)+C$+",
  r"($\frac{\frac{1}{3} x^3+\frac{1}{2} x^2 +x}{\frac{1}{2}x^2}+C$)",
  r"($x\cdot(\frac{1}{3} x^3+\frac{1}{2} x^2 +x)-(x^2+x+1)\cdot (\frac{1}{2} x^2)+C$)"
)  
```



```{r sbsr-2, echo=FALSE, results="markup"}
askMC(
  prompt=r"(Find the antiderivative $$\int \left(\frac{3}{t} - \frac{3}{t^2} \right)dt\ .$$)",
  r"($3\ln(t)+\frac{2}{t} +C$)",
  r"(+$3\ln|t|+\frac{2}{t} +C$+)" = r"($3\ln|t|+\frac{2}{t} +C$ is correct.  Remember, that in order for the antiderivative to match the domain of the integrand, we must take the absolute value within the natural log.)",
  r"($\frac{-3}{2t^2}+\frac 2 {3t^3} +C$)",
  r"($\frac{-3}{\frac{1}{2} t^2}+\frac {2}{\frac{1}{3} {t^3}} +C$)"
)
```





```{r sbsr-3, echo=FALSE, results="markup"}
askMC(
  prompt=r"(Find the value of $$\int_2^4(2x+3)dx\ .$$)",
  "$-18$",
  "$4$",
  "$12$",
  "+$18$+",
  random_answer_order=FALSE
)
```




```{r sbsr-4, echo=FALSE, results="markup"}
askMC(
  prompt=r"(What is the approximate value of $$\int_2^4 dnorm(x)dx\ ?$$  (Hint: You will need an R session to do the numerical calculation.)",
  "+$0.02271846$+",
  "$-0.02271846$",
  "$-0.05385714$",
  "$1.977218$",
  random_answer_order=FALSE
)
```

