---
id: "tiger-tug-shoe"
created: "Tue Jul 20 16:00:09 2021"
global_id: "CCwWGB"
---

In this activity, you are going to use the "Graph-antiD" web app which enables you to visualize the anti-derivative function in terms of areas. To use the app, click-drag-and-release to mark part of the domain of the function being displayed. 

::: {.todo}
Add a picture of the app and a link to it.
:::

To answer these questions correctly, **you must set the "Shape of function" box to 864**.


```{r tiger-C1, echo=FALSE, results="markup"}
askMC(
  "A. From the graph, roughly estimate $$\\int_0^3 f(t)dt$$ Choose the closest numerical value from the following. You could use either graph for this caclulation, but $F(t)$ will be simpler algebra.",
  -46, -26, "0"="F(t) has a net change over the interval", "3"="there is more stock at F(3) than F(0)", "19"="there is more stock at F(3) than F(0)", "26"="F(t) at the right end of the interval is lower than at the left end", right_one = -26,
  random_answer_order = FALSE
)
```

```{r tiger-C2, echo=FALSE, results="markup"}
askMC(
  "B. In order to construct the anti-derivative whose value at time $t=-3$ will be zero, what constant of integration $C$ should you **add** to the $F(t)$ shown.",
  "-120"= "Would adding this to F(-3) be equal to 0?", "-80"= "Would adding this to F(-3) be equal to 0?", "-50"= "Would adding this to F(-3) be equal to 0?", "0"= "Would adding this to F(-3) be equal to 0?", "50" = "Would adding this to F(-3) be equal to 0?", 
  "80" = "Are you sure you have the sign right?",
  "120" = "Would adding this to F(-3) be equal to 0?",
  right_one = -80,
  random_answer_order = FALSE
)
```

```{r tiger-C3, echo=FALSE, results="markup"}
askMC(
  "C. Examining the stock at time $t=0$, you observe that there are 40 units. Roughly how much stock will there be at $t=5$?",
  "-25" = "Did you shift the curve in the right direction?", "-15" = "That would be the answer if there had been 0 units of stock at time $t=0$.","0"="Imagine F(t) being shifted by the difference of 40 and F(0)", "15"="Imagine F(t) being shifted by the difference of 40 and F(0)",  25, right_one=25,
  random_answer_order = FALSE
)
```

```{r tiger-C4, echo=FALSE, results="markup"}
askMC(
  "D. You start with a stock of 100 units at time $t = -2$. At roughly what time $t$ will the stock be half of this?",
  "-1.2"="$F(t)$-$F(a)$=50, what is the value of a?", -0.3, "0.5"="$F(t)$-$F(a)$=50, what is the value of a?", "1.2"="$F(t)$-$F(a)$=50, what is the value of a?", "1.8"="$F(t)$-$F(a)$=50, what is the value of a?",
  "The stock will never fall so low.",
  right_one = -0.3,
  random_answer_order = FALSE
)
```

```{r tiger-C5, echo=FALSE, results="markup"}
askMC(
  "E. Your stock finally runs out at time $t=2.5$. When did you have 120 units in stock?",
  "+$t=-4$+", "$t=-3$"="This uses a similiar approach to the last question.", "$t=0$"="This uses a similiar approach to the last question.", 
  "There was never such a time."
)

```

```{r tiger-C6, echo=FALSE, results="markup"}
askMC(
  "F. After decreasing for a long time, the stock finally starts to increase from about $t=2.5$ onward. What about $f(t=2.5)$ tells you that $F(t=2.5)$ is increasing?",
  "The derivative is at a minimum."="Does this mean $F(t)$ must be increasing?",
  "The derivative is negative"="Does this mean $F(t)$ must be increasing?",
  "The derivative is near zero." = "Kind of. For the stock $F(t)$ to increase, what has to be true of the derivative at that instant.",
  "+The derivative becomes positive and stays positive.+",
  "The derivative is at a maximum."="Does this mean $F(t)$ must be increasing?",
  random_answer_order = FALSE
)
```

```{r tiger-C7, echo=FALSE, results="markup"}
askMC(
  "G. Find the argmin $t^\\star$ of $f(t)$ and note the sign of $f(t^\\star).$  What does this tell you about $F(t^\\star)$.",
  "$t^\\star$ is also the argmin of $F()$."="look at the corresponding point on $F(t)$.",
  "+$F(t^\\star)$ is decreasing at its steepest rate.+",
  "$F(t^\\star)$ is increasing at it's slowest rate."="look at the corresponding point on $F(t)$.",
  "$F(t^\\star)$ is increasing at its steepest rate."="look at the corresponding point on $F(t)$.",
  "$t^\\star$ is the argmax of $F()$"="look at the corresponding point on $F(t)$."
)
```

```{r tiger-C8, echo=FALSE, results="markup"}
askMC(
  "H. What is the average flow into stock over the period $-5 \\leq t \\leq 1$. (If the flow is *outward from stock*, that's the same as a negative inward flow.)",
  -30, -20, "0" = "But you can see that the stock is diminishing steadily during $-5 \\leq t \\leq 1$, so how could the average flow be zero.", "10", right_one = -20,
  random_answer_order = FALSE
)
```

```{r tiger-C9, echo=FALSE, results="markup"}
askMC(
  "I. Which of the following is an interval when the average flow is approximately zero?",
  "$-1.3 \\leq t \\leq 1.1$"="The area appears to be negative.",
  "+$0.8 \\leq t \\leq 5$+",
  "$-5 \\leq t \\leq 0$"="The area appears to be negative.",
  "None of the above",
  random_answer_order = FALSE
)
```

```{r tiker-C10, echo=FALSE, results="markup"}
askMC(
  "J. From the graph, estimate $$\\int_2^{-4} f(t)dt$$ Choose the closest numerical value from the following.",
  "-120" = "Pay attention to the order of the limits of integration.", -60, 60, 120, 
  "None of these answers are close to being right.", 
  right_one = 120,
  random_answer_order = FALSE
)
```

