---
id: "ups-and-downs"
title: "Ups and downs"
author: "Mike Brilleslyper"
---


Suppose the continuous function $f(x)$ is positive on $x \in [0, 4]$ and negative on $x \in [4, 8]$.  Let $$F(x) \equiv \int_0^x f(u) du.$$  In addition, suppose $\int_0^8 f(x)dx < 0$. 

Mark each statement as True or False.

```{r ud1, echo=FALSE}
askMC(
  "$F(x)$ has to be positive on [0,4] and negative on [4, 8].",
  "True",
  "False",
  right_one = "False", 
  random_answer_order = FALSE
)
```

```{r ud2, echo=FALSE}
askMC(
  "$F(x)$ must cross the x-axis at least once in the interval [0, 8].",
  "True",
  "False",
  right_one = "True", 
  random_answer_order = FALSE
)
```
 
	
```{r ud3, echo=FALSE}
askMC(
  "$F(0) < F(8)$.",
  "True",
  "False",
  right_one = "False", 
  random_answer_order = FALSE
)
```

	
	
```{r ud4, echo=FALSE}
askMC(
  "$F(x)$ is concave up on [0, 4] and concave down on [4, 8].",
  "True",
  "False",
  right_one = "False", 
  random_answer_order = FALSE
)
```

	
```{r ud5, echo=FALSE}
askMC(
  "$F(x)$ has a local maximum at x = 4.",
  "True",
  "False",
  right_one = "True", 
  random_answer_order = FALSE
)
```



```{r ud6, echo=FALSE}
askMC(
  "$F(x)$ has a point of inflection at x=4.",
  "True",
  "False",
  right_one = "False", 
  random_answer_order = FALSE
)
```
