---
id: "what-is"
title: "What is ...? Integral edition."
author: "Daniel Kaplan"
---

```{r whatis1, echo=FALSE, results="markup"}
askMC(
  "What is $$\\int_0^3 x^2 dx\\ \\text{?}$$",
  "$x^3/3$" = "Note that the limits of integration are numbers.",
  "$2x$",
  "6",
  "+9+",
  "a function of $x$",
  random_answer_order = FALSE)
```

```{r whatis2, echo=FALSE, results="markup"}
askMC(
  "What is $$\\int_0^u x^2 dx\\ \\text{?}$$",
  "$x^3/3$" = "One of the limits of integration is a name, namely, $u$.",
  "+$u^3/3$+",
  "6",
  "9",
  "a function of $x$",
  random_answer_order = FALSE)
```

```{r whatis3, echo=FALSE, results="markup"}
askMC(
  "What is $$\\int_v^u x^2 dx\\ \\text{?}$$",
  "$x^3/3$" = "One of the limits of integration is the named quantity $u$.",
  "$u^3/3$" = "One of the limits of integration is the named quantity $v$",
  "6",
  "9",
  "+a function of $u$ and $v$+",
  random_answer_order = FALSE)
```

```{r whatis4, echo=FALSE, results="markup"}
askMC(
  "What is $$\\int_0^3 u^2 dx\\ \\text{?}$$",
  "$x^3/3$" = "But the anti-derivative is $u^2$ with respect to $x$. that is  just $x u^2$.",
  "+$3 u^2$+" = "Right. Evaluate the anti-derivative $x u^2$ at the limits $x=0$ to $x=3$, giving $3 u^2 - 0 u^2$.",
  "6",
  "9",
  "a function of $x$" = "Note that the limits of integration are numbers.",
  random_answer_order = FALSE)
```

```{r whatis7, echo=FALSE, results="markup"}
askMC(
  "What is $$\\int_0^\\pi \\cos(2x) dx\\ \\text{?}$$",
  "$\\sin(2x) / 2$" = "that is  the right anti-derivative, but you still need to evaluate it at the two limits of integration, 0 and $\\pi$.",
  "-1" = "What is $\\sin(\\pi)$?",
  "+0+",
  "1" = "What is $\\sin(\\pi)$?",
  "a function of $x$" = "Note that the limits of integration are numbers.",
  random_answer_order = FALSE)
```

```{r whatis8, echo=FALSE, results="markup"}
askMC(
  "What is $$\\int_0^3 \\sin(\\pi t) dt\\ \\text{?}$$",
  "$-\\cos(\\pi t) / \\pi$" = "that is  the right anti-derivative, but you still need to evaluate it at the two limits of integration, 0 and 3",
  "+$$\\frac{2}{\\pi}$$+",
  "0" = "What is $\\cos(3\\pi)$?",
  "$$-\\frac{2}{\\pi}$$" = "What is $\\cos(3\\pi)$?",
  "a function of $t$" = "Note that the limits of integration are numbers.",
  random_answer_order = FALSE)
```


```{r whatis5, echo=FALSE, results="markup"}
askMC(
  "What is $$\\int_0^4 x\\, u^2 dx\\ \\text{?}$$",
  "$x^2/2$" = "Note that the limits of integration are numbers.",
  "+$8 u^2$+",
  "8",
  "16",
  "a function of $x$",
  random_answer_order = FALSE)
```

```{r whatis6, echo=FALSE, results="markup"}
askMC(
  "What is $$\\int_0^u x\\, u^2 dx\\ \\text{?}$$",
  "$x^2/2$" = "The anti-derivative will be $\\frac{x^2}{2} u^2$. Evaluate this at $x=0$ and $x=u$.",
  "+$u^4 / 2$+",
  "8",
  "16",
  "a function of $x$",
  random_answer_order = FALSE)
```
