---
id: "wolf-beat-book"
created: "Tue Sep  7 14:27:06 2021"
global_id: "bcJnUq"
---

```{r wbb9-1, echo=FALSE, results="markup"}
askMC(
  "What is the name of the with-respect-to input in $\\int g(y) dy$?",
  "+y+",
  "dy" = "The $d$ is just punctuation preceding the input name.",
  "x" = "There's no $x$ in the expression.",
  "t" = "There's no $t$ in the expression."
)
```


```{r wbb9-2, echo=FALSE, results="markup"}
askMC(
  "What is the name of the with-respect-to input in $\\int g(t) dy$",
  "+y+",
  "dy" = "The $d$ is just punctuation preceding the input name.",
  "x" = "There's no $x$ in the expression.",
  "t" = "Even though $g(t)$ is not a function of $y$, the notation says we are to anti-differentiate it with respect to $y$. The result will be $y g(t) + C$."
)

```


```{r wbb9-3, echo=FALSE, results="markup"}
askMC(
  "What is the name of the with-respect-to input in $\\int g(x, t) dt$",
  "y",
  "dt" = "The $d$ is just punctuation preceding the input name.",
  "x" = "$g()$ is a function of both $x$ and $t$, but we are indication that the anti-differentiation is to be done with respect to $t$, not $x$.",
  "+t+"
)
```
