---
id: "lion-look-shirt"
created: "Thu May 19 11:46:27 2022"
global_id: "KR1dfc"
skill: "F-exponential-params F-half-life"
---

A pot of water was boiled, then the heat turned off. The experimenter measured the water temperature (in degrees Celsius) over the next half hour. A model was built to describe the temperature data using a parameterization of the exponential function: $$\text{temp}(t)\equiv Ae^{kt}+C$$

This model is graphed below. Use the description above and the graph below to answer the following questions.

```{r echo=FALSE}
slice_plot(79*exp(-log(2)*t/3.5) + 21 ~ t, bounds(t=0:35)) %>%
  gf_labs(y="Temperature (deg. C)", x="Time (min)", subtitle="Water temperature")
```

```{r lls8-1, echo=FALSE}
askMC(
  prompt="What was the temperature of the room?",
  "$11^\circ$ Celcius",
  "+$21^\circ$ Celcius+",
  "$31^\circ$ Celcius",
  "$51^\circ$ Celcius",
  "$101^\circ$ Celcius",
  random_answer_order=FALSE
)
```

```{r lls8-2, echo=FALSE}
askMC(
  prompt="Given the temperature of the room, what value should the model use for $C$?",
  "$11^\circ$ Celcius",
  "+$21^\circ$ Celcius+" = "The temperature of the water will cool asymptotically to room temperature.",
  "$31^\circ$ Celcius",
  "$51^\circ$ Celcius",
  "$101^\circ$ Celcius",
  random_answer_order=FALSE
)
```

```{r lls8-3, echo=FALSE}
askMC(
  prompt="Using an initial temperature was $100^\\circ$ Celsius and the value of $C$, calculate the value of the parameter $A$. Enter your answer below, rounded to the nearest whole number.",
  69, "79"="At time $t=0$ the water temperature was 100$^\\circ$ C. Since $e^{k t}\\left.\\right|_{t=0} = 1$, the model reduces to $100 = A + C$.", 
  81, 100, random_answer_order=FALSE)
```

```{r lls8-4, echo=FALSE}
askMC(
  prompt="According to the graph, how long does it take the water to cool from $100^\\circ$ Celsius to $60.5^\\circ$?  (Note that 60.5 is halfway between 100 and 21.)",
  "1.0 minute",
  "+3.5 minutes+" = "Thus, 3.5 minutes is the \"half life.\"",
  "5.0 minutes",
  "15.0 minutes",
  random_answer_order=FALSE)
```

```{r lls8-5, echo=FALSE}
askMC(
  prompt="Using your answer to the question above, which of the following is the value of for the parameter $k$? (Hint: the formula is $$k=\\pm\\frac{\ln (2)}{\\text{half life}}\\ .$$ Please keep in mind that since your function is decaying, the value for $k$ must be negative.)",
  "-0.189",
  "+-0.198+",
  "-0.891",
  "-0.918",
  random_answer_order=FALSE)
```

