---
author: "Danny Kaplan"
date: 2020-06-03 
tags: [power-law, functions, third]
id: cat-lend-futon
global-id: "ILESX"
---

```{r include = FALSE}
library(etude2)
library(mosaic)
library(mosaicCalc)
library(math141Z)
```


```{r cat-lend-futon-C1, echo=FALSE}
askMC(
  prompt = "True or false: $2^x$ is a power-law function.",
  "TRUE" = "In a power-law function, the input is the base. In $2^x$, the input is the exponent. So it's an exponential function.",
  "+FALSE+",
  random_answer_order = FALSE)
```


```{r cat-lend-futon-C2, echo=FALSE}
askMC(
  prompt = "True or false: $3/x^2$ is a power-law function. ", 
  "+TRUE+",
  "FALSE" = "This is the same as $3 x^{-2}$. You can see that $x$ is the base, so this is a power-law function.",
  random_answer_order = FALSE)
```


```{r cat-lend-futon-C3, echo=FALSE}
askMC(
  prompt = "True or false: $5\\sqrt{x}$ is a power-law function. ", 
  "+TRUE+",
  "FALSE" = "This is the same as $5 x^{1/2}$. The input $x$ is the base, so this is a power-law function.")
```

```{r cat-lend-futon-C4, echo=FALSE}
askMC(
  prompt = "The gravitational force, F, between two bodies is inversely proportional to the square of the distance $d$ between them. Then ...",
  "$F = k d^{2}$" = "Inversely proportional to the square would be $d^{-2}$", 
  "+$F = kd^{-2}$+", 
  "$F = k d^{1/2}$" = "This is a square-root relationship.", 
  "$F = k d^{-1/2}$" = "This is inversely proportional to the square root."
  )
```


