---
id: "chicken-chew-screen"
created: "Thu Jul 22 09:48:56 2021"
global_id: "3KEgLM"
---

In this activity, you will start getting familiar with the structure of R computer commands. Particularly when mathematical formulas are involved, commands are similar across many computer languages, so what you learn will be applicable to any other languages such as Python or MATLAB.

The first high-level computer language was FORTRAN, released in 1957. The name stands for "formula translation." FORTRAN enabled arithmetic operations to be written in a way very nearly that of traditional notation. Until then, computer programs were written using alpha-numeric codes that were meaningless to a casual reader. We unfortunately still use the term "computer code" to refer to programs, despite 70-years progress in improving legibility. 

The best way to learn to implement mathematical formulas in a computer language is to read examples and practice writing them. 

Here are some examples:

Traditional notation | R notation 
---------------------|-------------
$3 + 2$              | `3 + 2`
$3 \div 2$           | `3 / 2`
$6 \times 4$         | `6 * 4`
$\sqrt{\strut4}$     | `sqrt(4)`
$\ln 5$              | `log(5)`
$2 \pi$              | `2 * pi`
$\frac{1}{2} 17$     | `(1 / 2) * 17`
$17 - 5 \div 2$      | `17 - 5 / 2`
$\frac{17 - 5}{\strut 2}$   | `(17 - 5) / 2`
$3^2$                | `3^2`
$e^{-2}$             | `exp(-2)`

Each of these examples has been written using numbers as inputs to the mathematical operations. The syntax will be the same when using an input name such as `x` or `y` or `altitude`, for instance `(x - y) / 2`. In order for that command using `x` and `y` to work, some meaning must have been previously attached to the symbols. We'll come back to this important topic on another day.

Read through the above table of examples several times. Note down any that you find at all confusing. Then cover up the right side of the table and write down the R expression for each item on the left side. Similarly, cover up the left side of the table and translate the R expression into traditional notation.

::: {.scaffolding  data-latex=""}
Open a `r sandbox_link()` and, one at a time, write and run the R expression for each of these traditional-notation expressions. We give the numerical result for each of the traditional expressions to let you confirm that your R version is correct.

i. $(16 - 3)/2$ gives result `r (16-3)/2`
ii. $\sqrt{\frac{19}{3}}$ gives `r sqrt(19/3)`
iii. $\cos(\frac{2 \pi}{3})$ gives `r cos(2 * pi / 3)`
iv. $\pi^3 + 2$ gives `r pi^3 + 2`
v. $\pi^{3+2}$ gives `r pi^(3+2)`

:::

Once you have a grasp of how to render traditional-notation formulas into R, read these few principles to help consolidate your understanding.

i. Computer languages generally, and R in particular, involve expressions that are written in a typewriter format: one conventional character after another in a straight line. There are no superscripts or subscripts used. So, $\frac{1}{3}$ will be written `1/3`. The equivalent of $\sqrt{7}$ is `sqrt(7)`.
ii. Parentheses:
    a. When an opening parenthesis directly follows a name, as in `sqrt(`, it means that the named operation is to be ***applied*** to the quantity inside the parentheses. So `sqrt(7)` means "take the square root of 7" and `log(10)` means "take the (natural) logarithm of 10." The common mathematical functions typically take only one input. We'll stick with those for now.
    b. When an opening parenthesis does not directly follow a name, as in `6 - (2+3)`, the parentheses stand for ***grouping*** in the same way as in traditional notation. For instance, $(6 + 15) / 3$ is translated as `(6 + 15) / 3`.
iii. Multiplication and exponentiation are often written traditionally in terms of the relative position of quantities. So $(3 + 2)\pi$ means to multiply 5 times $\pi$, even though there is no multiplication sign being written. Similar, $\pi^{3 + 2}$ means to raise $\pi$ to the fifth power. There is no "exponentiation sign" used, just the positioning of $3+2$ as a superscript: $^{3+2}$. In R (and almost every computer language) multiplication and exponentiation **must be written explicitly**. The quantities $(3 + 2)\pi$ and $\pi^{3 + 2}$ would be translated as `(3 + 2) * pi` and `pi^(3+2)`. 
    
One additional note: All these examples can be written with a single line of code, as is true for many short formulas. Later on, we'll encounter longer formulas that *could* be written on a single line but are more readable when spread over two or more consecutive lines.   


