---
id: "convention-drill"
author: "Daniel Kaplan"
global-id: "TKWEW"
---

```{r include=FALSE}

```

Use the *MOSAIC Calculus* naming conventions to answer these questions.

`r MC_counter$reset()`

```{r cdrill-1, echo=FALSE, results="markup"}
askMC(
  "What is $h()$?", 
  "+The name of a function+" = "Right. Typically we use $f()$, $g()$, $h()$ or something similarly generic to stand for a function that we're going to be working with for a little while. Think of these as pronouns. Just as we can say, meaningfully, \"She gave it to him,\" we can say $h(x) \\equiv f(x) + g(2*x)$",
  "The name of an input." = "Sorry, these will usually be letters like $x$, $y$, $t$.",
  "A specific numerical value" = "Sorry, but we'll use constructions with a subscript like $x_0$ or $y_\\star$ and the like for these."
)
```


```{r cdrill-2, echo=FALSE, results="markup"}
askMC(
  "How come we write $f()$ for the name of a function rather than just $f$ or $f(x)$?", 
  "No good reason" = "We certainly intend with the empty parentheses to remind the reader that a name refers to a function. If you spot a place where we violate this intention, point it out to us.",
  "+It's a reminder that we're talking about a function with the name \"$f$\".+",
  "The parentheses are part of the name." = "Not at all. Names in R never contain parentheses. So `f`, `fbar`, `fred` are all valid names in an R command, but `f()` is not. We use the parentheses when writing to a human audience as a reminder that the name is referring to a function. The computer doesn't need any such reminders"
)
```

```{r cdrill-3, echo=FALSE, results="markup"}
askMC(
  "What sort of thing is denoted by $x_0$ or $y_\\star$ or $y_{max}$?", 
  "+A particular numerical value+" = "Right. For instance, it might be the particular value for the input to a function which produces an output of zero. Or it might be a particular location in the domain of a function.",
  "The name of an input" = "Sorry. We won't typically use subscripts when referring to an input name."
)
```

```{r cdrill-4, echo=FALSE, results="markup"}
askMC(
  "Which of these symbols might stand for the entire **domain** of a function?",
  "+$y$+" = "Right. Another term to use for a symbol standing for a domain is \"name of an input\".", 
  "$f()$" = "No, this is how we write the name of the function called \"$f$\"",
  "$y_0$" = "No. $y_0$ might be used to stand for a single point in the domain."
)
```

```{r cdrill-5, echo=FALSE, results="markup"}
askMC(
  "Suppose you come across $v(w) \\equiv w + 3$ in this book. What do $v$ and $w$ stand for?",
  "+$v()$ is the name of a function and $w$ is the name of the input to that function.+" = "Right. Whenever we write something like \"name(another_name) $\\equiv$\", we're saying **explicitly** that \"name\" refers to a function and \"another_name\" refers to an input.",
  "It's meaningless." = "We'll try not to write meaningless mathematical expressions. If we do by mistake, let us know.",
  "It's the same thing as $v = w + 3$." = "$v = w+3$ is an **equation**. But $v(w) \\equiv w+3$ is the format for **defining a function** named $v()$."
)
```

```{r cdrill-6, echo=FALSE, results="markup"}
askMC(
  "Are $g(x) \\equiv x^2$ and $h(w) \\equiv w^2$ the same function?", 
  "+Yes, although that function is being given two different names.+" = "The only thing that's significant about the name of an input is that it be used consistently in the function algorithm.",
  "Of course not!" = "Sorry. I suppose you might ask, \"What do you mean by the **same** function?\" Remember that a function is a relationship between inputs and the output. $g(x) \\equiv x^2$ and $h(w) \\equiv w^2$ describe exactly the same relationship: the output will be the square of the input."
)
```

  
  
  
  
  
  
  
  
  
  
  
  


