---
id: "cow-likes-chair"
author: "Daniel Kaplan"
---


For each of the following function definitions, what is the input name?

```{r clc2-1, echo=FALSE, results="markup"}
askPDF(
  "Input name in $g(t) \\equiv 2 t^2 + 8$?",
  "+t+", "u", "v", "w", "x", "y", "z", random_answer_order=FALSE
)
```

```{r clc2-2, echo=FALSE, results="markup"}
askMC(
  "Input name in $\\line(z) \\equiv a z + b$?",
  "t", "u", "v", "w", "x", "y", "+z+", random_answer_order=FALSE
)
```

```{r clc2-3, echo=FALSE, results="markup"}
askMC(
  "Input name in $h(t) \\equiv 2 t^2 + 8 w$?",
  "+t+", "u", "v", "w", "x", "y", "z", random_answer_order=FALSE
)
```

```{r clc2-4, echo=FALSE, results="markup"}
askMC(
  "Input name in $f(u) \\equiv a u + b + u^2$?",
  "t", "+u+", "v", "w", "x", "y", "z", random_answer_order=FALSE
)
```


```{r clc2-5, echo=FALSE, results="markup"}
askMC(
  "Input name in $g(w) \\equiv x + 4$?",
  "t", "u", "v", "+w+", "x"="Tricked you! it is the name in the parentheses on the left side of $\\equiv$ that matters. Evidently, the output of $g(w)$ does not depend on $w$. That is not much of a relationship, but it is a common one.", "y", "z", random_answer_order=FALSE
)
```
