---
title: "Dimensions of parameters"
author: "Daniel Kaplan"
id: "dim-params"
global-id: "DVGKY"
---

```{r include=FALSE}
library(etude2)
```

```{r daily-digital-10-QA7, echo=FALSE, results="markup"}
askMC(
  prompt = "The dimension of $t$ is T,  that is, $[t] = T$. What must the dimension of $k$ be in $e^{kt}$ for the operation  to make sense?",
    "[1]"  = "Then $[k\\,t] = \\text{T}$, which  would violate the exponential rule.",
    "+T$^{-1}$+" = "Right, [k] needs to cancel out [t] so that the exponention is valid.",
    "T" = "Then $[k\\,t] = \\text{T}$^2$, which  would  violate the exponential rule.",
    "None of the above"  = "",
  inline = FALSE
)
```

```{r daily-digital-10-QA8, echo=FALSE, results="markup"}
askMC(
  prompt = "What must the dimension of $c$ for the arithmetic operation $1 + c \\cdot 2^{k\\,t}$  to make sense?",
    "+[1]+"  = "Right.  You're going to  have to add $c \\cdot 2^{kt}$ to 1. Since $[k\\,t] = [1]$, $c$ also needs to be dimensionless.",
    "T$^{-1}$" = "",
    "T" = "Then $[k\\,t] = $T^2$, which  would  violate the exponential rule.",
    "Depends on the dimension of  $2^{kt}$"  = "We already determined that $[kt]  = [1]$, so $[2^{kt}] = [1]$.",
  inline = FALSE,
  random_answer_order =  FALSE
)
```
