

```{r drill-M01-4, echo=FALSE, results='markup'}
askMC(
  prompt = r"(What is the **value** of $f(4)$ when $f(x) \equiv 2 x + 1\ ?$  )",
r"(-2)" = r"( )",
  r"(-4)" = r"( )",
  r"(2)" = r"( )",
  r"(4)" = r"( )",
  r"(+9+)" = r"( )",
  random_answer_order=FALSE,
  item_label = "Drill "
)
```



```{r drill-M01-5, echo=FALSE, results='markup'}
askMC(
  prompt = r"(What is the **change** in the value of $f()$ when the input goes from 2 to 4?     
Assume $f(x) \equiv 2 x + 1$    )",
r"(-4)" = r"( )",
  r"(-2)" = r"( )",
  r"(2)" = r"( )",
  r"(+4+)" = r"( )",
  r"(9)" = r"( )",
  random_answer_order=FALSE,
  item_label = "Drill "
)
```



```{r drill-M01-6, echo=FALSE, results='markup'}
askMC(
  prompt = r"(What is the **rate of change** in the value of $f()$ when the input goes from 2 to 4?     
Assume $f(x) \equiv 2 x + 1$   )",
r"(-2)" = r"( )",
  r"(-4)" = r"( )",
  r"(+2+)" = r"( )",
  r"(4)" = r"(You've calculated the net change, not the rate of change.)",
  r"(9)" = r"( )",
  random_answer_order=FALSE,
  item_label = "Drill "
)
```



```{r drill-M01-7, echo=FALSE, results='markup'}
askMC(
  prompt = r"(What is the **change** in the value of $f()$ when the input goes from 4 to 2?     
Assume $f(x) \equiv 2 x + 1$   )",
r"(-2)" = r"( )",
  r"(+-4+)" = r"( )",
  r"(2)" = r"( )",
  r"(4)" = r"(The change in the value of $f()$ when the input goes from $a$ to $b$ is $f(b) - f(a)$)",
  r"(9)" = r"( )",
  random_answer_order=FALSE,
  item_label = "Drill "
)
```



```{r drill-M01-8, echo=FALSE, results='markup'}
askMC(
  prompt = r"(What is the **rate of change** in the value of $f()$ when the input goes from 4 to 2?     
Assume $f(x) \equiv 2 x + 1$   )",
r"(-2)" = r"( )",
  r"(-4)" = r"( )",
  r"(+2+)" = r"(The rate of change in the value of $f()$ when the input goes from $a$ to $b$ is $$\frac{f(b) - f(a)}{b-a}$$ This does not depend on the order of $a$ and $b$, so the rate of change is the same when the input goes from $a$ to $b$ as when it goes from $b$ to $a.$)",
  r"(4)" = r"( )",
  r"(9)" = r"( )",
  random_answer_order=FALSE,
  item_label = "Drill "
)
```



```{r drill-M01-9, echo=FALSE, results='markup'}
askMC(
  prompt = r"(What is the **rate of change** of the function $f(x) \equiv 3 x - 2$ when the input is 4?  )",
r"(-2)" = r"( )",
  r"(0.3)" = r"( )",
  r"(2)" = r"( )",
  r"(+3+)" = r"( )",
  r"(10)" = r"(This is the **value** of $f(4)$, not the rate of change at $x=4$.)",
  random_answer_order=FALSE,
  item_label = "Drill "
)
```



```{r drill-M01-10, echo=FALSE, results='markup'}
askMC(
  prompt = r"(What is the **change** in value of the  function $f(x) \equiv 3 x - 2$ as the input goes from 3 to 3.1?  )",
r"(-2)" = r"( )",
  r"(+0.3+)" = r"($f(3.1) = 7.3$ and $f(3) = 7$, so $f(3.1) - f(3) = 0.3$.)",
  r"(2)" = r"( )",
  r"(3)" = r"( )",
  r"(10)" = r"( )",
  random_answer_order=FALSE,
  item_label = "Drill "
)
```



```{r drill-M01-11, echo=FALSE, results='markup'}
askMC(
  prompt = r"(What is the **rate of change** in value of the  function $$f(x) \equiv 3 x - 2$$ as the input goes from 3 to 3.1?  )",
r"(-2)" = r"( )",
  r"(0.3)" = r"( )",
  r"(2)" = r"( )",
  r"(+3+)" = r"(The rate of change is $$\frac{f(3.1) - f(3)}{3.1 - 3}$$)",
  r"(10)" = r"( )",
  random_answer_order=FALSE,
  item_label = "Drill "
)
```

```{r drill-M03-2, echo=FALSE, results='markup'}
askMC(
  prompt = r"(What is the period of the $\sin()$ function? )",
r"(1)" = r"( )",
  r"($2/\pi$)" = r"( )",
  r"($\pi/2$)" = r"( )",
  r"($\pi$)" = r"( )",
  r"(+$2 \pi$+)" = r"( )",
  random_answer_order=FALSE,
  item_label = "Drill "
)
```



```{r drill-M03-6, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Which of these words is most appropriate to describe the function $g(x) \equiv 2 - 3 x + 4x^3 ?$ )",
r"(+Polynomial+)" = r"( )",
  r"(Discontinuous)" = r"( )",
  r"(Periodic)" = r"( )",
  r"(Power-law)" = r"(Each of the functions in the sum is a power-law, but added together they are no longer a power-law function.)",
  random_answer_order=TRUE,
  item_label = "Drill "
)
```

```{r echo=FALSE}
#| label: fig-m3-twelve
#| fig-cap: "."
#| out-width: "100%"
pA <- slice_plot(exp(x) ~ x, domain(x=c(1,2))) %>% gf_labs(subtitle="(A)", y="")
pB <- slice_plot(sin(2*x) ~ x, domain(x = c(0,3))) %>% gf_labs(subtitle="(B)", y="")
pC <- slice_plot(log(x) ~ x, domain(x=c(1,2))) %>% gf_labs(subtitle="(C)", y="")
gridExtra::grid.arrange(pA, pB, pC, ncol=3)
```  
  
```{r drill-M03-12,  echo=FALSE, results='markup'}
askMC(
  prompt = "Which of the functions in @fig-m3-twelve is **concave up** over the domain shown in the graph?",
r"(+A+)" = r"( )",
  r"(B)" = r"(This is concave down toward the left and concave up toward the right.)",
  r"(C)" = r"(This is concave down.)",
  random_answer_order=TRUE,
  item_label = "Drill "
)
```

```{r echo=FALSE, warning=FALSE}
#| label: fig-m3-fourteen
#| fig-cap: "."
#| out-width: "100%"
pA <- slice_plot(log(x) ~ x, domain(x=c(-1,2)), npts=300) %>% gf_labs(subtitle="(A)", y="")
pB <- slice_plot(x^2 ~ x, domain(x=c(-3,3)))  %>% gf_labs(subtitle="(B)", y="")
pC <- slice_plot(sin(2*x) ~ x, domain(x = c(0,3))) %>% gf_labs(subtitle="(C)", y="")
gridExtra::grid.arrange(pA, pB, pC, ncol=3)
```

```{r drill-M03-13,  echo=FALSE, results='markup'}
askMC(
  prompt = r"(Which of these functions in @fig-m3-fourteen has a **vertical** asymptote? )",
  "+A+" = r"( )",
  "B" = r"(The $\sin()$ function does not have a vertical or horizontal asymptote.)",
  "C" = r"(This exponential function has a **horizontal** asymptote as $x \rightarrow -\infty$)",
  random_answer_order=TRUE,
  item_label = "Drill "
)
```


```{r echo=FALSE, warning=FALSE}
#| label: fig-m3-fourteen-b
#| fig-cap: "."
#| out-width: "100%"
pA <- slice_plot(log(x) ~ x, domain(x=c(-0.5,2))) %>% gf_labs(subtitle="(A)", y="")
pB <- slice_plot(exp(x) ~ x, domain(x=c(-4,2)), npts=300)  %>% gf_labs(subtitle="(B)", y="")
pC <- slice_plot(sin(2*x) ~ x, domain(x = c(0,3))) %>% gf_labs(subtitle="(C)", y="")
gridExtra::grid.arrange(pA, pB, pC, ncol=3)
```


```{r drill-M03-14,  echo=FALSE, results='markup'}
askMC(
  prompt = r"(Which of the functions in @fig-m3-fourteen-b has a **vertical** asymptote? )",
  "+A+" = r"( )",
  "B" = r"(This sigmoid function does not have a vertical asymptote, although it does have horizontal asymptotes. )",
  "C" = r"(This exponential function has a **horizontal** asymptote as $x \rightarrow -\infty$, but not a vertical asymptote.)",
  random_answer_order=TRUE,
  item_label = "Drill "
)
```

```{r echo=FALSE}
#| label: fig-m3-fourteen-c
#| fig-cap: "."
#| out-width: "60%"
slice_plot(1/(x-1) + 20 ~ x, domain(x=c(1.03,2)), npts=300) %>% 
  slice_plot(1/(x-1) + 20 ~ x, domain(x=c(-2, .97)), npts=300) 
```



```{r drill-M03-15,  echo=FALSE, results='markup'}
askMC(
  prompt = r"(For the function in @fig-m3-fourteen-c, where is the **vertical** asymptote located? )",
r"(At $x=0$)" = r"( )",
  r"(+At $x=1$+)" = r"( )",
  r"(At 20 as $x \rightarrow \pm\infty$)" = r"(For **horizontal** asymptotes, the description takes this form, but for vertical asymptotes specify the value of the input at which the function value skyrockets.)",
  random_answer_order=FALSE,
  item_label = "Drill "
)
```


```{r drill-M03-18,  echo=FALSE, results='markup'}
askMC(
  prompt = r"(For the function in @fig-m3-fourteen-c, where is the **horizontal** asymptote located? )",
r"(At $x=0$)" = r"(We are looking for a **horizontal** asymptote. This is a description of a **vertical** asymptote.)",
  r"(At $x=1$)" = r"(We are looking for a **horizontal** asymptote. This is a description of a **vertical** asymptote.)",
  r"(+At 20 as $x \rightarrow \pm\infty$+)" = r"( )",
  random_answer_order=FALSE,
  item_label = "Drill "
)
```

```{r echo=FALSE}
#| label: fig-m3-twelve-b
#| fig-cap: "."
#| out-width: "60%"
slice_plot(log(x) ~ x, domain(x=c(1,2))) 
```

```{r drill-M03-16,  echo=FALSE, results='markup'}
askMC(
  prompt = r"(Does the function in @fig-m3-twelve-b have an **inflection point**?)",
  r"(yes)" = r"(But there is no spot where the function switches from concave up to concave down.)",
  r"(+no+)" = r"(The function is concave down and never switches to concave up.)",
  r"(cannot tell)" = r"(Yes you can. You can see the curvature pretty easily on the graph.)",
  random_answer_order=FALSE,
  item_label = "Drill "
)
```


```{r echo=FALSE}
#| label: fig-m3-fourteen-d
#| fig-cap: "."
#| out-width: "60%"
slice_plot(pnorm(x) ~ x, domain(x=c(-4, 4))) 
```


```{r drill-M03-17,  echo=FALSE, results='markup'}
askMC(
  prompt = r"(Does the function in @fig-m3-fourteen-d have an **inflection point**?)",
r"(+yes+)" = r"(The function is concave up to the left of $x=0$, and concave down to the right. The concavity c70hanges at $x=0$ (although the exact point is hard to make out in the graph). A point where the concavity changes is an inflection point.)",
  r"(no)" = r"(The concavity changes from positive on the left of the graph to negative on the right. So there must be an inflection point in between.)",
  r"(cannot tell)" = r"(Yes you can. You can see the curvature pretty easily on the graph.)",
  random_answer_order=FALSE,
  item_label = "Drill "
)
```



```{r echo=FALSE}
#| label: fig-m3-fourteen-e
#| fig-cap: "."
#| out-width: "60%"
slice_plot(4* pnorm(x) + 2 ~ x, domain(x=c(-4, 4)))
```


```{r drill-M03-19,  echo=FALSE, results='markup'}
askMC(
  prompt = r"(Which of these is a correct description of a horizontal asymptote in the function in @fig-m3-fourteen-e?)",
r"(At 2 as $x \rightarrow \pm\infty$)" = r"(There are different horizontal asymptotes for $x \rightarrow \infty$ and for $x \rightarrow -\infty$)",
  r"(+At 2 as $x \rightarrow -\infty$+)" = r"( )",
  r"(At 6 as $x \rightarrow -\infty$)" = r"( )",
  r"(There is no horizontal asymptote.)" = r"( )",
  random_answer_order=TRUE,
  item_label = "Drill "
)
```



```{r drill-M03-20,  echo=FALSE, results='markup'}
askMC(
  prompt = r"(Which of these is a correct description of a horizontal asymptote in the function in @fig-m3-fourteen-e?)",
r"(At 2 as $x \rightarrow \pm\infty$)" = r"(There are different horizontal asymptotes for $x \rightarrow \infty$ and for $x \rightarrow -\infty$)",
  r"(At 2 as $x \rightarrow \infty$)" = r"( )",
  r"(+At 6 as $x \rightarrow \infty$+)" = r"( )",
  r"(There is no horizontal asymptote.)" = r"( )",
  random_answer_order=TRUE,
  item_label = "Drill "
)
```

```{r echo=FALSE}
#| label: fig-rev2-03
#| fig-cap: "."
#| out-width: "60%"
slice_plot(sin(2*pi*(t+2.5)/5) ~ t, domain(t=c(-5.2,5.2))) %>%
  gf_refine(scale_x_continuous(breaks = -5:5))
```

```{r drill-Quiz-2-7,  echo=FALSE, results='markup'}
askMC(
  prompt = r"(Which of these is the max of the function in @fig-rev2-03?)",
r"(0)" = r"( )",
  r"(1)" = r"( )",
  r"(2)" = r"( )",
  r"(+3+)" = r"( )",
  r"(4)" = r"(4 is close to the argmax, but we are asking about the max.)",
  random_answer_order=FALSE,
  item_label = "Drill "
)
```

```{r echo=FALSE}
#| label: fig-rev2-02b
#| fig-cap: "."
#| out-width: "60%"
slice_plot(sin(2*pi*(t+2.5)/5) ~ t, domain(t=c(-5.2,5.2))) %>%
  gf_refine(scale_x_continuous(breaks = -5:5))
```


```{r drill-Quiz-2-4,  echo=FALSE, results='markup'}
askMC(
  prompt = r"(Which of these is an argmin of the function in @fig-rev2-02b?)",
r"( $t = -2.5$)" = r"( )",
  r"( $t = -1.25$)" = r"(that is  an argmax!)",
  r"($t = 0$)" = r"( )",
  r"(+ $t = 1.25$+)" = r"( )",
  r"( $t = 2.5$)" = r"( )",
  random_answer_order=FALSE,
  item_label = "Drill "
)
```

```{r drill-Quiz-2-3, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Which of these is an argmax of the function in @fig-rev2-02b?)",
r"( $t = -2.5$)" = r"( )",
  r"(+ $t = -1.25$+)" = r"( )",
  r"($t = 0$)" = r"( )",
  r"( $t = 1.25$)" = r"(that is  an argmin!)",
  r"( $t = 2.5$)" = r"( )",
  random_answer_order=FALSE,
  item_label = "Drill "
)
```

```{r echo=FALSE}
#| label: fig-quiz-1-argmax
#| fig-cap: "."
#| out-width: "60%"
slice_plot(3*sin(2*pi*t/8) ~ t, domain(t=c(0,4))) 
```


```{r drill-Quiz-1-14, echo=FALSE, results='markup'}
askMC(
  prompt = r"(According to @fig-quiz-1-argmax, which of these values is the argmax of the function?)",
r"(0)" = r"( )",
  r"(1)" = r"( )",
  r"(+2+)" = r"( )",
  r"(3)" = r"( )",
  random_answer_order=FALSE,
  item_label = "Drill "
)
```



```{r drill-Quiz-1-15, echo=FALSE, results='markup'}
askMC(
  prompt = r"(According to @fig-quiz-1-argmax, which of these values is the maximum of the function?)",
r"(0)" = r"( )",
  r"(1)" = r"( )",
  r"(2)" = r"( )",
  r"(+3+)" = r"( )",
  random_answer_order=FALSE,
  item_label = "Drill "
)
```



```{r drill-Quiz-1-16, echo=FALSE, results='markup'}
askMC(
  prompt = r"(For the function in @fig-quiz-1-argmax, which of these properties **does not apply**?)",
r"(continuous)" = r"( )",
  r"(+monotonic+)" = r"( )",
  r"(concave-down)" = r"(The function is concave down.)",
  r"(no inflection point)" = r"(The concavity of the function does not change from up to down, so there is no inflection point.)",
  random_answer_order=TRUE,
  item_label = "Drill "
)
```

```{r echo=FALSE}
#| label: fig-properties-1
#| fig-cap: "."
#| out-width: "60%"
slice_plot(3 - 0.01* exp(t) ~ t, domain(t=c(0,5))) 
```


```{r drill-Quiz-1-17, echo=FALSE, results='markup'}
askMC(
  prompt = r"(For the function in @fig-properties-1, which of these properties **does not apply**?)",
r"(+discontinuous+)" = r"( )",
  r"(monotonic)" = r"( )",
  r"(concave-down)" = r"( )",
  r"(no inflection point)" = r"(The concavity of the function does not change from up to down, so there is no inflection point.)",
  random_answer_order=TRUE,
  item_label = "Drill "
)
```


```{r echo=FALSE}
#| label: fig-rev2-03b
#| fig-cap: "."
#| out-width: "60%"
slice_plot(2 * sin(2*pi*(t+2.5)/5)  + 1 ~ t, domain(t=c(-5.2,5.2))) %>%
  gf_refine(scale_x_continuous(breaks = -5:5))
```

```{r drill-Quiz-2-22, echo=FALSE, results='markup'}
askMC(
  prompt = r"(What's the period of the sinusoid in @fig-rev2-03b?)",
r"(1)" = r"( )",
  r"(2)" = r"( )",
  r"(3)" = r"( )",
  r"(4)" = r"( )",
  r"(+5+)" = r"( )",
  random_answer_order=FALSE,
  item_label = "Drill "
)
```

```{r drill-M03-1, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Which of these pattern-book functions has a discontinuity? )",
r"(+$g(x) \equiv x^{-1}$+)" = r"( )",
  r"($g(x) \equiv - x^1$)" = r"( )",
  r"($\text{dnorm}(x)$)" = r"( )",
  r"($\sin(x)$)" = r"( )",
  random_answer_order=TRUE,
  item_label = "Drill "
)
```