

```{r echo=FALSE}
#| label: fig-drill-rev2-05
#| fig-cap: "."
#| out-width: "60%"
f <- rfun(~ x & y, seed=201)
contour_plot(-f(x - 0.5, y) ~ x & y, 
             bounds(x=c(-3,3), y=c(0,6)),
             skip = 0) %>%
  gf_refine(coord_fixed(), 
            scale_x_continuous(breaks=-3:3),
            scale_y_continuous(breaks=0:6)) 
```


```{r drill-Quiz-2-9, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Considering the function shown in @fig-drill-rev2-05, at which of these inputs is the function output nearly zero? )",
r"(+$(x=0, y=6)$+)" = r"( )",
  r"($(x=1, y=5)$)" = r"( )",
  r"($(x=-2, y=6)$)" = r"( )",
  r"($(x=0, y=1)$)" = r"( )",
  random_answer_order=TRUE,
  item_label = "Drill "
)
```



```{r drill-Quiz-2-10, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Considering the function shown in @fig-drill-rev2-05, at which of these inputs is the function output nearly 1?)",
r"($(x=0, y=6)$)" = r"( )",
  r"(+$(x=1, y=5)$+)" = r"( )",
  r"($(x=-2, y=6)$)" = r"( )",
  r"($(x=0, y=1)$)" = r"( )",
  random_answer_order=TRUE,
  item_label = "Drill "
)
```





```{r drill-Quiz-2-11, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Which of these is a positive-going zero crossing of $g(t)$ where $$g(t) \equiv \sin\left(\frac{2\pi}{5}t-3\right)\ ?$$)",
r"(+$t=15/2\pi$+)" = r"(This makes the $\frac{2\pi}{5}t$ component go to 3, which cancels out the -3.)",
  r"($t = 2 \pi/15$)" = r"( )",
  r"($t = 3$)" = r"(Notice that the argument is **not** $\frac{2\pi}{5}(t-3)$.)",
  r"(None of the above)" = r"( )",
  random_answer_order=FALSE,
  item_label = "Drill "
)
```


```{r drill-Quiz-2-14, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Which of the following is a positive-going zero crossing of $g(t)$? $$\sin\left(\frac{2 \pi}{5} (t - 3) \right)$$ )",
r"($t=-5$)" = r"(5 isn't in the $\sin()$ parentheses.)",
  r"($t=-3$)" = r"(When the argument to $\sin()$ is zero, the function output is at zero and increasing.)",
  r"($t=0$)" = r"(When the argument to $\sin()$ is zero, the function output is at zero and increasing.)",
  r"(+$t=3$+)" = r"($t=3$ makes the whole argument zero.)",
  r"($t=5$)" = r"(5 isn't in the $\sin()$ parentheses.)",
  random_answer_order=FALSE,
  item_label = "Drill "
)
```

```{r echo=FALSE}
#| label: fig-rev2-02
#| fig-cap: "."
#| out-width: "60%"
slice_plot(sin(2*pi*(t+2.5)/5) ~ t, bounds(t=c(-5.2,5.2))) %>%
  gf_refine(scale_x_continuous(breaks = -5:5))
```


```{r drill-Quiz-2-2, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Which input is a negative-going zero-crossing of the function graphed in @fig-rev2-02?)",
r"( $t = -2.5$)" = r"( )",
  r"( $t = -1.25$)" = r"( )",
  r"(+$t = 0$+)" = r"( )",
  r"( $t = 1.25$)" = r"( )",
  r"( $t = 2.5$)" = r"( )",
  random_answer_order=FALSE,
  item_label = "Drill "
)
```

```{r}
#| label: fig-rev2-01
#| fig-cap: "."
#| out-width: "60%"
slice_plot(sin(2*pi*t/5) ~ t, bounds(t=c(-5.2,5.2))) %>%
  gf_refine(scale_x_continuous(breaks = -5:5))
```


```{r drill-Quiz-2-1, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Which input is a positive-going zero-crossing of the function graphed in @fig-rev2-01?)",
r"(+$t = -5$+)" = r"( )",
  r"( $t = -2.5$)" = r"( )",
  r"( $t = -1.25$)" = r"( )",
  r"( $t = 1.25$)" = r"( )",
  r"( $t = 2.5$)" = r"( )",
  random_answer_order=FALSE,
  item_label = "Drill "
)
```



```{r drill-Quiz-2-17, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Considering the function graphed in @fig-rev2-05, at which of these inputs is the function output nearly $-1$? )",
r"($(x=0, y=6)$)" = r"( )",
  r"($(x=1, y=5)$)" = r"( )",
  r"(+$(x=-2, y=6)$+)" = r"( )",
  r"($(x=0, y=1)$)" = r"( )",
  random_answer_order=TRUE,
  item_label = "Drill "
)
```

```{r echo=FALSE}
#| label: fig-M3-14-05
#| fig-cap: "."
#| out-width: "60%"
slice_plot(x^2 ~ x, bounds(x=c(-3,3)))
```


```{r drill-M04-29, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Which command made this plot in @fig-M3-14-05?)",
r"(+`slice_plot(x^2 ~ x, bounds(x=c(-3,3)))`+)" = r"( )",
  r"(`plot(x^2 ~ x, domain=c(-3,3))`)" = r"(Two things are wrong here: 1) the R/mosaic function to draw graphs of functions of one input is `slice_plot()`, not `plot`; 2) the graphics domain should be set this way: `bounds(x=c(-3,3))`)",
  r"(`slice_plot(x^2, bounds(x=c(-3,3)))`)" = r"(The first argument to `slice_plot()` needs to be a tilde expression, for instance `x^2 ~ x`.)",
  r"(`slice_plot(x^2 ~ x, x=c(-3,3))`)" = r"( )",
  r"(None of them correspond to the plot.)" = r"( )",
  random_answer_order=TRUE,
  item_label = "Drill "
)
```


```{r echo=FALSE}
#| label: fig-M3-14-04
#| fig-cap: "."
#| out-width: "60%"
slice_plot(pnorm(x) ~ x, bounds(x=c(-4, 4)))
```



```{r drill-M04-30, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Which command made the plot in @fig-M3-14-04?)",
r"(+`slice_plot(pnorm(x) ~ x, bounds(x=c(-4, 4)))`+)" = r"( )",
  r"(`slice_plot(pnorm(x) ~ x, bounds(x=(-4, 4))`)" = r"(The end-points of the domain need to be collected by the function `c()`, so the argument to `bounds()` should be `x=c(-4,4)` not `x=(-4, 4)`)",
  r"(`slice_plot(pnorm(x) ~ y, bounds(x=c(-4, 4)))`)" = r"(The name of the input to the function being graphed, `x` here, needs to be stated on the right-hand side of the tilde expression. So use `pnorm(x) ~ x` rather than `pnorm(x) ~ y`)",
  r"(None of them correspond to the plot.)" = r"( )",
  random_answer_order=TRUE,
  item_label = "Drill "
)
```



```{r drill-M04-31, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Only one of the following commands will successfully generate the graph of a function. Which one? )",
r"(+`slice_plot(exp(y) ~ y, bounds(y=c(-4, 4)))`+)" = r"(Perhaps you were mislead by my using `y` as the name of the input to the function. You can use whatever name you like so long as you use it **consistently** in the whole command.)",
  r"(`slice_plot(pnorm(x) ~ x, bounds(y=c(-4, 4)))`)" = r"(The domain has been specified using the name `y` rather than the input name used in the tilde expression.)",
  r"(`slice_plot(log(x) ~ x, bounds(x=c(0; 10)))`)" = r"(The arguments to `c()` are illegally separated by a semi-colon rather than the mandated comma.)",
  r"(`slice_plot(dnorm(y)) ~ x, bounds(y=c(-3,3)))`)" = r"(The `x` on the right-hand side of the tilde expression is inconsistent with the use of `y` as the input name elsewhere in the command.)",
  random_answer_order=TRUE,
  item_label = "Drill "
)
```
