```{r drill-M01-1, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Which of these is the symbol for "is defined as"? )",
r"($=$)" = r"(An equals sign says that the two sides happen to be equal, not that the left side is **defined** as the right side.)",
  r"(+$\equiv$+)" = r"(Three parallel bars signify a definition.)",
  r"($\sim$)" = r"( )",
  r"($\approx$)" = r"( )",
  random_answer_order=TRUE,
  item_label = "Drill "
)
```

```{r drill-M01-2, echo=FALSE, results='markup'}
askMC(
  prompt = "What is the name of the function defined by $$f(y) \\equiv \\sin(y) + e^y\\ ?$$",
r"(+$f$+)" = r"(Note that we will usually write function names with trailing parentheses, like $f()$, to remind you that $f$ refers to a function rather than an input or parameter or whatever.)",
  r"($\sin$)" = r"( )",
  r"($f(y)$)" = r"(This isn't a function name. This is how we write the **output** from applying function $f()$ to the input denoted by the name $y$.)",
  random_answer_order=TRUE,
  item_label = "Drill "
)
```

```{r drill-M01-3, echo=FALSE, results='markup'}
askMC(
  prompt = r"(How do we refer to the output generated by applying $g(x) \equiv x+3$ to the input 3?  )",
r"($g(x)$)" = r"( )",
  r"(+$g(3)$+)" = r"( )",
  r"($y = 6$)" = r"(it is a habit from high-school math to use the name $y$ for outputs. Breaking that habit will help you learn and use calculus.)",
  random_answer_order=TRUE,
  item_label = "Drill "
)
```



```{r drill-M03-22, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Using our notation conventions from the textbook, which one of the following kinds of things is $y_0 ?$ )",
r"(+A constant+)" = r"( )",
  r"(A function name)" = r"( )",
  r"(An input name)" = r"(A subscript (like $_0$ here) or non-numeric superscript (like $^\star$) on what would otherwise be an input name will be instead a **constant**.)",
  random_answer_order=FALSE,
  item_label = "Drill "
)
```


```{r drill-M04-1, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Using our notation conventions from the textbook, which one of the following kinds of things is $t^\star?$ )",
r"(+A constant+)" = r"( )",
  r"(A function name)" = r"( )",
  r"(An input name)" = r"(A subscript (like $_0$ here) or non-numeric superscript (like $^\star$) on what would otherwise be an input name will be instead a **constant**.)",
  random_answer_order=FALSE,
  item_label = "Drill "
)
```


```{r drill-M04-2, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Using our notation conventions from the textbook, which one of the following kinds of things is $B ?$ )",
r"(+A constant+)" = r"( )",
  r"(A function name)" = r"( )",
  r"(An input name)" = r"(The letters from the start of the alphabet, a-d, or A-D will refer to a **constant**. )",
  random_answer_order=FALSE,
  item_label = "Drill "
)
```


```{r drill-M04-3, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Using our notation conventions from the textbook, which one of the following kinds of things is $F() ?$ )",
r"(A constant)" = r"( )",
  r"(+A function name+)" = r"(Our standard pronouns for functions are $f(), g(), h()$ and $F(), G(), H()$)",
  r"(An input name)" = r"( )",
  random_answer_order=FALSE,
  item_label = "Drill "
)
```


```{r drill-M04-4, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Using our notation conventions from the textbook, which one of the following kinds of things is $u ?$ )",
r"(A constant)" = r"( )",
  r"(A function name)" = r"( )",
  r"(+An input name+)" = r"(Letters from the end of the alphabet, $u, v, w, x, y, z$, generally refer to an input to a function. But, remember, something like $x_0$ will always be a constant.)",
  random_answer_order=FALSE,
  item_label = "Drill "
)
```


```{r drill-M04-5, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Can function names be multiple letters, e.g. `g3()` or `altitude()`? )",
r"(+Yes+)" = r"(And they often do. Almost all R functions have multi-letter names, like `exp()`, `sin()`, `dnorm()`, and such. When you are building a model, it is helpful to use *mnemonic* function names rather than the usual pronouns like $f(), g()$, an $h()$. We use the short pronouns throughout the book whenever we are discussing general mathematical properties rather than specific models.)",
  r"(No)" = r"( )",
  random_answer_order=FALSE,
  item_label = "Drill "
)
```

```{r drill-M04-7, echo=FALSE, results='markup'}
askMC(
  prompt = r"(In the book, will input names have subscripts, like $x_0$ or  $u_2 ?$ )",
r"(Yes)" = r"( )",
  r"(+No+)" = r"(In the textbook, we try to reserve names like $x_0$ or $u_2$ for **constants**. But mathematics usage generally does not always adopt this helpful convention.)",
  random_answer_order=FALSE,
  item_label = "Drill "
)
```


```{r drill-M04-8, echo=FALSE, results='markup'}
askMC(
  prompt = r"(In the book, what is meant by the word "**variable**"? )",
r"(it is the same as input.)" = r"(Use **input** rather than variable! Even if you're used to calling quantities like $x$ and $y$ variables, it is a confusing practice since it can mean so many different things. In calculus, in this course, we will try to be strict about using the words **input** and **output**)",
  r"(it is the same as output.)" = r"( )",
  r"(+A column in a data table.+)" = r"(This is the use in statistics and data science. In calculus, we will try to avoid confusing by using **input** and **output** instead.)",
  random_answer_order=TRUE,
  item_label = "Drill "
)
```



```{r drill-M08-8, echo=FALSE, results='markup'}
askMC(
  prompt = r"(What is the name of the **function** being defined in $a(b) \equiv 3 x + 2 b$? )",
r"(+a+)" = r"(Any name $ggg$ appearing in a definition of the form $ggg(xxx) \equiv \cdots$ is being explicitly declared as the name of the function. Names don't have to be $f()$, $g()$, or $h()$, even though those are the pronouns we use most often.)",
  r"(b)" = r"( )",
  r"(x)" = r"( )",
  random_answer_order=FALSE,
  item_label = "Drill "
)
```




```{r drill-M08-9, echo=FALSE, results='markup'}
askMC(
  prompt = r"(What is the name of the **input** to the function being defined in $a(b) \equiv 3 x + 2 b$? )",
r"(a)" = r"( )",
  r"(+b+)" = r"(Any name $yyy$ appearing in a definition of the form $xxx(yyy) \equiv \cdots$ is being explicitly declared as the name of the the argument. Names don't have to be $x, y, z, t, u, v, w$, even though those are the the names we use most often.)",
  r"(x)" = r"( )",
  random_answer_order=FALSE,
  item_label = "Drill "
)
```

```{r drill-M08-10, echo=FALSE, results='markup'}
askMC(
  prompt = r"(What is wrong with this function definition?  $$\text{dorothy(kansas)} \equiv niece_of(AuntieEm) \times \text{kansas}\ ?$$)",
r"(You cannot name a function "dorothy.")" = r"(Why not?)",
  r"("kansas" is a US state, not the name of an argument.)" = r"( )",
  r"("dorothy" and "kansas" should be capitalized.)" = r"(that is  true in English, but we are writing mathematics here and we get to make the choices.)",
  r"(Auntie Em is a person, not a number.)" = r"(There is no reason why a person cannot be the argument to a function. For instance, we might have blood_pressure(patient3252).)",
  r"(+Nothing.+)" = r"( )",
  random_answer_order=FALSE,
  item_label = "Drill "
)
```

```{r drill-M08-11, echo=FALSE, results='markup'}
askMC(
  prompt = r"(What's wrong with this function definition? $$\text{electric}(z) \equiv 3 z + \ln()$$ )",
r"(+No input has been given to $\ln()$.+)" = r"(Although $\ln()$ is an important function, on the right-hand side of the definition, it can only make sense if it is evaluated on some argument. So writing $\ln(z)$ or even $\ln(year)$ would have made this a proper function definition.)",
  r"('electric() ' should have been written as E().)" = r"(The letter E can be a fine function name, but so can 'electric.')",
  r"(Nothing)" = r"( )",
  random_answer_order=FALSE,
  item_label = "Drill "
)
```

```{r drill-Quiz-1-27, echo=FALSE, results='markup'}
askMC(
  prompt = r"(You are modeling the population of *E. coli* growing in optimal conditions. (Optimal for the *E. coli*, not for you!)  In R, you've written `population <- makeFun(100*exp(hours) ~ hours)` What's the correct definition in traditional notation? )",
r"($\text{population} \equiv 100 e^\text{hours}$)" = r"( )",
  r"($\text{population}(t) \equiv 100 e^\text{hours}$)" = r"(The argument should be called hours, not t.)",
  r"(+$\text{population}(\text{hours}) \equiv 100 e^\text{hours}$+)" = r"( )",
  r"(None of the above.)" = r"( )",
  random_answer_order=FALSE,
  item_label = "Drill "
)
```



```{r drill-Quiz-1-26, echo=FALSE, results='markup'}
askMC(
  prompt = r"(In traditional notation, $$\text{Celsius}(\text{Fahrenheit}) \equiv \frac{5}{9} (\text{Fahrenheit} - 32)$$ defines a function named `Celsius()`. This of the following correctly defines that function in R? )",
r"(`Celsius(Fahrenheit) <- makeFun(5*(Fahrenheit-32)/9)`)" = r"(The left side of the assignment operator `<-` should be simply the name of the function, in this case `Celsius`.)",
  r"(`Celsius <- makeFun(5/9*Fahrenheit - 32 ~ Fahrenheit)`)" = r"( )",
  r"(`Celsius() <- makeFun(5*(Fahrenheit-32)/9 ~ Fahrenheit)`)" = r"(The `()` in `Celsius()` are not allowed in an R name.)",
  r"(+`Celsius <- makeFun(5*(Fahrenheit-32)/9 ~ Fahrenheit)`+)" = r"( )",
  r"(`Celsius(Fahrenheit) <- makeFun(5*(Fahrenheit-32)/9 ~ Fahrenheit)`)" = r"(Everything is good, but the name on the left side of the assignment operator `<-` should be simply `Celsius`)",
  random_answer_order=TRUE,
  item_label = "Drill "
)
```


```{r drill-Quiz-1-1, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Which of these does the symbol $y_0$ suggest using our CalcZ notation conventions? )",
r"(+a constant+)" = r"(We also sometimes refer to a constant as a parameter.)",
  r"(an input to a function)" = r"( )",
  r"(the output from a function)" = r"( )",
  r"(a function name)" = r"( )",
  r"(it is nonsense)" = r"( )",
  random_answer_order=TRUE,
  item_label = "Drill "
)
```



```{r drill-Quiz-1-2, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Given the definition $g(z) \equiv z \sin(z)$, which of these does the symbol $z$ suggest using our CalcZ notation conventions? )",
r"(a constant)" = r"( )",
  r"(+the input to the function+)" = r"( )",
  r"(the output from the function)" = r"( )",
  r"(the function name)" = r"( )",
  r"(it is nonsense)" = r"( )",
  random_answer_order=TRUE,
  item_label = "Drill "
)
```



```{r drill-Quiz-1-3, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Given the definition $g(z) \equiv z \sin(z)$, which of these does the symbol $g$ suggest using our CalcZ notation conventions? )",
r"(a constant)" = r"( )",
  r"(the input to the function)" = r"( )",
  r"(the output from the function)" = r"( )",
  r"(+the function name+)" = r"(Usually, we write function names with parentheses, like $g()$, just as a reminder that the name refers to a function.)",
  r"(it is nonsense)" = r"( )",
  random_answer_order=TRUE,
  item_label = "Drill "
)
```



```{r drill-Quiz-1-4, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Given the definition $pressure(H) \equiv \exp(- H/10)$, which of these does the symbol $H$ suggest using our CalcZ notation conventions? )",
r"(a constant)" = r"( )",
  r"(+the input to the function+)" = r"(Even though $H$ is not a name we will use frequently for the input to a function, whenever you see $f(H) \equiv ...$, you know that $H$ is being explicitly declared to be a function.)",
  r"(the output from the function)" = r"( )",
  r"(the function name)" = r"( )",
  r"(it is nonsense)" = r"( )",
  random_answer_order=TRUE,
  item_label = "Drill "
)
```



```{r drill-Quiz-1-5, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Given the definition $pressure(H) \equiv exp(-.1 H)$, which of these does the symbol $pressure$ suggest using our CalcZ notation conventions? )",
r"(a constant)" = r"( )",
  r"(the input to the function)" = r"( )",
  r"(the output from the function)" = r"( )",
  r"(+the function name+)" = r"( )",
  r"(it is nonsense)" = r"( )",
  random_answer_order=TRUE,
  item_label = "Drill "
)
```



```{r drill-Quiz-1-6, echo=FALSE, results='markup'}
askMC(
  prompt = r"(In the definition $h(z) \equiv a z + b$ what is the symbol $z$? )",
r"(a constant)" = r"( )",
  r"(+the input to the function+)" = r"( )",
  r"(the output from the function)" = r"( )",
  r"(the function name)" = r"( )",
  r"(it is nonsense)" = r"( )",
  random_answer_order=TRUE,
  item_label = "Drill "
)
```



```{r drill-Quiz-1-7, echo=FALSE, results='markup'}
askMC(
  prompt = r"(In the definition $h(z) \equiv a z + b$ what is the symbol $a$? )",
r"(+a constant+)" = r"(We call such constants "parameters" of the function.)",
  r"(the input to the function)" = r"( )",
  r"(the output from the function)" = r"( )",
  r"(the function name)" = r"( )",
  r"(it is nonsense)" = r"( )",
  random_answer_order=TRUE,
  item_label = "Drill "
)
```

```{r drill-M04-6, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Can function names have subscripts or superscripts, like $g_0()$ or  $f'() ?$ )",
r"(+Yes+)" = r"(we will use names like $g_0()$, $g_1()$ in sequence when we are discussing a set of functions that are very closely related, such as refinements.)",
  r"(No)" = r"( )",
  random_answer_order=FALSE,
  item_label = "Drill "
)
```
