
```{r drill-M02-1, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Is `xx` a legitimate name in R? )",
r"(+True+)" = r"( )",
  r"(False)" = r"( )",
  random_answer_order=FALSE,
  item_label = "Drill "
)
```



```{r drill-M02-2, echo=FALSE, results='markup', eval=FALSE}
askMC(
  prompt = "Is `x_x` a legitimate name in R?",
  r"(+True+)" = r"( )",
  r"(False)" = r"( )",
  random_answer_order=FALSE,
  item_label = "Drill "
)
```





```{r drill-M02-3, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Is `-x` a legitimate name in R? )",
r"(True)" = r"( )",
  r"(+False+)" = r"(The minus sign are other such symbols are not allowed characters in an R name.)",
  random_answer_order=FALSE,
  item_label = "Drill "
)
```



```{r drill-M02-4, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Is `3x` a legitimate name in R? )",
r"(True)" = r"( )",
  r"(+False+)" = r"(Names should start with a letter)",
  random_answer_order=FALSE,
  item_label = "Drill "
)
```



```{r drill-M02-5, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Is `x3` a legitimate name in R? )",
r"(+True+)" = r"(Numbers are OK in names, so long as the first character is a letter)",
  r"(False)" = r"( )",
  random_answer_order=FALSE,
  item_label = "Drill "
)
```



```{r drill-M02-6, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Is `sqrt` a legitimate name in R? )",
r"(+True+)" = r"(In fact, it is the name of an oft-used function in R.)",
  r"(False)" = r"( )",
  random_answer_order=FALSE,
  item_label = "Drill "
)
```



```{r drill-M02-7, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Is `x + y` a legitimate name in R? )",
r"(True)" = r"( )",
  r"(+False+)" = r"(`x + y` is an R expression that uses names, but the expression is not itself a name.)",
  random_answer_order=FALSE,
  item_label = "Drill "
)
```

```{r drill-M02-8, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Is `3 * x` a legitimate name in R? )",
r"(True)" = r"( )",
  r"(+False+)" = r"(`*` and <space> are not acceptable characters in a name.)",
  random_answer_order=FALSE,
  item_label = "Drill "
)
```



```{r drill-M02-9, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Is `xprime` a legitimate name in R? )",
r"(+True+)" = r"( )",
  r"(False)" = r"( )",
  random_answer_order=FALSE,
  item_label = "Drill "
)
```



```{r drill-M02-10, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Is `x prime` a legitimate name in R? )",
r"(True)" = r"( )",
  r"(+False+)" = r"(Names cannot have blank spaces internally.)",
  random_answer_order=FALSE,
  item_label = "Drill "
)
```



```{r drill-M02-11, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Is `dx` a legitimate name in R? )",
r"(+True+)" = r"( )",
  r"(False)" = r"( )",
  random_answer_order=FALSE,
  item_label = "Drill "
)
```



```{r drill-M02-13, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Is `dx_f` a legitimate name in R? )",
r"(+True+)" = r"( )",
  r"(False)" = r"( )",
  random_answer_order=FALSE,
  item_label = "Drill "
)
```



```{r drill-M02-14, echo=FALSE, results='markup'}
askMC(
  prompt = r"(What's wrong with this assignment statement? `x < 4` )",
r"(Nothing)" = r"( )",
  r"(+it is missing part of the `<-` token.+)" = r"( )",
  r"( `x` is an improper name.)" = r"( )",
  random_answer_order=FALSE,
  item_label = "Drill "
)
```



```{r drill-M02-15, echo=FALSE, results='markup'}
askMC(
  prompt = r"(What's wrong with this assignment statement? `3*x <- 4` )",
r"(Nothing)" = r"(The item to the left of `<-` needs to be a valid name. `3*x` is not.)",
  r"(It should use addition instead of multiplication.)" = r"( )",
  r"(+The item to the left of `<-` needs to be a name+)" = r"(`3 * x` is an instruction to multiply 3 times x. It is not a name.)",
  r"(There is no `x` on the right-hand side of the assignment arrow.)" = r"( )",
  random_answer_order=FALSE,
  item_label = "Drill "
)
```



```{r drill-M02-16, echo=FALSE, results='markup'}
askMC(
  prompt = r"(What's wrong with this assignment statement? `x -> 3+4` )",
r"(Nothing)" = r"( )",
  r"(You cannot use addition in an assignment statement.)" = r"(You can, but it has to be on the right side of the assignment, where you construct the value to be assigned to the name on the left side.)",
  r"(+The assignment has to point toward the **name**, not the *value*+)" = r"( )",
  random_answer_order=FALSE,
  item_label = "Drill "
)
```



```{r drill-M02-17, echo=FALSE, results='markup'}
askMC(
  prompt = "We can write something like $$f(x) \\equiv x^2$$  in mathematical notation. Is it legit in R to write `f(x) <- x^2` ?",
  r"(Yes, it is fine.)" = r"( )",
  r"(+`f(x)` is not a valid name in R.+)" = r"( )",
  r"(Almost. You need to use \(\equiv\) instead of `<-` .)" = r"(There is no symbol \(\equiv\) on the keyboard or recognized in the R language.)",
  random_answer_order=FALSE,
  item_label = "Drill "
)
```




```{r drill-Quiz-1-25, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Which of these is the right way to translate $e^x$ into R? )",
  r"(`e^x`)" = r"(This is a bit of arithmetic, raising the value of whatever is stored in the object `e` to the power `x`. )",
  r"(+`exp(x)`+)" = r"( )",
  r"(`e(x)`)" = r"(There is no function named `e()`.)",
  r"(There is no R equivalent.)" = r"(Yes there is. Remember $e^x$ has a definite meaning in traditional notation.)",
  random_answer_order=FALSE,
  item_label = "Drill "
)
```



```{r drill-Quiz-1-24, echo=FALSE, results='markup'}
askMC(
  prompt = r"(If `x` has been assigned the value `pi/2`, what will be the value of the R expression `2 sin(x)`? )",
r"(0, since $\sin(\pi/2) = 0$.)" = r"(Actually, $\sin(\pi/2) = 1$, but that is  not the only problem with this answer.)",
  r"(1, since $\sin(\pi/2) = 1$.)" = r"(What about the `2`?)",
  r"(2, since $\sin(\pi/2) = 1$.)" = r"(This would be right if the R expression had been written correctly.)",
  r"(+No value. The expression is in error.+)" = r"(It should presumably be `2*sin(x)`.)",
  random_answer_order=FALSE,
  item_label = "Drill "
)
```



```{r drill-Quiz-1-18, echo=FALSE, results='markup'}
askMC(
  prompt = "What's wrong with the R command\n\n`f <- 3*x + 2`\n\n for defining a function?",
r"(It needs to be `f(x) <- 3*x + 2`)" = r"(that is  reminiscent of traditional notation but to create a function we use `f <- makeFun( ... )`)",
  r"(It needs to be `f <- makeFun(3*x + 2)`)" = r"(Almost, but you're missing the right-hand side of the tilde expression, `3*x ~ x`, which tells us that `x` will be the name of the argument to `f()`.)",
  r"(+It needs to be `f <- makeFun(3*x + 2 ~ x)`.+)" = r"( )",
  r"(Nothing is wrong)" = r"( )",
  random_answer_order=FALSE,
  item_label = "Drill "
)
```



```{r drill-Quiz-1-19, echo=FALSE, results='markup'}
askMC(
  prompt = "What's wrong with this R command for creating an exponential function named `g`?\n\n `g <- makeFun(e^y ~ y)`",
r"(+`e^y` is not the exponential function+)" = r"(It should be `exp(y)`)",
  r"(It uses `y` as the argument instead of `x`.)" = r"(You can use any name you like for the argument, so long as you use it consistently.)",
  r"(Better to name the argument `x`)" = r"(`x` and `y` (and many others) are excellent names for arguments.)",
  r"(Nothing)" = r"( )",
  random_answer_order=TRUE,
  item_label = "Drill "
)
```



```{r drill-Quiz-1-20, echo=FALSE, results='markup'}
askMC(
  prompt = "What's suspect about this R command?\n\n `g <- makeFun(exp(y) ~ x)`",
r"(+The formula is `exp(y)` but the argument name is `x`+)" = r"( )",
  r"(There is a tilde expression as the argument to `makeFun()`.)" = r"(that is  exactly what is supposed to happen: give a tilde expression as the input to `makeFun()` !)",
  r"(The function name should be `G`, not `g`.)" = r"(The function name is your choice! Either would be right.)",
  r"(Nothing)" = r"(I guess that "suspect" is in the eye of the beholder. But I think there is a better choice here.)",
  random_answer_order=FALSE,
  item_label = "Drill "
)
```



```{r drill-Quiz-1-21, echo=FALSE, results='markup'}
askMC(
  prompt = r"(What's wrong with the R expression `sin*(x + 3)`? )",
r"(+There is no function named `sin*()`+)" = r"(And besides, `*` cannot be part of any valid name in R.)",
  r"(It should be `sin+(x+3)`)" = r"(There is no function named `sin+()`)",
  r"(It should be `sin^(x+3)`)" = r"(There is no function named `sin^()`)",
  r"(Nothing)" = r"(Hint: What's the name of the function being used? Is that really a function?)",
  random_answer_order=FALSE,
  item_label = "Drill "
)
```



```{r drill-Quiz-1-22, echo=FALSE, results='markup'}
askMC(
  prompt = r"(What does `e^3` mean in R? )",
r"(It corresponds to $e^3$, which happens to be 20.09)" = r"(Remember that $e^x$ is the traditional notation for the exponential function. In R, the exponential function is written `exp()`.)",
  r"(A shorthand for `eee`.)" = r"(There is no shorthand for names in R.)",
  r"(+The value stored under the name `e` will be raised to the third power.+)" = r"(And if there is no object named `e`, you will get an error message.)",
  random_answer_order=FALSE,
  item_label = "Drill "
)
```



```{r drill-Quiz-1-23, echo=FALSE, results='markup'}
askMC(
  prompt = r"(What's missing in the R expression `(x+3)(x+1)`? )",
r"(There is a missing closing parenthesis.)" = r"( )",
  r"(There is an extra closing parenthesis.)" = r"( )",
  r"(+The multiplication symbol, `*`, is missing.+)" = r"(It should be `(x + 3)*(x+1)`.)",
  r"(Nothing)" = r"( )",
  random_answer_order=TRUE,
  item_label = "Drill "
)
```



```{r drill-M04-14, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Which of these phrases is most appropriate for describing what the R command `z <- sin(17)` is doing?  )",
r"(Gives a name to a value.)" = r"( )",
  r"(+Applies a function to an input to produce an output.+)" = r"( )",
  r"(Makes a copy of an existing object.)" = r"( )",
  r"(The name of an object.)" = r"( )",
  r"(it is invalid as a command.)" = r"( )",
  random_answer_order=FALSE,
  item_label = "Drill "
)
```



```{r drill-M04-15, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Which of these phrases is most appropriate for describing what the R command `sin(17)` is doing?  )",
r"(Gives a name to a value.)" = r"( )",
  r"(+Applies a function to an input to produce an output.+)" = r"( )",
  r"(Makes a copy of an existing object.)" = r"( )",
  r"(The name of an object.)" = r"( )",
  r"(it is invalid as a command.)" = r"( )",
  random_answer_order=FALSE,
  item_label = "Drill "
)
```



```{r drill-M04-16, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Which of these phrases is most appropriate for describing what the R command `z <- x` is doing?  )",
r"(Gives a name to a value.)" = r"( )",
  r"(Applies a function to an input to produce an output.)" = r"( )",
  r"(+Makes a copy of an existing object.+)" = r"( )",
  r"(The name of an object.)" = r"( )",
  r"(it is invalid as a command.)" = r"( )",
  random_answer_order=FALSE,
  item_label = "Drill "
)
```



```{r drill-M04-17, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Which of these phrases is most appropriate for describing what the R command `fred` is doing?  )",
r"(Gives a name to a value.)" = r"( )",
  r"(Applies a function to an input to produce an output.)" = r"( )",
  r"(Makes a copy of an existing object.)" = r"( )",
  r"(+The name of an object.+)" = r"(When you give the name of an object as a stand-alone command, R prints out the value of that object.)",
  r"(it is invalid as a command.)" = r"( )",
  random_answer_order=FALSE,
  item_label = "Drill "
)
```



```{r drill-M04-18, echo=FALSE, results='markup'}
askMC(
  prompt = r"(In the statement `pnorm(3, mean=4, sd=6 )`, what is `pnorm`?  )",
r"(+The name of the function being applied to the three arguments.+)" = r"( )",
  r"(A named argument)" = r"( )",
  r"(An argument to be used without a name.)" = r"( )",
  random_answer_order=FALSE,
  item_label = "Drill "
)
```



```{r drill-M04-19, echo=FALSE, results='markup'}
askMC(
  prompt = r"(In the statement `pnorm(3, mean=4, sd=6 )`, what is `mean=4`?  )",
r"(The name of the function being applied to the three arguments.)" = r"( )",
  r"(+A named argument+)" = r"( )",
  r"(An argument to be used without a name.)" = r"( )",
  random_answer_order=FALSE,
  item_label = "Drill "
)
```



```{r drill-M04-20, echo=FALSE, results='markup'}
askMC(
  prompt = r"(In the statement `pnorm(3, mean=4, sd=6 )`, what is `3`?  )",
r"(The name of the function being applied to the three arguments.)" = r"( )",
  r"(A named argument)" = r"( )",
  r"(+An argument to be used without a name.+)" = r"( )",
  random_answer_order=FALSE,
  item_label = "Drill "
)
```



```{r drill-M04-21, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Will the statement `pnorm(x=3, mean=4, sd=6)` give the same result as `pnorm(3, mean=4, sd=6)` ?  )",
r"(Yes, same arguments to the same function means the output will be the same.)" = r"(In general, this is good reasoning. )",
  r"(+No. The name of the first argument to `pnorm()` is not `x`.+)" = r"(You cannot always know what are the names of the arguments to the basic built-in functions. So use them without naming the argument.)",
  random_answer_order=FALSE,
  item_label = "Drill "
)
```



```{r drill-M04-22, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Will the statement `pnorm(3, mean=4, sd=6)` give the same result as `pnorm(3, sd=6, mean=4)`?  )",
r"(+Yes.+)" = r"(The names for the arguments tell R how each argument should be used in the function.)",
  r"(No. The arguments are different.)" = r"(When an argument is used with its name, it can go anywhere in the argument list.)",
  random_answer_order=FALSE,
  item_label = "Drill "
)
```



```{r drill-M04-23, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Will the statement `pnorm(3, mean=4, sd=6)` give the same result as `pnorm(3, sd=4, mean=6)`?  )",
r"(Yes)" = r"(Look carefully at the value given to each argument.)",
  r"(+No+)" = r"(In the first statement, the mean is set to 4, while in the second the mean is set to 6.)",
  random_answer_order=FALSE,
  item_label = "Drill "
)
```



```{r drill-M04-25, echo=FALSE, results='markup'}
askMC(
  prompt = r"(What is the value of `16^1/2`? )",
r"(4)" = r"(This would be right if the exponent were in grouping parentheses, e.e. `16^(1/2)`. Without those parentheses, the computer reads `16^1/2` as `(16^1) / 2`)",
  r"(+8+)" = r"( )",
  random_answer_order=FALSE,
  item_label = "Drill "
)
```



```{r drill-M04-26, echo=FALSE, results='markup'}
askMC(
  prompt = r"(What is the value of `16^(1/2)`? )",
r"(+4+)" = r"(Since the `(1/2)` is in grouping parentheses, the expression is asking for 16 to the one-half power, in other words the square root of 16.)",
  r"(8)" = r"( )",
  random_answer_order=FALSE,
  item_label = "Drill "
)
```



```{r drill-M04-27, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Suppose `n <- 3`. What will be the value of `2^n-1`? )",
r"(4)" = r"(Without grouping parentheses around `n-1` the computer interprets `2^n-1` as `(2^n) - 1`)",
  r"(+7+)" = r"( )",
  r"(8)" = r"(What about the `-1` in the expression?)",
  random_answer_order=FALSE,
  item_label = "Drill "
)
```



```{r drill-M04-28, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Suppose `n <- 3`. What will be the value of `2^(n-1)`? )",
r"(+4+)" = r"( )",
  r"(7)" = r"(The grouping parentheses around `(n-1)` mean that the calculation is effectively `2^2`, giving 4.)",
  r"(8)" = r"(What about the `-1` in the expression?)",
  random_answer_order=FALSE,
  item_label = "Drill "
)
```



```{r drill-Quiz-1-8, echo=FALSE, results='markup'}
askMC(
  prompt = r"(In `g <- makeFun(3*z + 2 ~ z)`, which is the name of the input to the function `g()`? )",
r"($x$)" = r"( )",
  r"($y$)" = r"( )",
  r"(+$z$+)" = r"( )",
  r"($t$)" = r"( )",
  random_answer_order=FALSE,
  item_label = "Drill "
)
```



```{r drill-M04-9, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Will this statement work in R? `sin(4)` )",
r"(+Yes+)" = r"( )",
  r"(No)" = r"( )",
  random_answer_order=FALSE,
  item_label = "Drill "
)
```



```{r drill-M04-10, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Will this statement work in R? `Sin(4)`)",
r"(Yes)" = r"(It would except for the capital S. R treats capital and lower-case letters as completely different, so the name `abby` is utterly distinct from `Abby` or `aBBy`, etc.)",
  r"(+No+)" = r"( )",
  random_answer_order=FALSE,
  item_label = "Drill "
)
```



```{r drill-M04-11, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Will this statement work in R to calculate $\sin(4)$?  `sin[4]` )",
r"(Yes)" = r"(You must always use parentheses, not square braces, to carry the argument to the function.)",
  r"(+No+)" = r"(Only parentheses can be used to hand an argument off to a function.)",
  random_answer_order=FALSE,
  item_label = "Drill "
)
```