

```{r drill-M03-3, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Which of the pattern book bofunctions has an output value very near zero over almost **all** of its domain? )",
r"(+$\text{dnorm()}$+)" = r"(The gaussian function $\text{dnorm()}$ is practically zero everywhere except in $-4 < x < 4$)",
  r"($\sin()$)" = r"( )",
  r"($e^x$)" = r"( )",
  r"($\ln()$)" = r"( )",
  random_answer_order=TRUE,
  item_label = "Drill "
)
```

```{r drill-M03-4, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Which of these basic modeling functions has value very near zero over almost **half** of its domain? )",
r"(+$\text{pnorm()}$+)" = r"(The sigmoid function is practically zero everwhere in $x < -4$)",
  r"($\ln()$)" = r"( )",
  r"($x^{-1}$)" = r"( )",
  r"($x^{2}$)" = r"( )",
  random_answer_order=TRUE,
  item_label = "Drill "
)
```

```{r drill-M03-5, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Which of these basic modeling functions has value very near zero over almost **half** of its domain? )",
r"(+$e^x$+)" = r"(The exponential is less than 1 whenever $x < 0$, and it is less than 0.0001 whenever $x < -10$, even smaller for more negative $x$.)",
  r"($\ln()$)" = r"(The domain of the logarithm is the positive real numbers, which is half the number line. But within the domain, the logarithm is very near zero only for a short interval centered on $x=1$.)",
  r"($x^{-1}$)" = r"( )",
  r"($x^{2}$)" = r"( )",
  random_answer_order=TRUE,
  item_label = "Drill "
)
```

```{r drill-M03-7, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Which of these pattern-book functions is **not** a monomial? )",
r"(+$\sqrt{x}$+)" = r"(Monomials are functions of the form $x^n$, where $n = 0, 1, 2, \ldots$, that is, an integer.)",
  r"($x^2$)" = r"( )",
  r"($x$)" = r"(It might be easier to see that this is a monomial if we write it as $x^1$)",
  random_answer_order=TRUE,
  item_label = "Drill "
)
```






```{r drill-M03-8, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Which value(s) is **missing from** the domain of $x^{-1}$? )",
r"(+Zero+)" = r"( )",
  r"(All non-positive numbers)" = r"(This is another way of saying, "The number line except for zero and negative numbers.")",
  r"(Negative numbers)" = r"( )",
  r"(No numbers are missing.)" = r"( )",
  random_answer_order=FALSE,
  item_label = "Drill "
)
```



```{r drill-M03-9, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Which value(s) is **missing from** the domain of $x^{1/2}$? )",
r"(Zero)" = r"( )",
  r"(All non-positive numbers)" = r"(This is another way of saying, "The number line except for zero and negative numbers.")",
  r"(+Negative numbers+)" = r"( )",
  r"(No numbers are missing.)" = r"( )",
  random_answer_order=FALSE,
  item_label = "Drill "
)
```



```{r drill-M03-10, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Which value(s) is **missing from** the domain of $\ln(x)$? )",
r"(Zero)" = r"( )",
  r"(+All non-positive numbers+)" = r"(This is another way of saying, "The number line except for zero and negative numbers." The $\ln(x)$ function is not defined at $x=0$, although the value is often written as $-\infty$.)",
  r"(Negative numbers)" = r"( )",
  r"(No numbers are missing.)" = r"( )",
  random_answer_order=FALSE,
  item_label = "Drill "
)
```



```{r drill-M03-11, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Which value(s) is **missing from** the domain of $\sin(x)$? )",
r"(Zero)" = r"( )",
  r"(All non-positive numbers)" = r"(This is another way of saying, "The number line except for zero and negative numbers.")",
  r"(Negative numbers)" = r"( )",
  r"(+No numbers are missing.+)" = r"( )",
  random_answer_order=FALSE,
  item_label = "Drill "
)
```

```{r drill-M03-21, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Which value(s) is **missing from** the domain of $x^{-1/2}$? )",
r"(Zero)" = r"( )",
  r"(+All non-positive numbers+)" = r"(This is another way of saying, "The number line except for zero and negative numbers.")",
  r"(Negative numbers)" = r"(Power-law functions with non-integer exponents, e.g. $x^{3/2}$ or $\sqrt{x}$ or $x^{1.424}$ are not defined for negative $x$.)",
  r"(No numbers are missing.)" = r"( )",
  random_answer_order=FALSE,
  item_label = "Drill "
)
```



```{r drill-Quiz-1-11a, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Which of the following values is **in the domain** of the function $x^{0.429}$? )",
r"(-2)" = r"( )",
  r"(-1)" = r"( )",
  r"(+0+)" = r"( )",
  r"(All of them)" = r"( )",
  random_answer_order=FALSE,
  item_label = "Drill "
)
```



```{r drill-Quiz-1-12a, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Is zero **in the domain** of the function $x^{-1}$? )",
r"(Yes)" = r"( )",
  r"(+No+)" = r"( )",
  random_answer_order=FALSE,
  item_label = "Drill "
)
```



```{r drill-Quiz-1-13a, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Which of the following values is **in the domain** of the function $\sin(x)$? )",
r"(-2)" = r"( )",
  r"(-1)" = r"( )",
  r"(0)" = r"( )",
  r"(+All of them+)" = r"( )",
  random_answer_order=FALSE,
  item_label = "Drill "
)
```



```{r drill-M04-12, echo=FALSE, results='markup'}
askMC(
  prompt = r"(What is the output from the command `log(-1)` ? )",
r"(0)" = r"( )",
  r"(An error message.)" = r"(A warning is different from an error.)",
  r"(-Inf)" = r"( )",
  r"(+NaN+)" = r"(\(-1\) is outside of the domain of the logarithm function.)",
  random_answer_order=FALSE,
  item_label = "Drill "
)
```



```{r drill-M04-13, echo=FALSE, results='markup'}
askMC(
  prompt = r"(What is the output from the command `log(0)` ? )",
r"(0)" = r"( )",
  r"(+-Inf+)" = r"(There is a vertical asymptote involved here, so the programmers who wrote `log()` decided to tell you which direction it goes in.)",
  r"(NaN)" = r"( )",
  random_answer_order=FALSE,
  item_label = "Drill "
)
```



```{r drill-Quiz-1-9, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Which of the following values is **in the domain** of the function $\ln()$? )",
r"(-1)" = r"( )",
  r"(0)" = r"( )",
  r"(+1+)" = r"( )",
  r"(All of them)" = r"( )",
  random_answer_order=FALSE,
  item_label = "Drill "
)
```


```{r drill-Quiz-1-10, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Which of the following values is **in the domain** of the function $x^2$? )",
r"(-1)" = r"( )",
  r"(0)" = r"( )",
  r"(1)" = r"( )",
  r"(+All of them+)" = r"( )",
  random_answer_order=FALSE,
  item_label = "Drill "
)
```

```{r drill-Quiz-1-11, echo=FALSE, results='markup'}
askMC(
  prompt =  "By how much should you increase the input to the exponential function to produce a doubling of the output?",
  "0.5",
  "+0.693+" = "This is called the doubling time.",
  "1",
  "1.386",
  "2", 
  'none of these',
  random_answer_order=FALSE,
  item_label = "Drill "
)
```

```{r drill-Quiz-1-12, echo=FALSE, results='markup'}
askMC(
  prompt =  "By how much should you increase the input to the exponential function to produce a quadrupling of the output?",
  "0.5",
  "0.693" = "This is called the doubling time.",
  "1",
  "+1.386+" = "Increasing by twice the doubling time quadruples the output.",
  "2", 
  'none of these',
  random_answer_order=FALSE,
  item_label = "Drill "
)
```

```{r drill-Quiz-1-13, echo=FALSE, results='markup'}
askMC(
  prompt =  "By how much should you **decrease** the input to the exponential function to cut the output value by a factor of one-half?",
  "0.5",
  "+0.693+" = "A halving of the output is accomplished by decreasing the input by the doubling time 0.693.",
  "1",
  "1.386",
  "2", 
  'none of these',
  random_answer_order=FALSE,
  item_label = "Drill "
)
```
