---
id: "fish-sees-tree"
author: "Daniel Kaplan"
perm-id: "BXCA4"
skill: "Co-Fun-102b-drill"
---

Paste these two lines into your R console:

```{r results="hide"}
x <- 2
sin(x)*sqrt(x)
```

In the following questions, numbers have been rounded to two or three significant digits. Select the answer closest to the computer output.


```{r fst9-1, echo=FALSE, results="markup"}
askMC(
  "Change $x$ to 1. What's the output of $\\sin(x) \\ \\sqrt{\\strut x\ }$",
  "-1.51", "0.244", "+0.84+", "0.99", "2.14", "`NaN`",
  random_answer_order=FALSE
)
```

```{r fst9-2, echo=FALSE, results="markup"}
askMC(
  "Change $x$ to 3. What's the output of $\\sin(x) \\  \\sqrt{\\strut x\ }$",
  "-1.51", "+0.244+", "0.84", "0.99", "2.14", "`NaN`",
  random_answer_order=FALSE
)
```

```{r fst9-3, echo=FALSE, results="markup"}
askMC(
  "Change $x$ to $-5$. What's the output of $\\sin(x) \\  \\sqrt{\\strut x\ }$",
  "-1.51", "0.244", "0.84", "0.99", "2.14", "+`NaN`+" = "This stands for Not-a-Number, which is what you get when you calculate the square root of a negative input.",
  random_answer_order=FALSE
)
```

In the sandbox, change the formula from $\sin(x) \sqrt{x}$ to  $\sqrt{\strut\pnorm(x)}$.

```{r fst9-4, echo=FALSE, results="markup"}
askMC(
  "For $x=2$, what's the output of $\\sqrt{\\strut\\pnorm(x)\ }$?",
  "-1.51", "0.244", "0.84", "+0.99+", "2.14", "`NaN`",
  random_answer_order=FALSE
)
```
