---
id: "Flipping-1"
author: "Daniel Kaplan"
global-id: "YLWP1"
---

```{r flipping-1-1, echo=FALSE}
slice_plot(exp(x) ~ x, domain(x=c(-2, 2))) %>%
  slice_plot(exp(-x) ~ x, color="orange3") %>%
  slice_plot(-exp(-x) ~ x, color="green") %>%
  slice_plot(-exp(x) ~ x, color="dodgerblue") %>%
  gf_labs(title="(A)")
```

```{r flipping-1-1a, echo=FALSE, results="markup"}
askMC(
  "One of the curves in plot (A) is a pattern-book function. Which one?",
  "+black+" = "It's the exponential function.", "blue", "green", "tan", "none of them", random_answer_order=FALSE
  )
```

```{r flipping-1-1b, echo=FALSE, results="markup"}
askMC(
  "Taking $f()$ to be the pattern-book function in plot (A), which one of the curves is $f(-x)$?",
  "black", "blue", "green", "+tan+", "none of them", random_answer_order=FALSE
)
```


```{r flipping-1-2, echo=FALSE}
slice_plot(pnorm(-x) ~ x, domain(x=c(-2, 2))) %>%
  slice_plot(pnorm(x) ~ x, color="orange3") %>%
  slice_plot(-pnorm(-x) ~ x, color="green") %>%
  slice_plot(-pnorm(x) ~ x, color="dodgerblue") %>%
  gf_labs(title="(B)")
```

```{r flipping-1-2a, echo=FALSE, results="markup"}
askMC(
  "One of the curves in plot (B) is a pattern-book function. Which one?",
  "black", "blue", "green", "+tan+", "none of them", random_answer_order=FALSE
  )
```

```{r flipping-1-2b, echo=FALSE, results="markup"}
askMC(
  "Taking $f()$ to be the pattern-book function in plot (B), which one of the curves is $-f(x)$?",
  "black", "+blue+", "green", "tan", "none of them", random_answer_order=FALSE
)
```


```{r flipping-1-3, echo=FALSE}
slice_plot(-sin(x) ~ x, domain(x=c(-4, 4))) %>%
  slice_plot(-sin(-x) ~ x, color="orange3") %>%
  slice_plot(sin(-x) ~ x, color="green") %>%
  slice_plot(sin(x) ~ x, color="dodgerblue") %>%
  gf_labs(title="(C)")
```

The blue curve in plot (C), as you know, is the sinusoid pattern-book function.

```{r flipping-1-3a, echo=FALSE, results="markup"}
askMC(
  "Which of these functions is the green curve?",
  "$\\sin(-x)$", "$-\\sin(x)$", "$-\\sin(-x)$", 
  "Both $\\sin(-x)$ and $-\\sin(-x)$",
  "+Both $\\sin(-x)$ and $-\\sin(x)$+" = "The sine function has so-called \"odd\" symmetry around $x=0$.",
  random_answer_order=FALSE
  )
```

```{r flipping-1-4, echo=FALSE, warning=FALSE}
slice_plot(-log(-x) ~ x, domain(x=c(-2, 2))) %>%
  slice_plot(-log(x) ~ x, color="orange3") %>%
  slice_plot(log(x) ~ x, color="green") %>%
  slice_plot(log(-x) ~ x, color="dodgerblue") %>%
  gf_labs(title="(D)")
```

```{r flipping-1-4a, echo=FALSE, results="markup"}
askMC(
  "One of the curves in plot (D) is a pattern-book function. Which one?",
  "black", "dodgerblue", "+green+", "tan", "none of them", random_answer_order=FALSE
  )
```

```{r flipping-1-4b, echo=FALSE, results="markup"}
askMC(
  "Taking $f()$ to be the pattern-book function in plot (D), which one of the curves is $-f(-x)$?",
  "+black+", "dodgerblue", "green", "tan", "none of them", random_answer_order=FALSE
)
```

