---
id: "frog-swim-closet"
created: "Thu Apr 28 11:34:08 2022"
global_id: "sgmWCB"
---

EXERCISE: USE a plot like `surface_plot(exp(-z)*sin(y) ~ y & z, interval(y=-6:6, z=0:2), type="contour")` so that students can read off the (x,y,z) value. Ask for the value of the function at several input points. Ask them to trace the output value as the cursor moves along a contour line.

EXERCISE:
Here are some additional tasks which you should learn to perform at a glance when reading a contour plot:

1. Start at a given input pair and determine two directions:

    a.  the direction to move which is most steeply uphill, 
    b. the direction to move which will keep the function output the same. 
    
2. Translate a small region of a contour plot into the word for a corresponding geographical feature with that topology: hills, valleys, crests, coves, hollows, and so on.

EXERCISE: Match up the slice plots with the paths indicated on the contour plot.

EXERCISE: Ask them to find the actual lowest point in the graph
```{r echo=FALSE}
g <- rfun(~ x & y, seed=783)
contour_plot(g(x,y)-2.5 ~ x & y, interval(x=-3:3, y=-3:6), skip=0, label_alpha=.5)
```

