---
title: "Notation for functions"
author: "Daniel Kaplan"
global-id: LDNE
---

```{r include=FALSE, context="setup"}

library(mosaic)
library(mosaicCalc)
```

According to the notation style we use in CalcZ, which of these things is a function? Which a number?

```{r fn1-1, echo=FALSE, results="markup"}
askMC(
  "What kind of a thing is $\\sqrt{z}$?", 
  "+A function+",
  "A number" = "$z$ is one of the standard names we will use for an input to a function. If we had given the function a name, for instance $g(z) \\equiv \\sqrt{z}$, we would be able to tell from the $(z)$ that $g()$ is a function. But whenever we use a standard input name, the expression is a function.",
  random_answer_order = FALSE
)
```

```{r fn1-2, echo=FALSE, results="markup"}
askMC(
  "What kind of a thing is $\\sqrt{y^\\star}$?",
  "+A number+",
  "A function" = "According to our convention, the name $y^\\star$ refers to a particular value as opposed to the name of a function input.",
  random_answer_order = FALSE
)
```

```{r fn1-3, echo=FALSE, results="markup"}
askMC(
  "What kind of a thing is $e^{k t}$?",
  "+A function+",
  "A number" = "The letter $t$ is one of our standard letters for input names. $k$ is a letter, but since it is not from the end of the alphabet, you have a hint that it is intended to be a parameter, that is a symbol representing a specific numerical quantity.",
  random_answer_order = FALSE
)
```

```{r fn1-4, echo=FALSE, results="markup"}
askMC(
  "What kind of a thing is $k$ in the definition $g(k) \\equiv e^k$?",
  "A number",
  "+The name of an input to a function.+",
  "A function" = "Notwithstanding our convention that $k$ is not on its own a name used for inputs, when we use the full function-definition style, anything in the parentheses following the function name is explicitly stated as an input name.",
  random_answer_order = FALSE
)
```

