---
id: "pattern-book-axis-crossing"
author: "Daniel Kaplan"
global-id: "VIW7T"
---

These questions ask you, for each of the pattern-book functions, to find a specific input/output pair. 


To answer these questions, you will want to open a `r sandbox_link()` to try the various possibilities.

```{r nac89-1, echo=FALSE, results="markup"}
askMC(
  "What is the exact output of the pattern-book **exponential** function when the input is $x=0$?",
  0, "0.3989423", "1/2", "+1+",
  random_answer_order = FALSE
)
```

```{r nac89-2, echo=FALSE, results="markup"}
askMC(
  "What is the exact output of the pattern-book **sine** function when the input is $x=0$?",
  "+0+", "0.3989423", "1/2", "1",
  random_answer_order = FALSE
)
```



```{r nac89-4, echo=FALSE, results="markup"}
askMC(
  "What is the exact output of the pattern-book **sigmoid** function when the input is $x=0$?",
  "0", "0.3989423", "+1/2+", "1",
  random_answer_order = FALSE
)
```

```{r nac89-5, echo=FALSE, results="markup"}
askMC(
  "What is the output (to several digits) of the pattern-book **Gaussian** function when the input is $x=0$?",
  "0", "+0.3989423+" = "Right. But 0.4 will do when you're sketching a graph.", "1/2", "1",
  random_answer_order = FALSE
)
```


```{r nac89-8, echo=FALSE, results="markup"}
askMC(
  "What is the exact output of the pattern-book **constant** function?",
  0, "0.3989423", "1/2", "+1+",
  random_answer_order = FALSE
)
```


