---
id: "pattern-book-zeros"
author: "Daniel Kaplan"
global-id: "H2KG3"
exercise_format: "On paper"
---

Copy and paste the R/mosaic command below into your R session. The command shows a simple way to graph a function, in this case `exp()`. Press "Run code" to execute the command and draw the graph.

```{r}
slice_plot(exp(x) ~ x, domain(x=c(-3, 3)))
```

In this exercise, you'll be modifying the sandbox code to draw different functions, so you can examine their shapes.

Your task is to read and interpret the graphs of the basic modeling functions. Here, you will be looking for ***zero-crossings***: the neighborhood of a point in the function's domain where the **output** of the function is negative for inputs on one side and positive for inputs on the other side. If zero is touched but not crossed, we'll call that "touched zero."

Make a list of the pattern-book functions. For each function in the list, say whether the function crosses zero, touches zero but doesn't cross, or doesn't touch at all in the part of the domain shown in the graphic: $-3 \leq x \leq 3$. Also note if the value of the function appears to be reaching a horizontal asymptote at zero for very negative $x$, for very positive $x$, for both, or neither.

We'll show you the answers for the exponential function. You'll have to modify the computer command to graph the other pattern-book functions.

::: {.column-page-inset-right}
function name | R formula  | zero in domain shown in graph | asymptotic zero
--------------|------------|-------------------------------|--------------
exponential   | `exp(x)`   | no zeros                      | for very negative $x$
logarithm     |
sinusoid      |
square        |
proportional  |
constant      |
reciprocal    |
gaussian      |
sigmoid       |
:::

