---
id: "pattern-book-range"
author: "Daniel Kaplan"
global-id: "MNCLS2"
---

A function's ***domain*** is the set of possible inputs to the function. A function's ***range*** is the set of possible outputs. For each of the pattern-book functions, specify what is the range.

```{r nrlp2-1, echo=FALSE, results="markup"}
askMC(
  "What is the range of the pattern-book **exponential** function?",
  "+All positive outputs+", "All negative outputs", 
  "The whole number line", "A closed, finite interval of possibilities",
  random_answer_order = FALSE
)
```

```{r nrlp2-2, echo=FALSE, results="markup"}
askMC(
  "What is the range of the pattern-book **sine** function?",
  "All positive outputs", "All negative outputs", 
  "The whole number line", "+A closed, finite interval of possibilities+" = "Yes. The output of pattern-book sinusoid functions is always in the interval from -1 to 1, inclusive",
  random_answer_order = FALSE
)
```

```{r nrlp2-3, echo=FALSE, results="markup"}
askMC(
  "What is the range of the pattern-book **logarithm** function?",
  "All positive outputs", "All non-negative outputs", "All negative outputs", 
  "+The whole number line+", "A closed, finite interval of possibilities",
  random_answer_order = FALSE
)
```

```{r nrlp2-4, echo=FALSE, results="markup"}
askMC(
  "What is the range of the pattern-book **square** function?",
  "All positive outputs" = "Close. Zero is one of the possible outputs. We can say, equivalently, that the range is all the **positive outputs plus 0** or all the **non-negative** outputs.", "+All non-negative outputs+", "All negative outputs", 
  "The whole number line", "A closed, finite interval of possibilities",
  random_answer_order = FALSE
)
```

```{r nrlp2-5, echo=FALSE, results="markup"}
askMC(
  "What is the range of the pattern-book **proportional** function?",
  "All positive outputs", "All negative outputs", 
  "+The whole number line+", "A closed, finite interval of possibilities" = "The range extends from $-\\infty$ to $\\infty$.",
  random_answer_order = FALSE
)
```

```{r nrlp2-6, echo=FALSE, results="markup"}
askMC(
  "What is the range of the pattern-book **sigmoid** function?",
  "All positive outputs", "All negative outputs", 
  "The whole number line", "+A closed, finite interval of possibilities+" = "Right. The pattern-book sigmoid function has an output that is always in the interval $0 \\leq \\pnorm(x) \\leq 1 .$",
  random_answer_order = FALSE
)
```




