---
id: "pattern-book-concave"
author: "Daniel Kaplan"
global-id: PYKG5
---

In this activity, you will be examining the various pattern-book functions to look for two different features:

1. ***Slope***: whether the graph has a slope that is consistently positive, negative, both, or neither, and 
2. ***Concavity***: whether the function being graphed is concave up, concave down, neither, or both (i.e., concave up in some regions of the domain and down for others).

::: {.scaffolding  data-latex=""}
Copy and paste the R/mosaic command below in a `r sandbox_link()` to draw a function graph. Remember to press "Run code."
```{r results="hide"}
slice_plot(exp(x) ~ x, domain(x=c(-3, 3)))
```
To modify the command to draw another function, replace the `exp(x)` with another formula, for instance `1/x`. 

:::



Make a list of the pattern-book functions. For each function in the list, write down the R expression for the function, say whether the function has a consistently positive or negative slope, whether it is consistently concave up or down, and if the value of the function appears to be reaching a horizontal asymptote at zero for very negative $x$, for very positive $x$, for both, or neither.

We'll show you the answers for the exponential and sinusoid functions. You'll have to modify the computer command to graph the other pattern-book functions.

function name | R formula  | slope         | concavity    | horiz. asymptote
--------------|------------|---------------|--------------|--------
exponential   | `exp(x)`   | positive      | concave up   | $x \rightarrow -\infty$
logarithm     |
sinusoid      | `sin(x)`   | both          | both         | neither
square        |
proportional  |
constant      |
reciprocal    |
gaussian      |
sigmoid       |


