---
id: "pine-light-mug"
created: "Sun Dec 19 09:25:24 2021"
global_id: "ooJK5d"
---

Suppose you want to define a straight-line function named $f()$ such that $f(x)\equiv m x + b$. Each of the following R statements is **incorrect** for this purpose. Say why.

```{r plmy7-1, echo=FALSE, results="markup"}
askMC("`f <- m*x + b`",
      "+Need to use `makeFun()` to define a function.+",
      "`m` is not defined.", 
      "`b` is not defined.",
      "Should be `y <- m*x + b`.")
```

```{r plmy7-2, echo=FALSE, results="markup"}
askMC("`f <- makeFun(m*x + b)`",
      "+The first argument to `makeFun()` should be a *tilde expression*.+",
      "`m` is not defined.", 
      "`b` is not defined.",
      "`makeFun()` requires **two** inputs." = "No, but it does require a tilde expression input."
      )
```

```{r plmy7-3, echo=FALSE, results="markup"}
askMC("`f <- makeFun(x ~ m*x + b)`",
      "+The tilde expression should have the input name on the right-hand side of the `~`.+",
      "`m` is not defined.", 
      "`b` is not defined.",
      "The first argument is not a tilde expression." = "Actually, it is a tilde expression, just not the right sort of tilde expression."
)
```

```{r plmy7-4, echo=FALSE, results="markup"}
askMC("`f <- makeFun(mx + b ~ x)`",
      "+The tilde expression is missing the multiplication operator `*` between `m` and `x`+",
      "`m` is not defined.", 
      "`b` is not defined.",
      "The name `f` is mis-spelled."
)
```

```{r plmy7-5, echo=FALSE, results="markup"}
askMC("`f <- makeFun(b*x + m ~ x)`",
      "+The roles of `m` and `b` have been reversed.+",
      "`m` is not defined.", 
      "`b` is not defined.",
      "`x` is not defined."
)
```
