---
id: "range-domain"
author: "Daniel Kaplan"
global-id: "RLUCX"
skill: "Gi-Fun-105"
---


```{r include=FALSE}

library(mosaic)
library(mosaicCalc)
```

Consider this graph of a function $g(x)$:

```{r echo=FALSE}
g <- doodle_fun(~ x, seed=9387)
slice_plot(g(x) ~ x, bounds(x=c(-3, 2))) %>%
  gf_lims(x=c(-4,4), y=c(-10,40)) %>%
  gf_labs(x="g(x)")

```

```{r rdA-1, echo=FALSE, results="markup"}
askMC(
  "What is the **domain** of $g(x)$?",
  "$-\\infty < x < \\infty$",
  "+$-3 \\leq x \\leq 2$+",
  "$-4 \\leq x \\leq 4$" = "This might be called the \"graphics\" domain, yet the function graph does not extend over that whole interval.",
  "$-10 \\leq g(x) \\leq 40$" = "This is the vertical extent of the **graphics frame**.",
  "$-1 \\leq g(x) \\leq 33$" = "The **domain** refers to the horizontal axis.",
  random_answer_order = FALSE
)
```

```{r rdA-2, echo=FALSE, results="markup"}
message <- "The **range** refers output of the function. $x$ is the input."
askMC(
  "What is the **range** of $g(x)$?",
  "$-\\infty < x < \\infty$" = message,
  "$-3 \\leq x \\leq 2$" = message,
  "$-4 \\leq y \\leq 4$" = "You're used to calling the function output $y$, but that is  a bad habit. Break it!",
  "$-10 \\leq g(x) \\leq 40$" = "This is the vertical extent of the **graphics frame**.",
  "+$-1 \\leq g(x) \\leq 33$+",
  random_answer_order = FALSE
)
```
