---
id: "seahorse-hear-magnet"
created: "Mon Apr 18 16:41:17 2022"
global_id: "sUmMZv"
skill: "slice through 4-dimensional space"
---

TURN THIS INTO AN EXERCISE that requires drawing contour graphs and interpreting them. 


A triangle consists of three connected line segments: the sides. It has other properties that are related to the sides and each other, for example, the angles between sides, the perimeter, or the area enclosed by the triangle. 

Here's a description of the relationship between the perimeter $p$ and the lengths of the sides, $a$, $b$, $c$, written in the form of a function:
$$p(a,b,c) \equiv a + b + c\ .$$
The mathematical expression of the relationship between area $A$ enclosed by the triangle and the side lengths goes back at least 2000 years to [Heron of Alexandria](https://en.wikipedia.org/wiki/Hero_of_Alexandria) (circa 10–70). As a function, it can be written
$$A(a,b,c) \equiv \frac{1}{4}\sqrt{\strut 4a^2b^2-(a^2+b^2-c^2)^2}\ .$$

We cannot readily plot out this function because there are three inputs and one output, and it is unnatural to draw a 4-dimensional space. But we can draw a **slice** through the 4-dimensional space.

Let's do that by setting, say, $a=1$ and looking at the area as a function of the lengths of sides $b$ and $c$.

Another slice might set $a = b$, in which case we would be showing the areas of isosceles triangles.
