---
id: "boy-put-sofa"
created: "Tue Apr  5 14:54:50 2022"
global_id: "2iItLg"
skill: "Input and output scaling"
---



::: {.underconstruction}
Convert this to a guided exercise on finding the appropriate scale conversion parameters.
:::

 Figure \@ref(fig:covid-scale) shows the model we fit to the COVID-19 data for the cumulative number of confirmed cases for each day in March: $\text{cases(day)} = e^{0.19(\text{day}- -32)}$

```{r echo=FALSE}
#| label: fig-covid-scale
#| fig-cap: "A graph of the pattern-book exponential with an additional scale displayed (blue) to match it to the COVID-19 data"
Znotes::plot_scaled_input(exp(day) ~ day, domain(day=c(-1,9)), 1/0.19, 0.19*32) %>%
  gf_text(1500 ~ 4, label="Days from March 1", color="blue")
```

The function being drawn is simply $e^x$: a function from the pattern book. The black horizontal scale shows $x$, the input to the pattern-book function. Where does that value of $x$ come from? It's $0.19(\text{day} - -32)$, where day is the number of the day in March. For instance, on March 20, day$=10$ and $0.19*(\text{day}- -32) = 9.88$. You can see that 20 on the blue scale matches 10 on the black scale. The model says that on day 20 (blue scale) the input to the pattern-book function will be 9.88 (black scale). Plugging the input 9.88 into the pattern-book exponential gives $e^{9.88} = 19536 \approx 20,000$ cases. 

The pattern-book function does not give a good model of the COVID case numbers. But if we scale the input before applying the pattern-book function, we are effectively laying a new axis, the blue one in Figure \@ref(fig:covid-scale), that is stretched and shifted from the pattern-book input (blackscale). Using the blue axis lets us read off the number of cases as a function of the day in March. 

Input scaling empowers the pattern-book functions to model a huge variety of phenomena. There's just one exponential function and it always looks the same. But there is a huge variety of ways to draw a blue axis, that is, to scale the input. With input scaling, the pattern-book function is tailored to become one of our basic modeling functions.
$$\underbrace{e^x}_\text{pattern-book function}\  \text{versus}\  \underbrace{e^{k(x-x_0)}}_\text{basic modeling function}$$
