---
title: "Exponential discounts"
author: "Daniel Kaplan"
id: "chicken-choose-vase"
global-id: "vkwl4"
skill: "F-exponential-decay"
---

```{r include=FALSE}
library(mosaic)
library(mosaicCalc)
```


The Bargain Basement store wants to sell its goods quickly.  Consequently, they reduce each product's price $P$ by 5% per day. 

```{r CCV1-1, echo=FALSE}
askMC(
  prompt = "If a jacket costs $80 today, how much will it cost in $t$ days?",
    "$P = 80 - 5t$" = "Remember, 5 percent is the same as 0.05",
    "$P = 80 - 4t$" = "Remember, 4 percent is the same as 0.04",
    "$P = 80 - 0.05t$" = "This  would  be a decrease in  price by 5 cents every day.",
    "$P = 80 (0.05)^t$" = "Each day's price would  be  only 5% that of the previous day's price.",
    "+$P = 80 (0.95)^t$+" = ""
)
```



You will need to use an R console to answer the next question. A hint: the answer is related to the answer from the previous question. Remember, to raise a number to a power, you can use an expression like `0.95^7`.


```{r CCV1-2, echo=FALSE}
askMC(
  prompt = "You decided that you like the $80 jacket, but you have a budget of only $60. How long should you wait before coming back to the Bargain Basement store.?",
    "3 days" = "On day 3 the price will be $0.95\\times 0.95 \\times 0.95 \\times 80$. That is above your budget.",
    "4 days" = "On day 4 the price will be $80 \\times 0.95^4$= $65.16. Too much!",
    "5 days" = "On day 5 the price will be $80 \\times 0.95^5$= $61.90. Close, but still higher than your budget.",
    "+6 days+" = "",
  random_answer_order = FALSE
)
```

```{r CCV1-3, echo=FALSE}
askMC(
  prompt="The answer to the first question is an exponential function, even if at first it doesn't look like it. Which of these is the same function but written in the standard $e^{kt}$ format?",
  "+$80 \\exp( \\ln(0.95) t)$+",
  "$0.95 \\exp(80 t)$",
  "$80 \\exp(-\\ln(0.95) t)$" = "You're thinking that since the price is falling with time, the function is exponential decay, hence you've included a minus sign. But $\\ln(0.95)$ is itself negative.", 
  "$0.95 \\exp(\\ln(80) t)$"
)
```



