---
id: "child-sleep-bed"
created: "Wed May 25 09:08:53 2022"
global_id: "8krIme"
skill: "Gi-Fun-117a"
---

The two figures both show the same measurements of three dozen engines internal combustion engine power (BHP) and displacement.

```{r echo=FALSE}
gf_point(log(BHP) ~ log(displacement), data = Engines) %>%
  gf_labs(subtitle="(A)")
gf_point(BHP ~ displacement, data = Engines) %>%
   gf_refine(scale_y_log10(), scale_x_log10()) %>%
  gf_labs(subtitle="(B)")
```

```{r csbe-1, echo=FALSE, results="markup"}
askMC(
  prompt="What relationship is shown in Figure (A) above?",
  "$BHP\equiv m\cdot displacement+b$",
  "$\ln (BHP)\equiv m\cdot displacement+b$",
  "$BHP \equiv m\cdot \ln (displacement) +b$",
  "+$\ln (BHP)\equiv m\cdot \ln (displacement) +b$+"
)
```

```{r csbe-2, echo=FALSE, results="markup"}
askMC(
  prompt="What's the key difference between Figure (A) and Figure (B)?",
   "Figure (A) is a semi-log plot, and Figure (B) is a log-log plot.",
   "+Figure (A) uses linear axes to show the log-transformed data, while Figure (B) uses log-log to show the original data.+",
   "There is no difference!"
)
```


