---
id: "compose-1"
author: "Daniel Kaplan"
---

Use a `r sandbox_link()` to answer the following questions:

```{r compose83-1, echo=FALSE, results="markup"}
askMC(
  "What is the shape of the graph of the composition $\\pnorm(\\pnorm(x))$?",
  "+a sigmoid+", 
  "a gaussian",
  "an exponential"
)
```

```{r compose83-2, echo=FALSE, results="markup"}
askMC(
  "What is the shape of the graph of the composition $\\pnorm(\\dnorm(x))$?",
  "a sigmoid", 
  "+a gaussian+",
  "an exponential"
)
```

```{r compose83-3, echo=FALSE, results="markup"}
askMC(
  "What is the shape of the graph of the composition $\\dnorm(\\pnorm(x))$?",
  "+a sigmoid+", 
  "a gaussian",
  "an exponential"
)
```

```{r compose83-4, echo=FALSE, results="markup"}
askMC(
  "What is the shape of the graph of the composition $\\ln(\\dnorm(x))$?",
  "a sharp rise from (0,0) followed by an asymptotic approach to 0 as $x\\rightarrow \\infty$", 
  "a fishhook" = "You have a creative imagination!",
  "+a parabola+"
)
```

```{r compose83-5, echo=FALSE, results="markup"}
askMC(
  "What is the shape of the graph of the composition $\\ln(x^2)$?",
  "+similar to the log function itself+", 
  "a gaussian function",
  "a sigmoid"
)
```

```{r compose83-6, echo=FALSE, results="markup"}
askMC(
  "What is the shape of $\\exp(x^2)$?",
  "+U-shaped+",
  "V-shaped",
  "W-shaped",
  "a gaussian function"
)
```

```{r compose83-7, echo=FALSE, results="markup"}
askMC(
  "What is the shape of $\\exp(abs(x))$?",
  "+U-shaped+",
  "V-shaped",
  "W-shaped",
  "a sigmoid function"
)
```

```{r compose83-8, echo=FALSE, results="markup"}
askMC(
  "What is the shape of $\\exp(-x^2))$?",
  "U-shaped",
  "V-shaped",
  "W-shaped",
  "+a gaussian function+"
)
```

```{r compose83-9, echo=FALSE, results="markup"}
askMC(
  "What is the **range** of $\\sin(1/x)$?",
  "+$-1 \\leq \\sin(1/x) \\leq 1$+",
  "$\\infty <  \\sin(1/x) < \\infty$",
  "$0 \\leq  \\sin(1/x) < \\infty$",
  "$-\\infty <  \\sin(1/x) \\leq 1$"
)
```

```{r compose83-10, echo=FALSE, results="markup"}
askMC(
  "What is the **range** of $1/\\sin(x)$?",
  "+$-1 \\leq | \\sin(1/x) |$+" = "Or, in words, less than -1 or greater than 1",
  "$\\infty <  \\sin(1/x) < \\infty$",
  "$0 \\leq  \\sin(1/x) < \\infty$",
  "$-\\infty <  \\sin(1/x) \\leq 1$"
)
```
```{r compose83-11, echo=FALSE, results="markup"}
askMC(
  "What is the shape of the graph of the composition $\\ln(\\pnorm(x))$?",
  "+a rise followed by an horizontal asymptotic approach to 0 as $x\\rightarrow \\infty$+", 
  "a fishhook" = "You have a creative imagination!",
  "a parabola"
)
```

