---
title: "Dimensions in formulas"
author: "Daniel Kaplan"
---

For each mathematical operation, identify the operation as valid or invalid according to the rules of dimensional arithmetic.


```{r dim-1, echo=FALSE, results="markup"}
askMC(
  prompt = "In this formula $$\\frac{8 \\text{m} - 2.5 \\text{km}}{2 \\text{min} - 32 \\text{s}}$$ choose which rule (if any) is violated.",
    "Addition or Subtraction rule" = "Both the numerator and denominator are valid subtractions, with dimension L and T respectively.",
    "Multiplication  or Division rule" = "There are no restrictions for multiplication and division, so a formula can hardly violate them!",
    "Exponential" = "There is no exponent here.",
    "+it is valid. No rules are violated.+" = "",
  inline  = FALSE,
  random_answer_order = FALSE
)
```


```{r dim-2, echo=FALSE, results="markup"}
askMC(
  prompt = "In this formula $$\\frac{3 \\text{g} \\times 2 \\text{m}}{3 \\text{km}^2}$$ choose which rule (if any) is violated.",
    "Addition or Subtraction rule" = "No addition or subtraction here.",
    "Multiplication  or Division rule" = "There are no restrictions for multiplication and division, so a formula can hardly violate them!",
    "Exponential" = "There is no exponent here.",
    "+it is valid. No rules are violated.+" = "",
  inline  = FALSE,
  random_answer_order = FALSE
)
```

```{r dim3, echo=FALSE, results="markup"}
askMC(
  prompt = "For this formula $$10^{\\frac{4 \\text{hr}}{3 \\text{g}}}$$ choose which rule (if any) is violated.",
    "Addition or Subtraction rule" = "No addition in this formula.",
    "Multiplication  or Division rule" = "There are no restrictions for multiplication and division, so a formula can hardly violate them!",
    "+Exponential+" = "The  exponent is 4 ft /  3 g, which  has dimension L / M.  Exponents must *always* have dimension [1].",
    "it is valid. No rules are violated." = "",
  inline  = FALSE,
  random_answer_order = FALSE
)
```

```{r dim-4, echo=FALSE, results="markup"}
askMC(
  prompt = "In this formula $$6^{\\frac{2 \\text{hr}}{3 \\text{min}}}$$choose which rule (if any) is violated.",
    "Addition or Subtraction rule" = "No addition or subtraction in this formula.",
    "Multiplication  or Division rule" = "There are no restrictions for multiplication and division, so a formula can hardly violate them!",
    "Exponential" = "The exponent is 4 hr/3 min,  which has dimension T/T = [1]. So the rule is satisfied.",
    "+it is valid. No rules are violated.+" = "",
  inline  = FALSE,
  random_answer_order = FALSE
)
```

```{r dim-5, echo=FALSE, results="markup"}
askMC(
  prompt = "In this formula $$5 \\text{g} \\times 3 \\text{kg} - 7 \\text{lbs}$$ choose which rule (if any) is violated.",
    "+Addition or Subtraction rule+" = "You cannot subtract M from M$^2$. (Strictly speaking, lbs has dimension of force, $M L^2 / T^2$, but you cannot subtract force from M$^2$ either.",
    "Multiplication  or Division rule" = "There are no restrictions for multiplication and division, so a formula can hardly violate them!",
    "Exponential" = "There is no exponent here.",
    "it is valid. No rules are violated." = "",
  inline  = FALSE,
  random_answer_order = FALSE
)
```

```{r dim-6, echo=FALSE, results="markup"}
askMC(
  prompt = "In this formula $$\\sqrt[3]{8 m^3 + 27 \\text{ft}^2}$$ choose which rule (if any) is violated.",
    "+Addition or Subtraction rule+" = "You cannot add L$^3$ to L$^2$.",
    "Multiplication  or Division rule" = "There are no restrictions for multiplication and division, so a formula can hardly violate them!",
    "Exponential" = "Maybe you're thinking that the cube-root rule is violated, but since the  quantity in the cube root is invalid, the root does not do anything additionally wrong.",
    "it is valid. No rules are violated." = "",
  inline  = FALSE,
  random_answer_order = FALSE
)
```
