

```{r drill-Polynomials-1, echo=FALSE, results='markup'}
askMC(
  prompt = r"(In the polynomial $a_0 + a_x x + a_y y + a_{xy} xy$, what is the term $a_{xy}xy$ called?  )",
r"(+Interaction term+)" = r"( )",
  r"( Quadratic term)" = r"( )",
  r"( Linear term)" = r"( )",
  r"( Constant term)" = r"( )",
  random_answer_order=TRUE
)
```



```{r drill-Polynomials-2, echo=FALSE, results='markup'}
askMC(
  prompt = r"(In the polynomial $a_0 + a_x x + a_y y + a_{xx} xx$, what is the coefficient on the interaction term?  )",
r"(+0+)" = r"(You can treat a missing term as if it had a coefficient of zero.)",
  r"($a_{xy}$)" = r"(There is no such coefficient in the polynomial.)",
  r"($a_{xx}$)" = r"( )",
  r"($a_0$)" = r"( )",
  random_answer_order=TRUE
)
```



```{r drill-Polynomials-3, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Imagine a second-order polynomial in three inputs: $x$, $y$, and $z$, like this: $$b_0 + b_x x + b_y y + b_z z + b_{xy} xy + b_{xz} xz + b_{xx} x^2 + b_{yy} y^2 + b_zz z^2\ .$$ All of the possible second-order (or less) terms are shown, except for one. Which term is missing?  )",
r"(+the interaction between $y$ and $z$+)" = r"( )",
  r"(the quadratic term in $z$)" = r"( )",
  r"(the linear term in $y$)" = r"( )",
  r"(the constant term)" = r"( )",
  random_answer_order=TRUE
)
```

