For the following questions, the quantities involved are:

- $a = 25$ ft
- $b = 3$ hours
- $c = 4$
- $d = 1$ meter
- $e = 2.718$


```{r drill-Dimensions-1, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Is this combination dimensionally valid? $$a / c$$ Why or why not?)",
r"(+Division can accommodate any two quantities, regardless of dimension.+)" = r"( )",
  r"($c$ is a dimensionless quantity.)" = r"($c$ is dimensionless, but that is  not a complete explanation. For instance, $a + c$ would not be dimensionally valid.)",
  r"(You can only divide two quantities of the same dimension.)" = r"(that is  just wrong. Division is valid regardless of dimension.)",
  random_answer_order=TRUE
)
```



```{r drill-Dimensions-2, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Is this combination dimensionally valid? $$\sqrt{a}$$ Why or why not?)",
r"(+Invalid. You cannot have a non-integer exponent on a dimension.+)" = r"( )",
  r"(Valid. It is simply 5.)" = r"(You forgot about the "feet" unit. That is dimension L and there is no such thing as $L^{1/2}$.)",
  r"(Invalid. 25 feet is not a valid quantity.)" = r"(25 feet is a perfectly ordinary quantity. The issue is with the $\sqrt{\ \ \ }$)",
  random_answer_order=TRUE
)
```



```{r drill-Dimensions-3, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Consider these quantities: Is this combination dimensionally valid? $$b^c$$ Why or why not?)",
r"(Invalid. Exponentiation of a dimensionful quantity isn't allowed.)" = r"(Exponention is allowed, so long as the exponent is an integer (or if the operation results in an integer exponent))",
  r"(+Valid. Exponentiation by a dimensionless integer is always allowed.+)" = r"()",
  r"(Invalid. I cannot make any sense out of T$^4$ as a dimension.)" = r"(Get used to such things. What matters is whether the construction follows the rules. You will often encounter compound dimensions that seem crazy complicated. For instance, foot-pounds (L$^2$MT$^{-2}$) is a perfectly familiar unit to a mechanic.)",
  random_answer_order=TRUE
)
```



```{r drill-Dimensions-4, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Is this combination dimensionally valid? $$c^b$$ Why or why not?)",
r"(+Invalid. Exponentiation by a dimensionful quantity isn't allowed.+)" = r"(Exponention is allowed, so long as the exponent is an integer (or if the operation results in an integer exponent))",
  r"(Valid. Exponentiation by a dimensionless integer is always allowed.)" = r"($b$ isn't a dimensionless integer; it is 3 hours!)",
  r"(Valid. You can do what you want with plain (dimensionless) numbers like 4.)" = r"(Sorry, but you cannot add a dimensionless quantity to a dimensionful quantity, no can you raise a dimensionless quantity to a dimensionful power.)",
  random_answer_order=TRUE
)
```



```{r drill-Dimensions-5, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Is this combination dimensionally valid? $$\sqrt[3]{a^2 d}$$ Why or why not?)",
r"(Invalid. You cannot raise a dimensionful quantity to a non-integer power.)" = r"(You can always raise a dimensionful quantity to an integer power. And, if the result of raising to the non-integer power is to produce dimensions that have integer powers, that is valid, too.)",
  r"(+Valid. $a^2 d$ is a volume: L$^3$. The cube root of L$^3$ is L.+)" = r"( )",
  r"(Invalid. 25 feet squared is 625 square feet. It makes no sense to multiply square feet by meters.)" = r"(Why not? 625 square-feet meters is a volume. It has dimension L$^3$. Admittedly a strange unit, but no stranger than the "acre-foot" used to measure agricultural irrigation.)",
  random_answer_order=TRUE
)
```



```{r drill-Dimensions-6, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Is this combination dimensionally valid? $$\exp(a d)$$ Why or why not? )",
r"(+Invalid. The input to $\exp()$ must be a dimensionless quantity.+)" = r"($a d$ has dimension L$^2$ (with units of feet-meters).)",
  r"(Valid. The $a$ cancels out the dimension of the $b$.)" = r"(No it does not. $a d$ has dimension L$^2$.)",
  r"(Invalid. 25 foot-meters does not mean anything.)" = r"(Yes it does. It is the area of a rectangle that is 25 feet long and one meter wide.)",
  random_answer_order=TRUE
)
```



```{r drill-Dimensions-7, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Is this combination dimensionally valid? $$\exp(c d)$$ Why or why not? )",
r"(+Invalid. The input to $\exp()$ must be a dimensionless quantity.+)" = r"($c d$ has dimension L.)",
  r"(Valid. The dimension will be L$^4$)" = r"(This would be right for the combination $d^c$, but $\exp(c d)$ is completely different.)",
  r"(Invalid. $c d$ has dimension L.)" = r"(The dimension of $c d$ is indeed L, but you cannot have an argument to $\exp()$ that is dimensionful.)",
  random_answer_order=TRUE
)
```



```{r drill-Dimensions-8, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Is this combination dimensionally valid? $$\exp(c/d)$$ Why or why not? )",
r"(Invalid. The input to $\exp()$ must be a dimensionless quantity.)" = r"($c / d$ is not dimensionless.)",
  r"(Valid. The L dimension of $c$ is cancelled out by the L$^{-1}$ dimension of $1/d$)" = r"(This would be right for the combination $d^c$, but $\exp(c d)$ is completely different.)",
  r"(+Invalid. $c / d$ has dimension L$^{-1}$.+)" = r"(Check your arithmetic!)",
  random_answer_order=TRUE
)
```


For the following few problems, keep in mind these physical quantities and their dimension:

- [Force] = MLT^-2^
- [Distance] = L
- [Area] = L^2^
- [Velocity] = L T^-1^
- [Acceleration] = L T^-2^<br>
- [Momentum] = M L T^-1^

```{r drill-Dimensions-9, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Given that [Force] = [Pressure][Area], what is the dimension of Pressure? )",
r"(+M L$^{-1}$ T$^{-2}$+)" = r"( )",
  r"(M L$^{1}$ T$^{-2}$)" = r"( )",
  r"(M L$^{-2}$ T$^{-1}$)" = r"( )",
  random_answer_order=TRUE
)
```



```{r drill-Dimensions-10, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Which one of the following statements is true? )",
r"(+Momentum = Mass * Velocity+)" = r"( )",
  r"(Velocity = Mass / Momentum)" = r"( )",
  r"(Momentum = Mass * Acceleration)" = r"(Mass * Acceleration is Force)",
  random_answer_order=TRUE
)
```



```{r drill-Dimensions-11, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Which one of the following statements is true? )",
r"(+Volume = Distance * Area+)" = r"( )",
  r"(Area = Distance / Volume)" = r"( )",
  r"(Force = Momentum / Acceleration)" = r"( )",
  random_answer_order=TRUE
)
```



```{r drill-Dimensions-12, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Which of the following is true? )",
r"(+Energy = Distance * Force+)" = r"( )",
  r"(Force = Energy / Mass)" = r"( )",
  r"(Energy = Momentum * Acceleration)" = r"( )",
  random_answer_order=TRUE
)
```



```{r drill-Dimensions-13, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Which of the following is true? )",
r"(+Length = Velocity / Acceleration+)" = r"( )",
  r"(Length = Force / Momentum)" = r"( )",
  r"(Area = Velocity * Acceleration)" = r"( )",
  random_answer_order=TRUE
)
```



```{r drill-Dimensions-14, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Which of the following is true? )",
r"(+Time = Force / Momentum+)" = r"( )",
  r"(Length = Force / Momentum)" = r"( )",
  r"(Area = Force / Momentum)" = r"( )",
  r"(Mass = Force / Momentum)" = r"( )",
  random_answer_order=TRUE
)
```



```{r drill-Dimensions-15, echo=FALSE, results='markup'}
askMC(
  prompt = r"(What kind of thing is $$\sqrt[3]{(\text{4in})(\text{2 ft})(\text{1 mile})}\  ?$$ )",
r"(+Length+)" = r"( )",
  r"(Area)" = r"( )",
  r"(Volume)" = r"( )",
  r"(it is meaningless)" = r"( )",
  random_answer_order=TRUE
)
```



```{r drill-Dimensions-16, echo=FALSE, results='markup'}
askMC(
  prompt = r"(What kind of thing is $$\sin(\pi\ \text{seconds})\  ?$$ )",
r"(Length)" = r"( )",
  r"(1 / Length)" = r"( )",
  r"(The number 0)" = r"( )",
  r"(+it is meaningless+)" = r"(The input to the sinusoid (and other trig functions) must be dimensionless)",
  random_answer_order=TRUE
)
```



```{r drill-Dimensions-17, echo=FALSE, results='markup'}
askMC(
  prompt = r"(If $t$ is measured in seconds and $A$ is measured in feet, what will be the dimension of $A \sin(2\pi t/P)$ when $P$ is two hours? )",
r"(+L+)" = r"( )",
  r"(T)" = r"(Remember, the output of $\sin()$ is dimensionless.)",
  r"(L/T)" = r"(Remember, the output of $\sin()$ is dimensionless.)",
  random_answer_order=TRUE
)
```



```{r drill-Dimensions-18, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Engineers often prefer to describe sinusoids in terms of their *frequency* $\omega$, writing the function as $\sin(2 \pi \omega t)$, where $t$ is time.<br><br> What is the dimension of $\omega$? )",
r"(+T$^{-1}$+)" = r"(A common unit of frequency is Hertz (Hz), sometimes called "cycles per second.")",
  r"(T)" = r"(This would mean the input to $\sin()$ has dimension T$^2$. But $\sin()$ only makes sense for a dimensionless input.)",
  r"(T$^2$)" = r"(This would mean the input to $\sin()$ has dimension T$^3$. But $\sin()$ only makes sense for a dimensionless input.)",
  random_answer_order=TRUE
)
```



```{r drill-Dimensions-19, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Suppose $t$ is measured in hours and $x$ in yards. What will be the dimension of $P$ in $$\sin(2\pi t x/P)\ ?$$ )",
r"(There is no such $P$ that will make a valid input to $\sin()$)" = r"( )",
  r"(+L T+)" = r"( )",
  r"(L / T)" = r"( )",
  r"(T / L)" = r"( )",
  random_answer_order=TRUE
)
```



```{r drill-M04-24, echo=FALSE, results='markup'}
askMC(
  prompt = r"(What is the value of `sin(180)`? )",
r"(+-0.80+)" = r"(The argument to trigonometric functions is interpreted by R to be in **radians**.)",
  r"(0)" = r"(This would be right if sine interpreted its argument in *degrees*. But arguments to the trigonometric functions in R and most other languages are in **radians**." $\sin(\pi) = 0$.)",
  r"(0.80)" = r"(You've got the sign incorrect.)",
  r"(1)" = r"(The argument to `sin()` is in radians.)",
  random_answer_order=FALSE
)
```

