
```{r drill-Quiz-2-15, echo=FALSE, results='markup'}
askMC(
  prompt = r"(What is the period of the function $\sin(6\pi t)$?)",
r"(+1/3+)" = r"( )",
  r"(1/2)" = r"( )",
  r"(2)" = r"( )",
  r"(3)" = r"( )",
  r"(6)" = r"( )",
  random_answer_order=FALSE
)
```

```{r drill-Quiz-2-13, echo=FALSE, results='markup'}
askMC(
  prompt = r"(What is the period of $g(t)$? $$g(t) \equiv \frac{5}{\sin(2 \pi t)}$$  )",
r"(+1+)" = r"( )",
  r"(5)" = r"(Hint: 5 isn't inside the $\sin()$ parentheses.)",
  r"($2 \pi/5$)" = r"(Hint: 5 isn't inside the $\sin()$ parentheses.)",
  r"($5/2\pi$)" = r"(Hint: 5 isn't inside the $\sin()$ parentheses.)",
  r"($g(t)$ isn't periodic.)" = r"(Since the $\sin()$ is periodic, $1/\sin()$ is also periodic.)",
  random_answer_order=FALSE
)
```



```{r drill-Quiz-2-12, echo=FALSE, results='markup'}
askMC(
  prompt = r"(What is the period of $g(t)$? $$g(t) \equiv \text{dnorm}\left(\frac{2\pi}{5}(t-3)\right)$$ )",
r"(1)" = r"( )",
  r"(5)" = r"( )",
  r"($2 \pi/5$)" = r"( )",
  r"($5/2\pi$)" = r"( )",
  r"(+$g(t)$ isn't periodic.+)" = r"(The only one of our basic modeling functions that is period is $\sin()$. The gaussian, that is, $\text{dnorm}()$, has just one bump and therefore isn't periodic.)",
  random_answer_order=FALSE
)
```

```{r echo=FALSE}
#| label: fig-rev2-04
#| fig-cap: "."
#| out-width: "60%"
slice_plot(2 * dnorm(t,-1, 2)  + 1 ~ t, bounds(t=c(-5.2,5.2))) %>%
  gf_refine(scale_x_continuous(breaks = -5:5)) 
```

```{r drill-Quiz-2-8, echo=FALSE, results='markup'}
askMC(
  prompt = r"(One of the following choices is the standard deviation of the function graphed in @fig-rev2-04. Which one?)",
r"(0)" = r"(A gaussian with 0 standard deviation would be infinitely narrow and infinitely high!)",
  r"(1)" = r"( )",
  r"(+2+)" = r"( )",
  r"(3)" = r"(Remember the rule of thumb: half-width at half-height)",
  r"(4)" = r"( )",
  random_answer_order=FALSE
)
```

```{r echo=FALSE}
#| label: fig-rev2-06
#| fig-cap: "."
#| out-width: "60%"
slice_plot(exp(t) ~ t, bounds(t=c(-1,3))) %>%
  slice_plot(exp(1.5*(t-1)) -2 ~ t, color="dodgerblue") %>%
  gf_refine(scale_x_continuous(breaks = -5:5)) 
```

```{r drill-M06-1, echo=FALSE, results='markup'}
askMC(
  prompt = r"(What is the value of the parameter "mean" for the function shown in @fig-rev2-06?)",
  r"(-2)" = r"( )",
  r"(-1)" = r"( )",
  r"(0.5)" = r"( )",
  r"( 1)" = r"( )",
  r"(+ 2+)" = r"(The **argmax** of the gaussian.)",
  r"("mean" is not a parameter of this function.)" = r"( )",
  random_answer_order=FALSE
)
```

```{r echo=FALSE}
#| label: fig-M06-01
#| fig-cap: "."
#| out-width: "60%"
slice_plot(dnorm(t, 2, 1) ~ t, bounds(t=c(-5,5))) |> 
  gf_refine(scale_x_continuous(breaks = -5:5)) 
```

```{r drill-M06-2, echo=FALSE, results='markup'}
askMC(
  prompt = r"(What is the value of the parameter "sd" for the function shown in @fig-M06-01?)",
r"(-2)" = r"( )",
  r"(-1)" = r"(sd cannot be negative)",
  r"(0.5)" = r"( )",
  r"(+ 1+)" = r"( )",
  r"( 2)" = r"( )",
  r"("sd" is not a parameter of this function.)" = r"( )",
  random_answer_order=FALSE
)
```

```{r echo=FALSE}
#| label: fig-M06-02
#| fig-cap: "."
#| out-width: "60%"
slice_plot(dnorm(t, -2, 2) ~ t, bounds(t=c(-5,5))) |> 
  gf_refine(scale_x_continuous(breaks = -5:5)) 
```


```{r drill-M06-3, echo=FALSE, results='markup'}
askMC(
  prompt = r"(What is the value of the parameter "mean" for the function shown in @fig-M06-02?)",
r"(+-2+)" = r"( )",
  r"(-1)" = r"( )",
  r"(0.5)" = r"( )",
  r"( 1)" = r"( )",
  r"( 2)" = r"(The **argmax** of the gaussian.)",
  r"("mean" is not a parameter of this function.)" = r"( )",
  random_answer_order=FALSE
)
```



```{r drill-M06-4, echo=FALSE, results='markup'}
askMC(
  prompt = r"(What is the value of the parameter "sd" for the function shown in @fig-M06-02)",
r"(-2)" = r"(sd cannot be negative)",
  r"(-1)" = r"(sd cannot be negative)",
  r"(0.5)" = r"( )",
  r"( 1)" = r"( )",
  r"(+ 2+)" = r"( )",
  r"("sd" is not a parameter of this function.)" = r"( )",
  random_answer_order=FALSE
)
```

