
```{r echo=FALSE}
P0 <- ggplot(data=Engines, aes(x=bore, y=stroke)) +
  geom_blank() +
  labs(x = "x", y="y")

P1 <- P0 + 
  scale_y_log10()
P2 <- P1 + 
  scale_x_log10() 
P3 <- P0 + scale_x_log10(breaks=c(1,2,4,8,16,32,64,128), limits=c(1,150))
P4 <- P0 + scale_x_log10(breaks=c(1, 3, 5, 10, 30, 50, 100, 500), limits=c(1,600))
P5 <- P0 + scale_x_log10(breaks=c(1, 3, 5, 10, 30, 50, 100, 300, 500), limits=c(1,600), labels = c(10, 20, 30, 40, 50, 60, 70, 80, 90))

# save_graph(P0, "scales-linear.png")
# save_graph(P1, "scales-semilog.png")
# save_graph(P2, "scales-loglog.png")
# # These will be edited to keep ust the x-axis
# save_graph(P3, "scales-base2.png")
# save_graph(P4, "scales-semidecade.png")
# save_graph(P5, "scales-bogus.png")
  

P6 <- slice_plot(2 + 1.5*x ~ x, bounds(x=c(0,5)), size=2) 
P7 <- P6 %>%
  gf_labs(y = "ln(output)", x = "input")
P8 <- P6 %>%
  gf_labs(y = "ln(output)", x = "ln(input)")
P9 <- slice_plot(10 - 2*x ~ x, bounds(x=c(0,5)), size=2)  
P10 <- P9 %>%
  gf_labs(y = "ln(output)", x = "input")
P11 <- P9 %>%
  gf_labs(y = "ln(output)", x = "log(input)")

# save_graph(P6, "line.png")
# save_graph(P7, "exponential.png")
# save_graph(P8, "power-law.png")
# save_graph(P9, "line-neg.png")
# save_graph(P10, "exponential-neg.png")
# save_graph(P11, "power-law-neg.png")
```




```{r echo=FALSE}
#| label: fig-exponential-neg
#| fig-cap: "."
#| out-width: "60%"
P10
```

```{r drill-Scales-1, echo=FALSE, results='markup'}
askMC(
  prompt = r"(What is the correct form for the relationship shown in @fig-exponential-neg)",
r"(+$g(x) \equiv e^{10} e^{-2 x}$+)" = r"( )",
  r"($g(x) \equiv 10 e^{-2 x}$)" = r"(When $x=0$, the ln(output) is 10. This isn't the same as saying the output is 10.)",
  r"($g(x) \equiv e^{10} e^{-1.5 x}$)" = r"(Check the slope again)",
  r"($g(x) \equiv e^{-1.5} e^{10 x}$)" = r"(Isn't it a decaying function of $x$?)",
  r"($g(x) \equiv 10 x^{-1.5}$)" = r"(Are these log-log axes?)",
  random_answer_order=TRUE
)
```

```{r drill-Scales-1b, echo=FALSE, results="markup"}
askMC(
  prompt= "Which of these is the better modeling relationship for the following scenario: Your data looks linear on a semi-log plot.",
  "Power-law",
  "+Exponential+"
  )
```


```{r drill-Scales-1c, echo=FALSE, results="markup"}
askMC(
  prompt= "Which of these is the better modeling relationship for the following scenario: Your data looks linear on a log-log plot.",
  "+Power-law+",
  "Exponential"
  )
```

```{r echo=FALSE}
#| label: fig-power-law-neg
#| fig-cap: "."
#| out-width: "60%"
P11
```



```{r drill-Scales-2, echo=FALSE, results='markup'}
askMC(
  prompt = r"(What is the correct form for the relationship shown in @fig-power-law-neg?)",
  r"($g(x) \equiv 10 x^{-2}$)" = r"(When $x=0$, the ln(output) is 10. This isn't the same as saying the output is 10.)",
  r"($g(x) \equiv e^{10} e^{-1.5 x}$)" = r"(Check the slope again)",
  r"(+$g(x) \equiv e^{10} x^{-2}$+)" = r"(Isn't it a decaying function of $x$?)",
  r"($g(x) \equiv e^10 x^{-1.5}$)" = r"(Check the slope.)",
  random_answer_order=TRUE
)
```

```{r echo=FALSE}
#| label: fig-power-law
#| fig-cap: "."
#| out-width: "60%"
P8
```

```{r drill-Scales-3, echo=FALSE, results='markup'}
askMC(
  prompt = r"(What is the correct form for the relationship shown in @fig-power-law?)",
r"($g(x) \equiv e^{2} e^{1.5 x}$)" = r"(Are these semi-log axes?)",
  r"($g(x) \equiv 2 x^{1.5}$)" = r"(When $x=0$, the ln(output) is 2. This isn't the same as saying the output is 2.)",
  r"(+$g(x) \equiv e^{2} x^{1.5}$+)" = r"( )",
  r"($g(x) \equiv e^{2} x^{2}$)" = r"(Isn't it a decaying function of $x$?)",
  r"($g(x) \equiv e^2 x^{-1.5}$)" = r"(But the function has positive slope.)",
  random_answer_order=TRUE
)
```

```{r echo=FALSE}
#| label: fig-scales-base2
#| fig-cap: "."
#| out-width: "60%"
P8
```



```{r drill-Scales-4, echo=FALSE, results='markup'}
askMC(
  prompt = r"(@fig-scales-base2 shows a horizontal axis for a graph. How can you tell that this is a logarithmic axis?)",
r"(The labels are all multiples of 2.)" = r"(On it is own, that has nothing to do with logarithms.)",
  r"(+The labels are evenly spaced **and** each label is a factor of 2 larger than the previous one.+)" = r"( )",
  r"(Trick question. It is not  a log scale.)" = r"( )",
  random_answer_order=TRUE
)
```


```{r echo=FALSE}
#| label: fig-scales-semidecade
#| fig-cap: "."
#| out-width: "60%"
P4
```



```{r drill-Scales-5, echo=FALSE, results='markup'}
askMC(
  prompt = r"(@fig-scales-semidecade shows a horizontal axis for a graph. How can you tell that this is a logarithmic axis?)",
r"(The labels are 1, 3, 5, 10, ...)" = r"(On it is own, that has nothing to do with logarithms.)",
  r"(The labels are evenly spaced **and** each label is a factor of 3 larger than the previous one.)" = r"(If so, the labels would be 1, 3, 9, 27, 81, 243, ....)",
  r"(+The 3 label is about halfway between the 1 and 10 label for each decade, and the 1 and 10 labels have the same spacing for every decade.+)" = r"(And the 5 label is about 70% of the way from the 1 to the 10 label in each decade.)",
  r"(Trick question. It is not  a log scale.)" = r"( )",
  random_answer_order=TRUE
)
```

```{r echo=FALSE}
#| label: fig-scales-bogus
#| fig-cap: "."
#| out-width: "60%"
P5
```


```{r drill-Scales-6, echo=FALSE, results='markup'}
askMC(
  prompt = r"(@fig-scales-bogus shows a horizontal axis for a graph. How can you tell that this is a logarithmic axis?)",
r"(The labels are 10, 20, 30, 40, ...)" = r"(On a linear scale, such labels would be evenly spaced.)",
  r"(Each label is 10 + the previous label.)" = r"(On a linear scale, such labels would be evenly spaced.)",
  r"(The 3 label is about halfway between the 1 and 10 label for each decade, and the 1 and 10 labels have the same spacing for every decade.)" = r"(And the 5 label is about 70% of the way from the 1 to the 10 label in each decade.)",
  r"(+Trick question. It is not  a linear scale.+)" = r"(it is not even a log scale. The numbers are arithmetically evenly spaced, but graphically they are irregularly spaced, sometimes small spacing, sometimes large.)",
  random_answer_order=TRUE
)
```

