
```{r echo=FALSE}
f1 <- makeFun(ifelse(x > 1, 1, x^2) ~ x)
f2 <- makeFun(ifelse(x > 0, sin(x), x) ~ x)
f3 <- makeFun(ifelse(abs(x) > 1, x, x^3) ~ x)
f4 <- makeFun(ifelse(abs(x) > 1, x^3, x) ~ x)
f5 <- makeFun(ifelse(abs(x) > 1, x, exp(x^2)) ~ x)
P1 <- slice_plot(f1(x) ~ x, bounds(x=c(-2, 2)))
P2 <- slice_plot(f2(x) ~ x, bounds(x=c(-2, 2)))
P3 <- slice_plot(f3(x) ~ x, bounds(x=c(-2, 2)))
P4 <- slice_plot(f4(x) ~ x, bounds(x=c(-2, 2)))
P5 <- slice_plot(f5(x) ~ x, bounds(x=c(-2, 2)))
```


```{r echo=FALSE}
#| label: fig-pieces-01
#| fig-cap: "."
#| out-width: "60%"
P1
```

```{r drill-Piecewise-1, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Which of the following tilde-expressions could be used to generate the graph in @fig-pieces-01? )",
r"(+`ifelse(x > 1, 1, x^2) ~ x`+)" = r"( )",
  r"(`ifelse(x > 0, sin(x), x) ~ x`)" = r"( )",
  r"(`ifelse(abs(x) > 1, x, x^3) ~ x`)" = r"( )",
  r"(`ifelse(abs(x) > 1, x^3, x) ~ x`)" = r"( )",
  r"(`ifelse(abs(x) > 1, x, exp(x^2)) ~ x`)" = r"( )",
  random_answer_order=TRUE
)
```


```{r echo=FALSE}
#| label: fig-pieces-02
#| fig-cap: "."
#| out-width: "60%"
P2
```


```{r drill-Piecewise-2, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Which of the following tilde-expressions could be used to generate the graph in @fig-pieces-02?)",
r"(`ifelse(x > 1, 1, x^2) ~ x`)" = r"( )",
  r"(+`ifelse(x > 0, sin(x), x) ~ x`+)" = r"( )",
  r"(`ifelse(abs(x) > 1, x, x^3) ~ x`)" = r"( )",
  r"(`ifelse(abs(x) > 1, x^3, x) ~ x`)" = r"( )",
  r"(`ifelse(abs(x) > 1, x, exp(x^2)) ~ x`)" = r"( )",
  random_answer_order=TRUE
)
```

```{r echo=FALSE}
#| label: fig-pieces-03
#| fig-cap: "."
#| out-width: "60%"
P3
```

```{r drill-Piecewise-3, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Which of the following tilde-expressions could be used to generate the graph in @fig-pieces-03?)",
r"(`ifelse(x > 1, 1, x^2) ~ x`)" = r"( )",
  r"(`ifelse(x > 0, sin(x), x) ~ x`)" = r"( )",
  r"(+`ifelse(abs(x) > 1, x, x^3) ~ x`+)" = r"( )",
  r"(`ifelse(abs(x) > 1, x^3, x) ~ x`)" = r"( )",
  r"(`ifelse(abs(x) > 1, x, exp(x^2)) ~ x`)" = r"( )",
  random_answer_order=TRUE
)
```

```{r echo=FALSE}
#| label: fig-pieces-04
#| fig-cap: "."
#| out-width: "60%"
P4
```

```{r drill-Piecewise-4, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Which of the following tilde-expressions could be used to generate the graph in @fig-pieces-04? )",
r"(`ifelse(x > 1, 1, x^2) ~ x`)" = r"( )",
  r"(`ifelse(x > 0, sin(x), x) ~ x`)" = r"( )",
  r"(`ifelse(abs(x) > 1, x, x^3) ~ x`)" = r"( )",
  r"(+`ifelse(abs(x) > 1, x^3, x) ~ x`+)" = r"( )",
  r"(`ifelse(abs(x) > 1, x, exp(x^2)) ~ x`)" = r"( )",
  random_answer_order=TRUE
)
```

```{r echo=FALSE}
#| label: fig-pieces-05
#| fig-cap: "."
#| out-width: "60%"
P5
```

```{r drill-Piecewise-5, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Which of the following tilde-expressions could be used to generate the graph in @fig-pieces-05?)",
r"(`ifelse(x > 1, 1, x^2) ~ x`)" = r"( )",
  r"(`ifelse(x > 0, sin(x), x) ~ x`)" = r"( )",
  r"(`ifelse(abs(x) > 1, x, x^3) ~ x`)" = r"( )",
  r"(`ifelse(abs(x) > 1, x^3, x) ~ x`)" = r"( )",
  r"(+`ifelse(abs(x) > 1, x, exp(x^2)) ~ x`+)" = r"( )",
  random_answer_order=TRUE
)
```


