
```{r echo=FALSE, warning=FALSE, message=FALSE}
#| label: fig-rev2-03
#| fig-cap: "."
#| out-width: "60%"
slice_plot(2 * sin(2*pi*(t+2.5)/5)  + 1 ~ t, domain(t=c(-5.2,5.2))) %>%
  gf_refine(scale_x_continuous(breaks = -5:5),
            scale_x_continuous(breaks = -5:5)) 
```


```{r drill-Quiz-2-22, echo=FALSE, results='markup'}
askMC(
  prompt = r"(What's the period of the sinusoid in @fig-rev2-03?)",
  r"(1)" = r"( )",
  r"(2)" = r"( )",
  r"(3)" = r"( )",
  r"(4)" = r"( )",
  r"(+5+)" = r"( )",
  random_answer_order=FALSE
)
```

```{r echo=FALSE}
#| label: fig-rev2-07
#| fig-cap: "."
#| out-width: "60%"
slice_plot(exp(t) ~ t, domain(t=c(-1,3)), color="dodgerblue") %>%
  slice_plot(exp(-1.5*(t-1)) -2 ~ t) %>%
  gf_refine(scale_x_continuous(breaks = -5:5))
```

```{r drill-Quiz-2-23, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Which function(s) in @fig-rev2-03 have $k < 0$?)",
r"(blue)" = r"( )",
  r"(+black+)" = r"( )",
  r"(both)" = r"( )",
  r"(neither)" = r"( )",
  random_answer_order=FALSE
)
```

```{r echo=FALSE}
#| label: fig-rev2-06
#| fig-cap: "."
slice_plot(exp(t) ~ t, domain(t=c(-1,3))) %>%
  slice_plot(exp(1.5*(t-1)) -2 ~ t, color="dodgerblue") %>%
  gf_refine(scale_x_continuous(breaks = -5:5)) 
```

```{r drill-Quiz-2-24, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Which function(s) in @fig-rev2-06 have $k < 0$?)",
r"(blue)" = r"( )",
  r"(black)" = r"( )",
  r"(both)" = r"( )",
  r"(+neither+)" = r"(As the input gets bigger, both functions produce outputs that get further from their respective baselines. That' exponential growth.)",
  random_answer_order=FALSE
)
```

```{r echo=FALSE}
#| label: fig-rev2-08
#| fig-cap: "."
slice_plot(3 - exp(t) ~ t, domain(t=c(-1,3)), color="dodgerblue") %>%
  slice_plot(exp(1.5*(t-1)) - 8 ~ t) %>%
  gf_refine(scale_x_continuous(breaks = -5:5))
```

```{r drill-Quiz-2-25, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Which function(s) in @fig-rev2-08 have $k < 0$?)",
r"(blue)" = r"(Exponential decay means that the function output gets closer and closer to baseline as the input gets bigger.)",
  r"(black)" = r"( )",
  r"(both)" = r"( )",
  r"(+neither+)" = r"(As the input gets bigger, both functions produce outputs that get further from their respective baselines. That' exponential growth.)",
  random_answer_order=FALSE
)
```



```{r drill-Quiz-2-26, echo=FALSE, results='markup'}
askMC(
  prompt = r"(One of the functions in @fig-rev2-07 has a half-life, the other a doubling time. Which is bigger, the half-life or the doubling time?)",
r"(+doubling time+)" = r"( )",
  r"(half-life)" = r"( )",
  r"(about the same)" = r"( )",
  r"(they aren't exponential, so the concept of half-life/doubling-time does not apply.)" = r"( )",
  random_answer_order=FALSE
)
```


```{r drill-M04-8, echo=FALSE, results='markup'}
askMC(
  prompt = r"(In this book, what is meant by the word "**variable**"? )",
r"(it is the same as input.)" = r"(Use **input** rather than variable! Even if you're used to calling quantities like $x$ and $y$ variables, it is a confusing practice since it can mean so many different things. In calculus, in this course, we will try to be strict about using the words **input** and **output**)",
  r"(it is the same as output.)" = r"( )",
  r"(+A column in a data table.+)" = r"(This is the use in statistics and data science. In calculus, we will try to avoid confusing by using **input** and **output** instead.)",
  random_answer_order=TRUE
)
```



