---
chapter: "none yet"
author: "Danny Kaplan"
difficulty: "XX"
date: 2021-06-08 
version: 0.1
tags: [first, second, third]
id: eagle-bring-car
---

```{r eagle-bring-car-default, include = FALSE}
library(etude2)
library(mosaic)
library(mosaicCalc)
```

Consider the sinusoid function, graphed below.

```{r echo=FALSE}
slice_plot(sin(x) ~ x, domain(x=c(0, 10)), npts=200) %>%
  gf_refine(scale_x_continuous(breaks=0:10),
            scale_y_continuous(breaks=(-10:10)/10))
```
```{r ebc1-1, echo=FALSE, results="markup"}
askMC(
  "What is the average rate of change over the interval $0 < x < \\frac{1}{2}$? (Choose the closest value.)",
  "0" = "For this to be true, the function output would need to be the same at the two endpoints of the interval.",
  "0.5" = "Did you forget to divide the rise by the run?",
  "+1+" = "Right. From the interval you have that the run is 1/2. The rise over that interval is from 0 to 1/2, so a rise of 1/2. ",
  random_answer_order = FALSE
)
```

```{r ebc1-2, echo=FALSE, results="markup"}
askMC(
  "What is the average rate of change over the interval $0 < x < 6.25$? (Choose the closest value.)",
  "-0.5",
  "+0+" = "Right. The function output is zero at both endpoints of the interval, so the rise is zero. Hence, the run is zero.",
  "0.5",
  random_answer_order = FALSE
)
```

```{r ebc1-3, echo=FALSE, results="markup"}
askMC(
  "What is the average rate of change over the interval $0 < x < 10$? (Choose the closest value.)",
  "+-0.05+" = "Right. The rise is -0.5 and the run is 10.",
  "-0.5" = "This is the \"rise\" over the interval, but it's not the average rate of change. You'll need to divide the rise by another quantity to get the average rate of change.",
  "0",
  "0.5" = "The rise will be $f(10) - f(0) \approx -0.5 - 0 = -0.5$. You've got the sign wrong.",
  random_answer_order = FALSE
)
```


