---
id: "ebola-sigmoid"
title: "Ebola sigmoid"
author: "Daniel Kaplan"
global-id: "EKCIE"
skill: "Gi-Fun-115b-sigmoid"
---

```{r include=FALSE}
library(Zcalc)
```


-------

The graph shows the cumulative number of Ebola cases in Sierra Leone during an outbreak from May 1, 2014 (Day 0) to December 16, 2015. (Source: `{MMAC}` R package, Joel Kilty and Alex McAllister, *Mathematical Modeling and Applied Calculus*.) Put aside for the moment that the Ebola data don't have the exact shape of a sigmoid function, and follow the fitting procedure as best you can.

```{r}
gf_point(Cases ~ Day, data = MMAC::EbolaSierraLeone)
```

```{r daily-digital-08-QA12, echo=FALSE}
askMC(
  prompt = "Where is the top plateau?",
    "About Day 600." = "Measure the height of the plateau, not where it starts horizontally.",
    "+About 14,000 cases+" = "",
    "About 20,000 cases" = "Read the vertical axis markings more carefully.",
    "None of the above" = "One of the above answers is pretty good.",
  random_answer_order = TRUE
)
```

```{r daily-digital-08-QA13, echo=FALSE}
askMC(
  prompt = "Where is the centerline?",
    "+Near Day 200+" = "",
    "Near Day 300" = "That's  the center of the vertical scale, not the day at which the curve reaches half-way to the eventual plateau.",
    "At about 7000 cases" = "That's  half-way up to the plateau, but the answer you  want is the day at which the curve reaches that point."
)
```

```{r daily-digital-08-QA14, echo=FALSE}
askMC(
  prompt = "Now to find the `width` parameter. The curve looks more classically sigmoid to the left of the centerline than to the right, so follow the curve *downward* as in Step 4 of the algorithm to find the parameters. What's a good estimate for `width`?",
    "+About 50 days+" = "",
    "About 100 days" = "Too wide!",
    "About 10 days" = "Too small",
    "About 2500 cases" = "The width is measured along the horizontal axis, not the vertical"
)
```

