---
id: "fiducial-point"
author: "Daniel Kaplan"
global-id: "MWLCS"
skill: "Gi-Fun-108"
---


Each of the following plots shows a basic modeling function whose input scaling has the form $x - x_0$. Your job is to figure out from the graph what is the numerical value of $x_0$. (Hint: For simplicity, $x_0$ in the questions will always be an integer.)

```{r echo=FALSE}
slice_plot(dnorm(x-2) ~ x, bounds(x=c(-3,3))) |> gf_labs(title="(A)")
```

```{r fp-dnorm, echo=FALSE, results="markup"}
askMC(
  "In plot (A), what is $x_0$?",
  -2, -1, 0, 1, "+2+" = "Right. Look for the input that generates the peak output value.", random_answer_order = FALSE
)
```

```{r echo=FALSE}
slice_plot(sin(x+1) ~ x, bounds(x=c(-4,4))) |> gf_labs(title="(B)")
```


```{r fp-sin, echo=FALSE, results="markup"}
askMC(
  "In plot (B), what is $x_0$?",
  "-2", "+-1+"= "The fiducial point is a positive-going zero crossing.", 0, 1, "2" , random_answer_order = FALSE
)
```

```{r echo=FALSE, warning=FALSE}
slice_plot(log(x -1) ~ x, bounds(x=c(-2,5)), npts=500) |> gf_labs(title="(C)") 
```


```{r fp-log, echo=FALSE, results="markup"}
askMC(
  "In plot (C), what is $x_0$?",
  -2, "-1", 0, "+1+"= "The vertical asymptote is the clue.", "2" , random_answer_order = FALSE
)
```

```{r echo=FALSE}
slice_plot(pnorm(x -1) ~ x, bounds(x=c(-3,3))) |> gf_labs(title="(D)")
```


```{r fp-pnorm, echo=FALSE, results="markup"}
askMC(
  "In plot (D), what is $x_0$?",
  -2, "-1", 0, "+1+"="The input where the output is half way between the two horizontal asymptotes", "2" , random_answer_order = FALSE
)
```

```{r echo=FALSE}
slice_plot(1/(x+2) ~ x, bounds(x=c(-1.9,2))) |> gf_labs(title="(E)") %>%
  slice_plot(1/(x+2) ~ x, bounds(x=c(-3,-2.1)))
```

```{r fp-recip, echo=FALSE, results="markup"}
askMC(
  "In plot (E), what is $x_0$?",
  "+-2+" = "Right. The location of the vertical asymtote is the clue.", "-1", 0, "1", "2" , random_answer_order = FALSE
)
```


