---
id: "fish-walk-green"
author: "Daniel Kaplan"
global-id: "TLEXE"
---

```{r include=FALSE}

library(mosaic)
library(mosaicCalc)
```


```{r  echo=FALSE}
gf_blank(temp ~ time, data = CoolingWater) %>%
  gf_refine(scale_y_log10(breaks = c(10,20,30,50, 100), limits = c(10,100))) 
```


```{r daily-digital-05-QA1, echo=FALSE}
askMC(
  prompt = "Consider the axis scales shown above.  Which kind of scale is the horizontal axis?",
  choices = list(
    "+linear+" = "You can see this because a given length along the axis corresponds to the same arithmetic difference regardless of where you are on the axis.  the distance between 0 and 50 is the same as the difference between 50 and 100, or the distance between 150 and 200.",
    "logarithmic" = "A clue that an axis is **not** logarithmic is that  there is a zero marked. The log of zero is $-\\infty$, which  can't appear on any actual  graph. Another key is whether the scale shows doubling behavior.  The distance between 50 and 100 represents one doubling: 100 is twice 50. If the scale were logarithmic, moving forward that same distance from 100 would bring you to 200.  But that's not what happens here.",
    "semi-logarithmic" = "\"Semi-logarithmic\" is not about a single axis but about two axes: horizontal and vertical. It means that one axis is linear while the other is logarithmic.",
    "log-log" = "\"Log-log\"  is not about a single axis but about two axes. It means that both the horizontal and vertical axes are logarithmic."
  )
)
```

```{r daily-digital-05-QA2, echo=FALSE}
askMC(
  prompt = "Which kind of scale is the vertical axis?",
    "linear" = "Measure the distance from 30 to 50. If the scale were linear, then moving that same distance from 50 would bring you  to 70, and moving that distance again would bring you to 90. But you can see that instead of reaching 90, you'd reach something greater than 100 on the scale. So the scale is not linear.",
    "+logarithmic+" = "",
    "semi-logarithmic" = "\"Semi-logarithmic\" is not about a single axis but about two axes: horizontal and vertical. It means that one axis is linear while the other is logarithmic.",
    "log-log" = "\"Log-log\"  is not about a single axis but about two axes. It means that both the horizontal and vertical axes are logarithmic."
)
```

```{r daily-digital-05-QA5, echo=FALSE}
askMC(
  prompt = "Given your answers to the  previous two questions, what kind of plot would be made in the frame being displayed at the top of this question?",
    "+semi-log+" = "",
    "log-log" = "A log-log plot has log scales for both axes. The horizontal axis here is linear.",
    "linear-linear" = "No, the vertical axis is logarithmic."
)
```

