---
id: "Flipping-2"
author: "Daniel Kaplan"
skill: "Gi-Fun-115b-exponential"
global-id: "YLWP2"
---

Each of the curves in the graph is an exponential function $e^{kt}$, for various values of $k$.

```{r echo=FALSE}
#| label: figflipping-2-1
slice_plot(exp(-x) ~ x, domain(x=c(-2, 2)), label_x=0, label_text="A", label_vjust=2) %>%
  slice_plot(exp(x/2) ~ x, color="orange3", label_text="B") %>%
  slice_plot(exp(x/1.5) ~ x, color="magenta", label_text="C") %>%
  slice_plot(exp(-x/1.5) ~ x, color="orange", label_x=0, label_text="D", label_vjust=2) %>%
  slice_plot(exp(x) ~ x, color="dodgerblue", label_text="E", label_vjust=2) 
```


```{r flipping-2a, echo=FALSE, results="markup"}
askMC(
  "What is the order from $k$ smallest (most negative) to k largest?",
  "+A, D, B, C, E+" = "Exponential functions that grow slowly have $k$ with a small absolute value",
  "A, B, E, C, D" = "Sorry. Notice curve B grows the most slowly. This means it has the smallest $|k|$.",
  "E, C, D, B, A" = "The B and A curves have negative $k$, so they will be smaller than the other curves with positive sign."
)
```
