---
id: "IWLDN1"
author: "Daniel Kaplan"
---

The graphs of functions and their inverses are related by a flip around the ***line of identity***, shown in green in the following graph.

```{r if1-1, echo=FALSE, warning=FALSE, message=FALSE}
slice_plot(exp(x) ~ x, domain(x=c(-2,2))) %>%
  slice_plot(log(x) ~ x, color="magenta", npts=500) %>%
  gf_lims(y=c(-5,8)) %>%
  gf_abline(intercept=0, slope=1, color="green", size=1) %>%
  gf_refine(scale_y_continuous(breaks=c(-5, -3, -2, -1, 0, 1, 2, 3, 5), limits=c(-5, 5)),
            coord_fixed())
```


The black curve is the graph of $e^x$.

```{r if1-1a, echo=FALSE, results="markup"}
askMC(
  "Is the magenta curve the graph of a function? (Hint: Does it pass the vertical line test?)",
  "+Yes+", "No" = "The magenta curve has a vertical asymptote at $x=0$, but since it never reaches that asymptote, it passes the vertical line test.", random_answer_order = FALSE
)
```

```{r if1-1b, echo=FALSE, results="markup"}
askMC(
  "Which of these functions is graphed in magenta?",
  "$1/x$", "+$\\ln(x)$+", "$\\sqrt{x}$", "$e^{-x}$" = "Sorry, but this would be the reflection of the black curve around the vertical line at $x=0$",
  "$-e^{x}$" = "No. This would be the reflection of the black curve around the horizontal line at output $f(x)=0$"
)
```  
