---
id: "maple-pitch-jacket"
created: "Thu Aug  5 09:12:50 2021"
global_id: "LPhyTb"
---


The graph shows (in black) a function constructed as the product of two basic modeling functions. The graph also shows a pair of blue curves that encompass the black function. These are called the ***envelope*** of the black function.

```{r echo=FALSE}
slice_plot(sin(2*pi*t/2.1)*sin(2*pi*t/20) ~ t, domain(t=c(-30, 40)), npts=500) %>%
  slice_plot(sin(2*pi*t/20) ~ t, color="blue", alpha=0.6) %>%
  slice_plot(-sin(2*pi*t/20) ~ t, color="blue", alpha=0.6)
```


```{r sine-in-sine1, echo=FALSE, results="markup"}
askMC(
  "What are the two basic modeling functions being multiplied?",
  "+A sinusoid and another sinusoid with a faster period.+",
  "A gaussian and a sinusoid.",
  "A sigmoid function and a sinusoid."
)
```


```{r sine-in-sine2, echo=FALSE, results="markup"}
askMC(
"What is the period of the envelope?", 
"10" = "It is true that the broad peaks in the overall function occur every 10 time units. But a sine wave has two excursions from zero every cycle, one positive and one negative. So if the period of the envelope were 10, we would see an amplitude of the faster sinusoid near zero every 5 time units.",  
"+20+",
"30" = "If this were so, the dips in amplitude of the faster sign would occur every 15 time units.",
random_answer_order = FALSE
)
```
