---
chapter: "none yet"
author: "Danny Kaplan"
difficulty: "XX"
date: 2021-06-08 
version: 0.1
tags: [first, second, third]
id: pig-look-rug
---

```{r pig-look-rug-default, include = FALSE}
library(etude2)
```

For each of the following, compute the *average* rate of change of the function over the given interval.

```{r daily-digital-24-QA1, echo=FALSE}
askMC(
  prompt = "The average rate of change of $f(x) \\equiv x + 5$ over [3, 5] is",
  choices = list(
    "-2" = "Remember, the *difference* from $x=3$ to 5 is $f(5) - f(3)$, not the other way around. And the average *rate* of change is the difference divided by the length of the interval.",
    "-1" = "Remember, the *difference* from $x=3$ to 5 is $f(5) - f(3)$, not the other way around. Similarly, the length of the interval from $x=3$ to 5 is $5-3$, not $3-5$.",
    "+1+" = "$f(x=5) = 10$ and $f(x=3) = 8$, so the *difference* in values is 2. Since this difference occurs over an interval of length 2 (that is, from #x=3$ to 5), the average *rate* of change is 2/2.",
    "2" = "Are you sure you took the **rate** of change rather than simply the change?"
  ),
  random_answer_order = FALSE
)
```

```{r daily-digital-24-QA2, echo=FALSE}
askMC(
  prompt = "The average rate of change of $f(x) \\equiv 3 - 2 x$ over [-4, -2] is",
    "-4" = "This is the total difference over the interval, not the *rate* of change.",
    "+-2+" = "The difference from $x=-4$ to $-2$ is $f(-2) - f(-4) = (7) - (11) = -4$. The length of the interval is $(-2) - (-4) = 2$. So the rate is -4/2, just as you got.",
    "0" = "",
    "1" = "When $x$ changes by two units, $f(x)$ changes by 4. The *rate* of change is 4/2 = -2.",
    "2" = "Check your +/- signs.",
    "4" = "This is the negative total difference over the interval, not the *rate* of change. Also check your +/- signs.",
  random_answer_order = FALSE
)
```

```{r daily-digital-24-QA3, echo=FALSE}
askMC(
  prompt = "The average rate of change of $f(x) \\equiv -3 x^2$ over [0, 4] is",
    "-24" = "Perhaps you are looking at the derivative at $x=4$ and not the average rate of change from $x=0$ to 4.",
    "+-12+" = "The difference in $f()$ over the interval is $f(4) - f(2) = (-48) - 0 = -48$. The length of the interval is $4-0$, so the average rate of change over the interval is $(-48)/4 = -12$.",
    "0" = "Perhaps you are looking at the derivative at $x=0$ and not the average rate of change from $x=0$ to 4.",
    "1" = "",
    "2" = "",
    "12" = "Check the signs in your arithmetic.",
    "24" = "",
  random_answer_order = FALSE
)
```

```{r daily-digital-24-QA4, echo=FALSE}
askMC(
  prompt = "The average rate of change of $f(x) \\equiv x^3 - 2 x + 1$ over [0, 2] is",
    "-2" = "Either check your +/- signs or perhaps you are looking at the derivative at $x=0$ and not the average rate of change from $x=0$ to 2.",
    "1.5" = "",
    "+2+" = "The difference in $f()$ over the interval is $f(2) - f(0) = 5 - 1 = 4$. The length of the interval is $2 - 0$ so the average *rate* of change is $4/2 = 2$. ",
    "7" = "",
    "10" = "I think you are looking at the derivative at $x=2$ rather than the average rate of change from 0 to 2.",
  random_answer_order = FALSE
)
```



