---
id: "scale-input-1"
global-id: "uKCIE"
author: "Daniel Kaplan"
skill: "F-input-scaling"
---

```{r include=FALSE}

library(mosaic)
library(mosaicCalc)
```

Each of the graphs shows two horizontal scales and one of the basic modeling functions. Which horizontal scale (black or blue) corresponds to the pattern-book function? 

```{r echo=FALSE}
plot_scaled_input(dnorm(x) ~ x, domain(x=c(-3,3)), 0.25, 10) %>%
  gf_labs(y="output", x="input", title="Graph (A)")
```
```{r si1D-A, echo=FALSE, results="markup"}
askMC(
  "For graph (A), which scale corresponds to the pattern-book function?",
  "+black+",
  "blue", 
  "neither", 
  "both" = "It cannot be both. There is only one pattern-book function. When you scale the input, it becomes a \"basic modeling function\".",
  random_answer_order=FALSE
)
```

```{r echo=FALSE}
plot_scaled_input(pnorm(x, -3, .5) ~ x, domain(x=c(-6,0)), .5, -3) %>%
  gf_labs(y="output", x="input", title="Graph (B)")
```

```{r si1D-B, echo=FALSE, results="markup"}
askMC(
  "For graph (B), which scale corresponds to the pattern-book function?",
  "black",
  "+blue+" = "Right. The pattern-book function has an output of 1/2 when the output is zero. That is what the blue scale shows. ", 
  "neither", 
  "both" = "It cannot be both. There is only one pattern-book function. When you scale the input, it becomes a \"basic modeling function\".",
  random_answer_order=FALSE
)
```

```{r echo=FALSE}
plot_scaled_input(sin(2*pi*x/3+1) ~ x, domain(x=c(-2,10)), (2*pi)/3, 16/(2*pi)) %>%
  gf_labs(y="output", x="input", title="Graph (C)")
```

```{r si1D-C, echo=FALSE, results="markup"}
askMC(
  "For graph (C), which scale corresponds to the pattern-book function?",
  "black",
  "+blue+" = "The pattern-book sinusoid has a positive-going zero crossing at $x=0$. That is the blue scale.", 
  "neither", 
  "both" = "It cannot be both. There is only one pattern-book function. When you scale the input, it becomes a \"basic modeling function\".",
  random_answer_order=FALSE
)
```
