---
id: "scale-input-2"
author: "Daniel Kaplan"
global-id: "BLECL"
---

```{r include=FALSE}
library(etude2)
library(mosaic)
library(mosaicCalc)
```

Find the straight-line function that will give the value on the black scale for each point $x$ on the blue scale. The function will take the blue-scale reading as input and produce the black-scale reading as output, that is:
$$\text{black}(x) \equiv a (x - x_0)$$

```{r echo=FALSE}
scale_shift(-2, 2, 3, 0)%>% 
  gf_labs(title="Graph (A)")
```




```{r sc-in-2-A, echo=FALSE, results="markup"}
askMC(
  "For Graph A, which function maps blue $x$ to the value on the black scale?",
  "+$\text{black}(\text{blue}) \\equiv \\frac{1}{3} x$+",
  "$\text{black}(\text{blue}) \\equiv 3\\, x$" = "You're going the wrong way, from black to blue.",
  "$\text{black}(\text{blue}) \\equiv x + 3$" = "Is there a horiztontal shift?",
  "$\text{black}(\text{blue}) \\equiv x - 3$" = "Is there a horizontal shift?"
)
```


```{r echo=FALSE}
scale_shift(-3, 3, -1.5, 0) %>%
  gf_labs(title = "Graph (B)")
```

```{r sc-in-2-B, echo=FALSE, results="markup"}
askMC(
  "For Graph B, which function maps blue $x$ to the value on the black scale?",
  "+$\text{black}(\text{blue}) \\equiv -\\frac{2}{3}\\,x$+",
  "$\text{black}(\text{blue}) \\equiv \\frac{3}{2} x$" = "Look carefully at the $\\pm$ signs on the scales.",
  "$\text{black}(\text{blue}) \\equiv \\frac{2}{3} x$" = "Look carefully at the $\\pm$ signs on the scales.",
  "$\text{black}(\text{blue}) \\equiv -\\frac{3}{2}x$" = "You're going the wrong way, from black to blue."
)
```

```{r echo=FALSE}
scale_shift(-3, 3, 2, -1) %>% 
  gf_labs(title="Graph (C)")
```


```{r sc-in-2-C, echo=FALSE, results="markup"}
askMC(
  "For Graph C, which function maps blue $x$ to the value on the black scale?",
  "+$\text{black}(\text{blue}) \\equiv \\frac{1}{2}(x - 2)$+" = "Good. An interval of length 4 on the blue scale (say, from 2 to 6) becomes an interval of length 2 on the black scale. So you know that blue to black involves dividing by 2.",
  "$\text{black}(\text{blue}) \\equiv 3\\, x$" = "Is there a shift",
  "$\text{black}(\text{blue}) \\equiv 2\\,x$" = "Is there a shift?",
  "$\text{black}(\text{blue}) \\equiv 2\\,(x + 2)$" = "You're going the wrong way, from black to blue."
)
```

```{r echo=FALSE}
scale_shift(-3, 3, 1.5, 2) %>% 
  gf_labs(title="Graph (D)")
```


```{r sc-in-2-D, echo=FALSE, results="markup"}
askMC(
  "For Graph D, which function maps blue $x$ to the value on the black scale?",
  "+$\text{black}(\text{blue}) \\equiv \\frac{2}{3} (x + 3)$+",
  "$\text{black}(\text{blue}) \\equiv \\frac{3}{2} (x - 3)$",
  "$\text{black}(\text{blue}) \\equiv \\frac{3}{2} (x+1)$",
  "$\text{black}(\text{blue}) \\equiv \frac{3}{2}(x - 2)$" = "You're going the wrong way, from black to blue."
)
```
