---
title: "Sigmoid in the bath"
author: "Daniel Kaplan"
---

```{r include=FALSE}

library(mosaic)
library(mosaicCalc)
```


Have in mind a gaussian function and a sigmoid function that form a corresponding pair.

```{r echo=FALSE, out.width  = "50%", fig.align = "center"}
slice_plot(dnorm(t, mean = 3, sd=1) ~ t,  bounds(t = c(0,10))) %>%
  slice_plot(pnorm(t,  mean =3, sd = 1) ~ t) %>%
  gf_labs(x = "Time (minutes)")
```


```{r daily-digital-08-QA11, echo=FALSE, results="markup"}
askMC(
  prompt = "Which of these stories is consistent with the relationship between a gaussian and its corresponding sigmoid?",

    "The gaussian is the amount of water in a bathtub while the sigmoid is the time you spend in the bath." = "",
    "The gaussian is the amount of water in the bathtub while the sigmoid is the rate at which water flows from the tap." = "You turn the tap on and off after a while. That is not what the sigmoid looks like.",
    "+The gaussian is the rate at which water flows from the tap and the sigmoid is the amount of water in the bathtub.+" = "",
    "The gaussian indicates the amount the drain is open and the sigmoid is the amount of water in the bathtub." = "Shouldn't the amount of water go down when the drain is open?",
  inline = FALSE
)
```

