---
id: "slope-web-1"
author: "Daniel Kaplan"
---

```{r include=FALSE}
library(etude2)
library(mosaic)
library(mosaicCalc)
```


There is a web of connections between the pattern-book functions and their slopes. 

```{r slope-sin, echo=FALSE, results="markup"}
askMC(
  "1. Which pattern-book function has a slope function that is simply a input-shifted version of itself? (For small enough $h$.)",
  "exponential",
  "+sinusoid+",
  "logarithm",
  "power-law $x^{-1}$",
  random_answer_order = FALSE
)
```

```{r slope-exp, echo=FALSE, results="markup"}
askMC(
  "2. Which pattern-book function has a slope function that is identical to itself? (For small enough $h$.)",
  "+exponential+",
  "sinusoid",
  "logarithm",
  "power-law $x^{-1}$",
  random_answer_order = FALSE
)
```

```{r slope-log, echo=FALSE, results="markup"}
askMC(
  "3. Which pattern-book function has a slope function that is another pattern-book function? (Hint: The other function is also listed among the choices.)",
  "exponential",
  "sinusoid",
  "+logarithm+",
  "power-law $x^{-1}$",
  random_answer_order = FALSE
)
```

