---
id: "snake-leave-candy"
created: "Thu Jul 29 16:18:10 2021"
global_id: "aNEcW1"
---

Newton's law of universal gravitation---also known as the inverse square law---is generally written $$F = G \frac{m_1\ m_2}{r^2} .$$
$m_1$ and $m_2$ are the masses of the two objects (say, Earth and Sun). $r$ is the distance between the two objects (about 150,000,000 km). $F$ is the gravitational force and $G$ is a fixed quantity called the "gravitational constant."

Of course, you already know the dimension of force, mass, and distance. 

```{r slc-7-1, echo=FALSE, results="markup"}
askMC(
  "What is the dimension of the gravitational constant, $G$?",
  "+$L^3\\ M^{-1}\\ T^{-2}$+",
  "$L^2\\ M^{-2}$" = "Remember, $G m_1 m_2 / r^2$ has to have the same dimensions as force.",
  "$L^2\\ M^{2}\\ T^{-2}$" = "Check your signs!",
  "$L^2\\ M^{-2}\\ T^{-2}$"
)
```

```{r slc-7-2, echo=FALSE, results="markup"}
askMC(
  "The quantity $G$ is $6.674 \\times 10^{−11}$ when $L$ is in meters, $M$ is in kilograms, and $T$ in seconds. What is the gravitational force between Earth (mass $6 \\times 10^{24}$ kg) and Sun (mass $2\\times 10^{30}$ kg) ?",
  "+$3.6 \\times 10^{28}$ Newtons+",
  "$3.6 \\times 10^{31}$ meters",
  "$3.6 \\times 10^{28}$ meters per second-squared",
  "$3.6 \\times 10^{31}$ meter seconds per kg"
)
```
