---
id: "walnut-run-dish"
created: "Tue Apr  5 13:42:28 2022"
global_id: "amCjZG"
skill: "input & output scaling"
---

::: {.underconstruction}
Turn this into a guided problem to find the input and output scaling that turns $\sin()$ into the day-length versus day-of-year.
:::



To illustrate, suppose that $f(x)$ is one of the pattern-book function, say, $\sin()$. The input to pattern-book $\sin()$ must always be a pure number and the output will always be a pure number. Consider a phenomenon that shows oscillatory behavior, for instance the length of daylight (in hours) as a function of the day-of-the-year (1 to 365, in days). The output of the modeling function is a quantity in hours, the input is a quantity in days. Neither this input nor the output are pure numbers. 

To use the pattern $\sin()$ as a basis for modeling, we replace the input name $x$ with a straight-line function: $x(t) = a t + b$. This gives us the function $$\sin(a t + b)$$ where $a$ and $b$ are parameters. If $t$ is to be the day-of-year in units of days, then the parameter $a$ will have units "per day," so that $a t$ will be a pure number.

The output of the function $\sin(a t + b)$ will be a pure number. to translate this into a quantity such as length of daylight, we apply another straight-line function, for instance $$\text{daylight}(y) \equiv A y + B$$ where $y$ stands for the output from $\sin(a t + b)$ for any input $t$. Putting this all together, we have the function
$$\text{daylight}(t) = A \sin(a t + b) + B\ ,$$ a function with four parameters: $a$, $b$, $A$, and $B$.

For example, for a location at latitude 40$^\circ$N, the length of daylight is approximately $$\text{daylight}_{40^\circ}(t) = 2.75 \sin(0.0173 t - 0.155) + 12\ ,$$ where $t$ is in days (January 1 is $t=1$ and December 31 is $t=365$), 
2.75 and 12 are in hours, 0.0173 is "per day" and 0.155 is a pure number.

Keep in mind that the straight-line function is often written 
$\line(t) = a\left(t-t_0\right)$. 
In this form, the daylight() function would be written
$$\text{daylight}_{40^\circ}(t) = 2.75 \sin(0.0173 \left(t - 9\right) + 12\ ,$$ where the 9 is in days.
