---
id: "bee-throw-mug"
created: "Mon Aug 30 12:14:17 2021"
global_id: "k8H2vs"
exercise_format: "On paper"
---

In this exercise, you're going to approximate a sinusoid $sin(x)$ with polynomials of order 3, 5, and 7. The approximation should go exactly through the coordinate pair $(x_0=0, y=0)$ shown as a bright dot on the graph. Notice that the approximation is exacty tangent to the sinusoid at $x_0 = 0$: the approximating line goes straight through the dot and continues pretty much through the center of the thick line marking the sinusoid, until the sinusoid curves away from the straight line.  

```{r echo=FALSE}
slice_plot(sin(x) ~ x, domain(x = c(-6,6)), size = 3, alpha = 0.15) %>%
  gf_point(0 ~ 0, color="magenta", size=3) %>%
  slice_plot(x ~ x, domain(x=c(-2,2)), color="magenta") 
```
0. Draw your own graph of a sinusoid so that you can sketch on top of it the polynomial approximations you will design.


1. Start with **sketching** in a third-order polynomial that approximates the sinusoid near $x_0=0$.  The general formula for a third order polynomial is $$\text{third}(x) \equiv \overbrace{\underbrace{b_0 + b_1 x^1}_\text{first-order polynomial} + b_2 x^2}^\text{second-order polynomial} + b_3 x^3$$
To turn the first-order approximation into a third-order approximation algebraically, you would need to choose the coefficients $b_2$ and $b_3$. You want to choose the best possible $b_2$ and $b_3$ to stay close to the sinusoid. Of course, you could take the lazy person's approach and choose $b_2 = b_3 = 0$. If you did that, you would have the first-order polynomial. Here's the important point: the best third-order polynomial will not be any worse than the first-order polynomial, but it can be better!

    Remember what you know about the shape of third-order polynomials:
    
    a. One tail will go up, the other down.
    b. There can be both an argmin and an argmax.
    
2. Repeat (1), sketching out a 5th-order polynomial. Again, one tail will go up and the other down. But now there can be two argmaxes and two argmins that alternate along the $x$ axis: min, max, min, max.  

3. One more time, sketching now a 7th-order polynomial. Just like the first-, third-, and fifth-order polynomial, for the 7th one tail will go up and the other down. There can be as many as three argmaxes and three argmins. They will alternate: between any two argmaxes, there will be one argmin.
