---
id: "boy-hide-gloves"
created: "Tue May 24 08:43:48 2022"
global_id: "ZQ7pWO"
skill: "Gi-Cal-404-k"
---


The graphic shows several gaussian functions along with a single sigmoid function.

```{r  echo=FALSE}
slice_plot(pnorm(x, mean = 1, sd = 3) ~ x, domain(x=c(-10,10)),
           label_text = "sigmoid", color = "dodgerblue") %>%
  slice_plot(7.5*dnorm(x, mean = 1,  sd = 3) ~ x, label_text = "gaussian A",
             label_x  = 0.6) %>%
  slice_plot(dnorm(x, mean = 1, sd = 3) ~ x,
             label_text = "gaussian B", label_x = 0.65) %>%
  slice_plot(dnorm(x, mean = 0, sd = 0.5) ~ x,
             label_text = "gaussian C", label_x = 0.475, npts = 200) %>%
  slice_plot(6*dnorm(x, mean = -1, sd = 4) ~ x,
             label_text = "gaussian D", label_x = 0.3) %>%
  gf_labs(title = "Graph (D)")
```

```{r daily-digital-08-QA10, echo=FALSE}
askMC(
  prompt = "Which gaussian corresponds to  the sigmoid?",
    "A" = "The value of the gaussian output is much larger than the slope of the sigmoid.",
    "+B+" = "Right! The gaussian is centered on the steepest part of the sigmoid and falls to zero where the sigmoid levels out.",
    "C" = "The gaussian is too narrow.",
    "D" = "The gaussian is too broad and shifted to the left.",
  random_answer_order = FALSE
)
```

