---
id: "buck-draw-bed"
created: "Fri Aug 13 18:04:34 2021"
global_id: "QFzIOl"
---

In function compositions of the form $f\left(\strut g(x)\right)$, the function $f()$ is called the ***exterior function*** and $g()$ is called the ***interior function.***

```{r bdb932-1, echo=FALSE, results="markup"}
askMC(
  r"(In $\cos(\ln(x))$ which is the **interior** function?)",
  r"(+$\ln()$+)",
  r"($\cos()$)" = "This is the exterior function.", 
  r"($\sin()$)" = "Sine has nothing to do with it!",
  "None of the above", 
  "It is not a function composition",
  random_answer_order = FALSE
)
```

```{r bdb932-2, echo=FALSE, results="markup"}
askMC(
  r"(In $1/\sin(x)$ which is the **exterior** function?)",
  r"(+$\recip()$+)",
  r"($\cos()$)", 
  r"($\sin()$)" = "This is the interior function.", 
  "None of the above", 
  "It is not a function composition",
  random_answer_order = FALSE
)
```


```{r bdb932-3, echo=FALSE, results="markup"}
askMC(
  r"(In $\sin\left(\frac{2 \pi}{P} (t-t_0)\right)$ which is the **exterior** function?)",
  r"($t-t_0$)",
  r"($\frac{2\pi}{P}$)", 
  r"($\frac{2\pi}{P} t$)", 
  r"($\frac{2\pi}{P} (t-t_0)$)", 
  r"(+$\sin()$+)", 
  "None of the above", 
  "It is not a function composition",
  random_answer_order = FALSE
)
```


```{r bdb932-4, echo=FALSE, results="markup"}
askMC(
  "In $\\sin\\left(2 \\pi (t-t_0)/P\\right)$ which is the **interior** function?",
  "$t-t_0$" = "That's  part of it.",
  "$2\\pi /P$" = "That's  part of it.", 
  "$2\\pi t /P t$" = "That's  part of it.", 
  "+$2\\pi (t-t_0)/P$+", 
  "$\\sin()$" = "This is the interior function.", 
  "None of the above", 
  "It is not a function composition.",
  random_answer_order = FALSE
)
```

```{r bdb932-5, echo=FALSE, results="markup"}
askMC(
  r"(In $\sin(x)\dnorm(x^2)$, which is the **interior** function?)",
  r"($x^2$)",
  r"($x$)",
  r"($\dnorm(x^2)$)",
  "None of the above",
  "+It is not a function composition.+",
  random_answer_order = FALSE
)
```

