---
id: "camel-sing-futon"
created: "Wed May 25 10:42:29 2022"
global_id: "bbti5S"
skill: "Gi-Theory-605"
---

The Taylor polynomial $$T(x)\equiv-9-6(x-5)-9(x-5)^2$$ is used to approximate the function $f(x)$.

```{r csfj-1, echo=FALSE, results="markup"}
askMC(
  prompt = "At what value $x_0$ is the Taylor polynomial centered?",
  r"($x_0=9$)",
  r"($x_0=6$)",
  r"(+$x_0=5$+)",
  r"($x_0=0$)",
  random_answer_order=FALSE
)
```


```{r csfj-2, echo=FALSE, results="markup"}
askMC(
  prompt = "What do we know about $\\partial_{x} (x_0)$?",
  r"(+$\partial_{x} (x_0)$ is negative+)",
  r"($\partial_{x} (x_0)$ is zero)",
  r"($\partial_{x} (x_0)$ is positive)",
  r"(It cannot be determined from the polynomial)",
random_answer_order=FALSE
)
```

```{r csfj-3, echo=FALSE, results="markup"}
askMC(
  prompt = "What is the value of $\\partial_{xx} (x_0)$?",
  r"($\partial_{xx} (x_0)$ is negative, but we cannot determine its magnitude)",
  r"($\partial_{xx} (x_0)=-9$)",
  r"($\partial_{xx} (x_0)=-4.5$)",
  r"(+$\partial_{xx} (x_0)=-18$+)",
  random_answer_order=FALSE
)
```