---
id: "child-hide-lamp"
created: "Mon Sep 20 13:12:35 2021"
global_id: "RbuhMy"
---

```{r echo=FALSE, warning=FALSE}
funs <- list()
plots <- list()
dom <- bounds(x=-4:4, y=-4:4)
for (k in 1:6) funs[[k]] <- rfun(~ x + y, seed = 600 + k, n = 8)
for (k in 1:6) {
  j <- c(1,2,4,4,6,6)[k]
  plots[[k]] <- contour_plot(funs[[k]](x, y)~ x + y, dom) %>%
    gradient_plot(funs[[j]](x, y) ~ x + y, dom, npts=12, alpha=1, 
                  color="magenta") %>%
    gf_labs(title=paste("Figure", LETTERS[k])) %>%
    gf_refine(coord_fixed())
}
```

Each of the figures below shows a contour plot and a gradient field. For some of the figures, the contour plot and the gradient field show the same function, for others they do not. Your task is to identify whether the contour plot and the gradient field are of the same or different functions.


```{r echo=FALSE}
plots[[1]]
```

```{r chl9-1, echo=FALSE, results="markup"}
askMC(
  "For Figure A, do the contour plot and the gradient field show the same function?",
  "+Yes+",
  "No",
  random_answer_order=FALSE
)
```

```{r echo=FALSE}
plots[[2]]
```

```{r chl9-2, echo=FALSE, results="markup"}
askMC(
  "For Figure B, do the contour plot and the gradient field show the same function?",
  "+Yes+",
  "No",
  random_answer_order=FALSE
)
```

```{r echo=FALSE}
plots[[3]]
```

```{r chl9-3, echo=FALSE, results="markup"}
askMC(
  "For Figure C, do the contour plot and the gradient field show the same function?",
  "Yes",
  "+No+",
  random_answer_order=FALSE
)
```

```{r echo=FALSE}
plots[[4]]
```

```{r chl9-4, echo=FALSE, results="markup"}
askMC(
  "For Figure D, do the contour plot and the gradient field show the same function?",
  "+Yes+",
  "No",
  random_answer_order=FALSE
)
```

```{r echo=FALSE}
plots[[5]]
```

```{r chl9-5, echo=FALSE, results="markup"}
askMC(
  "For Figure E, do the contour plot and the gradient field show the same function?",
  "Yes",
  "+No+",
  random_answer_order=FALSE
)
```

```{r echo=FALSE}
plots[[6]]
```

```{r chl9-6, echo=FALSE, results="markup"}
askMC(
  "For Figure F, do the contour plot and the gradient field show the same function?",
  "+Yes+",
  "No",
  random_answer_order=FALSE
)
```


