---
id: "child-iron-laundry"
created: "Tue Aug 17 10:37:30 2021"
global_id: "0zyL02"
---

The simple model of the distance travelled by a tennis ball after launch from a slingshot is $$\text{hdist}(v_0, \theta) = 2 v_0^2 \cos(\theta)\sin(\theta) / g$$ where $\theta$ is the launch angle, measured from the horizontal, $v_0$ is the initial velocity, and $g$ is the acceleration due to gravity. 

```{r cil3-1, echo=FALSE, results="markup"}
askMC(
  "What is the dimension of $v_0$?",
  "L T",
  "+L / T+" = "As in miles/hour or meters/second.",
  "L / T$^2$",
  "L$^2$ / T$^2$"
)
```

```{r cil3-2, echo=FALSE, results="markup"}
askMC(
  "What is the dimension of $g$?",
  "M L" = "",
  "M L / T",
  "+L / T$^2$+",
  "M L / T$^2$" = "This is *force*, not acceleration.",
  random_answer_order = FALSE
)
```

```{r cil3-3, echo=FALSE, results="markup"}
askMC(
  "What is the dimension of $\\theta$?",
  "L",
  "L^2",
  "T/L",
  "+It's dimensionless+" = "An angle is measured by *distance* along the circumference of a circle divided by the radius of the circle, so L/L. The L dimensions cancel out.",
  random_answer_order = FALSE
)
```

```{r cil3-4, echo=FALSE, results="markup"}
askMC(
  "What is the dimension of $\\sin(\\theta$)?",
  "L",
  "L^2",
  "T/L",
  "+It's dimensionless+" = "The output of a sinusoid is always dimensionless. You would have to multiply by a dimensionful amplitude ($A \\sin(\\theta)$) to attach a dimension to the output.",
  random_answer_order = FALSE
)
```

```{r cil3-5, echo=FALSE, results="markup"}
askMC(
  "What is the dimension of $2 v_0^2 \\cos(\\theta)\\sin(\\theta) / g$?",
  "+L+",
  "L^2",
  "L/T",
  "L/T$^2$"
)
```

```{r cil3-6, echo=FALSE, results="markup"}
askMC(
  "Suppose the initial velocity of the ball is $v_0 = 10$ meters/second. Since we're on the surface of Earth, $g=9.8$ meters/second-squared. At the optimal launch angle $\\theta$, how far does the model predict the ball will travel?",
  "+10 meters+",
  "25 meters",
  "50 meters",
  "75 meters",
  random_answer_order = FALSE
)
```
