---
title: "Concavity"
author: "Daniel Kaplan"
---

```{r include=FALSE, context="setup"}

library(mosaic)
library(mosaicCalc)
```

The graph shows three different functions labeled (A), (B), and (C).

```{r echo=FALSE, fig.show='hold', warning=FALSE}
#| label: daily-digital-02-C1
#| out-width: "32%"
pA <- slice_plot(log(x) ~ x, bounds(x=c(-1, 4))) %>%
  gf_labs(title="(A)")
pB <- slice_plot(exp(x/3) ~ x,  bounds(x=c(-1, 4)))  %>%
  gf_labs(title="(B)")
pC <-slice_plot(3 - 2*x ~ x, bounds(x=c(-1, 4))) %>%
  gf_labs(title="(C)")
gridExtra::grid.arrange(pA, pB, pC, ncol=3)
```

```{r daily-digital-02-QA2, echo=FALSE}
askMC(
  prompt = "Function (A) is ",
    "+concave down+" = "",
    "non-concave" = "",
    "concave up" = "",
  random_answer_order = FALSE
)
```

```{r daily-digital-02-QA3, echo=FALSE}
askMC(
  prompt = "Function  (B) is ",
    "concave down" = "",
    "non-concave" = "",
    "+concave up+" = "",
  random_answer_order = FALSE
)
```

```{r daily-digital-02-QA4, echo=FALSE}
askMC(
  prompt = "Function  (C) is ",
    "concave down" = "",
    "+non-concave+" = "",
    "concave up" = "",
  random_answer_order = FALSE
)
```

```{r daily-digital-02-QA5, echo=FALSE}
askMC(
  prompt = "The **negative** of function  (A) is ",
    "concave down" = "",
    "non-concave" = "",
    "+concave up+" = "",
  random_answer_order = FALSE
)
```

The graph shows a function $\text{wave}(t) \equiv \sin(2 \pi t/4)$ and labels four input values  $t$. 


```{r daily-digital-02-C2, echo=FALSE}
points <- data.frame(x = c(0, 1, 2.5, 3.5),
                     y = 0,
                     name = c("A", "B", "C", "D"))
slice_plot(sin(2*pi*t/4) ~ t, bounds(t = c(-2, 8))) %>%
  gf_point(y ~ x, data = points) %>%
  gf_text( y ~ x, data = points, label = ~ name,vjust = 1.5, color="magenta")
```


```{r daily-digital-02-QA6, echo=FALSE}
askMC(
  prompt = "For what values of the input $t$ is the function concave up?",
  choices = c(
    "$t = A$ and $t=D$",
    "$t = A$ and $t=C$",
    "+$t = C$ and $t = D$+",
    "none of the above"
  ),
  random_answer_order = FALSE
)
```

```{r daily-digital-02-QA8, echo=FALSE}
askMC(
  prompt = "For what values of the input $t$ is the function non-concave?",
    "+$t = A$+",
    "$t=B$",
    "$t=C$",
    "none of the above",  
  random_answer_order = FALSE
)
```

```{r daily-digital-02-QA9, echo=FALSE}
askMC(
  prompt = "Where is the function steepest?",
    "+$t = A$+",
    "$t=B$",
    "$t=C$",
    "$t=D$",
  random_answer_order = FALSE
)
```
