---
id: "dnorm"
author: "Daniel Kaplan"
global-id: "QIELS"
---

Compare the functions $f_1 \equiv \dnorm(x, mn, sd)$ and $f_2 \equiv \dnorm\left(\left[x-mn\right]/sd\right)$ by plotting them out in a `r sandbox_link()`.

In order to construct the plot, you'll have to pick specific values for $mn$ and $sd$. Make sure that you use the same $sd$ and $mn$ when constructing $f_1()$ and $f_2()$. For instance:

```{r eval=FALSE}
f1 <- makeFun(dnorm(x, mn, sd) ~ x, mn=2, sd=3)
f2 <- makeFun(dnorm( (x-mn) / sd) ~ x, mn=2, sd=3)
```

```{r dnorm8-1, echo=FALSE, results="markup"}
askMC(
  "When $\\text{sd} = 1$, are the two functions the same?",
  "+Yes+",
  "Yes, but only if $\\text{mn}=1$",
  "Yes, but only if $\\text{mn}=0$",
  "No", 
  random_answer_order = FALSE
)
```

```{r dnorm8-2, echo=FALSE, results="markup"}
askMC(
  "When $\\text{sd} \\neq 1$, for any given mean, the two functions are not the same. What's the relationship between $f_1(x)$ and $f_2(x)$?",
  "+$f_2(x) = sd\\, f_1(x)$+",
  "$f_1(x) = sd\\, f_2(x)$",
  "$f_1(x) = sd^2 f_2(x)$",
  "$f_2(x) = sd^2 f_1(x)$",
  random_answer_order = FALSE
)
```
