---
id: "dolphin-mean-linen"
created: "Fri Sep  3 17:14:25 2021"
global_id: "cQT2v6"
---

At $x=0$, the value of $x \ln(x)$ is indeterminate, having the form $0 \cdot \infty$.

Using a sandbox, plot out $x \ln(x)$ over the domain $0 < x < \frac{1}{2}$. 

```{r zoz1-1, echo=FALSE, results="markup"}
askMC(
  "From the graph, determine $\\lim_{x\\rightarrow 0} x \\ln(x()$. Choose the correct answer.",
  -0.2, "+0+", 0.1, 0.5, "not well behaved", 
  random_answer_order = FALSE
)
```


Use l'Hopital's rule to confirm that $\lim_{x\rightarrow 0} x \ln(x()$ exists. Here, the rule has the form:

$$\lim_{x\rightarrow 0} x \cdot \ln(x) = [\lim_{x\rightarrow 0} \partial_x x] \cdot
 [\lim_{x\rightarrow 0} \partial_x \ln(x)]$$

```{r zoz1-2, echo=FALSE, results="markup"}
askMC(
  "Does the application of l'Hopital's rule confirm the result from graphing the function?",
  "+Yes+", 
  "No" = "Aren't you getting $\\frac{1}{1/x} = x$ when you carry out the differentiation involved?",
  random_answer_order = FALSE)
```
