

```{r echo=FALSE}
#| label: fig-rev2-09
#| fig-cap: "."
#| out-width: "60%"
slice_plot(5*pnorm(t, 0, 2) ~ t, bounds(t=c(-5,5))) %>%
  gf_refine(scale_x_continuous(breaks = -5:5),
            scale_y_continuous(breaks = 0:5))
```

```{r drill-Quiz-2-28, echo=FALSE, results='markup'}
askMC(
  prompt = r"(What is the average rate of change of the function in @fig-rev2-09 on the interval $-5 < t < 5$? (Choose the closest answer.) )",
r"(+0.5+)" = r"(Rise is 5, run is 10.)",
  r"(1)" = r"( )",
  r"(1.5)" = r"( )",
  r"(2)" = r"( )",
  random_answer_order=FALSE
)
```



```{r drill-Quiz-2-29, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Consider the average rate of change of the function in @fig-rev2-09 on the interval $-2 < t < 2$. Which of these statements best describes that average rate of change. )",
r"(very close to 1/2)" = r"( )",
  r"(+slightly less than 1+)" = r"( )",
  r"(slightly greater than 1)" = r"( )",
  r"(very close to 2)" = r"( )",
  random_answer_order=FALSE
)
```

