```{r drill-Pattern-book-derivs-1, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Which pattern-book function is the **derivative** of the sigmoid function pnorm()? That is, $${\large \text{pnorm}(x)}  \underset{\scriptsize \text{anti-diff}}{{\stackrel{\text{diff}}{\ \ \ \ {\Huge\rightleftharpoons}\ \ \ }}}  {\LARGE ?}$$  )",
r"(Reciprocal $1/x$)" = r"(The anti-derivative of the reciprocal is the natural logarithm.)",
  r"(Exponential $e^x$)" = r"(The anti-derivative of the exponential is the exponential.)",
  r"(Sinusoid $\sin(x)$)" = r"(The anti-derivative of a sinusoid is a shifted sinusoid.)",
  r"(+Gaussian dnorm(x)+)" = r"(The anti-derivative of the gaussian is the sigmoid.)",
  r"(Constant $1$)" = r"(The anti-derivative of the constant function is the identity function $x$.)",
  random_answer_order=TRUE
)
```



```{r drill-Pattern-book-derivs-2, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Which pattern-book function is the **anti-derivative** of the reciprocal $1/x$? That is, $${\LARGE ?}  \underset{\scriptsize \text{anti-diff}}{{\stackrel{\text{diff}}{\ \ \ \ {\Huge\rightleftharpoons}\ \ \ }}}  {\large \frac{1}{x}}$$<br> <br> NOTE: Differentiation produces a "child" function from a "parent" function. The child is the derivative of the parent. Putting the relationship the other way, the parent is the **anti-derivative** of the child. "Derivative" and "anti-derivative" are two ways of looking at the same relationship between a pair of functions. So, if $f(x)$ is the derivative of $F(x)$, then $F(x)$ is the anti-derivative of $f(x)$. )",
r"(Reciprocal $1/x$)" = r"(The derivative of the reciprocal is $- x^{-2}$.)",
  r"(+Logarithm $\ln(x)$+)" = r"(The derivative of the logarithm is the reciprocal $1/x$.)",
  r"(Sinusoid $\sin(x)$)" = r"(The derivative of a sinusoid is a shifted sinusoid.)",
  r"(Gaussian $\text{dnorm(x)}$)" = r"(The derivative of the gaussian is $- x \text{dnorm}(x)$, which is NOT one of our pattern book functions..)",
  r"(Constant $1$)" = r"(The derivative of the constant function is the zero function.)",
  random_answer_order=TRUE
)
```



```{r drill-Pattern-book-derivs-3, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Which pattern-book function is the **anti-derivative** of the gaussian $\text{dnorm()}$? That is, $${\LARGE ?}  \underset{\scriptsize \text{anti-diff}}{{\stackrel{\text{diff}}{\ \ \ \ {\Huge\rightleftharpoons}\ \ \ }}}  {\large \text{dnorm}(x)}$$<br> <br> NOTE: Differentiation produces a "child" function from a "parent" function. The child is the derivative of the parent. Putting the relationship the other way, the parent is the **anti-derivative** of the child. "Derivative" and "anti-derivative" are two ways of looking at the same relationship between a pair of functions. So, if $f(x)$ is the derivative of $F(x)$, then $F(x)$ is the anti-derivative of $f(x)$. In other words: $${\large F(x)}  \underset{\scriptsize \text{anti-diff}}{{\stackrel{\text{diff}}{\ \ \ \ {\Huge\rightleftharpoons}\ \ \ }}}  {\Large f(x)}$$ )",
r"(Reciprocal $1/x$)" = r"(The derivative of the reciprocal is $- x^{-2}$.)",
  r"(Logarithm $\ln(x)$)" = r"(The derivative of the logarithm is the reciprocal $1/x$.)",
  r"(+Sigmoid $\text{pnorm(x)}$+)" = r"(The derivative of the sigmoid is a gaussian.)",
  r"(Gaussian $\text{dnorm(x)}$)" = r"(The derivative of the gaussian is $- x \text{dnorm}(x)$, which is NOT one of our pattern book functions..)",
  r"(Constant $1$)" = r"(The derivative of the constant function is the zero function.)",
  random_answer_order=TRUE
)
```



```{r drill-Pattern-book-derivs-4, echo=FALSE, results='markup'}
askMC(
  prompt = r"(What is the **derivative** of the power-law function $x^p$?i That is, $${\Large x^p}  \underset{\scriptsize \text{anti-diff}}{{\stackrel{\text{diff}}{\ \ \ \ {\Huge\rightleftharpoons}\ \ \ }}}  {\LARGE ?}$$   )",
r"($p\, x^p$)" = r"( )",
  r"($(p-1)\, x^p$)" = r"( )",
  r"(+$p\, x^{p-1}$+)" = r"( )",
  r"($(p-1)\, x^{p-1}$)" = r"( )",
  r"($\frac{1}{p} x^{p+1}$)" = r"( )",
  random_answer_order=TRUE
)
```



```{r drill-Pattern-book-derivs-5, echo=FALSE, results='markup'}
askMC(
  prompt = r"(There are two pattern-book functions whose **second** derivative is proportional to the function itself. Which are they?  )",
r"(+Exponential and sinusoid+)" = r"( )",
  r"(Exponential and sigmoid)" = r"(The second derivative of the sigmoid is $-x\, \text{dnorm}(x)$.)",
  r"(Exponential and logarithm)" = r"(The second derivative of the logarithm is $-x^{-2}$)",
  r"(Sinusoid and gaussian)" = r"(The second derivative of the gaussian is far from obvious at first glance: $(x^2 - 1) \text{dnorm}(x)$. Don't freak out; you aren't expected to memorize this one!)",
  random_answer_order=TRUE
)
```



```{r drill-Pattern-book-derivs-6, echo=FALSE, results='markup'}
askMC(
  prompt = r"(What is the **derivative** of $t^5$ with respect to $t$? That is, $${\Large t^5}  \underset{\scriptsize \text{anti-diff}}{{\stackrel{\text{diff}}{\ \ \ \ {\Huge\rightleftharpoons}\ \ \ }}}  {\Large ?}$$)",
r"(+$5 t^4$+)" = r"( )",
  r"($4 t^5$)" = r"(Remember, $\partial_t t^p = p\, t^{p-1}$)",
  r"($\frac{1}{5} t^4$)" = r"( )",
  r"($\frac{1}{4} t^5$)" = r"( )",
  random_answer_order=TRUE
)
```



```{r drill-Pattern-book-derivs-7, echo=FALSE, results='markup'}
askMC(
  prompt = r"(What is $\partial_x x^2$?  )",
r"($2 x$)" = r"(As per the power-law rule for differentiation.)",
  r"(+$2$+)" = r"( )",
  r"($2 x^2$)" = r"( )",
  r"($2/x$)" = r"( )",
  random_answer_order=TRUE
)
```



```{r drill-Pattern-book-derivs-8, echo=FALSE, results='markup'}
askMC(
  prompt = r"(What is $\partial_t \sin(x)$   )",
r"($\cos(x)$)" = r"(Tricked you! We asked about the partial with respect to $t$, not the partial with respect to $x$. There is no $t$ in $\sin(x)$. So far as $t$ is concerned, $\sin(x)$ is a constant.)",
  r"(+0+)" = r"( )",
  r"($-\sin(x)$)" = r"(Tricked you! We asked about the partial with respect to $t$, not the partial with respect to $x$. There is no $t$ in $\sin(x)$. So far as $t$ is concerned, $\sin(x)$ is a constant.)",
  r"($-\cos(x)$)" = r"(Tricked you! We asked about the partial with respect to $t$, not the partial with respect to $x$. There is no $t$ in $\sin(x)$. So far as $t$ is concerned, $\sin(x)$ is a constant.)",
  random_answer_order=TRUE
)
```



```{r drill-Pattern-book-derivs-9, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Suppose you know only this one fact about $f(x)$, that $\partial_{xx}\, f(7.3) = 1.6$. Which of these statements must be true?  )",
  r"($f(x)$ is increasing at $x=7.3$.)" = r"(The first derivative $\partial_x f(x)$ would tell you about whether the function is increasing or decreasing. The second derivative $\partial_{xx} f(x)$ tells you about something else.)",
  r"($f(x)$ is concave up and decreasing at $x=7.3$)" = r"(Second derivatives tell you about concavity, but not about whether the function is increasing or decreasing.)",
  r"(+$f(x)$ is concave up at $x=7.3$+)" = r"(The 2nd derivative tells you **only** about the concavity of a function. It has nothing to say about the value of the slope.)",
  r"($f(x)$ is concave up at $x=7.3$, but eventually it will become concave down.)" = r"(In a graph of a function, the second derivative corresponds to concavity. But knowing only the numerical value for the second derivative at a single input value does not tell you what the function is doing anywhere else.)",
  random_answer_order=TRUE
)
```



```{r drill-Pattern-book-derivs-10, echo=FALSE, results='markup'}
askMC(
  prompt = r"(If $f(x)$ is discontinuous at $x=5$, can it possibly be **smooth** at $x=6$?  )",
r"(+Yes+)" = r"(Discontinuity of a function at one input does not tell you what the function is doing at another input.)",
  r"(No)" = r"(We told you something about $f(x)$ at $x=5$. Just knowing that does not tell you about $f(x)$ at other inputs.)",
  random_answer_order=TRUE
)
```



```{r drill-Pattern-book-derivs-11, echo=FALSE, results='markup'}
askMC(
  prompt = r"(If $g(x)$ is discontinuous at $x=1$, what will be the value of $\partial_x g(x)$ at $x=1$?   )",
r"(Depends on how big the gap is at the discontinuity.)" = r"( )",
  r"(0)" = r"( )",
  r"($1/x$)" = r"( )",
  r"(+The derivative isn't defined at a discontinuity.+)" = r"( )",
  random_answer_order=FALSE
)
```



```{r drill-Pattern-book-derivs-12, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Which of the following is the correct construction for $\partial_t g(t)$?   )",
r"(+$\lim_{h \rightarrow 0} \frac{g(t + h) - g(t)}{h}$+)" = r"( )",
  r"($\lim_{h \rightarrow 0} \frac{g(t + h) - g(t)}{t}$)" = r"(The division should be by $h$, not by $t$.)",
  r"($\lim_{h \rightarrow 0} \frac{g(t) - g(t+h)}{h}$)" = r"(This will be the $- \partial_t g(t)$.)",
  r"($\lim_{x \rightarrow 0} \frac{g(t + h) - g(t)}{h}$)" = r"($x$ has nothing to do with it, so $\lim_{x \rightarrow 0}$ means nothing in this context.)",
  random_answer_order=TRUE
)
```



```{r drill-Pattern-book-derivs-13, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Which of these is a reasonable definition of a derivative?   )",
r"(+A derivative is a function whose value tells, for any input, the instantaneous rate of change of the function from which it was derived.+)" = r"( )",
  r"(A derivative is the slope of a function.)" = r"(For functions that aren't straight lines, it does not mean anything to speak of "the slope" because the slope varies from place to place. Always remember that the derivative of a function is another **function**.)",
  r"(A derivative is a function whose value tells, for any input, the instantaneous change of the function from which it was derived.)" = r"(Not a bad start but a crucial word was left out. It should say, "the instantaneous **rate** of change". "Instantaneous" and "rate" go hand in hand.)",
  random_answer_order=TRUE
)
```



```{r drill-Pattern-book-derivs-14, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Which one of these is **not** the derivative of a pattern-book function?   )",
r"(Reciprocal)" = r"(The reciprocal is the derivative of the logarithm.)",
  r"(Zero)" = r"(Zero is the derivative of the constant function.)",
  r"(One)" = r"(The constant function 1 is the derivative of the identity function $x$.)",
  r"(+Sigmoid+)" = r"(There is some function whose derivative is the sigmoid, but it is not a function that we've discussed and it is not much (or ever!?) used in modeling.)",
  random_answer_order=TRUE
)
```



```{r drill-Pattern-book-derivs-15, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Which of the following shapes of functions is **not** allowed? You are **strongly** advised to try to draw each shape.  )",
r"(Increasing and concave up.)" = r"( )",
  r"(Decreasing and concave up.)" = r"( )",
  r"(Increasing and concave down.)" = r"( )",
  r"(Decreasing and concave down.)" = r"( )",
  r"(None of them are allowed.)" = r"( )",
  r"(+All of them are allowed.+)" = r"(The only restriction on mathematical functions is that for any given input, there can be at most one output.)",
  random_answer_order=FALSE
)
```
