```{r drill-Deriv-rules-1, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Which of the derivative rules should you use to find $$\partial_t e^{t^2}\ ?$$  )",
r"(The constant multiplier rule)" = r"( )",
  r"(The linear combination rule)" = r"( )",
  r"(The product rule)" = r"( )",
  r"(+The chain rule+)" = r"( )",
  r"(No rule needed, it is so basic.)" = r"( )",
  random_answer_order=FALSE
)
```



```{r drill-Deriv-rules-2, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Which of the derivative rules should you use to find $$\partial_t e^{x^2}\ ?$$  )",
r"(The constant multiplier rule)" = r"( )",
  r"(The linear combination rule)" = r"( )",
  r"(The product rule)" = r"( )",
  r"(The chain rule)" = r"(Tricked you! Pay close attention to the subscript in $\partial_t$.)",
  r"(+No rule needed, it is so basic.+)" = r"(There is no dependence on $t$ in the function being differentiated, so the derivative is simply zero.)",
  random_answer_order=FALSE
)
```



```{r drill-Deriv-rules-3, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Which of the derivative rules should you use to find $$\partial_t e^t \sin(t)\ ?$$  )",
r"(The constant multiplier rule)" = r"( )",
  r"(The linear combination rule)" = r"( )",
  r"(+The product rule+)" = r"(The function is the product of $\sin(t)$ and $e^t$.)",
  r"(The chain rule)" = r"( )",
  r"(No rule needed, it is so basic.)" = r"( )",
  random_answer_order=FALSE
)
```



```{r drill-Deriv-rules-4, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Which of the derivative rules should you use to find $$\partial_t e^t \sin(x)\ ?$$  )",
r"(+The constant multiplier rule+)" = r"( )",
  r"(The linear combination rule)" = r"( )",
  r"(The product rule)" = r"(This was a trick. So far as $\partial_t$ is concerned, $\sin(x)$ is a constant.)",
  r"(The chain rule)" = r"( )",
  r"(No rule needed, it is so basic.)" = r"( )",
  random_answer_order=FALSE
)
```



```{r drill-Deriv-rules-5, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Which of the derivative rules should you use to find $$\partial_t \ln(t)\ ?$$  )",
r"(The constant multiplier rule)" = r"( )",
  r"(The linear combination rule)" = r"( )",
  r"(The product rule)" = r"(it is just a pattern book function. You should have these memorized.)",
  r"(The chain rule)" = r"(it is just a pattern book function. You should have these memorized.)",
  r"(+No rule needed, it is so basic.+)" = r"(You've already memorized that $\partial_t \ln(t) = 1/t$.)",
  random_answer_order=FALSE
)
```



```{r drill-Deriv-rules-6, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Which of the derivative rules should you use to find $$\partial_t\, t\, e^{-t}\ ?$$  )",
r"(The constant multiplier rule)" = r"( )",
  r"(The linear combination rule)" = r"( )",
  r"(+The product rule+)" = r"( )",
  r"(The chain rule)" = r"(You could argue that you will need the chain rule, too, to find $\partial_t e^{-t}$. But before you get there, you will need the product rule.)",
  r"(No rule needed, it is so basic.)" = r"( )",
  random_answer_order=FALSE
)
```



```{r drill-Deriv-rules-7, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Which of the derivative rules should you use to find $$\partial_x\ 37 x^5\ ?$$  )",
r"(+The constant multiplier rule+)" = r"(The result will be 37 times $\partial_x x^5$. (Since you've memorized the derivatives of power-law functions, you know $\partial_x x^5 = 5 x^4$.))",
  r"(The linear combination rule)" = r"( )",
  r"(The product rule)" = r"(This is simply multiplying the power-law function $x^5$ by 37. No need for the product rule.)",
  r"(The chain rule)" = r"(There is no function composition here.)",
  r"(No rule needed, it is so basic.)" = r"( )",
  random_answer_order=FALSE
)
```



```{r drill-Deriv-rules-8, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Which of the derivative rules should you use to find $$\partial_x\ 19\ ?$$  )",
r"(The constant multiplier rule)" = r"( )",
  r"(The linear combination rule)" = r"( )",
  r"(The product rule)" = r"(This is simply multiplying the power-law function $x^5$ by 37. No need for the product rule.)",
  r"(The chain rule)" = r"( )",
  r"(+No rule needed, it is so basic.+)" = r"(The derivative of a constant is always zero.)",
  random_answer_order=FALSE
)
```



```{r drill-Deriv-rules-9, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Which of the derivative rules should you use to find $$\partial_x\ 15 x^2 - 3 x + 7 \ln(x)\ ?$$  )",
r"(The constant multiplier rule)" = r"(But there are several functions being combined.)",
  r"(+The linear combination rule+)" = r"(The functions being combined are $x^2$, $x$, and $\ln(x)$, which respectively have derivatives $2x$, 1, and $1/x$.)",
  r"(The product rule)" = r"(No products here.)",
  r"(The chain rule)" = r"(No function composition here.)",
  r"(No rule needed, it is so basic.)" = r"( )",
  random_answer_order=FALSE
)
```



```{r drill-Deriv-rules-10, echo=FALSE, results='markup'}
askMC(
  prompt = r"(What is $\partial_x\ 15 x^2 - 3 x + 7 \ln(x)$?  )",
r"($15 x - 3 + 7/x$)" = r"(The first term should be $2\times 15 x = 30 x$.)",
  r"(+$30 x - 3 + 7/x$+)" = r"( )",
  r"($30 x - 3x + 7/x$)" = r"(Forgot to differentiate the middle term.)",
  r"($30 x - 3 - 7/x$)" = r"(There is no negative sign on the 7.)",
  random_answer_order=TRUE
)
```



```{r drill-Deriv-rules-11, echo=FALSE, results='markup'}
askMC(
  prompt = r"(What is $\partial_t e^k + \ln(e^2) - t$? )",
r"(+-1+)" = r"( )",
  r"(0)" = r"( )",
  r"($e^{k} + 1/e$)" = r"(From the perspective of $\partial_t$, both $e^k$ and $\ln(e^2)$ are constants. the only term that depends on $t$ is the last one, $-t$.)",
  r"($k e^{k} + 2 / e - t$)" = r"( )",
  random_answer_order=TRUE
)
```



```{r drill-Deriv-rules-12, echo=FALSE, results='markup'}
askMC(
  prompt = r"(What is $\partial_{x} \ln(x)/x^2$? (Hint: You can write the function in a simpler way.) )",
r"($-2 x^{-1} \ln(x)$)" = r"( )",
  r"($-2 x^{-3} \ln(x)$)" = r"( )",
  r"(+$x^{-3} \left(1 - 2 \ln(x)\right)$+)" = r"( )",
  r"($-2 x^{-3} \left(1/x - 1\right)$)" = r"( )",
  random_answer_order=TRUE
)
```

```{r drill-Deriv-rules-12a, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Which of these is $\partial_t \left(ln(6)+t^4-e^t\right)$?)",
  r"($\frac{1}{6}+4t^3-e^t$)",
  r"($\frac{1}{6}+4t^3-e^{-t}$)", 
  r"($4t^3-e^{-t}$)",
  r"(+$4t^3-e^t$+)"
)
```
  
  
  
  
```{r drill-Deriv-rules-12b, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Which of these is $\partial_u(\frac{1}{u^6}-\pi^3+4u^3+e)$?)",
  r"($-6u^{-7}-3\pi^2+4u^3$)",
  r"($-6u^{-5}-3\pi^2+12u^2+\frac{1}{e}$)",
  r"(+$-6u^{-7}+12u^2$+)",
  r"($-6u^{-5}+12u^2 +\frac{1}{e}$)"
)
```
  
  
```{r drill-Deriv-rules-12c, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Which of these is $\partial_v(\sqrt[4]{v^7}+e^7-4-\frac{3v^6}{v^2})=$)",
  r"($\frac{7}{4}\frac{1}{v^4}+7e^6-\frac{18v^5}{2v}$)",
  r"(+$\frac{7}{4}v^{\frac{3}{4}}-12v^3$+)",
  r"($\frac{4}{7}v^{\frac{-3}{7}}-\frac{18v^5}{2v}$)",
  r"($\frac{7}{4}v^{\frac{3}{4}}+e^7-12v^3$)"
)
```

```{r drill-Deriv-rules-13, echo=FALSE, results='markup'}
askMC(
  prompt = r"(What is $\partial_{t} \left(4 \sin(2\pi t) - 5\right)$?  )",
r"($4 \cos(2\pi t) - 5$)" = r"( )",
  r"($4 \pi \cos(2 \pi t)$)" = r"( )",
  r"(+$8 \pi \cos(2 \pi t)$+)" = r"( )",
  r"($8 \cos(2 \pi t)$)" = r"( )",
  random_answer_order=TRUE
)
```



```{r drill-Deriv-rules-14, echo=FALSE, results='markup'}
askMC(
  prompt = r"(What is $\partial_{t} \left(7 + 8 t^2 + 3 t^4\right)$?  )",
r"(+$16 t + 12 t^3$+)" = r"( )",
  r"($8 t + 4 t^3$)" = r"( )",
  r"($16 t^2 + 9 t^3$)" = r"( )",
  r"($4 t + 12 t^2$)" = r"( )",
  random_answer_order=TRUE
)
```



```{r drill-Deriv-rules-15, echo=FALSE, results='markup'}
askMC(
  prompt = r"(The derivative $\partial_x \text{dnorm}(x) = - x\, \text{dnorm}(x)$. What is $$\partial_x \text{dnorm}\left(\frac{x^2}{4}\right)\ ?$$  )",
r"(+$- \frac{x^3}{8} \text{dnorm}\left(\frac{x^2}{4}\right)$+)" = r"( )",
  r"($-\frac{x}{2} \text{dnorm}\left(\frac{x^2}{4}\right)$)" = r"( )",
  r"($-\frac{x}{8} \text{dnorm}\left(\frac{x^2}{4}\right)$)" = r"( )",
  r"($-\frac{x^2}{2} \text{dnorm}\left(\frac{x^2}{4}\right)$)" = r"( )",
  random_answer_order=TRUE
)
```



```{r drill-Deriv-rules-16, echo=FALSE, results='markup'}
askMC(
  prompt = r"(What is $\partial_{t} \left(6 t - 3 t^2 + 2 t^4\right)$?  )",
r"(+$6 - 6 t + 8 t^3$+)" = r"( )",
  r"($6 - 3 t + 6 t^3$)" = r"( )",
  r"($-3 t + 6 t^3$)" = r"( )",
  r"($6 - 3 t + 8 t^2$)" = r"( )",
  random_answer_order=TRUE
)
```



```{r drill-Deriv-rules-17, echo=FALSE, results='markup'}
askMC(
  prompt = r"(What is $\partial_t \ln(t^2 + 1)$? )",
r"(+$\frac{2t}{t^2+1}$+)" = r"( )",
  r"($1/{t^2 + 1}$)" = r"( )",
  r"($1/2t$)" = r"( )",
  r"($2 t \ln(t^2 + 1)$)" = r"( )",
  random_answer_order=TRUE
)
```


```{r drill-M08-1, echo=FALSE, results='markup'}
askMC(
  prompt = r"(For the function $$g(t) \equiv \sin\left(\frac{2 \pi}{P} (t - t_0)\right)$$ is the interior function linear? )",
r"(+Yes+)" = r"( )",
  r"(No)" = r"( )",
  random_answer_order=FALSE
)
```



```{r drill-M08-2, echo=FALSE, results='markup'}
askMC(
  prompt = r"(For the function $$g(P) \equiv \sin\left(\frac{2 \pi}{P} (t - t_0)\right)$$ is the interior function linear? )",
r"(Yes)" = r"(Look carefully at the name of the argument to $g()$. Notice that it appears as a reciprocal in the interior function.)",
  r"(+No+)" = r"(You noticed that the name of the argument is $P$. Very good.)",
  random_answer_order=FALSE
)
```



```{r drill-M08-3, echo=FALSE, results='markup'}
askMC(
  prompt = r"(For the function $$h(u) \equiv \ln(a^2 u - \sqrt{b})$$ is the interior function linear? )",
r"(+Yes+)" = r"( )",
  r"(No)" = r"(Although $a^2$ and $\sqrt{b}$ appear to be nonlinear, they are not the inputs to the function. The function input is named $u$, and that appears in a strictly linear manner. If we had written the interior function as $9 u - 4$, you would have had no problem recognizing it as linear. We can equally well write this as $3^2 u - \sqrt{4}$; it is the same function and it is still linear in $u$.)",
  random_answer_order=FALSE
)
```



```{r drill-M08-4, echo=FALSE, results='markup'}
askMC(
  prompt = r"(For the function $f(w) \equiv e^{kw}$, is the interior function linear? )",
r"(+Yes+)" = r"( )",
  r"(No)" = r"(The interior function is $kw$, which is linear.)",
  random_answer_order=FALSE
)
```



```{r drill-M08-5, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Saying "the interior function is linear" is not an entirely complete statement. A full statement is "the interior function is linear in terms of the input $x$" or "in terms of the input $u$" or whatever name we choose to use for the input. <br> Is the expression $V x + U$ linear in terms of $U$? )",
r"(+Yes+)" = r"( )",
  r"(No)" = r"( )",
  random_answer_order=FALSE
)
```



```{r drill-M08-6, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Saying "the interior function is linear" is not an entirely complete statement. A full statement is "the interior function is linear in terms of the input $x$" or "in terms of the input $u$" or whatever name we choose to use for the input. <br> Is the expression $V x^2 + U$ linear in terms of $U$? )",
r"(+Yes+)" = r"( )",
  r"(No)" = r"(Don't be fooled by the $x^2$. We are interested in $V x^2 + U$ as a function of $U$, and $U$ appears in a linear form.)",
  random_answer_order=FALSE
)
```



```{r drill-M08-7, echo=FALSE, results='markup'}
askMC(
  prompt = r"(Saying "the interior function is linear" is not an entirely complete statement. A full statement is "the interior function is linear in terms of the input $x$" or "in terms of the input $u$" or whatever name we choose to use for the input. <br> Is the expression $V x^2 + U$ linear in terms of $X$? )",
r"(Yes)" = r"(we are asking about $V x^2 + U$ as a function of $x$. The $x^2$ term is definitely not linear!)",
  r"(+No+)" = r"( )",
  random_answer_order=FALSE
)
```

