---
id: "duck-takes-chair"
author: "Daniel Kaplan"
---

Each of the plots shows the graph of a function. Two specific inputs, labelled $A$ and $B$, are marked.

```{r echo=FALSE}
f <- doodle_fun(~ t, seed=76)
mosaicCalc::slice_plot(f(t) ~ t, bounds(t=c(-5,5))) %>%
  gf_refine(scale_x_continuous(breaks = -5:5),
            scale_y_continuous(breaks = 6:17)) %>%
  gf_text(6 ~ 5, label=~"B", color="orange3") %>%
  gf_text(6 ~ 3, label=~"A", color="orange3") %>%
  gf_labs(title="Plot (1)")
```

```{r dtc5-1, echo=FALSE, results="markup"}
say1 <- "Remember to take the *difference*: $f(B) - f(A)$."
say2 <- "Remember to take the *difference*: $B - A$"
say3 <- "The order of A and B is significant!"
say4 <- "It is \"rise\" over \"run\", not the other way around."
askMC(
  "In plot (1), what is the **rate of change** over the interval $A$ to $B$? (Pick the closest answer.)",
  "-15/2"=say1, "15/2"=say3, "2/15"=say4, "-2/15"=say4, "8/2"=say3, "+-8/2+", "2/8"=say3, "-2/8"=say4, "-15/5" = say2
)
```

```{r echo=FALSE}
f <- doodle_fun(~ t, seed=76)
slice_plot(f(t) ~ t, bounds(t=c(-5,5))) %>%
  gf_refine(scale_x_continuous(breaks = -5:5),
            scale_y_continuous(breaks = 6:17)) %>%
  gf_text(6 ~ -3, label=~"B", color="orange3") %>%
  gf_text(6 ~ -5, label=~"A", color="orange3") %>%
  gf_labs(title="Plot (2)")
```

```{r dtc5-2, echo=FALSE, results="markup"}
say1 <- "Remember to take the *difference*: $f(B) - f(A)$."
say2 <- "Remember to take the *difference*: $B - A$"
say3 <- "The order of A and B is significant!"
say4 <- "It is \"rise\" over \"run\", not the other way around."
askMC(
  "In plot (2), what is the **rate of change** over the interval $A$ to $B$? (Pick the closest answer.)",
  "-17/2"=say1, "2/17"=say4, "-10/2"=say3, "+10/2+", "2/10"=say3, "-2/10"=say4, "-17/-5" = say2
)
```

```{r echo=FALSE}
f <- doodle_fun(~ t, seed=76)
slice_plot(f(t) ~ t, bounds(t=c(-5,5))) %>%
  gf_refine(scale_x_continuous(breaks = -5:5),
            scale_y_continuous(breaks = 6:17)) %>%
  gf_text(6 ~ -1.5, label=~"C", color="orange3") %>%
  gf_labs(title="Plot (3)")
```

```{r dtc5-3, echo=FALSE, results="markup"}

askMC(
  "We haven't told you exactly how to do this yet, but give it a try. What is the rate of change near the point marked $C$? (Pick the closest answer.))",
  "-1/2", -1, -2, -3, "-3/2", -4, "+-5+" 
)
```
