---
id: "girl-think-clock"
created: "Fri May 13 11:53:51 2022"
global_id: "7fWerC"
---

Let's explore the derivative $\partial_x \frac{1}{x}$ using the evanescent-h method.

The general definition of the derivative of a function $f(x)$ is the limit as $h\rightarrow 0$ of a ratio:
$$\partial_x f(x) \equiv \underbrace{\lim_{h \rightarrow 0}}_\text{limit}\  \underbrace{\frac{f(x + h) - f(h)}{h}}_\text{ratio}\ .$$
For an evanescent-h calculation, we put aside for a moment $\lim_{h\rightarrow0}$ and operate algebraically on the ratio. In our operations, we treat $h$ as *non-zero*.

a. Substitute in $f(x) = 1/x$ and show step-by-step that the ratio (for non-zero $h$) is equivalent to $- \frac{1}{x^2 + hx}$.

b. The domain of the function $1/x$ is the entire number line, *except zero*. Examine the expression $- \frac{1}{x^2 + hx}$ to see if setting $h$ to zero would ever involve a division by zero for any $x$ in the domain of $1/x$. 

c. If setting $h=0$ can't cause a division by zero, it is legitimate to do so. Set $h=0$ and simplify the expression $- \frac{1}{x^2 + hx}$. Compare this to the rule for $\partial_x \frac{1}{x}$ given in Section @sec-d-pattern-book.




