---
id: "gradient-field-tan"
author: "Daniel Kaplan"
---

```{r include = FALSE}

library(mosaic)
library(mosaicCalc)
```


The graph shows the gradient field of a function. Imagine that the function represents the height of a smooth surface and that a drop of water has been placed at one of the lettered points. That drop will slide down the surface. Your job is to figure out where the drop ends up.

```{r echo=FALSE}
f <- rfun(~ x + y, seed = 868)
Points <- tibble::tribble(
  ~ x, ~ y, ~ label,
  -2, -2, "F", 
  -2.7, -0.7, "C",
  -2, -3.8, "D",
  -0.4, 3.1, "B",
  -1.5, 2, "E",
  3, 1, "A",
  3.5, -3, "G"
)
gradient_plot(f(x, y) ~ x + y, domain(x=c(-4, 4), y = c(-4, 4)), n=20, alpha=1) %>%
  gf_text(y ~ x, data=Points, color = "orange3", label = ~ label, inherit=FALSE)
```

```{r daily-digital-33-QA1, echo=FALSE}
askMC(
  prompt = "A drop is placed at point F. Which point does it slide by (or stop at)?",
    "C" = "You're following the arrows, but the gradient points uphill.",
    "+D+" = "... and it will keep on sliding, heading south.",
    "G" = "To get to G, the drop would have to start in the bottom right of the terrain.",
    "None of these" = "",
  inline = FALSE,
  random_answer_order = FALSE
)
```

```{r daily-digital-33-QA2, echo=FALSE}
askMC(
  prompt = "A drop is placed at point A. Where will it end up?",
    "A" = "Sometimes a drop will stay where you put it, but only if that place is flat. Clearly the function near A is not flat: the gradient has a non-zero length.",
    "B" = "To get from A to B, the drop would have to flow up the ridge that lies between them.",
    "C" = "C is the top of the mountain. Water doesn't flow up!",
    "+G+" = "G is the bottom of the catchment basement for much of the right side of the map.",
  inline = FALSE,
  random_answer_order = FALSE
)
```

```{r daily-digital-33-QA3, echo=FALSE}
askMC(
  prompt = "If many drops fell at random on the surface, a lake would form at one of these points. Which one?",
    "A" = "That's no a place where the surface forms a bowl to hold the lake, Water at A will flow to the east.",
    "+B+" = "",
    "C" = "Did you ever see a lake at the top of a mountain?",
    "D" = "Water at D is flowing south.",
    "E" = "Water at E will flow to the north-east.",
  inline=FALSE,
  random_answer_order = FALSE
)
```

