---
id: "gradient-field-orange"
author: "Daniel Kaplan"
global-id: "xdkw"
---

```{r include = FALSE}
```


It is relatively easy to assess partial derivatives when you know the gradient. After all, the gradient is the vector of $(\partial_x\,f(x,y), \partial_y f(x,y))$. To train your eye, here is a contour plot and a corresponding gradient plot.

```{r echo=FALSE, warning=FALSE}
g <- rfun(~ x + y, seed = 93923)
dom <- domain(x=c(-4,4), y=c(-4,4))
dom2 <- domain(x=c(-3.5, 3.5), y=c(-3.5, 3.5))
pA <- contour_plot(g(x,y) ~ x + y, dom)
pB <- gradient_plot(g(x,y) ~ x + y, dom2, n = 10, alpha=1) %>%
  gf_lims(x=c(-4, 4), y=c(-4, 4))
gridExtra::grid.arrange(pA, pB, ncol=2)
```


```{r gfo17-1, echo=FALSE}
askMC(
  prompt = "What is the rule for determining $\\partial_x f(x,y)$ from the direction of the gradient vector?",
  choices = list(
    "+If the vector has a component pointing right, $\\partial_x f$ is positive.+" = "",
    "If the vector has a component pointing left, $\\partial_x f$ is positive" = "If the gradient points left, then uphill is to the left. So the function is increasing from right to left. that is  a negative partial derivative.",
    "If the vector has a vertical component pointing up, $\\partial_x f$ is positive." = "This would be true for the partial derivative with respect to $y$, but that has to relevance to the partial with respect to $x$.",
    "If the vector has a component pointing downward, the partial derivative $\\partial_x f$ is positive." = "No, but the partial with respect to $y$ would be negative."
  ),
  inline=FALSE
)
```

```{r gfo17-2, echo=FALSE}
askMC(
  prompt = "What is the rule for determining $\\partial_y f(x,y)$ from the direction of the gradient vector?",
  choices = list(
    "If the vector has a component pointing right, $\\partial_y f$ is positive." = "Left and right are about $\\partial_x f$, not $\\partial_y f$.",
    "If the vector has a component pointing left, $\\partial_y f$ is positive." = "Left and right are about $\\partial_x f$, not $\\partial_y f$.",
    "+If the vector has a vertical component pointing up, $\\partial_y f$ is positive.+",
    "If the vector has a component pointing downward, the partial derivative $\\partial_y f$ is positive." = "The partial with respect to $y$ would be negative."
  ),
  inline=FALSE
)
```

