---
chapter: "none yet"
author: "Danny Kaplan"
difficulty: "XX"
date: 2021-06-08 
version: 0.1
tags: [first, second, third]
id: kid-mean-table
global-id: slwdkw
---

```{r kid-mean-table-default, include = FALSE}

```

Each question involves a pair of quantities that are a function of time and that might or might not be a quantity/rate-of-change pair. If they are, say which quantity is which. Feel free to look up a dictionary definition of words you are uncertain about.

```{r daily-digital-25-QA1, echo=FALSE}
askMC(
  prompt = "Deficit and debt",
    "+Deficit is the rate of change of debt with respect to time.+",
    "Debt is the rate of change of deficit with respect to time.",
    "They are not a rate of change pair.",
  random_answer_order = FALSE
)
```

```{r daily-digital-25-QA2, echo=FALSE}
askMC(
  prompt = "water contained and flow",
  
    "+Flow is the rate of change of water contained with respect to time.+",
    "Water contained is the rate of change of flow with respect to time.",
    "They are not a rate of change pair.",
  random_answer_order = FALSE
)
```
    
```{r daily-digital-25-QA3, echo=FALSE}
askMC(
  prompt = "Interest rate and debt owed on credit card",
    "+Interest rate is the rate of change of credit card debt with respect to time.+",
    "Credit card debt is the rate of change of interest rate with respect to time.",
    "They are not a rate of change pair.",
  random_answer_order = FALSE
)
```    

```{r daily-digital-25-QA4, echo=FALSE}
askMC(
  prompt = "Rain intensity and total rainfall",
    "+Rain intensity is the rate of change of total rainfall with respect to time.+",
    "Total rainfall is the rate of change of rain intensity with respect to time.",
    "They are not a rate of change pair.",
  random_answer_order = FALSE
)
```

```{r daily-digital-25-QA5, echo=FALSE}
askMC(
  prompt = "Force and acceleration",
    "Force is the rate of change of acceleration with respect to time." = "",
    "Acceleration is the rate of change of force with respect to time."  = "",
    "+They are not a rate of change pair.+" = "The dimension  of force is $ML/T^2$. The dimension of acceleration  is $L/T^2$. A  rate of change with respect to time should  have  an extra T in the denominator of the dimensions.",
  random_answer_order = FALSE
)
```

```{r daily-digital-25-QA6, echo=FALSE}
askMC(
  prompt = "Position  and acceleration",
    "Position is the rate of change of acceleration with repect to time." = "",
    "Acceleration is the rate of change of position with respect to time."  = "",
    "+They are not a rate of change pair.+" = "The  dimension of position is $L$. The dimension  of acceleration is $L/T^2$. The  rate of change  of position  would have  dimension  $L/T$. That is called 'velocity'.",
  random_answer_order = FALSE
)
```

```{r daily-digital-25-QA7, echo=FALSE}
askMC(
  prompt = "Velocity and air resistance",
    "Velocity is the rate of change of air resistance with repect to time." = "",
    "Air resistance is the rate of change of velocity with respect to time."  = "",
    "+They are not a rate of change pair.+" = "Air resistance is a force,  with dimension $M L/T^2$. Velocity  has dimension $L/T$. The rate of change of velocity with  respect to time is acceleration, which has dimension  $L/T^2$.",
  random_answer_order = FALSE
)
```



