---
chapter: "none yet"
author: "Danny Kaplan"
difficulty: "XX"
date: 2021-06-08 
version: 0.1
tags: [first, second, third]
id: kitten-put-kayak
global-id: eyded
---

```{r kitten-put-kayak-default, include = FALSE}
library(etude2)
```

In the following, three different functions are described. Your task is to write down the **dimension** of the input and of the output. Do this both for the function itself, and for the derivative of the function. For example, the dimension of the output of $N(y)$ given below is P, for population. The input has dimension T, for time.

A. The given function is $N(y)$, the population of the Netherlands in year $y$.

i. Dimension of input to $N(y)$?
i. Dimension of output from $N(y)$?
i. Dimension of input to $\partial_y N(y)$?
i. Dimension of output from $\partial_y N(y)$?

B. The given function is $p(u)$, the net profit from a manufactured good as a function of the number of units manufactured.

i. Dimension of input to $p(u)$?
i. Dimension of output from $p(u)$?
i. Dimension of input to $\partial_u p(u)$?
i. Dimension of output from $\partial_u p(u)$?

C. The given function is $w(t)$, the amount of water in a leaky bucket at any time after the bucket was filled.

i. Dimension of input to $w(t)$?
i. Dimension of output from $w(t)$?
i. Dimension of input to $\partial_t w(t)$?
i. Dimension of output from $\partial_t w(t)$?


