---
id: "kitten-wear-saw"
created: "Fri May 13 12:20:57 2022"
global_id: "btFLGr"
---

We don't yet have the tools needed to prove a formula for the derivative of power-law functions, but we already have some instances where we know the derivative:

- $\partial_x x^2 = 2 x$
- $\partial_x x^1 = 1$
- $\partial_x x^0 = 0$

A rule that fits all these examples is $$\partial_x x^p = p\, x^{p-1}\ .$$
For instance, when $p=2$ the rule gives $$\partial_x x^2 = 2\, x^1 = 2 x$$ since $p-1$ will be 1$.

It is not too hard to do the algebra to find the derivative of $x^3$. According to the proposed rule, the derivative should be $$\partial_x x^3 = 3 x^2\ .$$ 

Let's check this via the general definition of the derivative:
$$\partial_x x^3 = \underbrace{\lim_{h \rightarrow 0}}_\text{limit}\ \underbrace{\frac{(x+h)^3 - x^3}{h}}_\text{ratio}$$
In the evanescent-h technique, we put aside the limit for a moment and work algebraically on the ratio with the assumption that $h\neq0$.

a. Expand out $(x+h)(x+h)(x+h) - x^3$ to get a linear combination of monomials:  $x^2$, $x^1$, and $x^0$.

<!-- $$(x+h)^3 - x^3 = 3\, x^2 h + 3\, x h^2 + h^3$$ -->

b. Divide the linear combination in (a) by $h$ and simplify.

c. Examine the expression from (b) to determine if setting $h=0$ will result in a divide-by-zero. What did you find?

d. If your conclusion from (c) is that divide-by-zero does not occur when $h=0$, set $h=0$ and simplify the expression from (b) to find $\partial_x x^3$. Is your result consistent with the rule for the derivative of power-law functions described at the beginning of this problem. 

