---
id: "lamb-rise-sofa"
created: "Tue Jul 20 14:11:00 2021"
global_id: "3ICCCz"
---

For each of the following, say whether the function is a composition $f(g(x))$ or a product $f(x) g(x)$, or neither. 


```{r dedr1, echo=FALSE, results="markup"}
askMC("What sort of combination is $h_1(x)\\equiv \\ln(x) e^x$?","+product+", "composition", "neither", random_answer_order=FALSE)
```


```{r dedr2, echo=FALSE, results="markup"}
askMC("What sort of combination is $h_2(x)\\equiv \\sin(x) \\cos(x)$?","+product+", "composition", "neither", random_answer_order=FALSE)
```


```{r dedr3, echo=FALSE, results="markup"}
askMC(r"(What sort of combination is $h_3(x) \equiv \sin(\ln(x))$?)","product", "+composition+", "neither", random_answer_order=FALSE)
```

```{r dedr4, echo=FALSE, results="markup"}
askMC(r"(What sort of combination is $h_4(x) \equiv e^{\ln(x)}$?)","product", "+composition+", "neither", random_answer_order=FALSE)
```


```{r dedr5, echo=FALSE, results="markup"}
askMC(r"(What sort of combination is $h_5(x) \equiv \sin(x) - \dnorm(x)$?)","product", "composition", "+neither+", random_answer_order=FALSE)
```


```{r dedr6, echo=FALSE, results="markup"}
askMC(r"(What sort of combination is is $h_6(x) \equiv e^{x^2}$?)","product", "+composition+", "neither", random_answer_order=FALSE)
```


```{r dedr7, echo=FALSE, results="markup"}
askMC(r"(What sort of combination is $h_7(x) \equiv \pnorm(x^2)$?)","product", "+composition+", "neither", random_answer_order=FALSE)
```


```{r dedr8, echo=FALSE, results="markup"}
askMC(r"(What sort of combination is $h_8(x)  \equiv \pnorm(x) \dnorm(x)$?)","+product+", "composition", "neither", random_answer_order=FALSE)
```


```{r dedr9, echo=FALSE, results="markup"}
askMC(r"(What sort of combination is $h_9(x)  \equiv 1/\sin(x)$?)","product", "+composition+" = "Remember, $1/\\sin(x)$ is the same as $\\recip(\\sin(x))$.", "neither", random_answer_order=FALSE)
```

