---
id: "local-shift"
author: "Daniel Kaplan"
global-id: "683lsB"
skill: "Gi-Theory-605"
---

```{r include=FALSE}

library(mosaic)
library(mosaicCalc)
```

Each of the three functions graphed below is a simple power-law function that can be written $\left[x-x_0\right]^n$.  The three functions have different values for $x_0$ and for $n$.

```{r echo=FALSE}
f <- makeFun((x-4)^1 ~ x)
g <- makeFun((x-2)^2 ~ x)
h <- makeFun((x+1)^3 ~ x)

slice_plot(f(x) ~ x, bounds(x=c(0.3,5)), color="blue", size=2) %>%
  slice_plot(g(x) ~ x, bounds(x=c(0.2, 3.8)), color="orange3", size=2) %>%
  slice_plot(h(x) ~ x, bounds(x=c(-2.5, 0.5)), color="magenta", size=2) %>%
  gf_hline(yintercept = ~ 0, size=3, alpha=0.2, color="white") %>%
  gf_refine(scale_x_continuous(breaks=-2:5))
```
```{r reference-XX-1, echo=FALSE, results="markup"}
askMC("For the $\\color{blue}{\text{blue}}$ function, what is $x_0$?",
       0, 1, 2, 3, "+4+", 5,
      random_answer_order=FALSE)
```

```{r reference-XX-1b, echo=FALSE, results="markup"}
askMC("For the $\\color{blue}{\text{blue}}$ function, what is the order of the polynomial?",
      0, "+1+", 2, 3, 4, 5,
      random_answer_order=FALSE)
```

-----

```{r reference-XX-2, echo=FALSE, results="markup"}
askMC("For the $\\color{orange}{\text{orange}}$ function, what is $x_0$?",
      0, 1, "+2+", 3, "4", 5,
      random_answer_order=FALSE)
```

```{r reference-XX-2b, echo=FALSE, results="markup"}
askMC("For the $\\color{orange}{\text{orange}}$ function, what is the order of the polynomial?",
      0, "1", "+2+", 3, 4, 5,
      random_answer_order=FALSE)
```

-----

```{r reference-XX-3, echo=FALSE, results="markup"}
askMC("For the $\\color{magenta}{\text{magenta}}$ function, what is $x_0$?",
      -2, "+-1+", 0, 1, 2, 3,
      random_answer_order=FALSE)
```

```{r reference-XX-13, echo=FALSE, results="markup"}
askMC("For the $\\color{magenta}{\text{magenta}}$ function, what is the order of the polynomial?",
      0, "1", 2, "+3+", 4, 5,
      random_answer_order=FALSE)
```

