---
id: "maple-sail-boat"
created: "Fri Aug 13 11:06:16 2021"
global_id: "UNeewh"
---

The ramp function is defined algebraically as
$$\text{ramp}(x) \equiv \left\{\begin{array}{ll}0 & \text{for}\ x < 0\\ x & \text{otherwise} \end{array}\right. $$
or in R as
```{r}
ramp <- makeFun(ifelse(x<0, 0, x) ~ x)
```

Evaluate these three different forms for the definition of the instantaneous rate of change at $x=0$ using $h=0.1$.

- version 1: $${\cal D}_x f(x) \equiv \frac{f(x+h) - f(x)}{h}$$
- version 2: $${\cal D}_x f(x) \equiv  \frac{f(x) - f(x-h)}{h}$$
- version 3: $${\cal D}_x f(x) \equiv  \frac{f(x+h) - f(x-h)}{2 h}$$

```{r msb893-1, echo=FALSE, results="markup"}
askMC(
  "Do the three versions give different numerical results at $x=0$ for $h=0.01$?",
  "They all give the same result.",
  "Versions 1 and 3 give the same result, but 2 is different.",
  "Versions 1 and 2 give the same result, but 3 is different.",
  "+All three are different+",
  random_answer_order = FALSE
)
```

```{r msb893-2, echo=FALSE, results="markup"}
askMC(
  "For much smaller $h$ (say, $h=0.0001$), do the three versions give different numerical results at $x=0$?",
  "+Yes+",
  "No",
  random_answer_order=FALSE
  )
```


