---
id: "panda-drive-shirt"
created: "Tue Jul 20 14:01:59 2021"
global_id: "4nsU0z"
---


```{r echo=FALSE, warning=FALSE}
set.seed(2)
Pts <- tibble(x=runif(6, 0, 5), y=(rnorm(length(x))))
f <- mosaic::spliner(y ~ x, data = Pts)
ddf <- D(f(x) ~ x & x)
set.seed(723)
Pts <- tibble(x=0:5, y=sort(rnorm(length(x))))
f2 <- splinefun(Pts$x, Pts$y, method="monoH.FC")
df2 <- D(f2(x) ~ x)
```

```{r echo=FALSE, warning=FALSE}
graph_with_boxes(df2,
                 interval = tibble(x=c(.25, .8, 1.5),
                                   xend=c(.75, 1.3, 2.0)),
                 bounds(x=0:2))
```

```{r smoothA, echo=FALSE, results="markup"}
askMC("In which boxes is the function smooth?",
      "A and B",
      "B and C",
      "+A and C+",
      "none of them",
      "all of them",
      random_answer_order=FALSE)
```



```{r echo=FALSE}
graph_with_boxes(f,
                 interval = tibble(x=c( 2.75, 3.4, 4.25),
                                   xend=c( 3.25, 3.9, 4.75)),
                 bounds(x=2:4.8))
```
```{r smoothB, echo=FALSE, results="markup"}
askMC("In which boxes is the function smooth?",
      "A and B",
      "B and C",
      "A and C",
      "none of them",
      "+all of them+",
      random_answer_order=FALSE)
```



-----



```{r echo=FALSE}
graph_with_boxes(ddf,
                 interval = tibble(x=c( .75, 1.75 ),
                                   xend=c( 1.25, 2.25)),
                 bounds(x=0:2.7))
```
```{r smoothC, echo=FALSE, results="markup"}
askMC("In which boxes is the function smooth?",
      "A",
      "+B+",
      "neither of them",
      "both of them",
      random_answer_order=FALSE)
```


