---
id: "pig-see-pantry"
created: "Wed Sep 29 12:55:38 2021"
global_id: "JvtMuz"
---

Consider this function, $F(t)$, which is a linear combination of three time-shifted sigmoids.

```{r echo=FALSE}
f <- makeFun(2*pnorm(x+15) + 3*pnorm(x-1) - 5*pnorm(x-10) ~ x)
slice_plot(f(t) ~ t, domain(t=-25:25)) %>%
  gf_labs(y="F(t)")
```
As you know, the derivative of a sigmoid $\text{pnorm}(t)$ is a gaussian with the same center and standard deviation. 

```{r psp4-1, echo=FALSE, results="markup"}
askMC(
  "How many gaussians will be in $\\partial_t F(t)$.",
  "2",
  "+3+",
  "6",
  "none"
)
```

The following figure shows several functions. One of them is $\partial_t F(t)$.

```{r echo=FALSE, warning=FALSE}
ylabel <- latex2exp::TeX("$\\partial_t F(t)$")

PA <- slice_plot(3*dnorm(t+15) + 2*dnorm(t-1) + 3*dnorm(t-10) ~ t, domain(t=-25:25), npts=300) %>% 
  gf_labs(y = ylabel, title="Function A")

PB <- slice_plot(1*dnorm(t+15) +2*dnorm(t-1) - 2.5*dnorm(t-10) ~ t, 
                 domain(t=-25:25), npts=300) %>% 
  gf_labs(y = ylabel, title="Function B")

PC <- slice_plot(1*dnorm(t+15) +2*dnorm(t-1) - 2.5*dnorm(t-10) ~ t, 
                 domain(t=-25:25), npts=300) %>% 
  gf_labs(y = ylabel, title="Function C")

PD <- slice_plot(5*dnorm(t+15) + 8*dnorm(t-1) -10*dnorm(t-10) ~ t, 
                 domain(t=-25:25), npts=300) %>% 
  gf_labs(y = ylabel, title="Function D")
gridExtra::grid.arrange(PA, PB, ncol=2)
gridExtra::grid.arrange(PC, PD, ncol=2)

```

```{r psp4-2, echo=FALSE, results="markup"}
askMC(
  "Which function is the actual derivative of $F(t)$? (Hints: The vertical axis is important as is the value of $\\text{dnorm}(0)$.)",
  "A",
  "B",
  "C",
  "+D+",
  random_answer_order=FALSE
)
```


```{r echo=FALSE, warning=FALSE}
ylabel <- latex2exp::TeX("$\\partial_{tt} F(t)$")

PA <- slice_plot(-(t+17)*dnorm(t+15) + 2*(t-1)*dnorm(t-1) - 2.5*(t-10)*dnorm(t-10) ~ t, 
                 domain(t=-25:25), npts=300) %>% 
  gf_labs(y = ylabel, title="Function A")
PB <- slice_plot(-5*(t+15)*dnorm(t+15) + 8*(t-1)*dnorm(t-1) +10*(t-10)*dnorm(t-10) ~ t, 
                 domain(t=-25:25), npts=300) %>% 
  gf_labs(y = ylabel, title="Function C") # this one

PC <- slice_plot(-5*(t+15)*dnorm(t+15) - 8*(t-1)*dnorm(t-1) +10*(t-10)*dnorm(t-10) ~ t, 
                 domain(t=-25:25), npts=300) %>% 
  gf_labs(y = ylabel, title="Function C") # this one
PD <- slice_plot(1*(t+14)*dnorm(t+15) -2*(t-1)*dnorm(t-1) + 2.5*(t-10)*dnorm(t-10) ~ t, 
                 domain(t=-25:25), npts=300) %>% 
  gf_labs(y = ylabel, title="Function D")



gridExtra::grid.arrange(PA, PB, ncol=2)
gridExtra::grid.arrange(PC, PD, ncol=2)
```

```{r psp4-3, echo=FALSE, results="markup"}
askMC(
  "Which function is the actual second derivative of $F(t)$? (Hints: The vertical axis is important as is the value of $\\text{dnorm}(0)$.)",
  "A" = "The problem is with the first event.",
  "B" = "The first and second events go in the same direction. The third event is not as big as the second.",
  "+C+",
  "D" = "The first event isn't the second derivative of a sigmoid.",
  random_answer_order=FALSE
)
```
