---
id: "pine-burn-plate"
created: "Fri Sep  3 17:17:56 2021"
global_id: "2i2QSR"
---


Use the polynomial expansion of $e^x$ around $x=0$ to perform the following calculations.

```{r pc1-3, echo=FALSE, results="markup"}
askMC(
  "Find $f(1)$ exactly for your 4th-order polynomial approximation to $e^x$. Which of these is it?",
  "2 8/12",
  "+2 17/24+",
  "2 35/48",
  "2 7/10"
)
```

```{r pc1-4, echo=FALSE, results="markup"}
askMC(
  "Again using $f()$  for the 4th-order polynomial approximation to $e^x$, subtract $f(1)$ from $e^1$. The result will be near zero. To quantify how near, count the number of leading zeros after the decimal point. How many zeros are there?",
  1, "+2+", 3, 4,
  random_answer_order = FALSE
)
```

```{r pc1-5, echo=FALSE, results="markup"}
askMC(
  "Repeat the above calculation, but include the 5th- and 6th-order terms (that is, $a_5 x^5$ and $a_6 x^6$) when programming the polynomial computer. Subtract the new $f(1)$ from $e^1$.  How many leading zeros are there after the decimal point?",
  1, "2", "+3+", 4,
  random_answer_order = FALSE
)
```

