---
id: "pine-make-cotton"
created: "Fri May 13 11:31:59 2022"
global_id: "Ct9j6c"
---

Let's explore the derivative of the exponential function. By the general definition of the derivative of a function, 
$$\partial_t e^t \equiv \lim_{h\rightarrow 0} \frac{e^{t+h} - e^t}{h}\ .$$
a. Confirm that this can be re-written 
$$\partial_t e^t \equiv \lim_{h\rightarrow 0} e^t \frac{e^{h} - 1}{h}\ .$$

b. The difficulty with evanescent $h$ occurs when $h$ is in the denominator of the fraction, since division by zero isn't defined. But the $e^t$ term can never be zero, so it's legitimate to pull it outside of the limit, giving
$$\partial_t e^t \equiv e^t \lim_{h\rightarrow 0} \frac{e^{h} - 1}{h}\ .$$


We can numerically explore the limit$\lim_{h\rightarrow 0} \frac{e^{h} - 1}{h}$ by constructing a function of $h$:

```{r}
limit <- makeFun((exp(h) - 1)/h ~ h) 
```

Evaluate `limit(0)` and explain the result.

c. Evaluate `limit()` at each of a series of smaller and smaller values of $h$: 0.1, 0.01, 0.001, 0.0001, 0.00001, and so on. Describe the trend.

d. Due to the limited precision of computer arithmetic, when $h$ is too small the trend in (c) will break. Give an example of a too-small $h$ and show how the trend is broken by it.



