---
id: "rhinosaurus-hold-plate"
created: "Fri May 13 12:24:20 2022"
global_id: "8KQzUH"
---



Let's see what the evanescent-h procedure tells us about the derivative of the straight-line function $\line(x) \equiv a x + b$. Of course, you already know that the slope of $\line(x)$ with respect to $x$ is $a$. It would be nice if the evanescent-h method gives the same result!

has a slope function that is constant: $\diff{x}\line(x) = a$


$$\diff{x}\line(x) = \frac{\line(x+h) - \line(x)}{h} = \frac{\left[\strut a (x+h) + b\right] - \left[\strut a x + b\right]}{h} = \frac{ah}{h} = a$$
The derivative is the slope function with $h$ made as small as possible. It's tempting to think of this as $h = 0$, but that would imply dividing by zero in the differencing operator. 

Being wary about the possibility of dividing by zero, mathematicians adopt a convention that indicates clearly that $h$ is to be small, but **not zero**. This convention is marked with the notation $\lim_{h \rightarrow 0}$, which means "as close as you can get to zero, but not zero exactly". 

$$\partial_x \line(x) \equiv \lim_{h\rightarrow 0} \frac{\line(x+h) - \line(x)}{h} =\\
\ \\
= \lim_{h\rightarrow 0} \frac{a h}{h} = a$$

This derivation is unarguably correct for any non-zero $h$. 

This short derivation gives us a basic differentiation rule which we can divide into 3 special cases. 

- **Line rule**: $\partial_x ax + b = a$
    i. $\partial_x ax = a$. The function $ax$ is $\line(x)$ with $b=0$.
    ii. $\partial_x b = 0$. The function $b$ is $\line(x)$ with $a=0$ and thus is the constant function.
    iii. $\partial_x x = 1$. The function $x$ is $\line(x)$ with $a=1$ and $b=0$. 
    
Remember that $\partial_x f(x)$ is always a function no matter what kind of function $f(x)$ is. The functions associated with the line rule are all ***constant functions***, meaning the output doesn't depend on the input.

