---
id: "shark-bite-sheet"
created: "Mon Oct  4 12:14:21 2021"
global_id: "ZQlUv4"
---

Let's return to the water skier in @sec-differential-skier. When we left her, the rope was being pulled in at 10 feet per second and her corresponding speed on the water was 10.05 feet per second. The relationship between the rope speed and the skier's speed was $$dx = \frac{L}{x} dL$$ and, due to the right-angle configuration of the tow system, $x^2 = L^2 - H^2$. 

What happens to $dx$ as $L$ gets smaller with $dL$ being the same? We need to keep in mind that $dx$ depends on three things: $dL$, $L$, and $x$. But we can substitute in the Pythagorean relationship between $x$, $L$, and (fixed) $H$ to get
$$dx = \frac{L}{\strut\sqrt{L^2 - H^2}}\ dL\ .$$
This is bad news for the skier who holds on too long! As $L$ approaches $H$, the rope becomes more and more vertical and the skier's water speed becomes greater and greater, approaching $\infty$ as $L \rightarrow H$.

You, an engineer brought in to solve this dangerous possibility, have proposed to have the winch slow down as the rope is reeled in. How should the speed of the rope be set so that the skier's water speed remains safely constant?

```{r sbsx-1, echo=FALSE, results="markup"}
askMC(
  "What formula for $dL$ will allow $dx$ to stay constant at a value $v$?",
  "$dL = dx$" = "This is possible only for one value of $L$, when $\\sqrt{L^2 - H^2} = L$. So this isn't a way to keep $dx$ constant.",
  "+$dL = v \\sqrt{L^2 - H^2}{L}$+" = "The roop speed will get slower and slower, coming to zero when $L = H$",
  "$dL = v \\sqrt{L^2 - H^2}$" = "If $dL$ were set according to this rule, $dx = L$, which isn't going to be constant as $L$ gets smaller.",
  "There is no such formula."
)
```
