---
id: "tiger-blow-futon"
created: "Thu Aug 12 16:54:38 2021"
global_id: "rou0yO"
---

The function `road(x)` has been constructed to correspond to a curved road of gradually tighter radius from left to right


```{r}
R <- makeFun(3 - x/2 ~ x)
road <- makeFun(sqrt(R(x)^2 - x^2) ~ x)
slice_plot(road(x) ~ x, domain(x=c(-2, 2)), npts=500)
```                

Using a `r sandbox_link()`, calculate the curvature of this road for each value of $x$.

```{r tbf23-1, echo=FALSE, results="markup"}
askMC(
  "What is the curvature of the road at $x=-1$?",
  "+0.22+",
  "0.24" = "             ",
  "0.27" = "             ",
  "0.31" = "             ",
  0.35, 
  random_answer_order = FALSE
)
```

```{r tbf23-2, echo=FALSE, results="markup"}
askMC(
  "What is the curvature of the road at $x=1$?",
  "0.22" = "             ",
  "0.24" = "             ",
  "+0.27+",
  "0.31" = "             ",
  0.35, 
  random_answer_order = FALSE
)
```

```{r tbf23-3, echo=FALSE, results="markup"}
askMC(
  "What is the curvature of the road at $x=0$?",
  "0.22" = "             ",
  "+0.24+",
  "0.27" =  "             ",
  "0.31" = "             ",
  0.35, 
  random_answer_order = FALSE
)
```
