---
id: "tilde-function"
author: "Daniel Kaplan"
global-id: "kelwx"
---


The most common programming pattern in the R/mosaic calculus commands is:

> **Operator**(*tilde_expression*, [optional details])

Some operators: `slice_plot()`, `contour_plot`, `make_Fun()`, `D()`, `antiD()`, `Zeros()`

For each of the R/mosaic expressions, determine which kind of thing is being created. Feel free to run the expressions in a `r sandbox_link()`.


```{r tfS-1, echo=FALSE, results="markup"}
askMC(
  "\n\n`makeFun(a*x - b ~ x)`",
  "a function of `x`" = "Fair enough. But the function also has arguments `a` and `b` ",
  "+a function of `x`, `a`, and `b`+",
  "a tilde expression" = "The tilde expression is the **input** to the operator. The operator translates the tilde expression into something else.",
  "a plot",
  "a data frame",
  "an error"
)
```

```{r tfS-2, echo=FALSE, results="markup"}
askMC(
  "\n\n`D(a*x - b ~ x)`",
  "a function of `a`",
  "+a function of `x`, `a`, and `b`+",
  "a tilde expression",
  "a plot",
  "a data frame",
  "an error"
)
```

```{r tfS-3, echo=FALSE, results="markup"}
askMC(
  "\n\n`antiD(a*x - b ~ x)`",
  "a function of `a`",
  "+a function of `x`, `a`, and `b`+",
  "a tilde expression",
  "a plot",
  "a data frame",
  "an error"
)
```

```{r tfS-4, echo=FALSE, results="markup"}
askMC(
  "\n\n`slice_plot(a*x - b ~ x, domain(x=0:5))`",
  "a function of `x`",
  "a function of `x`, `a`, and `b`",
  "a tilde expression",
  "a plot" = "The expression is intended to make a plot, but it does not work. Specific numerical values would need to be provided for `a` and `b`. You could have provided numerical values to `a` and `b` by assigning them in previous statements. If that is  what you had in mind, you deserve full credit.",
  "a data frame",
  "+an error+" 
)
```

```{r tfS-5, echo=FALSE, results="markup"}
askMC(
  "\n\n`f <- makeFun(a*x + b ~ x, a=2, b=-4)`\n\n
  `slice_plot(f(x) ~ x, domain(x=0:5))`",
  "a function of `x`",
  "a function of `x`, `a`, and `b`",
  "a tilde expression",
  "+a plot+" = "This works because there are specific values provided for the `a` and `b` parameters.",
  "a data frame",
  "an error"
)
```

```{r tfS-6, echo=FALSE, results="markup"}
askMC(
  "\n\n`Zeros(a*x - b ~ x, domain(x=0:5))`",
  "a function of `x`",
  "a function of `x`, `a`, and `b`",
  "a tilde expression",
  "a plot" = "The expression is intended to make a data frame, but it does not work. Specific numerical values would need to be provided for `a` and `b`.",
  "a data frame",
  "+an error+"
)
```

```{r tfS-7, echo=FALSE, results="markup"}
askMC(
  "\n\n`a*x - b ~ x`",
  "a function of `x`",
  "a function of `x`, `a`, and `b`",
  "+a tilde expression+",
  "a plot" = "The expression is intended to make a plot, but it does not work. Specific numerical values would need to be provided for `a` and `b`.",
  "a data frame",
  "an error"
)
```

```{r tfS-8, echo=FALSE, results="markup"}
askMC(
  "\n\n`f <- makeFun(a*x + b ~ x, a=2, b=-4)`\n\n
  `Zeros(f(x) ~ x)`",
  "a function of `x`",
  "a function of `x`, `a`, and `b`",
  "a tilde expression",
  "a plot",
  "+a data frame+",
  "an error"
)
```

```{r tfS-9, echo=FALSE, results="markup"}
askMC(
  "Suppose you create a function in the usual way, e.g. `f <- makeFun(a*x + b ~ x, a=2, b=-4)`. Which of the following will plot a straight-line function with a slope of 5.",
  "`slice_plot(f(x) ~ x, domain(x=-5:5))`" = "The default value of `a` is 2, so the line would have a slope of 2.",
  "`slice_plot(f(x, b=2), domain(x=-5:5)`" = "It is `a` that is the slope parameter.",
  "+`slice_plot(f(x, a=5), domain(x=-5:5)`+"
)
```



