---
id: "titmouse-throw-sofa"
created: "Thu Aug 26 18:11:52 2021"
global_id: "1kZXxT"
---

The plots each show a function graphed in the usual way, and a slope function graphed using the slope function visualization. Your task is to determine whether the slope function being displayed in each graph is a match to the function in that graph. 

```{r echo=FALSE}
compare_slope_fun <- function(seed1, seed2, 
                              dom=domain(x=c(-3,3))) {
  f1 <- rfun( ~ x, seed = seed1)
  f2 <- rfun( ~ x, seed = seed2)
  Segs <- create_segments(f2(x) ~ x, dom, nsegs=50)
  slice_plot(f1(x) ~ x, dom) %>%
    gf_segment(y + yend ~ x + xend, data = Segs, 
           color=~slope,size=0.3) %>%
    gf_refine(scale_color_viridis_c())
  
}
```

```{r echo=FALSE}
compare_slope_fun(101,101) %>%
  gf_labs(title = "Plot (A)")
```

```{r tts3-1, echo=FALSE, results="markup"}
askMC("In plot (A), does the slope function displayed correspond to the function that's graphed?",
      "+Yes+",
      "No",
      random_answer_order = FALSE)
```


```{r echo=FALSE}
compare_slope_fun(1067,111) %>%
  gf_labs(title = "Plot (B)")
```

```{r tts3-2, echo=FALSE, results="markup"}
askMC("In plot (B), does the slope function displayed correspond to the function that's graphed?",
      "Yes",
      "+No+",
      random_answer_order = FALSE)
```

```{r echo=FALSE}
compare_slope_fun(1903,1903) %>%
  gf_labs(title = "Plot (C)")
```

```{r tts3-3, echo=FALSE, results="markup"}
askMC("In plot (C), does the slope function displayed correspond to the function that's graphed?",
      "+Yes+",
      "No",
      random_answer_order = FALSE)
```

```{r echo=FALSE}
compare_slope_fun(1066,1776) %>%
  gf_labs(title = "Plot (D)")
```

```{r tts3-4, echo=FALSE, results="markup"}
askMC("In plot (D), does the slope function displayed correspond to the function that's graphed?",
      "Yes",
      "+No+",
      random_answer_order = FALSE)
```
