---
id: "ant-lend-scarf"
created: "Mon Nov 15 12:45:28 2021"
global_id: "MQ1rZa"
---

Referring to the quadratic spline interpolating functions in @fig-four-quads, note that the different functions all go through the knots. The difference between them is the derivative at $t=4$.  Reading from the graphs, say what the slope $\partial_t x(t)\left.{\Large\strut}\right|_{t=4}$ is in each of the graphs:

```{r als3-1, echo=FALSE, results="markup"}
askMC(
  "What is $\\partial_t x(t)\\left.{\\Large\\strut}\\right|_{t=4}$ for the function in panel A?",
  "-9",
  "+-5+",
  "-2",
  "-1",
  random_answer_order = FALSE
)
```

```{r als3-2, echo=FALSE, results="markup"}
askMC(
  "What is $\\partial_t x(t)\\left.{\\Large\\strut}\\right|_{t=4}$ for the function in panel B?",
  "-9",
  "-5",
  "-2",
  "+-1+",
  random_answer_order = FALSE
)
```

```{r als3-3, echo=FALSE, results="markup"}
askMC(
  "What is $\\partial_t x(t)\\left.{\\Large\\strut}\\right|_{t=4}$ for the function in panel C?",
   "1",
  "+2+",
  "5",
  "9",
  random_answer_order = FALSE
)
```

```{r als3-4, echo=FALSE, results="markup"}
askMC(
  "What is $\\partial_t x(t)\\left.{\\Large\\strut}\\right|_{t=4}$ for the function in panel D?",
  "1",
  "2",
  "+5+",
  "9",
  random_answer_order = FALSE
)
```



