---
id: "ape-hurt-fridge"
created: "Fri Dec 17 14:45:29 2021"
global_id: "Muhyz8"
---

`r under_construction()`

INTRODUCE THE CUMULATIVE.

Variety of exercises on probabilities, e.g. prob of further out than 1 sd in gaussian, prob of further out than 1 sd in uniform, and so on.

For every probability density function, such as the one displayed in Figure \@ref(fig:dart-g), there is another way of displaying the model called a ***cumulative distribution function***. For the probability density function $g(x)$, the cumulative distribution function $G(x)$ is $$G(x) \equiv \int_{-\infty}^infty g(x) dx$$. 

```{r dart-g-cumulative, echo=FALSE, fig-cap: "The cumulative distribution function corresponding to $g(x)$ in Figure \\@ref(fig:dart-g)."}
slice_plot(pchisq(x, df=4) ~ x, domain(x=0:20)) %>%
  gf_labs(x="Distance from center of bullseye (cm)", 
          y="Cumulative probability")
```




The output of the cumulative distribution function is a probability: a number between zero and one. But the probability of what? The cumulative distribution function tells the probability of the outcome of the event being ***less-than*** the value of the input. For instance, in Figure \@ref(fig:dart-g-cumulative), the probability of the dart being closer to the bullseye than 5 cm is about 0.7.

Cumulative distribution functions are the means with which many common probability calculations are done. For instance, the probability that the dart will fall 2 to 5 cm from the bullseye is $G(5) - G(2)$. Such calculations are simply in the style of definite integrals: $$G(5) - G(2) = \int_2^5 g(x)\,dx\ .$$

::: {.example data-latex=""}
What is the probability that the dart will fall farther than 5 cm from the bullseye?

This is the same as asking for the probability that the dart will fall somewhere in the interval 5cm to $\infty$, that is:
$$\int_5^\infty g(x)\, dx = G(\infty) - G(5) = 1 - 0.7127 = 0.2873$$
To understand why $G(\infty) = 1$, ask yourself what is the probability that a thrown dot will land closer to the bullseye than $\infty$. Of course it will! That corresponds to a probability value of 1.
:::

EXERCISE: CALCULATIONS on the normal, F, and exponential distributions.

EXERCISE: Calculate the 95% credible intervals on the posterior on the disease.
