---
id: "ash-fly-canoe"
created: "Wed Nov  3 16:14:25 2021"
global_id: "DP2hxD"
---



These questions are just about R/mosaic code reading skills. They refer to the chapter example about Kepler's analysis of the orbit of Mars.

```{r rdi1-2, echo=FALSE, results="markup"}
askMC(
  "The data are stored in an object named `Kepler`. What kind of object is `Kepler`?",
  "+A data frame+",
  "A matrix",
  "A vector",
  "A function"
)
```

```{r rdi1-3, echo=FALSE, results="markup"}
askMC(
  "There are two variables from Kepler's data used in the code. What are their names?", 
  "`time` and `angle`",
  "`distance` and `angle`",
  "+`kepler.radius` and `kepler.angle`+",
  "`kepler.distance` and `kepler.angle`"
)
```

```{r rdi1-4, echo=FALSE, results="markup"}
askMC(
  "The object `connector` is defined on lines 2 and 3 of the sandbox code. What kind of R object is `connector`? (Hint, you may need to read further along in the code to figure this out.)",
  "A data frame",
  "A number",
  "A vector",
  "+A function+"
)
```



```{r rdi1-5, echo=FALSE, results="markup"}
askMC(
  "What kind of R object is `kepler.radius ~ kepler.angle`?",
  "+A tilde expression+",
  "An arithmetic expression",
  "A function",
  "A character string" = "Character strings always involve quotation marks."
)
```
```{r rdi1-6, echo=FALSE, results="markup"}
askMC(
  "The R function `gf_point()` as used here has how many arguments?",
  1, 2, 3, 4, right_one = 3, random_answer_order = FALSE
)
```

```{r rdi1-7, echo=FALSE, results="markup"}
askMC(
  "What's the give away that `polynomial` (as used here) is a **function**?",
  "+The name `polynomial` is followed by open and close parentheses.+",
  "The name `polynomial` begins with a `p`.",
  "The name `polynomial` is an English verb." = "This is a nice programming style to use natural-language verbs to name functions, but it is not at all required by the language. (And \"polynomial\" isn't a verb anyway.)"
)
```

```{r rdi1-8, echo=FALSE, results="markup"}
askMC(  
  "Why are there quotation marks in `'red'`?",
  "Because the color is only sort of red-ish, not pure red.",
  "Because Mars is the \"Red Planet\"",
  "+Because the word is a literal set of characters, not the name of a function or other R object.+"
)
```

