---
id: "fawn-walk-futon"
created: "Mon Jan 10 07:10:39 2022"
global_id: "T4Yf9r"
---

`r insert_calcZ_exercise("XX.XX", "T4Yf9r", "Exercises/fawn-walk-futon.Rmd")`


The careful reader will have noticed that in @sec-discount-functions we asserted that the proper form of the discounting function ${\cal D}(t)$ is $e^{kt}$ but in the building project example we used a different form, $(1+r)^{-t}$. These are, of course, both exponential functions---the input $t$ is in the exponent in both cases. For them to be the same requires $k = -\ln(1+r)$.  only the appropriate choice of $k$.


The reason it's preferable to use $k$ instead of $r$ has to do with compounding of interest. Being told $r=2\%$ per month is not quite the entire story. You also have to know how often the interest is compounded. For instance, it's natural (but wrong!) to believe that 2% per month is the same as 24% per year. But it depends on how often the interest is compounded. If it is compounded every month, the present value of one dollar at the end of a year is ${\cal V}_r(t= 1\ \text{year}) = (1+r)^{12}$. For $r = 2\%$ per month, that comes to $1.02^{12} = 1.2682$. In other words, the effective annual rate is 26.82%. If you round off 2% per month to 24% per year, you will be underestimating the amount you owe by about 10%.

In the $e^{kt}$ format, all you need to know is the value of $k$ and its units. The parameter $k$ will match a rate of $r$ per month when $e^{kt} = (1+r)^t$, in other words $k = \ln(1+r)$ per month. Whereas multiplying $r$ by 12 will not convert a monthly rate into an annual rate, things are much simpler with $k$. For instance, for $r=2\%$ per month, $k = \ln(1.02) = 0.019803$ per month. The $k$ corresponding to 12 months is a unit conversion: "per month" into "per year". Of course, 1 per month is the same quantity as 12 per year, so multiply 0.0198 per month by 12 months/year to get $12 \times 0.0198 = 0.2376$ per year. In this way of reckoning, the amount you owe after one year is $\exp(0.2376\ \text{per year} \times 1\ \text{year}) = 1.2682$.
