---
id: "giraffe-trim-book"
created: "Thu Nov 18 10:44:56 2021"
global_id: "N6z7nD"
exercise_format: "on paper"
---

In a Bézier spline, $x(t)$ and $y(t)$ can be interpreted as the $(x,y)$ coordinate at time $t$ of a pen on the drawing canvas. Let's take that interpretation literally and figure out some features of the pen's motion. It is reasonable to think about the pen in physical terms.

The $x$-component of the pen as a function of time $t$ is $$x(t) = (1-t)^3\, x_1 + 3(1-t)^2 t\, x_2 + 3(1-t) t^2\, x_3 + t^3\, x_4$$ where the domain is $0 \leq t \leq 1$.

In terms of the coefficients $x_1, x_2, x_3$, and $x_4$ ....

1. Where will the pen be at time $t=0$?
2. Where will the pen be at time $t=1$?
3. Consider the velocity $\partial_t x(t)$ of the pen. (we are thinking of the $x$- direction only. The pen will also have a $y$-component of velocity.)
    a. What is the velocity of the pen at $t=0$, that is, what is $\partial_t x(t=0)$? You should be able to give an algebraic form for this.
    b. Imagine that the pen moved with constant initial velocity $\partial_t x(t=0)$. (It does not, but imagine that it does.) At what value of $t$, if any, will the pen reach the $x$-value $x_2$?
    c. Find the velocity of the pen at $t=1$. Again, as in (a), you should be able to give an algebraic form for this.
    d. Imagine the pen moving backwards in time from $x(1) = x_4$ at the velocity $\partial_t x(t=1)$. At what time $t < 1$, if any, would the pen have been at value $x_3$?


GIVE VELOCITY, ...


```{r x-curve, echo=FALSE}
xpts <- c(1, 3, 2, 4)
xfun <- function(t) {
  (1-t)^3*xpts[[1]] + 3*(1-t)^2*t*xpts[[2]] + 3*(1-t)*t^2*xpts[[3]] + t^3*xpts[4]
}
slice_plot(xfun(t) ~ t, bounds(t=0:1)) %>%
  gf_refine(coord_fixed())
```
