<!--
We can replot the situation by calculating at each point the angle between the gradient vectors for the two functions.
-->

```{r echo=FALSE, eval=FALSE}
# This isn't working!
P <- makeFun((L^0.3)*(K^(1-0.3)) ~ K & L)
dPdL <- D(P(K=K, L=L) ~ L)
dPdK <- D(P(K=K, L=L) ~ K)
dEdL <- -6
dEdK <- -13
theta <- function(K,L) {
  LP <- sqrt(dPdL(K=K, L=L)^2 + dPdK(K=K, L=L)^2)
  LE <- sqrt(dEdL^2 + dEdK^2)
  dot <- (dPdL(K=K,L=L) * dEdL + dPdK(K=K,L=L)* dEdK)/(LP*LE)
  acos(dot) * 180/pi

}
theta(K=250,L=300)
theta(K=100,L=450)
dPdL(K=110, L=600)
dPdK(K=110, L=600)

contour_plot(theta(K=K,L) ~ L & K, domain(L=300:600, K=50:250)) %>%
  gf_labs(title="Angle between gradient vectors (degrees)", y="Capital", x="Labor") %>%
  gf_refine(coord_fixed())

```

:::


<!--
1. Intro: tin can and cardboard box
1. constraint curves vs constraint functions
2. normal and tangent direction along constraint curve
3. walk along constraint.

##

Shadow prices and lagrange multipliers

## Multiple constraints

Optional


MOVE THE FOLLOWING ELSEWHERE.




As examples of optimization
One important real-world optimization problem stems from the world of molecular biology. Organisms consist in part of a large number of differently shaped proteins that interact with their environment to carry out various biological processes. For example, the COVID-19 virus has a protein in the shape of a spike whose detailed shape is well suited to attaching to another protein found in the membranes of some human cells. By attaching in this way, COVID-19 is able to pass through the cell membrane and infect the cell. Knowing the shape of the spike program can be important to developing drugs that can protect the human cells. With genetic technology, a primary aspect of the structure of the protein can be read directly from the COVID-19 RNA sequence. The optimization problem is to figure out the shape of the spike protein from the amino-acid sequence that the  Many vaccines nowadays involve proteins specifically designed to attach to and disable some part of a virus that is critical to infection. To keep the story short, technology today allows scientists to specify a protein Proteins are polymers of amino acids linked as if they were beads on a necklace. The protein can be specified as a sequence of named amino acids, which can be translated into a DNA sequence of the  long strands.
Our strategy for presenting techniques for optimization will be to start with problems that have two inputs. For such problems, it's possible to graph the objective function and you can watch iterative solution techniques as they approach the solution. Such problems
To illustrate techniques for the solving phase of optimization problems with multiple inputs, we'll use two examples from physics that can straightforwardly be made

--/

