---
id: "panda-go-kayak"
created: "Sun Dec  5 17:06:29 2021"
global_id: "W11rG9"
---

The figure shows an objective function (contour plot) with two different constraints: an inequality constraint (satified outside the blue region), and an equality constraint (brown).

```{r echo=FALSE, warning=FALSE, message=FALSE}
f <- doodle_fun( ~ x + y, seed=421)
g <- doodle_fun( ~ x + y, seed=451)
h <- doodle_fun( ~ x + y, seed=463)
dom <- bounds(x=c(-3, 3), y=c(-3, 3))
contour_plot(f(x,y) ~ x + y, dom, skip=0) %>%
  contour_plot(g(x,y)  ~ x + y, filled=FALSE, 
               contours_at = 0, npts=300,
               contour_color="orange3", size=2, labels=FALSE) %>%
  inequality_constraint(h(x,y)  > 11 ~ x + y, dom, fill="blue", alpha=0.3, npts=200)
```
1. What is the min of the objective function, ignoring the constraints?

2. What is the max of the objective function, ignoring the constraints?

Sometimes, the argmax would **not change** if a constraint were removed entirely. Such constraints are said to be ***inactive***. An ***active constraint*** is one where the presence of the constraint changes the argmax from what it would otherwise be.


3. What is the min and max of the objective function, subject only to the equality constraint? Is the equality constraint active?

4. What is the min and max of the objective function, subject only to the inequality constraint? Is the constraint active?

5. Subject to **both** the equality and the inequality constraints, what is the max of the objective function? Are both constraints active?
