---
id: "spruce-wear-drawer"
created: "Mon Nov 15 08:56:37 2021"
global_id: "zp4ely"
format: "On paper"
---

There can be many ways to describe a given path using $x(t)$ and $y(t)$ functions. Your task in this problem is to construct a few such paths connecting points 10 and 11 in Figure \@ref(fig:robot-points).

To start, draw a pair of coordinate axes: one for $x$ versus $t$ and the other for $y$ versus $t$. For both, arrange the domain for $t$ to be $10 \leq t \leq 11$. The range of the vertical axis for the $x$ versus $t$ frame should cover the $x$-component of the path from point 10 to 11, and similarly for the range of the vertical axis for $y$.

**Task A**

On your axes, sketch the graphs of $x(t)$ and $y(t)$ that will construct a constant-velocity path starting from point 10 at $t=10$ and reaching point 11 at $t=11$. (The term "constant-velocity" has a specific technical meaning. Recall that the $x$-component of velocity will be $\partial_t x(t)$ and similarly for the $y$-component.)

**Task B**

On the same coordinate axes, graph new functions $x_2(t)$ and $y_2(t)$ arranged such that at time $t=10.1$, a position halfway between points 10 and 11 has been reached; at time $10.2$ a position half of the remaining distance to point 11 is reached; at time $10.3$ a point half of the remaining distance to 11 is reached; and so on until point 11 is reached at $t=11$. 

**Task C**

Again on the same coordinate axes (or new ones, if your graphs have become too crowded), graph new functions $x_3(t)$ and $y_3(t)$ such that the position along the path varies smoothly from point 10 at time $t=10$ to point 11 at time $t=11$, but the motion briefly comes to a halt halfway along the path, then starts up again. (Note that "smoothly" has a technical meaning.)

