---
id: "cat-do-pants"
created: "Thu Oct 21 09:16:08 2021"
global_id: "4QzeWP"
exercise_format: "on paper"
---

a. Place a dot on a piece of paper. Hold a pencil perpendicular to the paper  with the eraser on the dot. Now, (using  a pen!) draw a vector on the paper  that is  perpendicular  to  the pencil. Now draw 5 more vectors, each different from the other,  that are all  perpendicular to  the pencil.

b. Draw a vector $\vec{c}$ on the  paper.  Now draw  another vector on the paper that is perpendicular to the first. Label it $\vec{a}$. Find another vector, to be labeled $\vec{b}$ that lies on the paper, is orthogonal  to $\vec{c}$,  and has a different direction from $\vec{a}$. It will turn  out that $\vec{a} = k \vec{b}$.  Write down  the numerical value of the scalar $k$ for your $\vec{a}$ and $\vec{b}$.

c. Consider the vector $\vec{w} \equiv (2, 5)^T$. Using only arithmetic, find  some other vector $\vec{z}$ that is perpendicular  to  $\vec{w}$. (Hint: To be perpendicular, $\vec{z}^T \cdot \vec{w}$ must be zero. So make up  two numbers such  $a$ and $b$ such that $2 a + 5 b  = 0$.) Write $\vec{z}$ on  your paper.

d. Repeat (c) and create another vector  $\vec{z}_2$ that is different from $\vec{z}$. Write  $\vec{z}_2$ on your  paper.  In addition, find the scalar $k$ such  that $\vec{z}_2 = k \vec{z}$.

*In  the following  exercises,  you  are asked to find  numerical vectors that are perpendicular ("orthogonal") to the stated vector. This  is equivalent to  finding a new vector whose dot product with the stated vector is  zero. (Except ... the new vector cannot be all zeros! The all-zero vector is exceptional and has no direction.) One effective strategy is to write down  a vector consisting of a 1 in any position you like  and zeros elsewhere. Find the dot  product, calling it $d$.  Then  select one of the zeros to turn it non-zero. What  value should it have?  Just enough so that when included in the dot  product it contributes $-d$.*

e. Consider the vector $\vec{w} \equiv (1,  2,  -3, 2)^T$. 
    i.  Find a vector $\vec{a}$ that is perpendicular to $\vec{w}$. 
    ii. Find another vector $\vec{b}$ that is perpendicular both  to $\vec{w}$ and to $\vec{a}$. (Hint: It can be done.)
    iii. Create  yet another vector $\vec{c}$ that is a linear combination of $\vec{a}$ and $\vec{b}$.  (You can  choose whatever combination  you  like, but both  coefficients should  be non-zero.) What is the angle between $\vec{c}$ and $\vec{w}$?
    
f. You have been sent on  a mission to 5-dimensional space. Your task is to find  a vector that is perpendicular to  $\vec{w} \equiv (2,1,3,3,-4)^T$. Do so.  

g. BONUS. Find as many vectors as you  can that are  perpendicular  to $\vec{w} \equiv (2,1,3,3,-4)^T$ and to each other. The  arithmetic will not  necessarily be easy. When you  give up (with honor!), figure  out  how  many mutually  perpendicular vectors there  can be in  5-dimensional space. How about 10-dimensional space?

