---
id: "eagle-hold-piano"
created: "Sun Jan 16 09:07:57 2022"
global_id: "vUbXdq"
---


The previous exercise showed how to create mutually orthogonal columns. Generate four such mutually orthogonal vectors: `v1` through `v4`. 

a. Create a target vector `b` with the same dimension as the `v_` vectors. `b` can point in any direction whatsoever, your choice!

b. Using `%onto%, calculate the vector projection of `b` onto the matrix `A <- cbind(v1, v2, v3, v4)`. The result will be a vector. Call this vector `b_model`.

c. A previous exercise gave the formula for the scalar multiplier $\alpha$ of a vector $\vec{v}$ such that $\alpha\,\vec{v} = \modeledby{\vec{b}}{\vec{v}}$: $$\alpha = \frac{\vec{b} \bullet \vec{v}}{\vec{v} \bullet \vec{v}}\ .$$ Use this formula to calculate the four scalars multipliers that result from projecting respectively `b` onto `v1`, `b` onto `v2`, and so on. Call these scalars `alpha1`, `alpha2`, and so on.

d. Calculate the sum `alpha1*v1 + alpha2*v2 + alpha3*v3 + alpha4*v4`. 

Show that the vector found in step (d) matches the vector `b_model` found in step (b). This is a demonstration that, with mutually orthogonal vectors, finding scalar multipliers for a linear combination of those vectors can be done one vector at a time. 

Repeat the above, but this time using vectors `v1`, `v2`, `v3`, and `v4` that are not mutually orthogonal. One way to generate such vectors is at random: `v1 <- cbind(rnorm(4))` and so on. For non-mutually orthogonal vectors, does the one-vector-at-a-time approach produce a match to `b %onto% cbind(v1, v2, v3, v4)`?


