---
id: "kangaroo-light-bowl"
created: "Thu Oct 21 09:08:15 2021"
global_id: "yeY17y"
---




Here is  a direction,  $\vec{\mathbf D}$:

$$\vec{\mathbf D} \equiv  \left(\begin{array}{c}2\\5\end{array}\right)$$


```{r klbU-1, echo=FALSE}
askMC(
  prompt = "Find  the projection of  $\\vec{\\mathbf V} \\equiv (1, 3)^T$ onto $\\vec{\\mathbf D}$.",
      
    "+$0.59 \\vec{\\mathbf D}$+" = "",
    "$\\left(5, 6\\right)^T$" = "The projection of $\\vec{\\mathbf V}$ onto the direction of $\\vec{\\mathbf D}$ will always be a scalar multiple of $\\vec{\\mathbf D}$.",
    "$\\vec{\\mathbf V} - \\left(5, 6\\right)^T$" = "If $\\left(5,6\\right)^T$ were the residual vector, this would be true."
)
```

```{r klbU-2, echo=FALSE}
askMC(
  prompt = "Find  the **residual vector** $\\vec{\\mathbf R}$ from the projection of  $\\vec{\\mathbf V} \\equiv (1, 3)^T$ onto $\\vec{\\mathbf D}$.",
      
    #  "+$\\vec{\\mathbf R} = \\left(0.31, 1.28\\right)^T$+" = "",
    "+$\\vec{\\mathbf R} = \\left(0.83, 2.07\\right)$+" = "",
    "$\\vec{\\mathbf R} = \\left(0.31, 1.28\\right)$" = "The residual  from projecting a column vector onto another column vector will be a column vector",
    "$\\vec{\\mathbf R} = \\left(1.28, 0.31\\right)^T$" = "",
    "$\\vec{\\mathbf R}  = \\left(0.83, 0.31\\right)$" = "Try adding $\\vec{\\mathbf R} + \\vec{\\mathbf V}$ and see if you get $\\vec{\\mathbf D}"
)
```



```{r klbU-3, echo=FALSE}
askMC(
  prompt = "Find  the projection of  $\\vec{\\mathbf V} \\equiv (3, 1)^T$ onto $\\vec{\\mathbf D}$.",
      
    "+$0.379 \\vec{\\mathbf D}$+" = "",
    "$\\left(5, 6\\right)^T$" = "The projection of $\\vec{\\mathbf V}$ onto the direction of $\\vec{\\mathbf D}$ will always be a scalar multiple of $\\vec{\\mathbf D}$.",
    "$\\vec{\\mathbf V} - \\left(5, 6\\right)^T$" = "If $\\left(5,6\\right)^T$ were the residual vector, this would be true."
)
```



```{r klbU-4, echo=FALSE}
askMC(
  prompt = "Find  the **residual vector** $\\vec{\\mathbf R}$ from the projection of  $\\vec{\\mathbf V} \\equiv (3, 1)^T$ onto $\\vec{\\mathbf D}$.",
      
    "+$\\vec{\\mathbf R} = \\left(-0.17, 0.07\\right)^T$+" = "",
    "$\\vec{\\mathbf R} = \\left(-0.17, 0.07\\right)$" = "The residual  from projecting a column vector onto another column vector will be a column vector",
    "$\\vec{\\mathbf R} = \\left(0.07, -0.17\\right)^T$" = "",
    "$\\vec{\\mathbf R}  = \\left(0.07, -0.17\\right)$" = "Try adding $\\vec{\\mathbf R} + \\vec{\\mathbf V}$ and see if you get $\\vec{\\mathbf D}"
)
```

