---
id: "kid-become-pants"
created: "Fri Jan 14 11:25:16 2022"
global_id: "l5UR71"
---

Define the vector $$\vec{v} \equiv \left[\begin{array}{r}4\\1\\3\\-2\end{array}\right]\ .$$

Your task is to construct different vectors that are orthogonal to $\vec{v}$. You can use the trick presented in Section \@ref(orthogonality) of creating templates with zero in all but two of the positions, e.g.
$$\left[\begin{array}{r}0\\0\\\text{__}\\\text{__}\end{array}\right] \ \ \text{or}\ \ \ 
\left[\begin{array}{r}0\\\text{__}\\0\\\text{__}\end{array}\right] \ \ \text{and}\ \ \ 
\left[\begin{array}{r}\text{__}\\\text{__}\\0\\0\end{array}\right]$$
To construct a vector orthogonal to $\vec{v}$, fill in the blanks by taking the corresponding elements of $\vec{v}$, swapping them, and negating one of them. For example, taking the first template will produce

$$\left[\begin{array}{c}0\\0\\\underline{\ 2\ }\\\underline{\ 3\ }\end{array}\right]\ .$$

a. Fill in the blanks of the other two tempates to create vectors orthogonal to $\vec{v}$.

b. Construct 3 new vectors by taking different linear combinations of the vectors you created in (A). Are any of these new vectors orthogonal to $\vec{v}$? Show your work.

c. Prove algebraically that any linear combination of a set of vectors orthogonal to $\vec{x}$ will itself be orthogonal to $\vec{x}$.

