---
id: "octopus-sell-mattress"
created: "Wed Oct 20 11:42:38 2021"
global_id: "dwALW7"
---


Consider the two vectors 
$$\vec{u} \equiv \left(\begin{array}{c}3\\4\end{array}\right) \  \  \ \mbox{and}  \ \ \ \vec{w} \equiv \left(\begin{array}{c}1\\1\\1\\1\end{array}\right)
$$

```{r osmQ-1, echo=FALSE}
askMC(
  "What is the length of the vector $\\vec{u}$?",
    "2" = "There are two elements in $\\vec{u}$, but  that's not what the \"length\" of a vector means.",
    "+5+" = "",
    "25" = "This is the length-squared. Take the square root of it to find the length.",
    "None of the above" = "",
  random_answer_order = FALSE
)
```

```{r osmQ-2, echo=FALSE}
askMC(
  "What is the length of the vector $\\vec{w}$?",
    "+2+" = "Right: $\\sqrt{1^2 + 1^2 + 1^2 + 1^2}$",
    "4" = "There  are four elements in $\\vec{w}$$, and the square-length of $\\vec{v}$ happens  to be 4  ($1^2 + 1^2 + 1^2 + 1^2$), but neither  of  these is the \"length\"  of $\\vec{w}$.",
    "6" = "",
    "None of the above" = "",
  random_answer_order = FALSE
)
```

```{r osmQ-3, echo=FALSE}
askMC(
  "What is $w^T \\circ u$?",
  "7",
  "14",
  "+It doesn't exist.+" = "Two vectors have to have the same dimension for a dot product to make sense.",
  random_answer_order = FALSE
)
```
