---
id: "puppy-dream-spoon"
created: "Thu Oct 21 11:02:46 2021"
global_id: "dvWdE7"
---


Vectors $\vec{A},  \vec{B}, \cdots, \vec{H}$ have been  defined as  `A`, `B`,  ...,  `H` so that you  can  use them in  the sandbox. (To see one of  these vectors, give a command in  the sandbox consisting of just the vector name.) 

```{r}
A <- rbind(2.1,  -3.4)
B <- rbind(0.3, 4.2)
C <- rbind(-2, 3.8)
D <- rbind(1.1,  -3,  2.2,  -1)
E <- rbind(6,  4,  -2,  -1)
F <- rbind(0,  3,  2,  1)
G <- rbind(1, -2,  1,  1)
H <- rbind(-2, 0, 3, 4)
```

::: {.sandbox data-latex=""}
Here is the sequence of commands to project vector `C` onto `A` and `B`.

```{r results="hide"}
M <- cbind(A, B)    # Problem setup: Matrix packaging up vectors
b <- C              # Problem setup: Target vector 
x <- qr.solve(M, b) # Solve the target problem M %*% x = b for x
bhat <- M %*% x     # Result: projected  vector
resid <- b  - bhat  # Result: residual vector
t(A)  %*%  A        # square length of a vector
```
:::

```{r pdsA-A, echo=FALSE}
askMC(
  prompt = "A) Solve  $(\\vec{A},  \\vec{C}) \\cdot \\vec{x} = \\vec{B}$. What is the *length*  of  $\\vec{x}$?",
   "Exactly 0",  "About 1.6", "About  2.5", "About  3.43",  "+About 12+",  "Can't be solved",
  random_answer_order = FALSE)
```

```{r pdsA-B, echo=FALSE}
askMC(
  prompt = "B) Solve $(\\vec{A}) \\cdot \\vec{x} = \\vec{B}$. What's the length of  the *residual*?",
   "Exactly 0", "About  0.3", "About 1.6", "+About  2.5+", "About  3.43",  "About 12",  "Can't be solved",
  random_answer_order = FALSE)
```


```{r pdsA-C, echo=FALSE}
askMC(
  prompt = "D) Solve $(\\vec{D}, \\vec{E})  \\cdot \\vec{x} = \\vec{F}$. What is the  length of the residual?",
   "Exactly 0", "About  0.3", "About 1.6", "About  2.5", "+About  3.43+",  "About 12",  "Can't be solved",
  random_answer_order = FALSE)
```


```{r pdsA-D, echo=FALSE}
askMC(
  prompt = "E) Solve $(\\vec{D}, \\vec{E}, \\vec{F})  \\cdot \\vec{x} = \\vec{G}$. What is the  length of the residual?",
   "Exactly 0", "About 0.3", "+About 1.6+", "About  2.5", "About  3.43",  "About 12",  "Can't be solved",
  random_answer_order = FALSE)
```


```{r pdsA-E, echo=FALSE}
askMC(
  prompt = "F) Solve $(\\vec{D}, \\vec{E}, \\vec{F},  \\vec{G})  \\cdot \\vec{x} = \\vec{H}$. What is the  length of the residual?",
   "+Exactly 0+", "About 0.3", "About 1.6", "About  2.5", "About  3.43",  "About 12",  "Can't be solved",
  random_answer_order = FALSE)
```

