---
id: "rhinosaurus-break-knob"
created: "Wed Oct 20 11:48:18 2021"
global_id: "xuENab"
---



Suppose  $$\vec{\mathbf u} \equiv  \left(\begin{array}{c}4\\-3\end{array}\right)  \  \  \mbox{and}\ \ \vec{\mathbf v} \equiv  \left(\begin{array}{c}2\\2\end{array}\right)\ .$$
The following questions ask you to compute the **length** of the vector given.
(If none  of the available  choices are exactly right, choose the closest.)

```{r rbkD-1, echo=FALSE}
askMC(
  prompt = "$3 \\vec{u}$",
  3, 4, 5, 6,  10, "+15+",  16, 
  random_answer_order = FALSE
)
```

```{r rbkD-2, echo=FALSE}
askMC(
  prompt = "42) $-2 \\vec{u}$",
  "3", 4,  5, 6, "+10+", "15", 16, #c("$\\sqrt{3}$", 4, "$\\sqrt{5}$", 6, "+$\\sqrt{8}$+", "15",  16), 
  random_answer_order = FALSE
)
```

```{r rbkD-3, echo=FALSE}
askMC(
  prompt = "$-\\vec{v}$",
  "+3+"="Right.  it is $\\sqrt{8} = \\sqrt{2^2 + 2^2}$ to be precise.", 
  "4"="",  "5"="", "6"="", "10"="", 
  "15"="", "16"="", 
  random_answer_order = FALSE
)
```

```{r rbkD-4, echo=FALSE}
askMC(
  prompt = "$\\vec{u}+ \\vec{v}$",
  3,  4, 5, "+6+", 10, "15", 16, 
  random_answer_order = FALSE
)
```

```{r rbkD-5, echo=FALSE}
askMC(
  prompt = "$2 \\vec{u} -  5 \\vec{v}$",
  3,  4, 5, "6", 10, "15", "+16+", 
  random_answer_order = FALSE
)
```

