---
id: "shark-understand-saw"
created: "Mon Jul 19 12:59:42 2021"
global_id: "j2ettP"
---

```{r mm1-1, echo=FALSE, results="markup"}
askMC(
  "What's the result of this multiplication:$$\\left[\\begin{array}{rr}-1 & \\frac{3}{4}\\\\1 & 0\\end{array}\\right] \\cdot \\left[\\begin{array}{r}2\\\\1 \\end{array}\\right] ?$$", 
  "+$\\left[\\begin{array}{r}-\\frac{5}{4}\\\\2 \\end{array}\\right]$+",
  "$\\left[\\begin{array}{r}\\frac{5}{4}\\\\\\frac{1}{4} \\end{array}\\right]$",
  "$\\left[\\begin{array}{r}-\\frac{3}{4}\\\\2 \\end{array}\\right]$",
  "$\\left[\\begin{array}{r}\\frac{3}{4}\\\\-2 \\end{array}\\right]$"
)
```

```{r mm1-2, echo=FALSE, results="markup"}
askMC(
  "What's the result of this multiplication:$$\\left[\\begin{array}{rr}3 & 4\\\\1 & 0\\end{array}\\right] \\cdot \\left[\\begin{array}{r}-5\\\\6 \\end{array}\\right] ?$$", 
  "+$\\left[\\begin{array}{r}9\\\\-5 \\end{array}\\right]$+",
  "$\\left[\\begin{array}{r}9\\\\5 \\end{array}\\right]$",
  "$\\left[\\begin{array}{r}-7\\\\5 \\end{array}\\right]$",
  "$\\left[\\begin{array}{r}-7\\\\-5 \\end{array}\\right]$"
)
```

```{r mm1-3, echo=FALSE, results="markup"}
askMC(
  "What's the result of this multiplication:$$\\left[\\begin{array}{rr}0 & -2\\\\1 & 0\\end{array}\\right] \\cdot \\left[\\begin{array}{r}12.62\\\\-7.14 \\end{array}\\right] ?$$", 
  "+$\\left[\\begin{array}{r}14.28\\\\12.62 \\end{array}\\right]$+",
  "$\\left[\\begin{array}{r}-14.28\\\\12.62 \\end{array}\\right]$",
  "$\\left[\\begin{array}{r}14.28\\\\-12.62 \\end{array}\\right]$",
  "$\\left[\\begin{array}{r}12.62\\\\-12.62 \\end{array}\\right]$"
)
```


```{r mm1-4, echo=FALSE, results="markup"}
askMC(
  "All of these vectors point in the same (or exactly opposite) direction, except one:$$
  {\\mathbf v}_1 = \\left[\\begin{array}{r}7.2\\\\-2.4\\end{array}\\right], \\ \\ 
  {\\mathbf v}_2 = \\left[\\begin{array}{r}3.6\\\\1.2\\end{array}\\right],\\ \\ 
  {\\mathbf v}_3 = \\left[\\begin{array}{r}3.6\\\\-1.2\\end{array}\\right],\\ \\ 
  {\\mathbf v}_4 = \\left[\\begin{array}{r}-1.8\\\\0.6\\end{array}\\right]
  $$ Which is the one exception?", 
  "${\\mathbf v}_1$",
  "+${\\mathbf v}_2$+",
  "${\\mathbf v}_3$",
  "${\\mathbf v}_4$",
  random_answer_order = TRUE
)
```

```{r mm1-5, echo=FALSE, results="markup"}
askMC(
  "All of these vectors point in the same (or exactly opposite) direction, except one:$$
  {\\mathbf u}_1 = \\left[\\begin{array}{r}\\sqrt{2}/2\\\\\\sqrt{12}\\end{array}\\right], \\ \\ 
  {\\mathbf u}_2 = \\left[\\begin{array}{r}1/\\sqrt{2}\\\\2\\sqrt{3}\\end{array}\\right],\\ \\ 
  {\\mathbf u}_3 = \\left[\\begin{array}{r}-1/\\sqrt{2}\\\\-\\sqrt{2}\\sqrt{6}\\end{array}\\right],\\ \\ 
  {\\mathbf u}_4 = \\left[\\begin{array}{r}\\sqrt{2}/4\\\\\\sqrt{6}\\end{array}\\right],\\ \\ 
  {\\mathbf u}_5 = \\left[\\begin{array}{r}\\sqrt{2}/4\\\\\\sqrt{3}\\end{array}\\right]
  $$ Which is the one exception?", 
  "${\\mathbf u}_1$",
  "${\\mathbf u}_2$",
  "${\\mathbf u}_3$",
  "+${\\mathbf u}_4$+",
  "${\\mathbf u}_5$",
  random_answer_order = TRUE
)
```


