---
id: "snake-ride-glasses"
created: "Wed Oct 20 12:26:57 2021"
global_id: "1Jxboc"
---


In this exercise, you will *check* proposed solutions to the target problem. Each question poses one target problem. One of the answers is correct. Use R in a `r sandbox_link()` to select the correct answer.

The vectors you will be working with are:
$$\vec{a} \equiv \left(\begin{array}{c}1\\2\end{array}\right)\ \ \ \ \vec{b}  \equiv \left(\begin{array}{c}1\\1\end{array}\right)\ \ \ \ \vec{c}  \equiv \left(\begin{array}{c}1\\-2\end{array}\right)\ \ \ \ \vec{d}  \equiv \left(\begin{array}{c}-6\\2\end{array}\right)\ \ \ \ \vec{T}  \equiv \left(\begin{array}{c}3\\-1\end{array}\right)\ \ \ \ $$


```{r srgM-9, echo=FALSE}
askMC(
  prompt = "**i.** What linear combination  of $\\vec{a}$  and  $\\vec{b}$ will  reach target  $T$?",
    "$3\\vec{a} - 7\\vec{b}$" = "",
    "$\\vec{a} + 2\\vec{b}$" = "",
     "+$-4 \\vec{a} + 7 \\vec{b}$+" = "",
    "$- \\vec{a} + 4\\vec{b}$" = "",
    "No combination will reach $\\vec{T}$ exactly." = "Two 2-dimensional  vectors pointing in different directions can reach any point in the plane.",
    "None of the above" = "",
  random_answer_order = FALSE
)
```

```{r srgM-10, echo=FALSE}
askMC(
  prompt = "**ii.** What linear combination  of $\\vec{b}$  and  $\\vec{c}$ will  reach target  $T$?",
    "$\\frac{4}{3}\\vec{b} - \\frac{5}{3}\\vec{c}$" = "",
    "$\\frac{2}{3}\\vec{b} + \\frac{7}{3}\\vec{c}$" = "",
    "$-\\frac{7}{3}\\vec{b} + \\frac{5}{3}\\vec{c}$" = "",
    "+$\\frac{5}{3} \\vec{b} + \\frac{4}{3} \\vec{c}$+" = "",
    "No combination will reach $\\vec{T} exactly." = "Two 2-dimensional  vectors pointing in different directions can reach any point in the plane.",
    "None of the above" = "",
  random_answer_order = FALSE
)
```

```{r srgM-11, echo=FALSE}
askMC(
  prompt = "**iii.** What linear combination  of $\\vec{b}$  and  $\\vec{d}$ will  reach target  $T$?",
    "$0\\vec{b} - \\frac{3}{2}\\vec{d}$" = "",
    "$\\frac{1}{2}\\vec{b} + \\frac{1}{2}\\vec{d}$" = "",
    "+$0 \\vec{b} - \\frac{1}{2} \\vec{d}$+" = "",
    "$\\frac{3}{2}\\vec{b} + \\frac{1}{2}\\vec{d}$" = "",
    "No combination will reach $\\vec{T} exactly." = "Two 2-dimensional  vectors pointing in different directions can reach any point in the plane.",
    "None of the above" = "",
  random_answer_order = FALSE
)
```


```{r srgM-12, echo=FALSE}
askMC(
  prompt = "**iv.** Which of these linear combinations  of $\vec{a}$,  $\\vec{b}$  and  $\\vec{c}$ will  reach target  $T$?",
    "$\\vec{a} -\\vec{b} - 2\\vec{c}$" = "",
    "$2\\vec{a} +\\vec{b} - 2\\vec{c}$" = "",
    "+$2\\vec{a} -\\vec{b} + 2\\vec{c}$+" = "",
    "$-2\\vec{a} +\\vec{b} + 2\\vec{c}$" = "",
    "No combination will reach $\\vec{T} exactly." = "Two 2-dimensional  vectors pointing in different directions can reach any point in the plane. Adding a third vector just increases the number of  possibilities.",
    "None of the above" = "",
  random_answer_order = FALSE
)
```


