<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
  <meta charset="utf-8">
  <meta name="generator" content="quarto-0.9.80">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
  <title>MOSAIC Calculus - 31&nbsp; The target problem</title>
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    span.underline{text-decoration: underline;}
    div.column{display: inline-block; vertical-align: top; width: 50%;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      {   }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span.al { color: #ff0000; font-weight: bold; } /* Alert */
    code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
    code span.at { color: #7d9029; } /* Attribute */
    code span.bn { color: #40a070; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #4070a0; } /* Char */
    code span.cn { color: #880000; } /* Constant */
    code span.co { color: #60a0b0; font-style: italic; } /* Comment */
    code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
    code span.do { color: #ba2121; font-style: italic; } /* Documentation */
    code span.dt { color: #902000; } /* DataType */
    code span.dv { color: #40a070; } /* DecVal */
    code span.er { color: #ff0000; font-weight: bold; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #40a070; } /* Float */
    code span.fu { color: #06287e; } /* Function */
    code span.im { } /* Import */
    code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
    code span.kw { color: #007020; font-weight: bold; } /* Keyword */
    code span.op { color: #666666; } /* Operator */
    code span.ot { color: #007020; } /* Other */
    code span.pp { color: #bc7a00; } /* Preprocessor */
    code span.sc { color: #4070a0; } /* SpecialChar */
    code span.ss { color: #bb6688; } /* SpecialString */
    code span.st { color: #4070a0; } /* String */
    code span.va { color: #19177c; } /* Variable */
    code span.vs { color: #4070a0; } /* VerbatimString */
    code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
  </style>

  <script src="../site_libs/quarto-nav/quarto-nav.js"></script>
  <script src="../site_libs/quarto-nav/headroom.min.js"></script>
  <script src="../site_libs/clipboard/clipboard.min.js"></script>
  <meta name="quarto:offset" content="../">
  <script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
  <script src="../site_libs/quarto-search/fuse.min.js"></script>
  <script src="../site_libs/quarto-search/quarto-search.js"></script>
  <link href="../Linear-combinations/B5-stat-modeling.html" rel="next">
  <link href="../Linear-combinations/B5-projection.html" rel="prev">
  <script src="../site_libs/quarto-html/quarto.js"></script>
  <script src="../site_libs/quarto-html/popper.min.js"></script>
  <script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
  <script src="../site_libs/quarto-html/anchor.min.js"></script>
  <link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
  <link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet">
  <script src="../site_libs/bootstrap/bootstrap.min.js"></script>
  <link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
  <link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet">
  <script id="quarto-search-options" type="application/json">{
    "location": "sidebar",
    "copy-button": false,
    "collapse-after": 2,
    "panel-placement": "start",
    "type": "textbox",
    "limit": 20,
    "language": {
      "search-no-results-text": "No results",
      "search-matching-documents-text": "matching documents",
      "search-copy-link-title": "Copy link to search",
      "search-hide-matches-text": "Hide additional matches",
      "search-more-match-text": "more match in this document",
      "search-more-matches-text": "more matches in this document",
      "search-clear-button-title": "Clear",
      "search-detached-cancel-button-title": "Cancel",
      "search-submit-button-title": "Submit"
    }
  }</script>
  <script async="" src="https://hypothes.is/embed.js"></script>
  </head><body class="floating slimcontent"><span class="math inline" style="display: none;">
  \(\newcommand{\line}{\text{line}}
  \newcommand{\hump}{\text{hump}}
  \newcommand{\sigmoid}{\text{sigmoid}}
  \newcommand{\recip}{\text{recip}}
  \newcommand{\diff}[1]{{\cal D}_#1}
  \newcommand{\pnorm}{\text{pnorm}}
  \newcommand{\dnorm}{\text{dnorm}}
  \let\origvec\vec
  \let\origmathit\mathit
  \let\orighat\hat
  \let\origbar\bar
  \newcommand{\vec}[1]{\overset{{\rule[-1pt]{0mm}{1mm}}\rightharpoonup}{\mathbf{#1}}}
  \newcommand{\bar}[1]{\overset{{\rule[-1pt]{12pt}{.5mm}}}{\mathbf{#1}}}
  \newcommand{\mathit}[1]{\underset{\leftharpoondown}{\overset{{\rightharpoonup}}{\large\mathbf #1}}}
  \newcommand{\hat}[1]{\widehat{\ \mathbf#1\ }}
  \newcommand{\len}[1]{{\|{\mathbf #1}\|}}
  \newcommand{\tvec}[1]{\overset{\uparrow}{\mathbf #1}}
  \newcommand{\tmat}[1]{\overset{\leftrightarrows}{\mathbf #1}}
  \newcommand{\perpendicularto}[2]{#1\!\perp\!#2}
  \newcommand{\modeledby}[2]{#1\!\sim\!#2}
  \newcommand{\CC}[1]{\color{#648fff}{#1}}
  \newcommand{\CE}[1]{\color{#785ef0}{#1}}
  \newcommand{\CA}[1]{\color{#dc267f}{#1}}
  \newcommand{\CB}[1]{\color{#fe6100}{#1}}
  \newcommand{\CD}[1]{\color{#ffb000}{#1}}\)
  </span>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>
  <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv-printshiv.min.js"></script>
  <![endif]-->
  <link rel="stylesheet" href="../mosaic-calc-style.css">


<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">The target problem</span></h1>
      <button type="button" class="quarto-btn-toggle btn">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">MOSAIC Calculus</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/dtkaplan/MC2/" title="Source Code" class="sidebar-tool px-1"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">Preface</a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a href="../preliminaries-part.html" class="sidebar-item-text sidebar-link">Preliminaries</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-preliminaries-partqmd" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-preliminaries-partqmd" class="collapse list-unstyled sidebar-section depth1 show">  
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Preliminaries/01-modeling-change.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Quantity, function, space</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Preliminaries/02-notation.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Notation</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Preliminaries/03-computing.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Computing with R</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Preliminaries/04-graphs-and-graphics.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Visualizing functions</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Preliminaries/05-pattern-book-functions.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Pattern-book functions</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Preliminaries/06-describing-functions.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Describing functions</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Preliminaries/07-data-and-data-graphics.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Data and data graphics</span></a>
  </div>
</li>
    </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a href="../modeling-part.html" class="sidebar-item-text sidebar-link">Modeling</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-modeling-partqmd" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-modeling-partqmd" class="collapse list-unstyled sidebar-section depth1 show">  
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Modeling/01-parameters.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Parameters</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Modeling/02-assembling-functions.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Assembling functions</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Modeling/03-functions-with-multiple-inputs.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Functions with multiple inputs</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Modeling/04-fitting-by-eye.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Fitting features</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Modeling/05-low-order-polynomials.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Low-order polynomials</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Modeling/06-operations.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Operations on functions</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Modeling/07-magnitudes.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Magnitude</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Modeling/08-dimensions.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Dimensions and units</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Modeling/09-modeling-cycle.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Modeling cycle [DRAFT]</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Modeling/Modeling-projects.html" class="sidebar-item-text sidebar-link">Projects</a>
  </div>
</li>
    </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a href="../differentiation-part.html" class="sidebar-item-text sidebar-link">Differentiation</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-differentiation-partqmd" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-differentiation-partqmd" class="collapse list-unstyled sidebar-section depth1 show">  
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Differentiation/16-continuous-change.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Continuous change</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Differentiation/17-rate-of-change.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Rate of change</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Differentiation/18-evanescent-h.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Evanescent h</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Differentiation/19-computing.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Constructing derivatives</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Differentiation/20-concavity.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Concavity and curvature</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Differentiation/21-cont-and-smooth.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Continuity and smoothness</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Differentiation/22-rules.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Derivatives of assembled functions</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Differentiation/23-optim.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Optimization</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Differentiation/24-partial.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Partial change and the gradient vector</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Differentiation/25-approximation.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Local approximations [DRAFT]</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Differentiation/26-taylor.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Polynomials</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Differentiation/Differentiation-projects.html" class="sidebar-item-text sidebar-link">Projects</a>
  </div>
</li>
    </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a href="../linear-combinations-part.html" class="sidebar-item-text sidebar-link">Vectors and linear combinations</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-linear-combinations-partqmd" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-linear-combinations-partqmd" class="collapse list-unstyled sidebar-section depth1 show">  
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Linear-combinations/B5-Vectors.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Vectors</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Linear-combinations/B5-linear-combinations.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Linear combinations of vectors</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Linear-combinations/B5-projection.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Projection &amp; residual</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Linear-combinations/B5-target-problem.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">The target problem</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Linear-combinations/B5-stat-modeling.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Statistical modeling and R<sup>2</sup></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Linear-combinations/B5-functions.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Functions as vectors</span></a>
  </div>
</li>
    </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a href="../accumulation-part.html" class="sidebar-item-text sidebar-link">Accumulation</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-accumulation-partqmd" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-accumulation-partqmd" class="collapse list-unstyled sidebar-section depth1 show">  
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Accumulation/27-intro.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Change &amp; accumulation</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Accumulation/28-visualizing.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">Totaling the little bits</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Accumulation/29-integration.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">Integration</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Accumulation/30-euler.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title">Integrals step-by-step</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Accumulation/31-symbolic.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">38</span>&nbsp; <span class="chapter-title">Symbolic anti-differentiation</span></a>
  </div>
</li>
    </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a href="../dynamics-part.html" class="sidebar-item-text sidebar-link">Dynamics</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-dynamics-partqmd" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-dynamics-partqmd" class="collapse list-unstyled sidebar-section depth1 show">  
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Dynamics/B6-diff-eq.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">39</span>&nbsp; <span class="chapter-title">Differential equations</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Dynamics/B6-solution.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">40</span>&nbsp; <span class="chapter-title">Finding a “solution”</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Dynamics/B6-flow-on-line.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">41</span>&nbsp; <span class="chapter-title">Flows on the line</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Dynamics/B6-flow-on-plane.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">42</span>&nbsp; <span class="chapter-title">Flows on the plane</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Dynamics/B6-modeling.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">43</span>&nbsp; <span class="chapter-title">Modeling dynamics</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Dynamics/B6-equilibria.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">44</span>&nbsp; <span class="chapter-title">Equilibrium and transient</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Dynamics/B6-eigen.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">45</span>&nbsp; <span class="chapter-title">Eigenvalues, eigenvectors</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Dynamics/B6-second-order.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">46</span>&nbsp; <span class="chapter-title">Force-balance equations</span></a>
  </div>
</li>
    </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
    <div class="sidebar-item-container"> 
        <a href="../manifestations-part.html" class="sidebar-item-text sidebar-link">Manifestations</a>
      <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-manifestations-partqmd" aria-expanded="true">
        <i class="bi bi-chevron-right ms-2"></i>
      </a>
    </div>
    <ul id="quarto-sidebar-section-manifestations-partqmd" class="collapse list-unstyled sidebar-section depth1 show">  
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Manifestations/B4-operations.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">47</span>&nbsp; <span class="chapter-title">Operations on functions</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Manifestations/B4-splines.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">48</span>&nbsp; <span class="chapter-title">Data-driven functions</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Manifestations/B4-optimization.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">49</span>&nbsp; <span class="chapter-title">Optimization and constraint</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Manifestations/B4-probability.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">50</span>&nbsp; <span class="chapter-title">Probability and evidence</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Manifestations/B4-future-value.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">51</span>&nbsp; <span class="chapter-title">Present and future value</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Manifestations/B4-mechanics.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">52</span>&nbsp; <span class="chapter-title">Mechanics</span></a>
  </div>
</li>
    </ul>
  </li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc">
<h2 id="toc-title">Table of contents</h2>
<ul>
<li><a href="#sec-linear-equations" class="nav-link active" data-scroll-target="#sec-linear-equations"> <span class="header-section-number">31.1</span> Linear equations</a></li>
<li><a href="#visualization-in-a-two-dimensional-subspace" class="nav-link" data-scroll-target="#visualization-in-a-two-dimensional-subspace"> <span class="header-section-number">31.2</span> Visualization in a two-dimensional subspace</a></li>
<li><a href="#properties-of-the-solution" class="nav-link" data-scroll-target="#properties-of-the-solution"> <span class="header-section-number">31.3</span> Properties of the solution</a></li>
<li><a href="#application-of-the-target-problem" class="nav-link" data-scroll-target="#application-of-the-target-problem"> <span class="header-section-number">31.4</span> Application of the target problem</a></li>
<li><a href="#exercises" class="nav-link" data-scroll-target="#exercises"> <span class="header-section-number">31.5</span> Exercises</a></li>
</ul>
<div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.com/dtkaplan/MC2/edit/main/Linear-combinations/B5-target-problem.Rmd" class="toc-action">Edit this page</a></p></div></div></nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">
<header id="title-block-header">
<h1 class="title display-7"><span id="sec-target-problem" class="quarto-section-identifier d-none d-lg-block"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">The target problem</span></span></h1>
</header>

<div class="cell" data-layout-align="center" data-fig.showtext="false">

</div>
<blockquote class="blockquote">
<p><em>“In theory there is no difference between theory and practice, while in practice there is.”</em></p>
</blockquote>
<p>In this chapter, we ask you to reconsider a mathematical theory that is universally taught in high-school and to consider augmenting it with newer computational ideas that address the same kind of problems, but which produce useful results even when the mathematical theory insists the “a solution does not exist.”</p>
<p>The time-honored theory is that taught in high-school algebra. There is nothing wrong with that theory except that it is incomplete. It does not address the needs of present-day practice, particularly in data science, statistics, and machine learning.</p>
<p>Algebra, in its basic sense, is about generalizing arithmetic to handle situations where some quantities are not yet known numerically and so are represented by symbols. The algebra student learns rules for symbolic expressions that allow the expressions to be re-arranged into other forms that would plainly be valid if replaced by numbers. Some examples of these rules:</p>
<p>i. <span class="math inline">\(ax = b\)</span> is equivalent to <span class="math inline">\(x = a/b\)</span>.</p>
<p>ii. <span class="math inline">\(a + x = b\)</span> is equivalent to <span class="math inline">\(x=b-a\)</span>.</p>
<p>iii. <span class="math inline">\(a x^2 + b x + c = 0\)</span> is equivalent to <span class="math inline">\(x = \frac{-b\pm \sqrt{\strut b^2 - 4ac}}{2a}\)</span>.</p>
<p>iv. <span class="math inline">\(\ln(ax) = b\)</span> is equivalent to <span class="math inline">\(x = \frac{1}{a}\ln(b)\)</span>.</p>
<p>A major challenge to the algebra student is to use such rules to re-arrange expressions into a form <span class="math inline">\(x=\)</span> that enables <span class="math inline">\(x\)</span> to be calculated from the numerical values of the other symbols. Unfortunately, students are given little or no insight to the historical origins of algebra techniques and why they are not necessarily appropriate for all tasks.</p>
<p>In English, the word “algebra” is seen as early as 1551. It comes from a book written by the Persian Muhammad ibn Musa al-Khwarizmi (780-850), <em>The Compendious Book on Calculation by Completion and Balancing</em>. The book introduced the use of rules familiar to every algebra student. In the original Arabic, the title includes the word “al-jabr,” meaning “completion” or “rejoining.” According to some sources, the literal meaning of “al-jabr” was resetting and rejoining broken bones. That literal meaning correctly conveys the importance of the subject, but also the pain endured by many algebra students. (Incidentally, the “algorithm” comes from the name of the book’s author: al Khwarizmi. He is a major figure in the history of mathematics.)</p>
<p>This history may not be of immediate interest to every reader, but there is a good point to it. The roots of algebra are ancient and developed in an era very different from our own. Today’s student learns algebra to facilitate the study and practice of physics, chemistry, statistics, engineering, and other fields. None of these fields existed when algebra was being conceived. That is, the theory was developed before the recognition of the problems and calculations that arise in modern practice. Thus, “in practice, theory and practice are different.”</p>
<p>This chapter is about re-expressing some basic algebraic theory to align it better to today’s practice.</p>
<section id="sec-linear-equations" class="level2" data-number="31.1">
<h2 data-number="31.1" class="anchored" data-anchor-id="sec-linear-equations"><span class="header-section-number">31.1</span> Linear equations</h2>
<p>The focus of interest will be the familiar task</p>
<p><span class="math display">\[\ \ \ \ \ \ \text{given}\ \ a x = b\,,\ \ \text{find}\ \ x\ .\]</span> All algebra students learn that <span class="math inline">\(x = b/a\)</span>, with the proviso that if <span class="math inline">\(a = 0\)</span>, “there is no solution.”</p>
<p>A somewhat more advanced algebra task is to work with “simultaneous linear equations,” for example: <span class="math display">\[\ \ \ \text{given}\ \ \ \begin{array}{rrrcr}
3 x &amp; + &amp; 2 y &amp; = &amp; 7\\
-1&amp;+&amp;y&amp;=&amp;4\end{array}
\ \ \ \ \text{find}\ \ x\,\&amp;\,y\ .
\]</span></p>
<p>Solving simultaneous linear equations is hard. It involves more arithmetic than <span class="math inline">\(ax = b\)</span> and requires the student to make good choices how to take linear combinations of the two equations to reduce the problem to two equations, one with <span class="math inline">\(x\)</span> as the only unknown and one with <span class="math inline">\(y\)</span>. Also, the “there is no solution” proviso is not easy to state, so you cannot know at a glance whether there is indeed a solution.</p>
<p>The simultaneous linear equation problem can be more compactly written using matrix and vector notation. <span class="math display">\[\begin{array}{rrrcr}3x &amp; + &amp;2y &amp; = &amp; 7\\-1&amp;+&amp;y&amp;=&amp;4\end{array} \ \ \text{is the same as}\ \ \left[\begin{array}{r}3\\-1\end{array}\right] x + \left[\begin{array}{r}2\\1\end{array}\right] y =
\left[\begin{array}{r}7\\4\end{array}\right] \]</span> You can see the vector form as a linear combination of two vectors. Collecting these two vectors into a matrix <span class="math inline">\(\mathit{A}\)</span>, and similarly writing <span class="math inline">\(x\, \text{and}\, y\)</span> as the scalar components of a vector <span class="math inline">\(\vec{x}\)</span> gives <span class="math display">\[\left[\begin{array}{rr}3&amp;2\\-1&amp;1\end{array}\right]\ \vec{x} = \left[\begin{array}{r}7\\4\end{array}\right]\]</span> Which can be expressed as <span class="math inline">\(\mathit{A} \vec{x} = \vec{b}\)</span>.</p>
<p>A student, recognizing the similarity of <span class="math inline">\(\mathit{A}\vec{x} = \vec{b}\)</span> to <span class="math inline">\(a x = b\)</span> would reasonably suggest the solution <span class="math inline">\(\vec{x} = \vec{b}/ \mathit{A}\)</span>. Such a student might be instructed, “No, you cannot do this.” A better response would be, “Good. Now tell me what you mean by <span class="math inline">\(\vec{b}/\mathit{A}\)</span>?”</p>
<p>Modern practice often calls for solving <span class="math inline">\(\mathit{A}\vec{x} = \vec{b}\)</span> in settings where a traditional algebra teacher might say, as for <span class="math inline">\(0 x = b\)</span> that “there is no solution.”</p>
<p>To illustrate such a setting, recall the problems from Section <a href="../Modeling/04-fitting-by-eye.html#sec-exponential-water">Section&nbsp;<span>11.3</span></a> of finding the linear combination of the functions <span class="math inline">\(f(\mathtt{time})=1\)</span> and <span class="math inline">\(g(\mathtt{time}) = e^{-0.019 \mathtt{time}}\)</span> that best matches the <code>CoolingWater</code> data:</p>
<div class="cell" data-layout-align="center" data-fig.showtext="false">
<div class="cell-output-display">
<table>
 <thead>
  <tr>
   <th style="text-align:right;"> time </th>
   <th style="text-align:right;"> temp </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 98.2 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 94.4 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 2 </td>
   <td style="text-align:right;"> 91.4 </td>
  </tr>
  <tr><td colspan="2" align="center">... and so on ...</td></tr>
  <tr>
  </tr>
  <tr>
   <td style="text-align:right;"> 220 </td>
   <td style="text-align:right;"> 25.9 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 221 </td>
   <td style="text-align:right;"> 25.8 </td>
  </tr>
</tbody>
</table>

</div>
</div>
<p>We seek scalars <span class="math inline">\(C\)</span> and <span class="math inline">\(D\)</span> such that the function <span class="math inline">\(C f(\mathtt{time}) + D g(\mathtt{time})\)</span> gives the best possible match to <code>temp</code>.</p>
<p>We can compactly write the problem of finding the best linear combination into matrix form by evaluating <span class="math inline">\(f()\)</span> and <span class="math inline">\(g()\)</span> at the values listed in the <code>time</code> column: <span class="math display">\[\underbrace{\left[\begin{array}{rr}1&amp;1.0000\\1&amp;0.9812\\1&amp;0.9627\\\vdots\\1&amp;0.0153\\1&amp;0.0150\end{array}\right]}_{\!\!\!\!\!\!\!\!{\large\mathit{A}} = \left[\strut f(\mathtt{time})\,,\ \ \ g(\mathtt{time})\right]} \underbrace{\left[\begin{array}{r}C\\D\end{array}\right]}_{\large\vec{x}} \ \text{is the best match to}\  \underbrace{\left[\begin{array}{r}\mathtt{98.2}\\\mathtt{94.4}\\\mathtt{91.4}\\\vdots\\\mathtt{25.9}\\\mathtt{25.8}\end{array}\right]}_{\large\vec{b}}\]</span></p>
<p>Regrettably, the classical algebraicists did not propose a rule for “is the best match to.” Replacing “is the best match to” with <span class="math inline">\(=\)</span> is not literally correct since “there is no solution” that makes the equality literally true.</p>
<p>We will use the term <strong><em>target problem</em></strong> to name the task of finding <span class="math inline">\(\vec{x}\)</span> such that <span class="math inline">\(\mathit{A} \vec{x}\)</span> is the best possible match to <span class="math inline">\(\vec{b}\)</span>. This term is motivated by the idea that <span class="math inline">\(\vec{b}\)</span> is a target, and we seek to use the resources in <span class="math inline">\(\mathit{A}\)</span> to get as close as possible to the target: choose <span class="math inline">\(\vec{x}\)</span> such that <span class="math inline">\(\mathit{A} \vec{x}\)</span> falls as closely as possible to the target.</p>
<p>To address the practical problem in the notation of algebra theory, people write <span class="math display">\[\mathit{A} \vec{x} = \vec{b} - \vec{r}\]</span> where <span class="math inline">\(\vec{r}\)</span> is a vector specially selected to path up <span class="math inline">\(\mathit{A} \vec{x} = \vec{b}\)</span> so that when the best-matching <span class="math inline">\(C\)</span> and <span class="math inline">\(D\)</span> are found, there will be a literal equality solution to <span class="math inline">\(\mathit{A} \vec{x} = \vec{b} - \vec{r}\)</span>.</p>
<p>At first glance, <span class="math inline">\(\mathit{A} \vec{x} = \vec{b} - \vec{r}\)</span> might seem intractable: How are we to find <span class="math inline">\(\vec{r}\)</span>. The answer is that <span class="math inline">\(\vec{r}\)</span> will be the solution to the projection problem <span class="math inline">\(\vec{b}\sim\mathit{A}\)</span>. When <span class="math inline">\(\vec{r}\)</span> is selected this way, <span class="math inline">\(\vec{r}\)</span> will be the shortest possible vector that can do the matching up. In other words, by choosing <span class="math inline">\(\vec{r} = \vec{b} \sim \mathit{A}\)</span> we are implementing the following definition of “is the best match to”: “the best match is the one with the smallest length <span class="math inline">\(\vec{r}\)</span>.”</p>
<p>It is remarkable that one can find <span class="math inline">\(\vec{r}\)</span> even without knowing <span class="math inline">\(\vec{x}\)</span>. That is why we introduced and solved the <strong><em>projection problem</em></strong> before taking on the <strong><em>target problem</em></strong>.</p>
<p>The part of the target problem that we have still to figure out is how, given <span class="math inline">\(\vec{r}\)</span>, to find <span class="math inline">\(\vec{x}\)</span>. But even at this point you can see that <span class="math inline">\(\mathit{A}\vec{x} = \vec{b} - \vec{r}\)</span> must have a solution, since <span class="math inline">\(\vec{b} - \vec{r}\)</span> is exactly the model vector <span class="math inline">\(\hat{b}\)</span> which, as we saw in Chapter <a href="B5-projection.html">Section&nbsp;<span>30</span></a>), must lie in <span class="math inline">\(span{\mathit{A}}\)</span>.</p>
</section>
<section id="visualization-in-a-two-dimensional-subspace" class="level2 page-columns page-full" data-number="31.2">
<h2 data-number="31.2" class="anchored" data-anchor-id="visualization-in-a-two-dimensional-subspace"><span class="header-section-number">31.2</span> Visualization in a two-dimensional subspace</h2>
<p>To help you create a mental model of the geometry of the target problem, we will solve it graphically for a two dimensional subspace. That is, we will solve <span class="math inline">\(\left[\vec{u}, \vec{v}\right] \vec{x} = \vec{b}\)</span>. For simplicity, the vectors <span class="math inline">\(\vec{u}\)</span>, <span class="math inline">\(\vec{v}\)</span> and <span class="math inline">\(\vec{b}\)</span> will have two components. This means that there is no need to project <span class="math inline">\(\vec{b}\)</span> onto the subspace; it is already there (so long as <span class="math inline">\(\vec{u}\)</span> and <span class="math inline">\(\vec{v}\)</span> have different directions. )</p>
<p>You may already have encountered the step (ii) technique in your childhood reading. The problem appears in Robert Louis Stevenson’s famous novel, <a href="https://www.gutenberg.org/cache/epub/120/pg120-images.html#link2H_4_0039"><em>Treasure Island</em></a>. The story is about the discovery of a treasure map indicating the location of buried treasure on the eponymous Island. There is a red X on the map labelled “bulk of treasure here,” but that is hardly sufficient to guide the dig for treasure. After all, every buried treasure needs some secret to protect it. On the back of the map is written a cryptic clue to the precise location:</p>
<blockquote class="blockquote">
<p>Tall tree, Spy-glass shoulder, bearing a point to the N. of N.N.E.<br>
Skeleton Island E.S.E. and by E.<br>
Ten feet.</p>
</blockquote>
<p>Skeleton Island is marked on the map, as is Spy-glass Hill. The plateau marked by the red X “was dotted thickly with pine-trees of varying height. Every here and there, one of a different species rose forty or fifty feet clear above its neighbors.” But which of these was the “tall tree” mentioned in the clue?</p>
<div class="cell page-columns page-full" data-layout-align="center" data-fig.showtext="false">
<div class="cell-output-display page-columns page-full">
<div id="fig-treasure-island" class="quarto-figure quarto-figure-center anchored page-columns page-full">
<figure class="figure page-columns page-full">
<p><img src="www/drawings/treasure-island-annotated.png" class="img-fluid figure-img" style="width:70.0%"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption margin-caption">Figure 31.1: The map of <em>Treasure Island</em>. The heading ‘E.S.E. and by E.’ is marked with a solid black line starting at Skeleton Island. The heading ‘N. of N.N.E.’ is marked by dotted lines, one of which is positioned to point at the shoulder of Spy-glass Hill. Where the bearing from Skeleton Island meets the bearing to Spy-glass Hill will be the Tall tree.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>With your new-found background in vectors, you will no doubt recognize that “N. of N.N.E” is the direction of a vector as is “E.S.E. and by E.” Pirate novels seem always to use the length unit of “pace,” which we will use here as well. The target is the shoulder of Spy-glass Hill. Or, in vector terms, <span class="math inline">\(\vec{b}\)</span> is the vector with Skeleton Island as the tail and the should of Spy-glass Hill as the tip. The vectors are <span class="math inline">\(\vec{u} = \text{N. of N.N.E.}\)</span> and <span class="math inline">\(\vec{v} = \text{E.S.E. and by E.}\)</span> We need to <span class="math display">\[\text{solve} \ \ \underbrace{\left[\vec{u}, \vec{v}\right]}_{\Large\strut\mathit{A}} \underbrace{\small\left[\begin{array}{c}C\\D\end{array}\right]}_{\Large\vec{x}} = \vec{b}\ \ \text{for}\ \ {\small\left[\begin{array}{c}C\\D\end{array}\right]}\ .\]</span></p>
<p>Long John Silver, obviously an accomplished mathematician, starts near Skeleton Island, moving on along the vector that keeps Skeleton Island to the compass bearing one point east of east-south-east. While on the march, he keeps a telescope trained on the shoulder of Spy-glass Hill. When that telescope points one point north of north-north-east, they are in the vicinity of a tall tree. That is the tree matching the clue.</p>
<p>The vectors in <em>Treasure Island</em> were perpendicular to one another, that is, <strong><em>mutually orthogonal</em></strong>. The more general situation is that the vectors in <span class="math inline">\(\mathit{A}\)</span> will be somewhat aligned with one another: not mutually orthogonal. <a href="#fig-telescope">Figure&nbsp;<span>31.2</span></a> illustrates the situation: <span class="math inline">\(\vec{v}\)</span> is not perpendicular to <span class="math inline">\(\vec{u}\)</span>. The task, still, is to find a linear combination of <span class="math inline">\(\vec{u}\)</span> and <span class="math inline">\(\vec{v}\)</span> that will match <span class="math inline">\(\vec{b}\)</span>. The diagram shows the <span class="math inline">\(\vec{u}\)</span> vector and the subspace aligned with <span class="math inline">\(\vec{u}\)</span>, and similarly for <span class="math inline">\(\vec{v}\)</span></p>
<div class="cell page-columns page-full" data-layout-align="center" data-fig.showtext="false">
<div class="cell-output-display column-page-inset-right">
<div id="fig-telescope" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="www/drawings/u-v-spyglass.png" class="img-fluid figure-img" style="width:90.0%"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">Figure 31.2: The telescope method of solving projection onto two vectors.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>The algorithm is based in Long John Silver’s technique. Pick either <span class="math inline">\(\vec{u}\)</span> or <span class="math inline">\(\vec{v}\)</span>, it does not matter which. In the diagram, we’ve picked <span class="math inline">\(\vec{v}\)</span>. Align your telescope with that vector. Now march along the other vector, <span class="math inline">\(\vec{u}\)</span>, carefully keeping the telescope on the bearing aligned with <span class="math inline">\(\vec{v}\)</span>. From the diagram, you can see that when you’ve marched to <span class="math inline">\(\frac{1}{2} \vec{u}\)</span>, the telescope does not yet have <span class="math inline">\(\vec{b}\)</span> in view. Similarly, at <span class="math inline">\(1 \vec{u}\)</span>, the target <span class="math inline">\(\vec{b}\)</span> isn’t yet visible. Marching a little further, to about <span class="math inline">\(1.6 \vec{u}\)</span> brings you to the point in the <span class="math inline">\(\vec{u}\)</span>-subspace where the target falls into view. This tells us that the coefficient on <span class="math inline">\(\vec{u}\)</span> will be 1.6.</p>
<p>To find the coefficient on <span class="math inline">\(\vec{v}\)</span>, you will need to march along the line of the telescope, taking steps of size <span class="math inline">\(\|\vec{v}\|\)</span>. In the diagram, we’ve marked the march with copies of <span class="math inline">\(\vec{v}\)</span> to make the counting easier. We will need to march <em>opposite</em> the direction of <span class="math inline">\(\vec{v}\)</span>, so the coefficient will be negative. Taking 2.8 steps of size <span class="math inline">\(\|\vec{v}\|\)</span> brings us to the target. Thus:</p>
<p><span class="math display">\[\vec{b} = 1.6 \vec{u} - 2.8 \vec{v}\ .\]</span></p>
<p>To handle vectors in spaces where telescopes are not available, we need an arithmetic algorithm. In R, that algorithm is packaged up as <code>qr.solve()</code>. We will pick this up again the next section.</p>
<div class="example">
<p>In 3-dimensional space, visualization of the solution to the target problem is possible, at least for those who have the talent of rotating three-dimensional objects in their head. For the rest of us, a physical model can help; take three pencils labeled <span class="math inline">\(\vec{u}\)</span>, <span class="math inline">\(\vec{v}\)</span>, and <span class="math inline">\(\vec{b}\)</span> and bury their tails in a small ball of putty. (Chemistry molecular construction kits are a good alternative.)</p>
<p>In case putty, pencils, or a molecular model kit are not available, use the interactive diagram in <a href="#fig-b-onto-u-v">Figure&nbsp;<span>31.3</span></a>. This diagram also includes <span class="math inline">\(\hat{b}\)</span> and <span class="math inline">\(\vec{r}\)</span> with the hope that this will guide you into orienting the diagram appropriately to see where the solution comes from.</p>
<p style="text-align:center">
<iframe frameborder="0" height="480px" src="https://c3d.libretexts.org/CalcPlot3D/dynamicFigure/index.html?type=jaxlabel;position=middle;math=.;textonly=false&amp;type=vector;vector=%3C2,1,0%3E;visible=true;color=rgb(17,109,192);size=2;initialpt=(0,0,0)&amp;type=vector;vector=%3C-1,1,0%3E;visible=true;color=rgb(208,20,240);size=2;initialpt=(0,0,0)&amp;type=vector;vector=%3C1/2,2,2.5%3E;visible=true;color=rgb(106,168,79);size=2;initialpt=(0,0,0)&amp;type=z;z=0;visible=true;umin=-3;umax=3;vmin=-3;vmax=3;grid=30;format=normal;alpha=40;hidemyedges=true;constcol=rgb(255,0,0);view=0;contourcolor=red;fixdomain=true;contourplot=true;showcontourplot=false;firstvalue=-1;stepsize=0.2;numlevels=11;list=;xnum=46;ynum=46;show2d=false;hidesurface=false;hidelabels=true;showprojections=false;surfacecontours=true;projectioncolor=rgba(255,0,0,1);showxygrid=false;showxygridonbox=true;showconstraint=false&amp;type=vector;vector=%3C.5,2,0%3E;visible=true;color=rgb(173,255,0);size=2;initialpt=(0,0,0)&amp;type=vector;vector=%3C0,0,2.5%3E;visible=true;color=rgb(255,0,0);size=2;initialpt=(.5,2,0)&amp;type=text;text=Target%3A%20b;visible=true;point=(1/2,1,1.4);color=rgb(106,168,79);font=Arial;fontsize=14pt;bold=true;italic=false;fontmath=true;align=Lower-right&amp;type=text;text=Residual;visible=true;point=(.5,2,1);color=rgb(255,0,0);font=Arial;fontsize=11pt;bold=false;italic=false;fontmath=true;align=Upper-right&amp;type=text;text=u;visible=true;point=(1,.6,0);color=rgb(17,109,192);font=Arial;fontsize=14pt;bold=true;italic=false;fontmath=true;align=Upper-right&amp;type=text;text=v;visible=true;point=(-.6,.4,.1);color=rgb(208,20,240);font=Arial;fontsize=14pt;bold=true;italic=false;fontmath=true;align=Upper-right&amp;type=spacecurve;spacecurve=curve;x=-t;y=t;z=0;visible=true;width=2;view=0;tmin=-3;tmax=3;tsteps=10;color=rgb(233,185,233);showtrace=false;tval=0;constcol=true;twod=false;arrows=0;showpt=true;trace=false;vel=false;acc=false;osc=false;k=false;repeat=false;bounce=false;dashed=false;tanline=false;dropcurtain=false;showtvector=false;shownvector=false;showbvector=false;showtnbeqs=false;showtnblabels=false;showoscplane=false;showrectplane=false;shownormplane=false;optimizecurve=true;maxjointangle=10&amp;type=spacecurve;spacecurve=curve;x=2t;y=t;z=0;visible=true;width=2;view=0;tmin=-1.6;tmax=1.6;tsteps=10;color=rgb(159,187,213);showtrace=false;tval=0;constcol=true;twod=false;arrows=0;showpt=true;trace=false;vel=false;acc=false;osc=false;k=false;repeat=false;bounce=false;dashed=false;tanline=false;dropcurtain=false;showtvector=false;shownvector=false;showbvector=false;showtnbeqs=false;showtnblabels=false;showoscplane=false;showrectplane=false;shownormplane=false;optimizecurve=true;maxjointangle=10&amp;type=point;point=(1.66666,0.83333,0);visible=true;color=rgb(0,255,255);size=4&amp;type=point;point=(-1.1666,1.1666,0);visible=true;color=rgb(228,125,228);size=4&amp;type=spacecurve;spacecurve=curve;x=-t+1.6666;y=t+0.83333;z=0;visible=true;width=2;view=0;tmin=-2;tmax=2;tsteps=10;color=rgb(233,185,233);showtrace=false;tval=0;constcol=true;twod=false;arrows=0;showpt=true;trace=true;vel=true;acc=true;osc=false;k=false;repeat=false;bounce=false;dashed=false;tanline=false;dropcurtain=false;showtvector=false;shownvector=false;showbvector=false;showtnbeqs=false;showtnblabels=false;showoscplane=false;showrectplane=false;shownormplane=false;optimizecurve=true;maxjointangle=10&amp;type=spacecurve;spacecurve=curve;x=2t-1.1666;y=t+1.1666;z=0;visible=true;width=2;view=0;tmin=-.9;tmax=2;tsteps=200;color=rgb(162,193,222);showtrace=false;tval=0;constcol=true;twod=false;arrows=0;showpt=true;trace=true;vel=true;acc=true;osc=false;k=false;repeat=false;bounce=false;dashed=false;tanline=false;dropcurtain=false;showtvector=false;shownvector=false;showbvector=false;showtnbeqs=false;showtnblabels=false;showoscplane=false;showrectplane=false;shownormplane=false;optimizecurve=true;maxjointangle=10&amp;type=vector;vector=%3C-.6,1.2,0%3E;visible=false;color=rgb(228,125,228);size=2;initialpt=(0,0,0)&amp;type=text;text=v%20perp%20u;visible=false;point=(-.5,1,-.1);color=rgb(208,20,240);font=Times%20New%20Roman;fontsize=14pt;bold=false;italic=false;fontmath=true;align=Upper-right&amp;type=window;hsrmode=0;nomidpts=true;anaglyph=-1;center=0.09657308993109837,1.8128995478040388,9.833822698615093,1;focus=0,0,0,1;up=0.6869713273879257,-0.7158150586575313,0.12521660092011352,1;transparent=false;alpha=140;twoviews=false;unlinkviews=false;axisextension=0.7;xaxislabel=x;yaxislabel=y;zaxislabel=z;edgeson=true;faceson=true;showbox=false;showaxes=false;showticks=true;perspective=false;centerxpercent=0.5;centerypercent=0.5;rotationsteps=30;autospin=true;xygrid=false;yzgrid=false;xzgrid=false;gridsonbox=true;gridplanes=true;gridcolor=rgb(128,128,128);xmin=-2;xmax=2;ymin=-2;ymax=2;zmin=-2;zmax=2;xscale=1;yscale=1;zscale=1;zcmin=-4;zcmax=4;xscalefactor=1;yscalefactor=1;zscalefactor=1;tracemode=0;keep2d=false;zoom=0.78" width="90%">
</iframe>
</p>
<p>NEED TO PROVIDE A SHORT LINK for PDF version</p>
<div class="cell" data-layout-align="center" data-fig.showtext="false">
<div class="cell-output-display">
<div id="fig-b-onto-u-v" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="www/tiny-blank.png" class="img-fluid figure-img" style="width:1.0%"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">Figure 31.3: Showing the relative orientation of the three vectors <span class="math inline">\(\vec{u}\)</span>, <span class="math inline">\(\vec{v}\)</span> and <span class="math inline">\(\vec{b}\)</span>. Drag the image to rotate it.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p><span class="math inline">\(\vec{u}\)</span> and <span class="math inline">\(\vec{v}\)</span> are fixed in length. However, their lengths will appear to change as you rotate the space. This might be called the “gun-barrel” effect; a tube looks very short when you look down its longitudinal axis, but looks longer when you look at it from the side. Rotate the space until <strong>both</strong> <span class="math inline">\(\vec{u}\)</span> and <span class="math inline">\(\vec{v}\)</span> reach their maximum apparent length. The viewpoint that accomplishes this is looking downward perpendicularly onto the <span class="math inline">\(\left[\vec{u},\vec{v}\right]\)</span>-plane. In this orientation, you will be looking down the barrel of the <span class="math inline">\(\vec{r}\)</span> gun. Vector <span class="math inline">\(\vec{b}\)</span> is not in that plane, as you can confirm by rotating the plot a bit out of the <span class="math inline">\(\left[\vec{u},\vec{v}\right]\)</span>-plane. Returning to the perspective looking down perpendicularly on the place, you can see how <span class="math inline">\(\vec{b}\)</span> corresponds to <span class="math inline">\(\hat{b}\)</span>, the point in the plane where the projection of <span class="math inline">\(\vec{b}\)</span> will fall.</p>
<p>To find the scalar multiplier on <span class="math inline">\(\vec{v}\)</span>, rotate the space until the vector <span class="math inline">\(\vec{u}\)</span> is pointing straight toward you. You will see only the arrowhead of <span class="math inline">\(\vec{u}\)</span>. Vectors <span class="math inline">\(\vec{v}\)</span> and <span class="math inline">\(\hat{b}\)</span> will appear parallel to each other, but that is because you are looking at the plane edge on. In this orientation, <span class="math inline">\(\hat{b}\)</span> will appear just a little longer than <span class="math inline">\(\vec{v}\)</span>, perhaps 1.2 times longer. So 1.2 is the scalar multiplier on <span class="math inline">\(\vec{v}\)</span>.</p>
<p>To figure out the scalar multiplier on <span class="math inline">\(\vec{u}\)</span>, follow the same procedure as in the previous paragraph, but looking down the barrel of <span class="math inline">\(\vec{v}\)</span>. From this perspective, <span class="math inline">\(\vec{u}\)</span> appears longer than <span class="math inline">\(\hat{b}\)</span>; the scalar multiplier on <span class="math inline">\(\vec{u}\)</span> will be about 0.9. In terms of <span class="math inline">\(\mathit{A} \vec{x} = \hat{b}\)</span>, the solution is <span class="math display">\[\vec{x} = \left[\begin{array}{r}0.9\\1.2\end{array}\right]\ .\]</span></p>
</div>
</section>
<section id="properties-of-the-solution" class="level2" data-number="31.3">
<h2 data-number="31.3" class="anchored" data-anchor-id="properties-of-the-solution"><span class="header-section-number">31.3</span> Properties of the solution</h2>
<p>As you might expect, there is a known solution to the target problem. We will start by using a computer implementation of this solution to demonstrate some simple properties of the solution. As an example, we will use three vectors <span class="math inline">\(\vec{u}\)</span>, <span class="math inline">\(\vec{v}\)</span>, and <span class="math inline">\(\vec{w}\)</span> in a 5-dimensional space as the “screen” to be projected onto, and another vector <span class="math inline">\(\vec{b}\)</span> as the object being projected.</p>
<p>The matrix <span class="math inline">\(\mathit{A}\)</span> is: <span class="math display">\[{\mathbf A} \equiv \left[\strut \begin{array}{ccc}|&amp;|&amp;|\\\vec{u} &amp; \vec{v} &amp; \vec{w}\\|&amp;|&amp;|\end{array}\right]\]</span></p>
<p>For the sake of example, we will make up some vectors. In your own explorations, you can change them to anything you like.</p>
<div class="cell" data-layout-align="center" data-fig.showtext="false">
<div class="sourceCode" id="cb1"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># the three vectors</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>u <span class="ot">&lt;-</span> <span class="fu">rbind</span>(<span class="dv">6</span>, <span class="dv">4</span>, <span class="dv">9</span>, <span class="dv">3</span>, <span class="dv">1</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>v <span class="ot">&lt;-</span> <span class="fu">rbind</span>(<span class="dv">1</span>, <span class="dv">5</span>,<span class="sc">-</span><span class="dv">2</span>, <span class="dv">0</span>, <span class="dv">7</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>w <span class="ot">&lt;-</span> <span class="fu">rbind</span>(<span class="dv">3</span>,<span class="sc">-</span><span class="dv">5</span>, <span class="dv">2</span>, <span class="dv">8</span>, <span class="dv">4</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>A <span class="ot">&lt;-</span> <span class="fu">cbind</span>(u, v, w)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="co"># the target</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>b <span class="ot">&lt;-</span> <span class="fu">rbind</span>(<span class="dv">8</span>, <span class="dv">2</span>,<span class="sc">-</span><span class="dv">5</span>, <span class="dv">7</span>, <span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The operator <code>%onto%</code> model vector and from that we can calculate the residual vector.</p>
<div class="cell" data-layout-align="center" data-fig.showtext="false">
<div class="sourceCode" id="cb2"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>s <span class="ot">&lt;-</span> b <span class="sc">%onto%</span> A </span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>r <span class="ot">&lt;-</span> b <span class="sc">-</span> s</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Those two simple commands constitute a complete solution to the <strong><em>projection problem</em></strong>, where see seek to model vector and the residual vector.</p>
<p>In the <strong><em>target problem</em></strong> we want more: How to express <span class="math inline">\(\hat{b}\)</span> as a linear combination of the columns in <span class="math inline">\(\mathit{A}\)</span>. At the risk of being repetitive, this means finding <span class="math inline">\(\color{magenta}{\vec{x}}\)</span> in <span class="math display">\[\mathit{A}\ \color{magenta}{\large\vec{x}} = \vec{b}\]</span> where <span class="math inline">\(\mathit{A}\)</span> and <span class="math inline">\(\vec{b}\)</span> are given.</p>
<p>The function <code>qr.solve()</code> finds <span class="math inline">\(\vec{x}\)</span>. ::: {.cell layout-align=“center” fig.showtext=‘false’}</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">qr.solve</span>(A, b)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>::: ::: {.cell layout-align=“center” fig.showtext=‘false’}</p>
<pre><code>##            [,1]
## [1,] 0.03835171
## [2,] 0.33478133
## [3,] 0.48849968</code></pre>
<p>:::</p>
<p>How can we confirm that this really is the solution to the target problem for this set of vectors? Easy! Just multiply <span class="math inline">\(\mathit{A}\)</span> by the <span class="math inline">\(\vec{x}\)</span> that we found. The result should be the target vector <span class="math inline">\(\hat{b}\)</span>:</p>
<div class="cell" data-layout-align="center" data-fig.showtext="false">
<div class="sourceCode" id="cb5"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>A <span class="sc">%*%</span> x</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="do">##            [,1]</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="do">## [1,]  2.0303906</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="do">## [2,] -0.6151849</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="do">## [3,]  0.6526021</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="do">## [4,]  4.0230526</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="do">## [5,]  4.3358197</span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>s</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a><span class="do">##            [,1]</span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a><span class="do">## [1,]  2.0303906</span></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a><span class="do">## [2,] -0.6151849</span></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a><span class="do">## [3,]  0.6526021</span></span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a><span class="do">## [4,]  4.0230526</span></span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a><span class="do">## [5,]  4.3358197</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="takenote">
<p>You should add <code>qr.solve()</code> to your computational toolbox of R functions.</p>
</div>
</section>
<section id="application-of-the-target-problem" class="level2" data-number="31.4">
<h2 data-number="31.4" class="anchored" data-anchor-id="application-of-the-target-problem"><span class="header-section-number">31.4</span> Application of the target problem</h2>
<p>In Chapter <a href="#sec-linear-equations">Section&nbsp;<span>31.1</span></a> we translated into vector/matrix form the problem, originally stated in Block 1, of finding the best linear combination of <span class="math inline">\(f(\mathtt{time}) \equiv 1\)</span> and <span class="math inline">\(g(\mathtt{time}) \equiv e^{-0.019 \mathtt{time}}\)</span>. Let’s solve that problem now.</p>
<div class="rmosaic">
<p>Earlier we introduced <code>rbind()</code> for the purpose of making column vectors, as in ::: {.cell layout-align=“center” fig.showtext=‘false’}</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rbind</span>(<span class="dv">3</span>,<span class="dv">7</span>,<span class="sc">-</span><span class="dv">1</span>)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="do">##      [,1]</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="do">## [1,]    3</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="do">## [2,]    7</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="do">## [3,]   -1</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now we will work with <strong><em>columns of data</em></strong> stored in the <code>CoolingWater</code> data frame. A good way to extract a column from a data frame is using the <code>with()</code> function. For instance,</p>
<div class="cell" data-layout-align="center" data-fig.showtext="false">
<div class="sourceCode" id="cb7"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>b <span class="ot">&lt;-</span> <span class="fu">with</span>(CoolingWater, temp)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>time <span class="ot">&lt;-</span> <span class="fu">with</span>(CoolingWater, time)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>A <span class="ot">&lt;-</span> <span class="fu">cbind</span>(<span class="dv">1</span>, <span class="fu">exp</span>(<span class="sc">-</span><span class="fl">0.019</span> <span class="sc">*</span> time))</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(A)</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="do">##      [,1]      [,2]</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a><span class="do">## [1,]    1 1.0000000</span></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a><span class="do">## [2,]    1 0.9811794</span></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a><span class="do">## [3,]    1 0.9627129</span></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a><span class="do">## [4,]    1 0.9445941</span></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a><span class="do">## [5,]    1 0.9268162</span></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a><span class="do">## [6,]    1 0.9093729</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Notice that <code>cbind()</code> automatically translated <code>1</code> into the vector of all ones.</p>
<p>We are all set up to solve the target problem:</p>
<div class="cell" data-layout-align="center" data-fig.showtext="false">
<div class="sourceCode" id="cb8"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">qr.solve</span>(A, b)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center" data-fig.showtext="false">
<pre><code>## [1] 25.92024 61.26398</code></pre>
</div>
<p>How good an answer is the <code>x</code> calculated by <code>qr.solve()</code>? Judge for yourself!</p>
<div class="cell" data-layout-align="center" data-fig.showtext="false">
<div class="sourceCode" id="cb10"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>(temp <span class="sc">~</span> time, <span class="at">data =</span> CoolingWater, <span class="at">size=</span><span class="dv">0</span>) <span class="sc">%&gt;%</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_plot</span>(<span class="fl">25.92</span> <span class="sc">+</span> <span class="fl">61.26</span><span class="sc">*</span><span class="fu">exp</span>(<span class="sc">-</span><span class="fl">0.019</span><span class="sc">*</span>time) <span class="sc">~</span> time,</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">color=</span><span class="st">"blue"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="B5-target-problem_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" style="width:90.0%"></p>
</figure>
</div>
</div>
</div>
<p>You may recall from Block 1 the explanation for the poor match between the model and the data for early times: that the water cooled quickly when poured into the cool mug, but the mug-with-water cooled much slower into the room air.</p>
<p>Let’s augment the model by adding another vector with a much faster exponential cooling, say, <span class="math inline">\(e^{-0.06 \mathtt{time}}\)</span>.</p>
<div class="cell" data-layout-align="center" data-fig.showtext="false">
<div class="sourceCode" id="cb11"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>newA <span class="ot">&lt;-</span> <span class="fu">cbind</span>(A, <span class="fu">exp</span>(<span class="sc">-</span><span class="fl">0.06</span><span class="sc">*</span>time))</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">qr.solve</span>(newA, b)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="do">## [1] 26.82297 53.27832 12.67486</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center" data-fig.showtext="false">
<div class="sourceCode" id="cb12"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_point</span>(temp <span class="sc">~</span> time, <span class="at">data =</span> CoolingWater, <span class="at">size=</span><span class="dv">0</span>) <span class="sc">%&gt;%</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_plot</span>(<span class="fl">26.82</span> <span class="sc">+</span> <span class="fl">53.28</span><span class="sc">*</span><span class="fu">exp</span>(<span class="sc">-</span><span class="fl">0.019</span><span class="sc">*</span>time) <span class="sc">+</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>               <span class="fl">12.67</span><span class="sc">*</span><span class="fu">exp</span>(<span class="sc">-</span><span class="fl">0.06</span><span class="sc">*</span>time) <span class="sc">~</span> time,</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">color=</span><span class="st">"green"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="B5-target-problem_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" style="width:90.0%"></p>
</figure>
</div>
</div>
</div>
<p>:::</p>
</section>
<section id="exercises" class="level2" data-number="31.5">
<h2 data-number="31.5" class="anchored" data-anchor-id="exercises"><span class="header-section-number">31.5</span> Exercises</h2>
<section id="exercise-31.01" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="exercise-31.01">Exercise 31.01</h4>
<p>In this exercise, you will <em>check</em> proposed solutions to the target problem. Each question poses one target problem. One of the answers is correct. Use R in a <a href="https://maa-statprep.shinyapps.io/CalcZ-Sandbox/">SANDBOX</a> to select the correct answer.</p>
<p>The vectors you will be working with are: <span class="math display">\[\vec{a} \equiv \left(\begin{array}{c}1\\2\end{array}\right)\ \ \ \ \vec{b}  \equiv \left(\begin{array}{c}1\\1\end{array}\right)\ \ \ \ \vec{c}  \equiv \left(\begin{array}{c}1\\-2\end{array}\right)\ \ \ \ \vec{d}  \equiv \left(\begin{array}{c}-6\\2\end{array}\right)\ \ \ \ \vec{T}  \equiv \left(\begin{array}{c}3\\-1\end{array}\right)\ \ \ \ \]</span></p>
<div class="cell" data-layout-align="center" data-fig.showtext="false">
<div class="cell-output-display">
<p><strong>Part A</strong> <strong>i.</strong> What linear combination of <span class="math inline">\(\vec{a}\)</span> and <span class="math inline">\(\vec{b}\)</span> will reach target <span class="math inline">\(T\)</span>?</p>
<ol type="a">
<li><span class="math inline">\(3\vec{a} - 7\vec{b}\)</span></li>
<li><span class="math inline">\(\vec{a} + 2\vec{b}\)</span></li>
<li><span class="math inline">\(-4 \vec{a} + 7 \vec{b}\)</span></li>
<li><span class="math inline">\(- \vec{a} + 4\vec{b}\)</span></li>
<li>No combination will reach <span class="math inline">\(\vec{T}\)</span> exactly.</li>
<li>None of the above</li>
</ol>
</div>
</div>
<div class="cell" data-layout-align="center" data-fig.showtext="false">
<div class="cell-output-display">
<p><strong>Part B</strong> <strong>ii.</strong> What linear combination of <span class="math inline">\(\vec{b}\)</span> and <span class="math inline">\(\vec{c}\)</span> will reach target <span class="math inline">\(T\)</span>?</p>
<ol type="a">
<li><span class="math inline">\(\frac{4}{3}\vec{b} - \frac{5}{3}\vec{c}\)</span></li>
<li><span class="math inline">\(\frac{2}{3}\vec{b} + \frac{7}{3}\vec{c}\)</span></li>
<li><span class="math inline">\(-\frac{7}{3}\vec{b} + \frac{5}{3}\vec{c}\)</span></li>
<li><span class="math inline">\(\frac{5}{3} \vec{b} + \frac{4}{3} \vec{c}\)</span></li>
<li>No combination will reach $ exactly.</li>
<li>None of the above</li>
</ol>
</div>
</div>
<div class="cell" data-layout-align="center" data-fig.showtext="false">
<div class="cell-output-display">
<p><strong>Part C</strong> <strong>iii.</strong> What linear combination of <span class="math inline">\(\vec{b}\)</span> and <span class="math inline">\(\vec{d}\)</span> will reach target <span class="math inline">\(T\)</span>?</p>
<ol type="a">
<li><span class="math inline">\(0\vec{b} - \frac{3}{2}\vec{d}\)</span></li>
<li><span class="math inline">\(\frac{1}{2}\vec{b} + \frac{1}{2}\vec{d}\)</span></li>
<li><span class="math inline">\(0 \vec{b} - \frac{1}{2} \vec{d}\)</span></li>
<li><span class="math inline">\(\frac{3}{2}\vec{b} + \frac{1}{2}\vec{d}\)</span></li>
<li>No combination will reach $ exactly.</li>
<li>None of the above</li>
</ol>
</div>
</div>
<div class="cell" data-layout-align="center" data-fig.showtext="false">
<div class="cell-output-display">
<p><strong>Part D</strong> <strong>iv.</strong> Which of these linear combinations of $ec{a}$, <span class="math inline">\(\vec{b}\)</span> and <span class="math inline">\(\vec{c}\)</span> will reach target <span class="math inline">\(T\)</span>?</p>
<ol type="a">
<li><span class="math inline">\(\vec{a} -\vec{b} - 2\vec{c}\)</span></li>
<li><span class="math inline">\(2\vec{a} +\vec{b} - 2\vec{c}\)</span></li>
<li><span class="math inline">\(2\vec{a} -\vec{b} + 2\vec{c}\)</span></li>
<li><span class="math inline">\(-2\vec{a} +\vec{b} + 2\vec{c}\)</span></li>
<li>No combination will reach $ exactly.</li>
<li>None of the above</li>
</ol>
</div>
</div>
</section>
<section id="exercise-31.02" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="exercise-31.02">Exercise 31.02</h4>
<p>This exercise uses R to find solutions to the target problem. Each question poses one target problem. You could solve these problems by eye, but we want to get you started on the computer solution so that you will be ready to solve harder problems that must be worked on the computer.</p>
<p>The vectors you will be working with are: <span class="math display">\[\vec{a} \equiv \left(\begin{array}{c}1\\2\end{array}\right)\ \ \ \ \vec{b}  \equiv \left(\begin{array}{c}1\\1\end{array}\right)\ \ \ \ \vec{c}  \equiv \left(\begin{array}{c}1\\-2\end{array}\right)\ \ \ \ \vec{d}  \equiv \left(\begin{array}{c}-6\\2\end{array}\right)\ \ \ \ \vec{T}  \equiv \left(\begin{array}{c}3\\-1\end{array}\right)\ \ \ \ \]</span></p>
<p>To make your life easier, here are the commands for defining these vectors. <strong>One of the commands is wrong</strong>. You will have to correct it before moving on the the rest of the problem.</p>
<p>NEED TO BREAK ONE OF THESE ::: {.cell layout-align=“center” fig.showtext=‘false’}</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r cell-code code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>a <span class="ot">&lt;-</span> <span class="fu">rbind</span>(<span class="dv">1</span>, <span class="dv">2</span>)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>b <span class="ot">&lt;-</span> <span class="fu">rbind</span>(<span class="dv">1</span>, <span class="dv">1</span>)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>c <span class="ot">&lt;-</span> <span class="fu">rbind</span>(<span class="dv">1</span>, <span class="sc">-</span><span class="dv">1</span>)</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> <span class="fu">rbind</span>(<span class="sc">-</span><span class="dv">6</span>, <span class="dv">2</span>)</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>T <span class="ot">&lt;-</span> <span class="fu">rbind</span>(<span class="dv">3</span>, <span class="sc">-</span><span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>:::</p>
<div class="cell" data-layout-align="center" data-fig.showtext="false">

</div>
<div class="cell" data-layout-align="center" data-fig.showtext="false">
<div class="cell-output-display">
<p><strong>Part A</strong> What what is the correct linear combination of <span class="math inline">\(\vec{a}\)</span> and <span class="math inline">\(\vec{b}\)</span> to reach the target $ec{T}?</p>
<ol type="a">
<li><span class="math inline">\(-4 \vec{a} + 7 \vec{b}\)</span></li>
<li><span class="math inline">\(-2 \vec{a} + 5 \vec{b}\)</span></li>
<li><span class="math inline">\(2 \vec{a} -7 \vec{b}\)</span></li>
<li><span class="math inline">\(4 \vec{a} - 5 \vec{b}\)</span></li>
</ol>
</div>
</div>
<div class="cell" data-layout-align="center" data-fig.showtext="false">
<div class="cell-output-display">
<p><strong>Part B</strong> What what is the correct linear combination of <span class="math inline">\(\vec{b}\)</span> and <span class="math inline">\(\vec{c}\)</span> to reach the target $ec{T}?</p>
<ol type="a">
<li><span class="math inline">\(\frac{5}{3}\vec{b} + \frac{4}{3} \vec{c}\)</span></li>
<li><span class="math inline">\(\frac{4}{3}\vec{b} + \frac{7}{2} \vec{c}\)</span></li>
<li><span class="math inline">\(\frac{5}{2}\vec{b} + \frac{4}{5} \vec{c}\)</span></li>
<li><span class="math inline">\(\frac{2}{3}\vec{b} + \frac{9}{4} \vec{c}\)</span></li>
</ol>
</div>
</div>
<div class="cell" data-layout-align="center" data-fig.showtext="false">
<div class="cell-output-display">
<p><strong>Part C</strong> What what is the correct linear combination of <span class="math inline">\(\vec{c}\)</span> and <span class="math inline">\(\vec{d}\)</span> to reach the target $ec{T}?</p>
<ol type="a">
<li><span class="math inline">\(\frac{0}{3}\vec{c} + \frac{4}{5} \vec{d}\)</span></li>
<li><span class="math inline">\(\frac{1}{3}\vec{c} + \frac{1}{3} \vec{d}\)</span></li>
<li><span class="math inline">\(\frac{1}{2}\vec{c} + \frac{5}{7} \vec{d}\)</span></li>
<li><span class="math inline">\(\frac{0}{3}\vec{c} + \frac{1}{2} \vec{d}\)</span></li>
</ol>
</div>
</div>
<div class="cell" data-layout-align="center" data-fig.showtext="false">
<div class="cell-output-display">
<p><strong>Part D</strong> What what is the correct linear combination of <span class="math inline">\(\vec{a}\)</span> and <span class="math inline">\(\vec{c}\)</span> to reach the target $ec{T}?</p>
<ol type="a">
<li><span class="math inline">\(\frac{5}{4}\vec{a} + \frac{7}{4} \vec{c}\)</span></li>
<li><span class="math inline">\(\frac{5}{4}\vec{a} + \frac{5}{4} \vec{c}\)</span></li>
<li><span class="math inline">\(\frac{7}{4}\vec{a} + \frac{9}{4} \vec{c}\)</span></li>
<li><span class="math inline">\(\frac{3}{4}\vec{a} + \frac{7}{4} \vec{c}\)</span></li>
</ol>
</div>
</div>
</section>
<section id="exercise-31.03" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="exercise-31.03">Exercise 31.03</h4>
<p>Each of the diagrams below consists of two vectors and a target point (denoted with a bull’s eye). Being a point, the target has a definite location relative to the coordinate axes.</p>
<p>“Solving” this sort of system amounts to finding a linear combination of the two vectors whose result is a vector that can connect the origin to the target. (We call this a <strong><em>target problem</em></strong>.)</p>
<div class="cell" data-layout-align="center" data-fig.showtext="false">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="www/4targets.png" class="img-fluid figure-img" style="width:90.0%"></p>
</figure>
</div>
</div>
</div>
<p>Copy over each diagram to your paper. (Any reasonable approximation will do.) Then, for each diagram, find the linear combination of the two vectors that will reach from the origin to the target. Show your work, meaning that you should draw the scaled vectors in a proper position that demonstrates that they do indeed connect the origin to the target. Underneath the diagram, write down the numerical value of the scalars in the linear combination. (Again, any reasonable approximation will do.)</p>


</section>
</section>
</main> <!-- /main -->
<script type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    setTimeout(function() {
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../Linear-combinations/B5-projection.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Projection &amp; residual</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../Linear-combinations/B5-stat-modeling.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Statistical modeling and R<sup>2</sup></span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->


</body></html>