---
id: "ant-keep-screen"
created: "Sat Mar 19 19:59:58 2022"
global_id: "x4CiKv"
skill: "M-P1ZSV"
---

```{r echo=FALSE, message=FALSE}
f <- doodle_fun( ~ u & v, seed=78)
g <- doodle_fun( ~ u & v, seed=87)
f2 <- doodle_fun( ~ u & v, seed=577)
g2 <- doodle_fun( ~ u & v, seed=186)
trajA <- integrateODE(du ~ f(u, v), dv ~ g(u, v), u = -2, v=2,
                      bounds(t=-3:3))
trajB <- integrateODE(du ~ f2(u, v), dv ~ g2(u, v), u = 2, v=-3,
                      bounds(t=0:3))
trajC <- integrateODE(du ~ f(u, v), dv ~ g(u, v), u = 3, v=1,
                      bounds(t=0:3))
trajD <- integrateODE(du ~ f2(u, v), dv ~ g(u, v), u = 2, v=1,
                      bounds(t=0:3))
```

```{r echo=FALSE}

P1 <- traj_plot(u(t) ~ v(t), trajA, nt=0) %>%
  gf_labs(subtitle="Plot A")
P2 <- traj_plot(u(t) ~ t, trajA, nt=0) %>%
  gf_labs(subtitle="Plot B")

P3 <- traj_plot(u(t) ~ t, trajB, nt=0) %>%
  gf_labs(subtitle="Plot C")
P4 <- traj_plot(u(t) ~ v(t), trajB, nt=0) %>%
  gf_labs(subtitle="Plot D", x="", y="")

gridExtra::grid.arrange(P1, P2, P3, P4, ncol=2)
```

```{r echo=FALSE}
P5 <- traj_plot(u(t) ~ v(t), trajC, nt=0) %>%
  gf_labs(subtitle="Plot E", x="", y="")
P6 <- traj_plot(u(t) ~ t, trajC, nt=0) %>%
  gf_labs(subtitle="Plot F")

P7 <- traj_plot(u(t) ~ t, trajD, nt=0) %>%
  gf_labs(subtitle="Plot G")
P8 <- traj_plot(u(t) ~ v(t), trajD, nt=0) %>%
  gf_labs(subtitle="Plot H")

gridExtra::grid.arrange(P5, P6, P7, P8, ncol=2)

```
              
```{r aks72-A, echo=FALSE, results="markup"}
askMC("Plot A", 
      "time series", "+trajectory+", random_answer_order=FALSE)
```

```{r aks72-B, echo=FALSE, results="markup"}
askMC("Plot B", 
      "+time series+", "trajectory", random_answer_order=FALSE)
```

```{r aks72-C, echo=FALSE, results="markup"}
askMC("Plot C", 
      "+time series+", "trajectory", random_answer_order=FALSE)
```

```{r aks72-D, echo=FALSE, results="markup"}
askMC("Plot D", 
      "time series", "+trajectory+", random_answer_order=FALSE)
```
 
 
```{r aks72-E, echo=FALSE, results="markup"}
askMC("Plot E", 
      "time series", "+trajectory+", random_answer_order=FALSE)
```             
 
```{r aks72-F, echo=FALSE, results="markup"}
askMC("Plot F", 
      "+time series+", "trajectory", random_answer_order=FALSE)
```
 
```{r aks72-G, echo=FALSE, results="markup"}
askMC("Plot G", 
      "+time series+", "trajectory", random_answer_order=FALSE)
``` 
 
```{r aks72-H, echo=FALSE, results="markup"}
askMC("Plot H", 
      "time series", "+trajectory+", random_answer_order=FALSE)
``` 
                 
