---
id: "ape-grow-oven"
created: "Tue Jan 25 14:26:34 2022"
global_id: "jd6HE8" 
---

The differential equation $\partial_t x = a x$ is so commonly encountered that you should simply memorize the solution: $$x(t) = A e^{a t}$$ which you can recognize as exponential growth (or decay, if $a < 0$) from an initial condition $x_0 = A$.

Exponential growth is considered fast, but there are far faster forms of growth. To illustrate, consider the differential equation $$\partial_t x = a x^2\ .$$

This can be interpreted in terms of a model of the size of the flame as one lights a match.  Think of the flame as a ball of hot gas of radius $x$; the gas include oxygen (O_2_), nitrogen, and carbon dioxide, as well as a vapor of the combustible material such as the potassium chlorate of the match head.

Within the ball of flame, O_2_ reacts with the cumbustible material to produce the products of combustion and heat. Needless to say, this reaction eliminates the O_2_ in the ball. But O_2_ can diffuse into the ball from outside. The O_2_ infusion rate available in this way is proportional to the surface area of the ball, that is, $a x^2$. Thus the differential equation models the growth of the flame ball.

The match-flame equation is one that can be separated into parts: all the $x$ components on one side, the $t$ on the other.  That is:
$$\underbrace{\frac{dx}{dt} = a x^2}_{\text{original DE}}\ \ \ \implies \underbrace{\frac{dx}{x^2} = a dt}_{\text{separated DE}}$$ 

Integrating both sides of the separated equation will produce $a t + C$ on the right side.

A. Integrate the left side of the separated equation and use that to find a relationship between $x$ and $a t + C$.

B. The constant of integration, $C$, will reflect the initial condition. Plug in $t=0$ and calculate from the relationship in (A) what is $C$ in terms of $x_0$.

C. Replace $C$ in your relationship with the expression in terms of $x_0$ you found in (B). Confirm that this is $$x(t) = \frac{1}{a t - 1/x_0}\ .$$

D. $x(t)$ has a vertical asymptote. Find it.

E. Use `integrateODE()` to integrate the original differential equation. You will have to pick some numerical value for $a$ and $x_0$.  Take care to make $dt$ small enough. You will know that $dt$ is small enough when you get the approximately same solution using $dt/10$. 

F. Describe in everyday words what the solution says and how big the ball of flame becomes.

The model $\partial_t x = a x^2$, like all models, includes some features of the real-world system and excludes others. In this case, once the ball reaches a critical diameter, there is no longer enough combustion product to continue the reaction at the rate depicted in the model. If you watch a match being lit, you will see both the explosion and the eventual exhaustion of the combustion material. 

