---
id: "beech-ride-bowl"
created: "Mon Jul 19 16:37:13 2021"
global_id: "Rdc7vE"
skill: "D-BRUPM"
---



```{r char1-1, echo=FALSE, results="markup"}
askMC(
  "What are the numerical values of the eigenvalues of the matrix $\\left[\\begin{array}{rc}-1 & \\frac{3}{4} \\\\ 1 & 0\\end{array}\\right]$?",
  "+$\\frac{1}{2}$ and $-\\frac{3}{2}$+",
  "$\\frac{1}{2}$ and $-\\frac{5}{2}$",
  "$\\frac{1}{2}$ and $+\\frac{5}{2}$",
  "$-\\frac{1}{2}$ and $-\\frac{5}{2}$"
)
```

```{r char1-2, echo=FALSE, results="markup"}
askMC(
  "What are the numerical values of the eigenvalues of the matrix $\\left[\\begin{array}{rc}0 & \\frac{1}{2} \\\\ 1 & 0\\end{array}\\right]$?",
  "+$\\pm\\sqrt{2}/2$+",
  "$\\pm\\sqrt{2}$",
  "$\\pm 2$",
  "$\\pm\\frac{1}{2}$"
)
```

<!-- 
Eigenvalues are important because they dramatically simplify the interpretation of matrices and of dynamical system behavior near fixed points.

Eigenvalues are numbers. To use the language of linear combinations, an eigenvalue is a *scalar*. As you know, when you multiply a vector times a scalar, the result has the same direction (or the exact opposite direction) but might be longer or shorter. Like this:
$$ 3 \left[\begin{array}{c}1\\2 \end{array}\right] = \left[\begin{array}{c}3\\6 \end{array}\right]\ \ \ \ \text{or}\ \ \ \ \ 
-4 \left[\begin{array}{r}3\\-1 \end{array}\right] = \left[\begin{array}{r}-12\\4\end{array}\right]$$
In contrast, **matrix** multiplication of a vector can generate a result that has a *different direction* than the original vector, like this:

$$\left[\begin{array}{rc}0 & \frac{1}{2} \\ 1 & 0\end{array}\right]\cdot \left[\begin{array}{c}2 \\ 1\end{array}\right] =
\left[\begin{array}{c}\frac{1}{2} \\2\end{array}\right]\ \ \ \ \text{or}\ \ \ \ \left[\begin{array}{rc}-1 & \frac{3}{4} \\ 1 & 0\end{array}\right]\cdot \left[\begin{array}{r}1 \\ -4\end{array}\right] =
\left[\begin{array}{c}4 \\1\end{array}\right]$$

An **eigenvector** is a vector has a seemingly magical property with respect to multiplication by the matrix it characterizes: the result of the multiplication is a vector that has the same direction as the original but scaled by it's corresponding eigenvalue $\lambda$. That is, if $\lambda$ is an eigenvalue of ${\mathbf M}$ and ${\mathbf \Lambda}$ is the corresponding eigenvector: 
$${\mathbf M}\cdot {\mathbf \Lambda} = \lambda {\mathbf \Lambda}$$

```{r char1-3, echo=FALSE, results="markup"}
askMC(
  "Which of these is an eigenvector of the matrix $\\left[\\begin{array}{rc}-1 & \\frac{3}{4} \\\\ 1 & 0\\end{array}\\right]$? (Hint: Multiply the matrix by each of the vectors listed. For one of them, the result of the multiplication will be aligned with the vector used. You can use the constant of proportionality to answer the next question, but you'll have to start by choosing the right one of the options that follow.)",
  "+$\\left[\\begin{array}{r}-3\\\\2\\end{array}\\right]$+",
  "$\\left[\\begin{array}{r}3\\\\2\\end{array}\\right]$",
  "$\\left[\\begin{array}{r}-2\\\\3\\end{array}\\right]$", 
  "$\\left[\\begin{array}{r}2\\\\3\\end{array}\\right]$"
)
```

```{r char1-4, echo=FALSE, results="markup"}
askMC(
  "What is the eigenvalue associated with the correct answer from the previous problem?",
  "+-1.5+",
  "-1",
  "-0.5",
  "0.5", 
  "1.5",
  random_answer_order = TRUE
)
```

```{r char1-5, echo=FALSE, results="markup"}
askMC(
  "Consider the two matrices $${\\mathbf M}_1 = \\left[\\begin{array}{rr}5 & 6 \\\\0 & 1\\end{array}\\right]\\ \\ \\text{and}\\ \\ \\left[\\begin{array}{rr}-3 & 1 \\\\0 & 1\\end{array}\\right]$$ Which of the following is **not** an eigenvector of ${\\mathbf M}_1$ or of ${\\mathbf M}_2$? (We've rounded off to two decimal places and provided a sandbox for calculations.)",
  "$\\left[\\begin{array}{r}6\\\\1\\end{array}\\right]$",
  "$\\left[\\begin{array}{r}-1\\\\1\\end{array}\\right]$",
  "+$\\left[\\begin{array}{r}3\\\\2\\end{array}\\right]$+",
  "$\\left[\\begin{array}{r}3.02\\\\10\\end{array}\\right]$",
  "$\\left[\\begin{array}{r}3.30\\\\-1\\end{array}\\right]$"
)
```

You can use the sandbox below either for arithmetic calculations that you hand write or to use matrix-related R commands. In the initial code in the sandbox is a test that shows whether a vector `v` is an eigenvector of `M`. In this example it is and has eigenvalue 0.5615 (rounding off to 4 decimal places). You can print out `M` or `v` in the ordinary way, with the simple commands `M` or `v` respectively.
```{r char1-6, exercise=TRUE, exercise.cap="Matrix calculations", exercise.nlines=7, eval=FALSE}
M <- rbind(cbind(-3, 2), cbind(1, 0))
v <- rbind(5.6155, 10)
(M %*% v) / v # element-by-element division

```

-->
