---
id: "bird-trim-bulb"
created: "Sun Mar 20 09:53:47 2022"
global_id: "gLXhdu""
skill: "N-088YI"
---

The graph shows two trajectories, A, B.

```{r echo=FALSE}
f <- rfun(~ u & v, seed=9391)
g <- rfun(~ u & v, seed=29932)
trajA <- integrateODE(du ~ f(u, v)/2, dv ~ g(u, v)/3, 
                      u=-1.5, v=1, bounds(t=0:3))
trajB <- integrateODE(du ~ f(u, v)/2, dv ~ g(u, v)/3, 
                      u=3, v=3, bounds(t=0:3))
traj_plot(v(t) ~ u(t), trajA, color="magenta") %>%
  traj_plot(v(t) ~ u(t), trajB, color="blue") %>%
vectorfield_plot(u ~ f(u, v), v ~ g(u, v), 
                 bounds(u=-3:3, v=-3:5)) %>%
  gf_refine(coord_fixed())
```



For each trajectory, sketch the time series.

- Trajectory A, variable $u(t)$
- Trajectory A, variable $v(t)$
- Trajectory B, variable $u(t)$
- Trajectory B, variable $v(t)$

<!-- Note that the duration of trajectories A and B are different. -->

```{r echo=FALSE, eval=FALSE}
# The solutions
traj_plot(u(t) ~ t, trajA)
traj_plot(v(t) ~ t, trajA)
traj_plot(u(t) ~ t, trajB)
traj_plot(v(t) ~ t, trajB)
```
