---
id: "cheetah-hit-chair"
created: "Sat Mar 19 19:38:03 2022"
global_id: "34QnFG"
skill: "D-93XWJ"
---



Here is a flow field:

```{r echo=FALSE}
f <- rfun( ~ u & v, seed=9578)
g <- rfun( ~ u & v, seed=3187)
f2 <- rfun( ~ u & v, seed=9577)
g2 <- rfun( ~ u & v, seed=3186)
trajA <- integrateODE(du ~ f(u, v), dv ~ g(u, v), u = -2, v=2,
                      tdur=5)
trajB <- integrateODE(du ~ f2(u, v), dv ~ g2(u, v), u = 2, v=-3,
                      tdur=5)
trajC <- integrateODE(du ~ f(u, v), dv ~ g(u, v), u = 3, v=1,
                      tdur=5)
vectorfield_plot(f(u,v) ~ u & v, g(u,v) ~ u & v, 
                 domain(u=-3:3, v=-3:3), transform=function(x) x^0.25) %>%
  gf_label(2 ~ -2, label="A", color="magenta") %>%
  gf_label(-3 ~ 2, label="B", color="blue") %>%
  gf_label(1 ~ 3, label="C", color="orange") %>%
  gf_refine(coord_fixed())
```

```{r echo=FALSE}
Pa <- traj_plot(v(t) ~ t, trajA) %>%
  gf_labs(y="", subtitle="Plot 1")
Pb <- traj_plot(u(t) ~ t, trajC) %>%
  gf_labs(y="", subtitle="Plot 2")
Pc <- traj_plot(u(t) ~ t, trajB) %>%
  gf_labs(y="", subtitle="Plot 3")
Pd <- traj_plot(v(t) ~ t, trajC) %>%
  gf_labs(y="", subtitle="Plot 4")
gridExtra::grid.arrange(Pa, Pb, Pc, Pd, nrow=2)
```

All but one of the plots above is a time series from a trajectory starting at one of the initial conditions A, B, or C. The time series might be $u(t)$ or $v(t)$ (or neither, for the bogus time series).

```{r chc32-1, echo=FALSE, results="markup"}
askMC("To which of these choices does Plot 1 belong?",
      "$u(t)$ from point A",
      "+$v(t)$ from point A+",
      "$u(t)$ from point B",
      "$v(t)$ from point B",
      "$u(t)$ from point C",
      "$v(t)$ from point C",
      "none of the above",
      random_answer_order = FALSE
      )
```

```{r chc32-2, echo=FALSE, results="markup"}
askMC("To which of these choices does Plot 2 belong?",
      "$u(t)$ from point A",
      "$v(t)$ from point A",
      "$u(t)$ from point B",
      "$v(t)$ from point B",
      "+$u(t)$ from point C+",
      "$v(t)$ from point C",
      "none of the above",
      random_answer_order = FALSE
      )
```

```{r chc32-3, echo=FALSE, results="markup"}
askMC("To which of these choices does Plot 3 belong?",
      "$u(t)$ from point A",
      "$v(t)$ from point A",
      "$u(t)$ from point B",
      "$v(t)$ from point B",
      "$u(t)$ from point C",
      "$v(t)$ from point C",
      "+none of the above+",
      random_answer_order = FALSE
      )
```

```{r chc32-4, echo=FALSE, results="markup"}
askMC("To which of these choices does Plot 4 belong?",
      "$u(t)$ from point A",
      "$v(t)$ from point A",
      "$u(t)$ from point B",
      "$v(t)$ from point B",
      "$u(t)$ from point C",
      "+$v(t)$ from point C+",
      "none of the above",
      random_answer_order = FALSE
      )
```
