---
id: "chicken-make-room"
created: "Fri Mar 18 11:22:49 2022"
global_id: "JsRKvA"
skill: "D-BRUPM"
---

You've seen that sometimes the two eigenvalues of an abcd matrix are **complex numbers**, that is, have a nonzero imaginary part. You may also have noticed that the eigenvalues are closely related to one another: the imaginary part of one will be the negative of the imaginary part of the other. Such vectors are called ***complex conjugates***.

Whenever a matrix has a complex eigenvalue, it will also have the complex conjugate of that eigenvalue; complex eigenvalues *always* come in pairs.

For a 2x2 matrix, there will be two eigenvalues. If one is complex, the other will be the complex conjugate.

For a 3x3 matrix, either one or all three of the eigenvalues will **not** be complex.

Here's a way to generate a random nxn matrix:
```{r}
n <- 3
M <- matrix(rnorm(n^2), nrow=n)
eigen(M)$values
```


Your task: for $n=3$, run the previous commands over and over, 20 times altogether. Report what fraction of the time the random matrix generated has 3 real eigenvalues. (Note: Something like `1.548950+0.00000i` is a real eigenvalue, because the imaginary part is zero.)

