---
id: "crow-find-sofa"
created: "Mon Jul 19 12:54:52 2021"
global_id: "KzgT1c" 
skill: "X-HGCV2"
---

```{r echo=FALSE, out.width="75%", warning=FALSE, message=FALSE}
draw_flow(6725) %>% gf_labs(title="(A)")
```
```{r 2d1-2, echo=FALSE, results="markup"}
askMC(
  "In plot (A), how many fixed points are visible?",
  0, 1, 2, 3, 4, 5, 
  right_one = 0,
  random_answer_order=FALSE
)
```

```{r echo=FALSE, out.width="75%", warning=FALSE, message=FALSE}
draw_flow(6726) %>% gf_labs(title="(B)")
```

```{r 2d1-3, echo=FALSE, results="markup"}
askMC(
  "In plot (B), how many fixed points are visible?",
  0, 1, 2, 3, 4, 5, 
  right_one = 4,
  random_answer_order=FALSE
)
```

```{r echo=FALSE, out.width="75%", warning=FALSE, message=FALSE}
draw_flow(6727) %>% gf_labs(title="(C)")
```

```{r 2d1-4, echo=FALSE, results="markup"}
askMC(
  "In plot (C), how many fixed points are visible?",
  0, 1, 2, 3, 4, 5, 
  right_one = 3,
  random_answer_order=FALSE
)
```

```{r echo=FALSE, out.width="75%", warning=FALSE, message=FALSE}
draw_flow(6729) %>% gf_labs(title="(D)")
```

```{r 2d1-5, echo=FALSE, results="markup"}
askMC(
  "In plot (D), how many fixed points are visible?",
  0, 1, 2, 3, 4, 5,
  right_one = 3,
  random_answer_order=FALSE
)
```

