---
id: "deer-cost-door"
created: "Fri Mar 18 11:10:40 2022"
global_id: "Pl64dp"
skill: "WP-103-14"
---

An eigenvector  $\vec{\Lambda}$ of a matrix $\mathit{M}$ always has this property:

$$\mathit{M} \vec{\Lambda} = \lambda \vec{\Lambda}$$
This merely says that if you multiply a matrix by one of its eigenvectors, the result is a vector that points in the same direction as the eigenvector but may have a different length or reversed orientation.

Your task:

1. Construct a numerical abcd matrix with whatever values you like and, using `eigen()`, calculate its eigenvalues and eigenvectors.

2. Multiply the matrix by one of the eigenvectors to create a new vector.

3. Confirm that the vector in (2) is proportional to the eigenvector. When two vectors are proportional, dividing component-wise one vector by the other will create a vector with every element the same. (Note: if both of the vectors in the division have any zero component, the result of the division will be `NaN`. In contrast, if one of the vectors has a zero component, but the other doesn't, you will get a result of 0 or `Inf` for that component.)


