---
id: "dolphin-hang-dish"
created: "Fri Jan 28 11:04:48 2022"
global_id: "9aVYdV" 
---

Answer these questions with respect to Figure \@ref(fig:road-rules).

```{r drive1-1, echo=FALSE, results="markup"}
askMC(
  "At mile marker 4, which way is the car going?",
  "+West+" = "A negative velocity means heading west.",
  "East",
  "At a standstill"
)
```

```{r drive1-2, echo=FALSE, results="markup"}
askMC(
  "How long will it take for the car to go from mile marker 4 to mile marker 0? (Choose the closest answer.)",
  "5 minutes",
  "15 minutes",
  "+25 minutes+" = "The velocity is about -10 mph over that segment of the road. To go 4 miles at 10 mph takes 24 minutes.",
  "45 minutes",
  "Can't be done.",
  random_answer_order = FALSE
)
```

```{r drive1-3, echo=FALSE, results="markup"}
askMC(
  "A car starts at mile marker 8. Where will it end up?",
  "+All the way west+",
  "About mile 9",
  "About mile 10",
  "About mile 13",
  "All the way east",
  random_answer_order = FALSE
)
```

```{r drive1-4, echo=FALSE, results="markup"}
askMC(
  "A car starts at mile marker 10. Where will it end up?",
  "All the way west",
  "About mile 9",
  "About mile 10",
  "+About mile 13+",
  "All the way east",
  random_answer_order = FALSE
)
```


```{r drive1-5, echo=FALSE, results="markup"}
askMC(
  "You and your friend plan to bike along the road. (Bikes are not covered by the speed mandate.) You'll stop at a point where you can sell snacks to motorists through their car windows. What's the most profitable point for you to set up your business.",
  "All the way west",
  "About mile 9",
  "About mile 10",
  "+About mile 13+",
  "All the way east",
  random_answer_order = FALSE
)
```

A government commission is exploring ways to improve road use by changing the speed mandate. They will add a constant to the existing speed mandate.

```{r drive1-6, echo=FALSE, results="markup"}
askMC(
  "One group of citizens wants to facilitate east-to-west travel. Which of these would be a suitable value of the constant to add to the speed mandate?",
  "+-75 mph+",
  "-25 mph",
  "15 mph",
  "35 mph",
  "60 mph",
  random_answer_order = FALSE
)
```

```{r drive1-7, echo=FALSE, results="markup"}
askMC(
  "Another group of citizens wants to facilitate west-to-east travel. Which of these would be a suitable value of the constant to add to the speed mandate?",
  "-75 mph",
  "-25 mph",
  "15 mph",
  "35 mph",
  "+60 mph+",
  random_answer_order = FALSE
)
```

```{r drive1-8, echo=FALSE, results="markup"}
askMC(
  "An angry chef has a road-side hamburger stand at mile 5. His business has been non-existent since the current speed mandate was implemented. To give his stand the best chance at success, which policy should he advocate?",
  "-75 mph",
  "-25 mph",
  "+15 mph+",
  "35 mph",
  "60 mph",
  random_answer_order = FALSE
)
```

