---
id: "falcon-have-mattress"
created: "Wed Mar  9 11:12:13 2022"
global_id: "iX26Ra"
skill: "D-BRUPM"
---

Most any mathematics textbook devotes a considerable amount of space to **deriving** formulas. This is well and good. But in practical work, there is considerable room for error even if you already know the formula. 

It's a good professional practice to try to have at least two ways to perform a calculation so that you can confirm that you are doing the calculation properly.  In this exercise, we give you a formulas for the eigenvalues and eigenvectors of an abcd matrix. And, of course, there is the `eigen()` function that should give the same results as the formula.

Your task is to use both `eigen()` and the formulas directly to confirm that the two calculations are the same. The formulas have symbols; replace these with numbers of your choice to do the calculations.

You might start with numbers that are simple integers, then switch to numbers that are more or less random.

The formula for the eigenvalues of an abcd matrix $$\left[\begin{array}{cc}a & b\\c & d\end{array}\right]$$ is
$$\lambda_{1,2} = \frac{1}{2}\left[{\large\strut}(a-d)^2 \pm \sqrt{\strut(a+d)^2 - 4bc}\right]\ .$$ 

Once you know the eigenvalues, the eigenvectors can be calculated this way:
$$\vec{\Lambda_1} = \left[\begin{array}{c}\lambda_1 - d\\c\end{array}\right]\ \ \text{and}\ \ \vec{\Lambda_2} = \left[\begin{array}{c}\lambda_2 - d\\c\end{array}\right]$$

1. Calculate the eigenvalues and eigenvectors of 
$$\left[\begin{array}{rr}1 & 0 \\-2 & 6\end{array}\right]$$

2. Calculate the eigenvalues and eigenvectors of 
$$\left[\begin{array}{rr}8 & 6 \\4 & -1\end{array}\right]$$

3. Calculate the eigenvalues and eigenvectors of 
$$\left[\begin{array}{rr}-9 & 2\\8 & -6\end{array}\right]$$

