---
id: "hamster-bend-sofa"
created: "Tue Mar 22 09:43:58 2022"
global_id: "3mU3qO"
skill: "R-208IA"
---



```{r hbs25-1, echo=FALSE, results="markup"}
askMC(
  "Which of the three flows below corresponds to Lanchester's Law?",
  "+A+", "B", "C",
  random_answer_order = FALSE
)
```

```{r eval=FALSE, echo=FALSE, warning=FALSE, out.width="50%", fig.show="keep"}
math141Z::streamlines(list(~ 0.001*R -2*B, ~ .001*B-R), 
                      domain(R=-1:5, B=-1:5), nsteps=15, stepsize=0.01) %>%
  gf_refine(coord_fixed(x=-1:5, y=-1:5, clip="on")) %>%
  gf_labs(title="(A)")

math141Z::streamlines(list(~ 0.001*R +B/2, ~ .001*B-R), 
                      domain(R=-1:5, B=-1:5), nsteps=15, stepsize=0.01) %>%
  gf_refine(coord_fixed(x=-1:5, y=-1:5, clip="on")) %>%
  gf_labs(title="(B)")

math141Z::streamlines(list(~ 0.001*R +B/2, ~ .001*B+R), 
                      domain(R=-1:5, B=-1:5), nsteps=15, stepsize=0.01) %>%
  gf_refine(coord_fixed(x=-1:5, y=-1:5, clip="on")) %>%
  gf_labs(title="(C)")
```

```{r hbs25-2, echo=FALSE, results="markup"}
askMC(
  "Which of these sentences best describes the dynamics of Lanchester's Law?",
  "Both forces battle to complete annihilation.",
  "+The stronger force wipes out the weaker force.+",
  "The weaker force holds off the stronger force."
)
```



