---
id: "rabbit-grow-candy"
created: "Tue Jan 25 10:35:17 2022"
global_id: "Z3Mq3G"
skill: "N-9IU5J"
---

@fig-fox-rabbit-ts shows time series for the rabbit and fox population density starting at the initial condition $r=2, f=0.5$ for the first 5 time units thereafter. The fox graph looks like a hump function, the rabbit graph show a little uptick near $t=5$.

Using the R/mosaic commands given in the text to make @fig-fox-rabbit-ts, integrate the equations from $t=0$ to $t=15$ and plot the time series for both rabbits and foxes. 

A. Using the time-series plots, estimate the period of the cyclic oscillations. 
- What is the period of the fox population cycle? <!-- about 8 -->
- How large in amplitude (peak to trough) is the fox population cycle? <!-- about 1.1 -->
- How do the cycle period and amplitude for the rabbits compare to those for the foxes?

B. Change the initial condition from $r=2, f=0.5$ to $r=1, f=0.5$ and plot the time series.
- What is the period of the fox population cycle? <!-- still about 8 -->
- How large in amplitude (peak-to-trough) is the fox population cycle? <!-- very small, about 0.01 -->

```{r echo=FALSE, results="hide"}
Eco_soln <- integrateODE(
  dr ~ 0.66*r - 1.33*r*f, 
  df ~     -f +      r*f,
  r = 1, f = 0.5, #initial conditions
  tdur=list(from=0, to=20, dt=0.1))

slice_plot(Eco_soln$r(t) ~ t, domain(t=0:20)) %>% gf_labs(title="Rabbits")
slice_plot(Eco_soln$f(t) ~ t, domain(t=0:20)) %>% gf_labs(title="Foxes")
```
