---
id: "rat-find-closet"
created: "Sat Mar 19 19:03:42 2022"
global_id: "frkSBa"
skill: "D-93XWJ"
---





Trace a trajectory from each of the points labeled A, B, C, and D until it reaches the edge of the box.  Note the **direction** in which the trajectory is heading using compass directions.

```{r echo=FALSE}
f <- rfun( ~ u & v, seed=829)
g <- rfun( ~ u & v, seed=873)
vectorfield_plot(u ~ f(u,v), v ~ g(u,v), 
                 bounds(u=-0:3, v=-2:1), transform=function(x) x^0.25) %>%
  gf_label(.75 ~ 0, label="A", color="magenta") %>%
  gf_label(-1.5 ~ 2, label="B", color="blue") %>%
  gf_label(1 ~ 0.3, label="C", color="orange") %>%
  gf_label(-1.5 ~ 3, label="D", color="brown") %>%
  gf_refine(coord_fixed())
```

```{r fc98-2A, echo=FALSE, results="markup"}
askMC("Which direction for trajectory A?",
      "N", "NE", "E", "SE", "S", "+SW+", "W", "NW")
```

```{r fc98-2B, echo=FALSE, results="markup"}
askMC("Which direction for trajectory B?",
      "N", "NE", "E", "SE", "S", "+SW+", "W", "NW")
```

```{r fc98-2C, echo=FALSE, results="markup"}
askMC("Which direction for trajectory C?",
      "N", "+NE+", "E", "SE", "S", "SW", "W", "NW")
```

```{r fc98-2D, echo=FALSE, results="markup"}
askMC("Which direction for trajectory D?",
      "N", "+NE+", "E", "SE", "S", "SW", "W", "NW")
```

