---
id: "squirrel-tell-chair"
created: "Sat Mar 19 19:32:36 2022"
global_id: "9x2tYm"
skill: "X-KZLDP"
---


Consider a dynamical system with state variables $x$ and $y$.


```{r stc02-1, echo=FALSE, results="markup"}
askMC(
  "What type of object is shown by the graph $x(t)$ versus $y(t)$?",
  "a time series",
  "+a trajectory+",
  "a state space",
  "an instantaneous state",
  "nonsense",
  random_answer_order=FALSE
)
```

```{r stc02-2, echo=FALSE, results="markup"}
askMC(
  "What type of object is shown by the graph $x(t)$ versus $t$?",
  "+a time series+",
  "a trajectory",
  "a state space",
  "an instantaneous state",
  "nonsense",
  random_answer_order=FALSE
)
```

```{r stc02-3, echo=FALSE, results="markup"}
askMC(
  "What type of object is shown by the graph $x(y)$ versus $y$?",
  "a time series",
  "a trajectory",
  "a state space",
  "an instantaneous state",
  "+nonsense+",
  random_answer_order=FALSE
)
```

```{r stc02-4, echo=FALSE, results="markup"}
askMC(
  "What type of object is the coordinate $(x=2, y=1)$?",
  "a time series",
  "a trajectory",
  "a state space",
  "+an instantaneous state+",
  "nonsense",
  random_answer_order=FALSE
)
```

```{r stc02-5, echo=FALSE, results="markup"}
askMC(
  "What type of object is the $(x,y)$ coordinate plane?",
  "a time series",
  "a trajectory",
  "+a state space+",
  "an instantaneous state",
  "nonsense",
  random_answer_order=FALSE
)
```

