---
id: "zebra-wake-shoe"
created: "Tue Mar 22 09:04:09 2022"
global_id: "KkxELm"
skill: "X-DE4WK N-CB2LE X-LG744 U-5PMG7"
---

The Susceptible-Infective-Recovered (SIR) model has only two parameters, $\alpha$ and $\beta$. 

$$\partial_t S = -\beta S I\\
\partial_t I = \beta S I - \alpha I$$

The $\alpha$ parameter controls how long it takes for an infective to recover. If we are considering only recovery, and not the introduction of new infectives from the susceptible population, the relevant differential equation is simply
$$\partial_t I = \alpha I\ .$$
1. Set $\alpha$ so that the half-life for infectiveness is 5 days.

<!-- 0.139 -->

2. Using $\beta = 0.5$ and $\alpha$ as in (1), set up a numerical integration of the SIR model. Integrate out to $t=100$ from an initial condition of $S=0.999$ and $I=0.001$, corresponding to 0.1% of the population being infected. Plot out the time series $S(t)$.  From the time series, what fraction of the population eventually get the disease?

3. One sort of government tactic to keep small the spread of disease is to close borders, with the idea that there will be fewer infectives at the start of the epidemic which will keep the epidemic smaller. Public health professionals are skeptical of this common-sense tactic. Follow the same procedure in (2), but set the initial condition to $S=0.99999$ and $I=0.00001$. Does common sense hold?

4. Another strategy is "social distancing" and isolating infectives. To model this, reduce $\beta$, the rate at which susceptibles interact with infectives. Keeping $\alpha$ at the value you determined in (1), set $\beta$ that only about half the susceptibles are ever infected. 


