## Linearization

$$\partial_t x(t) = f(x)$$ can be approximated by $f(x_0) + f'(x_0) (x - x_0)$: the linear approximation, first order Taylor polynomial. Let $y = x - x_0$. Then $\partial_t y = \partial_t x$. Near state $x_0$, dynamics are $\partial_t y = f'(x_0) y$ --- exponential growth.



i. Linear expansion around a fixed point 
i. Qualitative solution to exponential growth
i. Understand that growth involves exponentials
i. Impulse response and convolution (?)
i. Bang/bang control theory (?)



## Mortgage example

Example: In Chapter FUTURE-VALUE we examined the problem of determining the rate of payback for a loan of amount ${\cal P}_0$ extending over 30 months at an interest rate $r$. We determined the rate of repayment $A$ (in dollars per month) by discounting future payments and accumulating the present value of the payment stream over the duration of the loan. The mathematics were

$$\int_0^{30} A e^{-kt} \, dt = {\cal P}_0$$ where $k = \ln(1+r)$.

Let's return to the problem from the perspective of dynamical systems. The state quantity will be the principal yet to be repaid: ${\cal P}(t)$. At $t=0$ this is the amount of the loan, ${\cal P}_0$. The principal grows at a rate of $r$ per month. Countering this is the repayment of the loan at the rate $A$ per month. Taken together, the time rate of change of the principal is
$$\partial_t {\cal P}(t) = r {\cal P}(t) - A\ .$$
To figure out the proper amount of payment $A$, we can solve this differential equation subject to the initial condition ${\cal P}(0) = {\cal P}$ and the terminating condition $P(30) = 0$. 

As usual, we find the fixed point of the dynamics:$$\partial_t{\cal P}(t) = 0 = r {\cal P}(t) - A$$ and replace $P(t)$ by a shifted quantity $y(t)$ that is zero at the fixed point: $y(t) = {\cal P}(t) - A/r$. The dynamics of $y(t)$ are exponentialgrowth : $\partial_t y(t) = r y(t)$ and have a solution $y(t) = y(0) exp^{r t}$. Translating this back into terms of ${\cal P}()$, the solution is $${\cal P}(t) - \frac{A}{r} = \left[\strut {\cal P}_0 - \frac{A}{r}\right] e^{rt} \ \ \implies\ \  P(t) = \left[\strut {\cal P}_0 - \frac{A}{r}\right] e^{rt} + \frac{A}{r}\ .$$ 

We now seek to find the amount $A$ that will give ${\cal P}(t) = 0$. This is, of course, a zero-finding problem. [SEE EXERCISE (to be written) where we will ask to solve it both symbolically and with `findZeros()`] The answer we will get is $443.27 per month, which is slightly different from the amount we got in Chapter future value, which was 442.09. I DO NOT KNOW WHERE THE DIFFERENCE COMES FROM. NEED TO FIGURE IT OUT.
