# Dynamics: Outline {#sec-dynamics-draft}

1. Introduction to dynamics
    a. Objectives/topics: 
        i. Explain the format in which we present dynamics as opposed to trajectories
        i. Find qualitative solutions from an initial condition
        i. Articulate the difference between state, dynamics, and trajectory
2. May’s Cows
    a. Objectives/topics
        i. Classify fixed points as stable/unstable given the dynamics
        i. Identify the dynamics of constant growth
        i. Compute Euler solutions (format for expressing the system and the format of the result)
        i. Analyze models in application contexts (for example May’s Cows - a model of bistability in ecology)
3. Linearization
    a. Objectives/topics
        i. Linear expansion around a fixed point 
        i. Qualitative solution to exponential growth
        i. Understand that growth involves exponentials
        i. Impulse response and convolution (?)
        i. Bang/bang control theory (?)
4. Systems of nonlinear differential equations
    a. Objectives/topics
        i. Understand the format of presentations of dynamics (vector fields) and trajectories ( x vs t, y         i. vs t or phase plane)
        i. Finding solutions graphically (flow fields)
        i. Dependence on initial condition
5. Models leading to flow fields
    a. Objectives/topics
        i. Apply modeling techniques (from block 2) local low order polynomials
        i. Predatory/Prey (flow fields and the phenomena of the trajectories)
        i. SIR (flow fields and the phenomena of the trajectories)
        i. The differences between these two models
6. Additional models and flow fields (catch up day)
    a. Objectives/topics
        i. (Richardson’s arms race model and conflict model, action potentials) Numerics, look at the trajectories 
        i. Exercise: `insert_calcZ_exercise("XX.XX", "iRZfBY", "Exercises/walnut-tell-pot.Rmd")`
        i. Analysis of phase plane with nullclines
7. Fixed points of nonlinear systems in the phase plane 
    a. Objectives/topics
        i. Determine fixed points and linearize the system around the fixed points
        i. Flow field of the linear approximation
        i. Matrix representation of the flow field
        i. Iteration of matrices
        
        

8. Eigenvalue/Eigenvector analysis
    a. Objectives/topics
        i. Understand the geometry of the flow (what an eigenvector looks like in terms of the flow, as it emerges from the image of the flow field)
        i. Trajectories as linear combinations of eigenflows
        i. Classification of fixed points
9. Calculus of second order differential equations
    a. Objectives/topics
        i. Force balance equations
        i. Equivalence to phase plane description
        i. Exponential Ansatz (solution is made up of exponentials, which one?)
        i. Complex eigenvalues
10. Harmonic Oscillator 
    a. Objectives/topics
        i. Complex exponentials and their equivalency to sinusoids 
        i. Sinusoids with exponential amplitudes (damping)
        i. Relation to the real and complex parts of the eigenvalues
        i. Forcing and resonance

