---
id: "calf-fly-boat"
created: "Mon Jul 19 12:44:05 2021"
global_id: "YsZp7T"
---

The dynamical system $x_{n+1} = 5 [\sin(x_n)]^2$ has five fixed points. Use iteration to determine whether each fixed point is stable or unstable.

```{r stb1-2, echo=FALSE, results="markup"}
askMC(
  "Using iteration, is the fixed point at $x=0$ stable?", 
  "Yes",
  "No",
  random_answer_order = FALSE,
  right_one = "Yes"
)
```

```{r stb1-3, echo=FALSE, results="markup"}
askMC(
  "Using iteration, is the fixed point at $x=0.2027$ stable?", 
  "Yes",
  "No",
  random_answer_order = FALSE,
  right_one = "No"
)
```

```{r stb1-4, echo=FALSE, results="markup"}
askMC(
  "Using iteration, is the fixed point at $x=2.3802$ stable?", 
  "Yes",
  "No",
  random_answer_order = FALSE,
  right_one = "No"
)
```

```{r stb1-5, echo=FALSE, results="markup"}
askMC(
  "Using iteration, is the fixed point at $x=4.3408$ stable?", 
  "Yes",
  "No",
  random_answer_order = FALSE,
  right_one = "No"
)
```

```{r stb1-6, echo=FALSE, results="markup"}
askMC(
  "Using iteration, is the fixed point at $x=4.8726$ stable?", 
  "Yes",
  "No",
  random_answer_order = FALSE,
  right_one = "No"
)
```


