---
id: "kitten-mean-tv"
created: "Mon Jul 19 12:27:06 2021"
global_id: "DtLAhm"
---


```{r fdem1, echo=FALSE, results="markup"}
askMC(
  "If today is $n$, what is the day after tomorrow?",
  "$n-1$" = "$n-1$ is yesterday.",
  "$n$" = "$n$ is today.",
  "$n+1$" = "$n+1$ is tomorrow.",
  "+$n+2$+",
  "$n=3$",
  random_answer_order = FALSE
)
```

```{r fdem2, echo=FALSE, results="markup"}
askMC(
  "If today is $n$, what is the day one week from now?",
  "$7n$",
  "$n + 1 week$" = "Although $n$ stands for \"today\", $n$ is a pure number.",
  "+$n+7$+"
)
```

```{r fdem3, echo=FALSE, results="markup"}
askMC(
  "If today is $n$, what is the day one week ago?",
  "$-7 n$",
  "$n - 1$ week" = "Although $n$ stands for \"today\", $n$ is a pure number.",
  "+$n-7$+"
)
```

```{r fdem4, echo=FALSE, results="markup"}
askMC(
"Given ${\\mathbf S}_{n+1} = g({\\mathbf S}_n)$, what is ${\\mathbf S}_{n+3}$ ?",
  "+$g(g(g({\\mathbf S}_n)))$+",
  "$3 g({\\mathbf S}_n)$" = "$3 g({\\mathbf S}_n)$ is \"three times ${\\mathbf S}_{n+1}$\", not ${\\mathbf S}_{n+3}$.",
  "$g({\\mathbf S}_n)^3$",
  "$g({\\mathbf S}_n) + 2 {\\mathbf S}_{n}$"
)
```

```{r fdem5, echo=FALSE, results="markup"}
askMC(
"Given ${\\mathbf S}_{n+1} = g({\\mathbf S}_n)$, which of these is **not** ${\\mathbf S}_{n+1}$ ?",
  "$g(g(g({\\mathbf S}_{n-2})))$",
  "+$g({\\mathbf S}_{n-1})$+" = "This is ${\\mathbf S}_{n}$.",
  "$g(g({\\mathbf S}_{n-1}))$",
  "$g(g(g(g(g(g(g(g({\\mathbf S}_{n-7}))))))))$" = "These 8 applications of $g()$ will take ${\\mathbf S}_{n-7}$ up to ${\\mathbf S}_{n+1}$"
)
```


