---
id: "lobster-become-sofa"
created: "Mon Jul 19 12:35:09 2021"
global_id: "9mSE8t"
---


```{r soln1-1, echo=FALSE, results="markup"}
askMC(
  "For the arithmetic sequence with $x_0 = 2$ and $b=3$, what is the numerical value $x_{100}$?",
  203,
  230,
  "+302+",
  320,
  "Not enough information given.",
  random_answer_order = FALSE
)
```

```{r soln1-2, echo=FALSE, results="markup"}
askMC(
  "For the geometric sequence with $x_0 = 2$ and $\\alpha = \\frac{1}{2}$, what is the numerical value $x_{10}$?",
  "1/1028",
  "+1/512+" = "$2 \\times \\frac{1}{2}^{10} = 2 / 1024 = 1/512$",
  "512",
  "1028",
  "Not enough information given.",
  random_answer_order = FALSE
)
```

```{r soln1-3, echo=FALSE, results="markup"}
askMC(
  "For the affine sequence with $x_0 = 2$ and $\\alpha = \\frac{1}{2}$ and $b=10$, what is the numerical value of $x_{100}$? (These answers are shown to only one decimal point.)  Hint: What is $\\alpha^{100}$?",
  "+20.0+",
  "-20.0",
  "$(1/2)^{100}$",
  "0.0", 
  random_answer_order = FALSE
)
```    

