---
id: "snake-drive-socks"
created: "Mon Jul 19 12:37:57 2021"
global_id: "dBCKD6"
---


```{r ffp-a, echo=FALSE, results="markup"}
askMC(
  "Consider the dynamical system $$x_{n+1} = 2 x_n + 3$$ To find the fixed point, re-write the equation as $x^\\star = 2 x^\\star + 3$ and solve for $x^\\star$. What is the fixed point $x^\\star$?",
  "+-3+" = "Right. Plug in $-3$ for $x^\\star$ in $2 x^\\star + 3$ and you get ... -3. ",
  "-1.5",
  "0", 
  "1.5",
  "3",
  random_answer_order = FALSE
)
```

```{r ffp-b, echo=FALSE, results="markup"}
askMC(
  "Consider the dynamical system $$y_{n+1} =  1/y_n + 9$$ To find the fixed point, re-write the equation as $y^\\star = 1/y^\\star + 9$ and solve for $y^\\star$. How many fixed points are there",
  0, 1, "+2+" = "Right, because the equation becomes $(y^\\star)^2 = 9$ which has two solutions, $y^\\star = \\pm 3$.", 3, 4, "an infinite number",
  random_answer_order = FALSE
)
```

```{r ffp-c, echo=FALSE, results="markup"}
askMC(
  "How come the first question used $x_n$ for the state while the second on used $y_n$?",
  "Because you can't write $1/x_n$",
  "Using $y_n$ is a mistake. Dear problem writer, Please be more careful in the future!",
  "+Because you can use any name you like for a variable, so long as you use it consistently. And using $x$ all the time gets tiring, to say nothing about how hard it makes to work with more than one variable at a time.+" = "It would have been fun to use names like $\\text{dog_hunger}_n$ or $\\text{snowfall}_n$. We used $y_n$ so that we don't freak you out. But $y$ is just a name like any other."
)
```


