# Block 2 Projects and review {.unnumbered}

## Labor vs capital

The ***Cobb-Douglas production function*** is a simple mathematical model of how labor $L$ and capital $K$ combine to produce a factory's output $P$. It is $$P(L, K) \equiv A K^\alpha L^{1-\alpha}\ .$$

For simplicity, imagine that capital and labor are both measured in dollars per year---the amount that the labor force is paid in a year and the amount that one could rent a factory for a year.

a. If production $P(L, K)$ is also measured in dollars per year (say, the value of the factory output each year), what is the dimension of the constant $A$?

b. According to the model, what happens to production if both $K$ and $L$ are increased by a factor constant factor $\beta$? (Hint: Substitute in $K \rightarrow \beta K$ and $L \rightarrow \beta L$ and simplify.)

c. Consider a particular factory with $A = 2.5$ and exponent $\alpha = 0.33$. In a sandbox, implement the function $P (K, L)$. Use your function to compute the production of the factory for $K = 10$ and $L=20$. Confirm that you get $P(K=10,L=20)= 39.78$

d. A factory that rents for $10/yr and where the labor costs $20/yr is silly. Calculate the value $P (K, L)$ when $K$ is $10 million/yr and $L$ is $20 million/yr.

We’ll stick with numbers like $K = 10$ and $L = 20$ to keep things easy to read, but feel free to interpret them as "millions of dollars."

Congratuations! Based on your ability to use the Cobb-Douglas model, you’ve been promoted to manager of the factory. One of your jobs is to decide how to balance expenditures on capital and labor to raise productivity.

One basic question is what happens when you raise either capital or labor, holding the other one constant. Using ap- propriate partial derivatives evaluated at $K = 10$, $L = 20$, calculate:

i. The rate at which an increase in spending on labor will increase productivity.
i. The rate at which an increase in spending on capital will increase productivity.
i. Based on the above, if you had to choose between spending on capital or labor, and your goal is to increase productivity as much as possible, which would you spend on, capital or labor?

Your economist friend tells you to watch out for "diminishing marginal returns." This means that, as you increase spending on either labor or capital, the rate of increase in production tends to diminish. You’ll still get increased production as you increase spending, but it won’t increase as fast at high levels of expense as at low levels.

d. Compute the partial derivative of production with respect to labor at a higher level of labor, say $L = 21$, but holding $K = 10$. How does the value of the derivative at $L = 21$ compare to that at $L = 20$? Is this consistent with the idea of "diminishing marginal returns" for labor?

e. Do the same for the partial derivative of production with respect to capital, evaluated at $L = 20$ and $K = 11$. How does the value of the derivative at $K = 11$ compare to that at $K = 10$. Is this consistent with the idea of "diminishing marginal returns" for capital?

f. Use an appropriate partial second derivative to find the rate of diminishing partial returns for labor at $L = 20$ and $K = 10$. Show that it's consistent with the difference you got in Part (d).

g. Use an appropriate partial second derivative to find the rate of diminishing partial returns for capital at $L = 20$ and $K = 10$. Show that it's consistent with the difference you got in Part (3).

h. You might think of the rate of increase in production with respect to labor as the "value rate" of labor. Similarly, the rate of increase in production with respect to capital is the value rate of capital. Due to diminishing marginal returns, an increase in labor spending, holding capital constant, decreases the value rate of labor. Similarly, an increase in capital spending holding labor spending constant decreases the value rate of capital.

But what happens to the value rate of labor when capital
spending is increased? You can answer this by comparing
the value rate of labor, $\partial_L P$ , at two different capital spending levels, say $(K = 10,L = 20)$ and $(K = 11,L = 20)$. Notice that even though you're looking at the rate with respect to labor, you’re changing the expenditure on capital.

    i. Compare $\partial_L P$ at slightly different values of $K$ , holding $L$ constant at 20. Does the value rate of labor increase or decrease with spending on capital?
    ii. Similarly, compare $\partial_K P$ at slightly different values of  $L$, holding $K$ constant at 20. Does the value rate of labor increase or decrease with spending on capital?
    iii. Finally, construct and evaluate the mixed partial derivative, $\partial_L \partial_K P at $K = 10$, $L = 20$. Compare this to the results you got for the way $\partial_K P$ changes with increasing $L$ and the way $\partial_L P$ changes with increasing $K$.
    
