# Prolog: Differentiation and birth {.unnumbered}

Stories are an important way in which people communicate and receive their understanding of the world. History, as the name suggests, is replete with stories. The definition of history as the "study of what happened in the light of what might have happened" even suggests a counter-factual aspect to some stories.^[The American Heritage Dictionary of the English Language, 5th Edition gives this word origin for "history": "Middle English *histoire* from Old French from Latin *historia* from Greek historiā from *historein* to inquire from histōr learned man weid- in Indo-European roots." [weid is also the origin of "wit".]]

Mathematics instruction is weak on stories, with a few exceptions such as the Eureka! moment or the apple falling from an orchard tree. Our new topic, differentiation, might be well served by connecting it to stories ... but judge for yourself.

The ancient Greek understanding of the origins and actions of the world was conveyed by stories of titans, gods, nymphs, and other characters. For the most part, these characters were created by the coupling of two parents, somewhat as we can create new functions by bringing together existing ones in composition, multiplication, and (linear) combination.

In Greek mythology, the twelve Olympians of the pantheon, are Zeus, Hera, Poseidon, Demeter, Athena, Apollo, and others such as Ares (war fighting) and Aphrodite (love, beauty). Each Olympian has his or her own character and special power and authority.  Athena, for instance, is a god of wisdom, craft, and war strategy. Similarly, we have our nine pattern-book functions, each of which can morph into a variety of shapes by introducing parameters.

Athena is said to have emerged fully formed from the forehead of her father Zeus, a strange form of birth but a birth nonetheless. The technical word for birth is "parturition" whose first syllable is reminiscent of "to part" or "parting": the separation of child from parent. And, as every parent and child knows, a child is different from---apart from---the parent. A person in their own right. Their characteristics and hopes are, even if related, distinct and they can play utterly different roles in history or myth.

In Greek mythology, **parthenogenesis**---procreation from a single parent---is common. For instance, Dionysos sprang from the virgin Persephone.

The topic of this Block, differentiation, is to be thought of much like parthenogenesis. There is one parent---a function.  From this parent springs a new being, also a function. Among our pattern-book functions, there are many parent-child pairs, just as the Olympian Athena is the child of Zeus. For instance, the reciprocal function is the child of the logarithm. The exponential is its own parent and the sine is its own grandparent.

Insofar as the role of functions is to convey information about relationships and patterns, the child function created by differentiation conveys different information or a different perspective or emphasis than the parent. (Not so true in the case of the exponential, which is its own child, grandchild, and down the line. As such, it has a special role to play in modeling.)

Calculus books tend to be technical. Their description of the the process of one-parent birth---that is, differentiation---usually emphasizes the details of pushing and pulling, viscera and parturition.^[Athena's birth story features iron-mongering within Zeus's head, and the male mid-wife's use of an axe-blow to the head.] But usually these efforts are details that contribute little or nothing to the important story and don't make it into polite conversation. The basis of the story is the fact of the parent-child relationship and the understanding that the child and the parent are different people whose characteristics and actions, desires, fates, and foibles are intertwined but different.

So before we delve into the obstetric details of differentiation in the next chapters, keep in mind that the important part is the creation of a new and different being whose story will convey to us different information and insight than the parent. Examples of the parent-child connection created by differentiation are all around us. When the parent function signifies the volume of water in a lake, differentiation produces a new function that tells us about the flows of streams into and out of the lake, rain, and evaporation. Differentiating the function that conveys the position of an object generates a new function that represents the velocity of that object. If the parent is the function of time that tells the size of retirement investment, the birth by differentiation creates a function with a different story: savings, expenditure, profit, and loss.

Just as people have a solid, immediate understanding of the parent-child relationship, people have an almost tangible grasp of differentiation relationships. You can sense position with your eyes, as you can sense velocity by the wind in your face regardless of where you happen to be at the time. You know whether a flow is great or small even without knowing the volume of the lake or ocean to which the flow is delivered.

Science as a story is full of parent-child relationships, and sometimes is constructed out of the child-grandparent relationship. For instance, the function representing acceleration is the child of velocity, which is in turn the child of position. And, occasionally in science and mathematics, the great-grandchild or the great-great-grandchild are part of the relationships being described.

A warning: There is one important way in which thinking of differentiation as parthenogenesis is utterly misleading. With functions, birth can be run in reverse, generating the parent function from the child. The process of this utterly unbiological reverse birthing is called "anti-differentiation," and is every bit as important as differentiation even if it is harder to envision.
